SELECT Q1.USERID, Q1.TOPICID, Q1.CART, Q1.KEYID, Q1.KEYWORDS, Q1.SRC, Q1.SORTER, Q1.COUNTRY_CODE, CNT.HCNT, CNT.LCNT FROM
( 
/* START OF CART PORTION OF SORTER 1 */
SELECT UC1.USERID, UC1.TOPICID, UC1.CART, K1.KEYID, K1.KEYWORDS, 'A' SRC, K1.CREATION_DTM SORTER, K1.COUNTRY_CODE
FROM OPN_P_KW K1
, OPN_USER_CARTS UC1
WHERE UC1.KEYID = K1.KEYID AND UC1.TOPICID = 1 AND UC1.USERID = 1033749 
/* END OF CART PORTION OF SORTER 1 */
UNION ALL
/* START OF NON-CART PORTION OF SORTER 1 - FOR USER.CCODE = KW.CCODE */
SELECT 1033749 USERID, 1 TOPICID, NULL CART, K1.KEYID, K1.KEYWORDS, 'B' SRC, K1.CREATION_DTM SORTER, K1.COUNTRY_CODE
FROM OPN_P_KW K1
WHERE 1=1
AND K1.TOPICID = 1
AND K1.COUNTRY_CODE = 'IND'
AND K1.PRIVATE_KW_FLAG = 'N'
AND K1.CLEAN_KW_FLAG = 'Y'
AND K1.KEYID NOT IN 
(SELECT KEYID FROM OPN_USER_CARTS WHERE USERID = 1033749 AND TOPICID = 1)
/* END OF NON-CART PORTION OF SORTER 1 - FOR USER.CCODE = KW.CCODE  */
UNION ALL
/* START OF NON-CART PORTION OF SORTER 1 - FOR USER.CCODE <> KW.CCODE */
SELECT 1033749 USERID, 1 TOPICID, NULL CART, K1.KEYID, K1.KEYWORDS, 'C' SRC, K1.CREATION_DTM SORTER, K1.COUNTRY_CODE
FROM OPN_P_KW K1
WHERE 1=1 
AND K1.TOPICID = 1
AND K1.COUNTRY_CODE <> 'IND'
AND K1.PRIVATE_KW_FLAG = 'N'
AND K1.CLEAN_KW_FLAG = 'Y'
AND K1.KEYID NOT IN 
(SELECT KEYID FROM OPN_USER_CARTS WHERE USERID = 1033749 AND TOPICID = 1)
/* END OF NON-CART PORTION OF SORTER 1 - FOR USER.CCODE <> KW.CCODE  */
) Q1 LEFT OUTER JOIN (SELECT KEYID, SUM(CASE WHEN CART = 'H' THEN 1 ELSE 0 END) HCNT
, SUM(CASE WHEN CART = 'L' THEN 1 ELSE 0 END) LCNT
FROM OPN_USER_CARTS WHERE TOPICID = 1 GROUP BY KEYID) CNT
ON Q1.KEYID = CNT.KEYID
ORDER BY SRC, CART, SORTER DESC LIMIT 0 , 30 ;