INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105087, USERID, 1, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE BOT_FLAG = 'Y' AND COUNTRY_CODE IN ('IND')
AND USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (105087))
AND USERID NOT IN (SELECT DISTINCT USERID FROM OPN_MAIN_BOTS WHERE TOPICID = 1 AND CCODE = 'IND') 
ORDER BY RAND() LIMIT 600)Q ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'H', 105087, USERID, 1, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE BOT_FLAG = 'Y' AND COUNTRY_CODE IN ('IND')
AND USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (105087))
AND USERID NOT IN (SELECT DISTINCT USERID FROM OPN_MAIN_BOTS WHERE TOPICID = 1 AND CCODE = 'IND') 
ORDER BY RAND() LIMIT 60)Q ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105087, USERID, 1, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE BOT_FLAG = 'Y' AND COUNTRY_CODE IN ('USA')
AND USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (105087))
AND USERID NOT IN (SELECT DISTINCT USERID FROM OPN_MAIN_BOTS WHERE TOPICID = 1 AND CCODE = 'USA') 
ORDER BY RAND() LIMIT 2000)Q ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'H', 105087, USERID, 1, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE BOT_FLAG = 'Y' AND COUNTRY_CODE IN ('USA')
AND USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (105087))
AND USERID NOT IN (SELECT DISTINCT USERID FROM OPN_MAIN_BOTS WHERE TOPICID = 1 AND CCODE = 'USA') 
ORDER BY RAND() LIMIT 200)Q ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105087, USERID, 1, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE BOT_FLAG = 'Y' AND COUNTRY_CODE IN ('GGG')
AND USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (105087))
AND USERID NOT IN (SELECT DISTINCT USERID FROM OPN_MAIN_BOTS WHERE TOPICID = 1 AND CCODE = 'GGG') 
ORDER BY RAND() LIMIT 200)Q ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'H', 105087, USERID, 1, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE BOT_FLAG = 'Y' AND COUNTRY_CODE IN ('GGG')
AND USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (105087))
AND USERID NOT IN (SELECT DISTINCT USERID FROM OPN_MAIN_BOTS WHERE TOPICID = 1 AND CCODE = 'GGG') 
ORDER BY RAND() LIMIT 20)Q ;