-- ADD_NUSERS_XYZNEWS -- 

DELIMITER //
DROP PROCEDURE IF EXISTS ADD_NUSERS_XYZNEWS //
CREATE PROCEDURE ADD_NUSERS_XYZNEWS(K1 INT, CCODE VARCHAR(5), TID INT, N INT)


thisProc: BEGIN

/* 09/14/2024 AST: for loading demo users carts with specific kKWs (mostly the XYZNEWS KWs) 
It became necessary to do this proc beccause of the following reasons:

- The Instream started showing zero records - this has been going on for a while
- The instream posts do not create new KWs in the OPN_P_KW 
- Found that the XYZNEWS KWs had very few BOT users - the Instream Posts are supposed to be 
distributed to BOT users. But if only a handful of BOT users have the XYZNEWS in their carts then 
the distribution of STP instream posts have no impact on the zero rows in the instream.

Hence, it is essential to add hundreds or even thousands of BOTs for each XYZNEWS KW

Another consideration: the createBOTDiscussion proc uses the OPN_MAIN_BOTS table to 
distribute the STD posts. We need to use USERIDs that are outside the OPN_MAIN_BOTS table.

*/

DECLARE  USAHCOUNT, INDHCOUNT, GGGHCOUNT, USALCOUNT, INDLCOUNT, GGGLCOUNT INT ;
DECLARE CCD2, CCD3 VARCHAR(5) ;

SET HCOUNT = N DIV 10 ;

SET LCOUNT = N-HCOUNT ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'H', K1, USERID, TID, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (K1))
AND BOT_FLAG = 'Y' AND COUNTRY_CODE IN (CCODE) ORDER BY RAND() LIMIT HCOUNT)Q ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', K1, USERID, TID, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (K1))
AND BOT_FLAG = 'Y' AND COUNTRY_CODE IN (CCODE) ORDER BY RAND() LIMIT LCOUNT)Q ;

-- CALL NEWCART_TOP_NOTAILOR(UUID, TID1) ;

/* Added on 07/01/2020 AST */

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'H', K1, USERID, TID, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (K1))
AND BOT_FLAG = 'Y' AND COUNTRY_CODE IN (CCD2) ORDER BY RAND() LIMIT HCOUNT )Q ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', K1, USERID, TID, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (K1))
AND BOT_FLAG = 'Y' AND COUNTRY_CODE IN (CCD2) ORDER BY RAND() LIMIT LCOUNT )Q ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'H', K1, USERID, TID, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (K1))
AND BOT_FLAG = 'Y' AND COUNTRY_CODE IN (CCD3) ORDER BY RAND() LIMIT HCOUNT)Q ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', K1, USERID, TID, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (K1))
AND BOT_FLAG = 'Y' AND COUNTRY_CODE IN (CCD3) ORDER BY RAND() LIMIT LCOUNT)Q ;

/* End of 07/01/2020 addition */

INSERT INTO OPN_RAW_LOGS(KEYVALUE_KEY, KEYVALUE_VALUE, LOG_DTM) VALUES(
'ADD_NUSERS_4K1-KEYID-CCODE1-HCOUNT-LCOUNT'
, CONCAT(K1, '-', CCODE,'-',HCOUNT,'-', LCOUNT), NOW() ) ;

 
END; //
 DELIMITER ;
 
 -- 