-- addNewKWToUIDCart

 DELIMITER //
DROP PROCEDURE IF EXISTS addNewKWToUIDCart //
CREATE PROCEDURE addNewKWToUIDCart(UID INT, TID INT, KID INT, CARTV varchar(5))
BEGIN

/* 03282019: Removing the CALL NEWCART_TOP */
/* 04/25/2020 AST: Rebuilding - not sure if this proc is used in the App - 
 this could be one of the ancillary procs - for testing various things 
 
  04/25/2020 AST: Added check to make sure that TID-KID combo is genuine
 
 CALL addNewKWToUIDCart(UID INT, TID INT, KID INT, CARTV varchar(5))
 */

DECLARE AlreadyExists, wrongTIDKIDCombo INT;
DECLARE USUUID VARCHAR(45) ;

SET SQL_SAFE_UPDATES = 0;
SET AlreadyExists = (SELECT COUNT(*) FROM OPN_USER_CARTS WHERE USERID = UID AND KEYID = KID);
SET wrongTIDKIDCombo = ((SELECT COUNT(1) FROM OPN_P_KW WHERE TOPICID = TID AND KEYID = KID) - 1) ;

CASE WHEN wrongTIDKIDCombo = 0 THEN 

CASE WHEN AlreadyExists = 1 THEN

SELECT 'THE SELECTED USER ALREADY HAS THIS KEYWORD IN THE CART' FROM DUAL ;

WHEN AlreadyExists = 0 THEN

DELETE FROM OPN_CART_ARCHIVE WHERE USERID = UID AND TOPICID = TID;

INSERT INTO OPN_CART_ARCHIVE(OLD_CART_ID, USERID, TOPICID, CART, KEYID, CREATION_DTM, DELETE_DTM)
SELECT ROW_ID, USERID, TOPICID, CART, KEYID, CREATION_DTM, NOW() 
FROM OPN_USER_CARTS WHERE USERID = UID AND TOPICID = TID ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
VALUES(CARTV, KID, UID, TID, NOW(), NOW());

SET USUUID = bringUUID(UID) ;

CALL ludtmUpdate(USUUID, TID) ;

-- CALL NEWCART_TOP(USUUID, TID);

END CASE;

WHEN wrongTIDKIDCombo <> 0 THEN SELECT 'THE SELECTED COMBO IS WRONG' FROM DUAL ;

END CASE ;
  
END //
DELIMITER ;

-- 