/* SQL TO ANALYZE THE CURRENT CONDITIONS IN THE APP : THE QUESTIONS TO BE ASKED ARE:
- LATEST POSTS GROUPED BY TOPICID, COUNTRY CODE AND STP TYPE: TO SEE IF THERE IS AN EVEN DISTRIBUTION OF ALL THE TOPICS, COUNTRIES AND DISCUSSIONS/POSTS






*/

SELECT P.STP_PROC_NAME, P.TOPICID, P.POSTOR_COUNTRY_CODE, SUM(CASE WHEN U.BOT_FLAG = 'Y' AND P.DEMO_POST_FLAG = 'Y' THEN 1 ELSE 0 END)  POSTCNT
, SUM(CASE WHEN U.BOT_FLAG = 'Y' AND P.DEMO_POST_FLAG = 'N' THEN 1 ELSE 0 END)  DISCCNT
, SUM(CASE WHEN U.BOT_FLAG <> 'Y' THEN 1 ELSE 0 END) REALPOSTS
FROM OPN_POSTS P, OPN_USERLIST U WHERE P.POST_BY_USERID = U.USERID 
AND P.POST_DATETIME > CURRENT_DATE() - INTERVAL 7 DAY GROUP BY P.STP_PROC_NAME, P.TOPICID, P.POSTOR_COUNTRY_CODE;