-- simulating callSTDbyENTCELEBIND

-- first find out if the current ENT/CELEB(IND) are already converted

CALL WSRL_DEDUPE_ALL() ; -- leaves 97 ENT IND

SELECT * FROM OPN_POSTS ORDER BY POST_ID DESC ; -- 1510587
SELECT * FROM OPN_POSTS_RAW ORDER BY POST_ID DESC ; 

CALL callSTDbyENTCELEBIND(2) ;

SELECT USERID, USERNAME, USER_UUID FROM OPN_MAIN_BOTS WHERE CCODE = 'USA' AND TOPICID = 2 ORDER BY RAND() LIMIT 1 ;
SELECT NEWS_URL, NEWS_HEADLINE, 	IFNULL(NEWS_EXCERPT, "This is a great discussion. I agree with it in principle. Will post more comments shortly")
, SCRAPE_SOURCE, SCRAPE_TOPIC, IFNULL(NEWS_TAGS, 'PYSCRAPE'), NEWS_DATE FROM WEB_SCRAPE_RAW_L WHERE ROW_ID = 186 ;
-- SELECT COUNT(1) FROM OPN_P_KW WHERE TOPICID = 2 AND KEYWORDS LIKE CONCAT("'", SUBSTR("Devin McCourty laments ‘subtle shots' between Belichick and Mayo", 1, 150), "%'") 
SELECT COUNT(1) FROM OPN_P_KW WHERE TOPICID = 2 AND KEYWORDS LIKE CONCAT(SUBSTR("Devin McCourty laments ‘subtle shots' between Belichick and Mayo", 1, 150), '%') ;


SELECT * FROM OPN_POSTS WHERE TOPICID = 2 AND POSTOR_COUNTRY_CODE = 'USA' AND POST_DATETIME > '2024-10-10' ;

SELECT * FROM OPN_P_KW WHERE KEYWORDS LIKE 'https://www.espn.com/wnba/story/_/id/41699737/wnba-finals%' ;

SELECT * FROM OPN_P_KW WHERE TOPICID = 2 AND COUNTRY_CODE = 'USA' ORDER BY KEYID DESC ;

SELECT MAX(POST_ID) FROM OPN_POSTS WHERE POST_BY_USERID = orig_uid AND STP_PROC_NAME = 'SCRAPE_TO_DISC'
AND POST_CONTENT = URL