-- First find out which carts need to be reduced. This is done by the following sql:

CREATE TABLE TEMP_KEYID4_CLEANUP AS
SELECT C.KEYID, COUNT(1) TCNT, SUM(CASE WHEN U.COUNTRY_CODE = 'USA' THEN 1 ELSE 0 END) USA, SUM(CASE WHEN U.COUNTRY_CODE = 'IND' THEN 1 ELSE 0 END) IND
, SUM(CASE WHEN U.COUNTRY_CODE = 'GGG' THEN 1 ELSE 0 END) GGG FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_P_KW K
WHERE C.USERID = U.USERID AND C.KEYID = K.KEYID AND U.BOT_FLAG = 'Y' AND C.TOPICID = 2 AND K.COUNTRY_CODE = 'USA' GROUP BY C.KEYID 
HAVING SUM(CASE WHEN U.COUNTRY_CODE = 'GGG' THEN 1 ELSE 0 END) > 30 OR SUM(CASE WHEN U.COUNTRY_CODE = 'IND' THEN 1 ELSE 0 END) > 30 ORDER BY COUNT(1) ;

SELECT C.KEYID, COUNT(1) TCNT, SUM(CASE WHEN U.COUNTRY_CODE = 'USA' THEN 1 ELSE 0 END) USA, SUM(CASE WHEN U.COUNTRY_CODE = 'IND' THEN 1 ELSE 0 END) IND
, SUM(CASE WHEN U.COUNTRY_CODE = 'GGG' THEN 1 ELSE 0 END) GGG FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_P_KW K
WHERE C.USERID = U.USERID AND C.KEYID = K.KEYID AND U.BOT_FLAG = 'Y' AND C.TOPICID = 1 AND K.COUNTRY_CODE = 'IND' GROUP BY C.KEYID 
HAVING SUM(CASE WHEN U.COUNTRY_CODE = 'IND' THEN 1 ELSE 0 END) > 30  ORDER BY COUNT(1) DESC ;

SELECT  U.COUNTRY_CODE, COUNT(1) TCNT FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_P_KW K
WHERE C.USERID = U.USERID AND C.KEYID = K.KEYID AND U.BOT_FLAG = 'Y' AND C.TOPICID = 1 GROUP BY  U.COUNTRY_CODE ;


DROP TABLE TEMP_KEYID4_CLEANUP ;
SELECT * FROM TEMP_KEYID4_CLEANUP ;

SELECT COUNT(1) FROM OPN_USER_CARTS ;
SELECT COUNT(1) FROM TEMP_KEYID4_CLEANUP ;

SELECT COUNT(1) FROM (SELECT T.*, K.CREATION_DTM FROM TEMP_KEYID4_CLEANUP T, OPN_P_KW K WHERE T.KEYID = K.KEYID AND K.CREATION_DTM < CURRENT_DATE() - INTERVAL 10 DAY )Q  ;

SELECT T.*, K.CREATION_DTM FROM TEMP_KEYID4_CLEANUP T, OPN_P_KW K WHERE T.KEYID = K.KEYID AND K.CREATION_DTM < CURRENT_DATE() - INTERVAL 10 DAY ORDER BY TCNT DESC ; 

SELECT C.KEYID, COUNT(1) TCNT, SUM(CASE WHEN U.COUNTRY_CODE = 'USA' THEN 1 ELSE 0 END) USA, SUM(CASE WHEN U.COUNTRY_CODE = 'IND' THEN 1 ELSE 0 END) IND
, SUM(CASE WHEN U.COUNTRY_CODE = 'GGG' THEN 1 ELSE 0 END) GGG FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_P_KW K
WHERE C.USERID = U.USERID AND C.KEYID = K.KEYID AND U.BOT_FLAG = 'Y' AND C.TOPICID = 1 AND K.COUNTRY_CODE = 'USA'  GROUP BY C.KEYID ORDER BY COUNT(1) DESC ;

CALL OPN_BULK_CART_CLEANUP(2) ;

SELECT COUNT(DISTINCT C.KEYID) FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_P_KW K WHERE C.USERID = U.USERID AND C.KEYID = K.KEYID AND U.BOT_FLAG = 'Y' AND C.TOPICID = 1 AND K.COUNTRY_CODE = 'USA' ; -- 1421532

SELECT COUNT(1) TCNT FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_P_KW K WHERE C.USERID = U.USERID AND C.KEYID = K.KEYID AND U.BOT_FLAG = 'Y' AND C.TOPICID = 1 AND K.COUNTRY_CODE = 'IND' ;
SELECT TOPICID, COUNT(1) TCNT FROM OPN_USER_CARTS C WHERE C.CREATION_DTM > CURRENT_DATE() - INTERVAL 10 DAY GROUP BY TOPICID ;

SELECT COUNT(1) FROM OPN_POSTS_RAW ; -- 1.3M

SELECT COUNT(1) FROM WEB_SCRAPE_RAW_L wsrl WHERE SCRAPE_DATE > CURRENT_DATE() - INTERVAL 3 DAY ;

SELECT * FROM WEB_SCRAPE_RAW_L wsrl ;

CALL WSR_DEDUPE(SCRAPESRC varchar(45), srcTable varchar(45)) ;

