-- DEBUGGING THE CLEAN_POST_FLAG ISSUE - WHERE EVERYTHING IS TURNING INTO A BLOCKED POST

SELECT * FROM OPN_USERLIST WHERE USERNAME = 'AST121022' ; -- 1026625
SELECT * FROM OPN_POSTS WHERE POST_BY_USERID = 1026625 ORDER BY POST_ID DESC LIMIT 100 ;

-- CHECK IF THE DOMAIN.EXT HAS BEEN CORRECTLY SAVED IN THE POST

-- NOW CHECK IF THE CLEAN_POST_FLAG cursor IS CORRECTLY CAPTURING THE DATA

SELECT POST_ID, POST_BY_USERID, EMBEDDED_CONTENT , LENGTH(EMBEDDED_CONTENT) - LENGTH(REPLACE(EMBEDDED_CONTENT, ',', ''))+1  AS count FROM OPN_POSTS_RAW where post_id = 1223604 ;

-- NOW CHECK IF THE DOMAIN EXTRACT OPERATION IS DOING PROPERLY IN THE CLEAN_POST_FLAG

SELECT TRIM(substring_index('apple.news', ',', 1)) ;

-- IF THE DOMAIN.EXT IS CORRECTLY BEING CAPTURED BY THE EXTARCT SQL, THEN CHECK IF THE DOMAIN.EXT IS IN THE LIST OF CLEAN DOMAINS

select * from OPN_CLEAN_DOMAINS WHERE SITE_NAME = (SELECT TRIM(substring_index('apple.news', ',', 1))) ;

-- IF IT IS NOT THERE, THEN WHITELIST IT. BUT FIRST CHECK IF ANY OTHER VERSION OF IT IS THERE

select * from OPN_CLEAN_DOMAINS WHERE SITE_NAME LIKE '%APPLE.%' ;
CALL addCleanDomain('apple.news', 'WWW.apple.news', 'apple.news' ) ;
