-- DB CHANGES and DB POPULATE SQL

ALTER TABLE `opntprod`.`OPN_USERLIST` 
ADD COLUMN `INVITEE_FLAG` VARCHAR(3) NULL AFTER `CHAT_FLAG`,
ADD COLUMN `INVITER_UNAME` VARCHAR(45) NULL AFTER `INVITEE_FLAG`,
ADD COLUMN `INVITER_UID` INT NULL AFTER `INVITER_UNAME`;

ALTER TABLE `charcha`.`OPN_P_KW` 
CHANGE COLUMN `KEYWORDS` `KEYWORDS` VARCHAR(60) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL ;
ALTER TABLE `charcha`.`OPN_P_KW` 
CHANGE COLUMN `KW_TRIM` `KW_TRIM` VARCHAR(60) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL ;
ALTER TABLE `charcha`.`OPN_P_KW` 
CHANGE COLUMN `SCRAPE_TAG1` `SCRAPE_TAG1` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL ;
ALTER TABLE `charcha`.`OPN_P_KW` 
CHANGE COLUMN `SCRAPE_TAG2` `SCRAPE_TAG2` VARCHAR(60) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL ;

INSERT INTO charcha.OPN_TOPICS SELECT * FROM opntprod.OPN_TOPICS ;
SELECT * FROM charcha.OPN_TOPICS ;
INSERT INTO charcha.OPN_P_KW SELECT * FROM opntprod.OPN_P_KW WHERE COUNTRY_CODE IN ('IND', 'GGG') OR ORIGIN_COUNTRY_CODE IN ('IND', 'GGG') ;
SELECT * FROM charcha.OPN_P_KW ORDER BY KEYID DESC ;
INSERT INTO charcha.OPN_KW_TAGS SELECT * FROM opntprod.OPN_KW_TAGS WHERE COUNTRY_CODE IN ('IND', 'GGG') OR ORIGIN_COUNTRY_CODE IN ('IND', 'GGG') ;
SELECT * FROM charcha.OPN_KW_TAGS ORDER BY KEYID DESC ;
INSERT INTO charcha.OPN_USERLIST SELECT * FROM opntprod.OPN_USERLIST ;
INSERT INTO charcha.OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT C.CART, C.KEYID, C.USERID, C.TOPICID, C.CREATION_DTM, C.LAST_UPDATE_DTM
FROM opntprod.OPN_USER_CARTS C, OPN_P_KW K WHERE C.KEYID = K.KEYID AND (K.COUNTRY_CODE IN ('IND', 'GGG') OR K.ORIGIN_COUNTRY_CODE IN ('IND', 'GGG') );

INSERT INTO charcha.OPN_POSTS_RAW(TOPICID, POST_DATETIME, POST_BY_USERID, POST_CONTENT, EMBEDDED_CONTENT,  EMBEDDED_FLAG
, TAG1_KEYID, TAG2_KEYID, TAG3_KEYID, CLEAN_POST_FLAG, POST_UPDATE_DTM, DEMO_POST_FLAG, POSTOR_COUNTRY_CODE, POSTOR_TYPE_TAG
, POST_PROCESSED_FLAG, POST_PROCESSED_DTM, SCRAPE_ROW_ID, STP_PROC_NAME, MEDIA_CONTENT, MEDIA_FLAG, URL_TITLE
, URL_EXCERPT, SEARCH_STRING)
SELECT TOPICID, POST_DATETIME, POST_BY_USERID, POST_CONTENT, EMBEDDED_CONTENT, IFNULL(EMBEDDED_FLAG, 'N') EMBEDDED_FLAG
, TAG1_KEYID, TAG2_KEYID, TAG3_KEYID, CLEAN_POST_FLAG, IFNULL(POST_UPDATE_DTM, POST_DATETIME) POST_UPDATE_DTM
, DEMO_POST_FLAG, POSTOR_COUNTRY_CODE, POSTOR_TYPE_TAG, POST_PROCESSED_FLAG, POST_PROCESSED_DTM
, SCRAPE_ROW_ID, STP_PROC_NAME, MEDIA_CONTENT, MEDIA_FLAG, URL_TITLE, URL_EXCERPT, SEARCH_STRING
FROM opntprod.OPN_POSTS_RAW P, opntprod.OPN_USERLIST U WHERE P.POST_BY_USERID = U.USERID AND (U.COUNTRY_CODE IN ('IND', 'GGG') ) 
AND U.BOT_FLAG = 'Y' AND POST_DATETIME > CURRENT_DATE() - INTERVAL 5 DAY ORDER BY POST_ID ;

SELECT COUNT(1) FROM charcha.OPN_POSTS_RAW ;

SELECT POST_ID, TOPICID, POST_DATETIME, POST_BY_USERID, POST_CONTENT, EMBEDDED_CONTENT, IFNULL(EMBEDDED_FLAG, 'N') EMBEDDED_FLAG
, TAG1_KEYID, TAG2_KEYID, TAG3_KEYID, CLEAN_POST_FLAG, IFNULL(POST_UPDATE_DTM, POST_DATETIME) POST_UPDATE_DTM
, DEMO_POST_FLAG, POSTOR_COUNTRY_CODE, POSTOR_TYPE_TAG, POST_PROCESSED_FLAG, POST_PROCESSED_DTM
, SCRAPE_ROW_ID, STP_PROC_NAME, MEDIA_CONTENT, MEDIA_FLAG, URL_TITLE, URL_EXCERPT, SEARCH_STRING
FROM opntprod.OPN_POSTS_RAW P, opntprod.OPN_USERLIST U WHERE P.POST_BY_USERID = U.USERID AND (U.COUNTRY_CODE IN ('IND', 'GGG') ) 
AND U.BOT_FLAG = 'Y' AND POST_DATETIME > CURRENT_DATE() - INTERVAL 500 DAY ORDER BY POST_ID LIMIT 100 ;

CREATE TABLE `opntprod`.`OPN_INVITE_ACCEPT_LOG` (
  `ROW_ID` INT NOT NULL AUTO_INCREMENT,
  `INVITE_ID` INT NULL,
  `INVITE_TYPE` VARCHAR(45) NULL,
  `INVITER_UUID` VARCHAR(45) NULL,
  `INVITER_UID` INT NULL,
  `INVITER_UNAME` VARCHAR(45) NULL,
  `INVITE_POSTID` INT NULL,
  `INVITE_TID` INT NULL,
  `INVITE_DTM` DATETIME NULL,
  `INVITEE_UUID` VARCHAR(45) NULL,
  `INVITEE_UID` INT NULL,
  `INVITEE_UNAME` VARCHAR(45) NULL,
  `INVITEE_UTYPE` VARCHAR(5) NULL,
  `INVITE_TRX_CONCAT` VARCHAR(250) NULL,
  PRIMARY KEY (`ROW_ID`));
  
  ALTER TABLE `opntprod`.`OPN_INVITE_ACCEPT_LOG` 
ADD COLUMN `INVITE_ACCEPT_DTM` DATETIME NULL AFTER `INVITE_TRX_CONCAT`;

ALTER TABLE `opntprod`.`OPN_INVITE_ACCEPT_LOG` 
ADD COLUMN `COPYKID` INT NULL AFTER `INVITE_ACCEPT_DTM`,
ADD COLUMN `CARTTO` VARCHAR(5) NULL AFTER `COPYKID`;

ALTER TABLE `opntprod`.`OPN_POSTS` 
ADD COLUMN `DELETED_FLAG` VARCHAR(5) NULL AFTER `SEARCH_STRING`;

ALTER TABLE `opntprod`.`OPN_POSTS_RAW` 
ADD COLUMN `DELETED_FLAG` VARCHAR(5) NULL AFTER `SEARCH_STRING`;

CREATE TABLE `opntprod`.`OPN_INVITE_LOG` (
  `INVITE_BYUUID` VARCHAR(45) NULL,
  `INVITE_BYUID` INT NOT NULL,
  `INVITE_POSTID` INT NOT NULL,
  `INVITE_UUID` VARCHAR(45) NULL,
  `INVITE_DTM` DATETIME NULL,
  `INVITE_LAST_ACCEPT_DTM` DATETIME NULL,
  PRIMARY KEY (`INVITE_BYUID`, `INVITE_POSTID`));
  
  CREATE TABLE `opntprod`.`OPN_POST_BOOKMARKS` (
  `ROW_ID` INT NOT NULL AUTO_INCREMENT,
  `TOPICID` INT NULL,
  `USERID` INT NULL,
  `POST_BYUID` INT NULL,
  `POST_ID` INT NULL,
  `BOOKMARK_DTM` DATETIME NULL,
  `BKM_REMOVE_DTM` DATETIME NULL,
  `ACTIVE_FLAG` VARCHAR(5) NULL,
  PRIMARY KEY (`ROW_ID`));
  
CREATE TABLE `opntprod`.`OPN_POST_RETAG_RECORD` (
  `TOPICID` INT NOT NULL,
  `POST_ID` INT NOT NULL,
  `OLD_TAG1_KID` INT NOT NULL,
  `NEW_TAG1_KID` INT NULL,
  `RETAG_DTM` DATETIME NULL,
  PRIMARY KEY (`TOPICID`, `POST_ID`, `OLD_TAG1_KID`));
  
ALTER TABLE `opntprod`.`OPN_KW_TAGS` 
ADD COLUMN `KW_EXT` LONGTEXT NULL AFTER `NEWS_ONLY_FLAG`,
ADD COLUMN `ALT_KEYID` INT NULL AFTER `KW_EXT`;

ALTER TABLE `opntprod`.`OPN_P_KW` 
ADD COLUMN `KW_EXT` LONGTEXT NULL AFTER `KW_EXT`,
ADD COLUMN `ALT_KEYID` INT NULL AFTER `KW_EXT`;

ALTER TABLE `opntprod`.`OPN_KW_TAGS` 
ADD COLUMN `KW_URL` LONGTEXT NULL AFTER `KW_EXT` ;

ALTER TABLE `opntprod`.`OPN_P_KW` 
ADD COLUMN `KW_URL` LONGTEXT NULL AFTER `KW_EXT` ;

ALTER TABLE `opntprod`.`OPN_P_KW` 
ADD UNIQUE INDEX `ALT_KID` (`ALT_KEYID` ASC) ; 

CREATE TABLE `opntprod`.`OPN_POST_TO_KW_LOG` (
  `ROW_ID` INT NOT NULL AUTO_INCREMENT,
  `TOPICID` TINYINT(1) NULL,
  `POST_ID` INT NULL,
  `KEYID` INT NULL,
  `POST_TO_KW_DTM` DATETIME NULL,
  PRIMARY KEY (`ROW_ID`));

ALTER TABLE `opntprod`.`OPN_POSTS` 
ADD COLUMN `KEYID` INT NULL DEFAULT NULL AFTER `POST_QUALITY`;

ALTER TABLE `opntprod`.`OPN_USER_POST_ACTION` 
ADD COLUMN `KEYID` INT NULL DEFAULT NULL AFTER `ACTION_TYPE`;

CREATE TABLE `opntprod`.`OPN_RAW_LOGS` (
  `ROW_ID` INT NOT NULL AUTO_INCREMENT,
  `KEYVALUE_KEY` VARCHAR(250) NULL,
  `KEYVALUE_VALUE` VARCHAR(450) NULL,
  `LOG_DTM` DATETIME NULL,
  PRIMARY KEY (`ROW_ID`));
  
  ALTER TABLE `opntprod`.`OPN_KW_TAGS` 
CHANGE COLUMN `KEYWORDS` `KEYWORDS` VARCHAR(160) NULL DEFAULT NULL ,
CHANGE COLUMN `KW_TRIM` `KW_TRIM` VARCHAR(160) NULL DEFAULT NULL ;

ALTER TABLE `opntprod`.`OPN_P_KW` 
CHANGE COLUMN `KEYWORDS` `KEYWORDS` VARCHAR(160) CHARACTER SET 'latin1' NOT NULL ,
CHANGE COLUMN `KW_TRIM` `KW_TRIM` VARCHAR(160) CHARACTER SET 'latin1' NULL DEFAULT NULL ;

ALTER TABLE `opntprod`.`OPN_USERLIST` 
ADD COLUMN `TRUE_COUNTRY_CODE` VARCHAR(5) NULL AFTER `INVITER_UID`;

ALTER TABLE `opntprod`.`OPN_POSTS_RAW` 
ADD COLUMN `SCRAPE_TYPE` VARCHAR(15) NULL AFTER `DELETED_FLAG`,
ADD COLUMN `SCRAPE_SOURCE` VARCHAR(85) NULL AFTER `SCRAPE_TYPE`,
ADD COLUMN `EXTRA_ATTRIB1` VARCHAR(145) NULL AFTER `SCRAPE_SOURCE`,
ADD COLUMN `EXTRA_ATTRIB2` INT NULL AFTER `EXTRA_ATTRIB1`,
ADD COLUMN `EXTRA_ATTRIB3` DATETIME NULL AFTER `EXTRA_ATTRIB2`,
ADD COLUMN `EXTRA_ATTRIB4` LONGTEXT NULL AFTER `EXTRA_ATTRIB3`,
ADD COLUMN `EXTRA_ATTRIB5` FLOAT NULL AFTER `EXTRA_ATTRIB4`;

ALTER TABLE `opntprod`.`OPN_POSTS` 
ADD COLUMN `SCRAPE_TYPE` VARCHAR(15) NULL AFTER `KEYID`,
ADD COLUMN `SCRAPE_SOURCE` VARCHAR(85) NULL AFTER `SCRAPE_TYPE`,
ADD COLUMN `EXTRA_ATTRIB1` VARCHAR(145) NULL AFTER `SCRAPE_SOURCE`,
ADD COLUMN `EXTRA_ATTRIB2` INT NULL AFTER `EXTRA_ATTRIB1`,
ADD COLUMN `EXTRA_ATTRIB3` DATETIME NULL AFTER `EXTRA_ATTRIB2`,
ADD COLUMN `EXTRA_ATTRIB4` LONGTEXT NULL AFTER `EXTRA_ATTRIB3`,
ADD COLUMN `EXTRA_ATTRIB5` FLOAT NULL AFTER `EXTRA_ATTRIB4`;







