-- LIST OF DISCREPANCIES IN THE DATA

SET SQL_SAFE_UPDATES = 0;

SELECT DISTINCT USERID FROM OPN_NW_STATS WHERE USERID NOT IN  (SELECT USERID FROM OPN_USERLIST) ; -- 146

SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE USERID NOT IN  (SELECT USERID FROM OPN_USERLIST) ; -- 44

-- CLEAN UP OF THESE 2 DISCREPANCIES

DELETE FROM OPN_NW_STATS WHERE USERID NOT IN  (SELECT USERID FROM OPN_USERLIST) ;

DELETE FROM OPN_USER_CARTS WHERE USERID NOT IN  (SELECT USERID FROM OPN_USERLIST) ; -- 44

-- 

SELECT * FROM OPN_USER_CARTS WHERE USERID IS NULL ;

SELECT * FROM OPN_USER_CARTS WHERE KEYID IS NULL ;

SELECT * FROM OPN_USER_CARTS WHERE TOPICID IS NULL ;

SELECT * FROM OPN_USER_CARTS WHERE CART IS NULL ;

DELETE FROM OPN_USER_CARTS WHERE USERID IS NULL ;

DELETE FROM OPN_USER_CARTS WHERE KEYID IS NULL ;

-- 

SELECT * FROM OPN_POSTS_RAW WHERE POST_BY_USERID IS NULL ;
SELECT * FROM OPN_POSTS_RAW WHERE POST_CONTENT IS NULL ;

SELECT * FROM OPN_POSTS WHERE POST_BY_USERID IS NULL ;

UPDATE OPN_POSTS SET CLEAN_POST_FLAG = 'Z' WHERE POST_BY_USERID IS NULL AND POST_ID = 1208279 ;
SELECT * FROM OPN_POSTS WHERE TOPICID IS NULL ;

DELETE FROM OPN_POSTS_RAW WHERE POST_BY_USERID IS NULL ;
DELETE FROM OPN_POSTS WHERE POST_BY_USERID IS NULL ;

SELECT * FROM OPN_KW_TAGS WHERE KEYID IN (105573) ;

SELECT COUNT(*) FROM OPN_USER_CARTS WHERE KEYID = 105573 ;

SELECT COUNT(1) FROM OPN_POSTS WHERE TAG1_KEYID = 105573 ;

SELECT DISTINCT C.USERID FROM OPN_USER_CARTS C, OPN_USERLIST U1
WHERE C.KEYID = 105573 AND C.CART = 'H' AND C.USERID = U1.USERID AND U1.COUNTRY_CODE = 'USA' 
AND U1.BOT_FLAG = 'Y' ORDER BY RAND() LIMIT 1 ;

-- KEYWORDS IN CARTS THAT HAVE WRONG TOPICIDS IN CART COMPARED TO OPNPKW

SELECT C.USERID, U.USERNAME, C.ROW_ID, C.TOPICID, C.KEYID, K.KEYWORDS, K.TOPICID, C.CART, C.LAST_UPDATE_DTM 
FROM OPN_USER_CARTS C, OPN_P_KW K, OPN_USERLIST U
WHERE  C.KEYID = K.KEYID AND C.USERID = U.USERID AND C.TOPICID <> K.TOPICID
ORDER BY C.LAST_UPDATE_DTM DESC ;

SELECT ROW_ID FROM (
SELECT C.USERID, U.USERNAME, C.ROW_ID, C.TOPICID CTID, C.KEYID, K.KEYWORDS, K.TOPICID KTID, C.CART, C.LAST_UPDATE_DTM 
FROM OPN_USER_CARTS C, OPN_P_KW K, OPN_USERLIST U
WHERE  C.KEYID = K.KEYID AND C.USERID = U.USERID AND C.TOPICID <> K.TOPICID
)Q  ;

DELETE FROM OPN_USER_CARTS WHERE ROW_ID IN (
SELECT ROW_ID FROM (
SELECT C.USERID, U.USERNAME, C.ROW_ID, C.TOPICID CTID, C.KEYID, K.KEYWORDS, K.TOPICID KTID, C.CART, C.LAST_UPDATE_DTM 
FROM OPN_USER_CARTS C, OPN_P_KW K, OPN_USERLIST U
WHERE  C.KEYID = K.KEYID AND C.USERID = U.USERID AND C.TOPICID <> K.TOPICID
)Q 
);

-- Same user + topic + keyid in a cart having 2 or more rows (This means some keyword is showing up twice)

SELECT USERID, TOPICID, KEYID, COUNT(1), MAX(LAST_UPDATE_DTM) FROM OPN_USER_CARTS 
GROUP BY USERID, TOPICID, KEYID HAVING COUNT(1) > 1 ORDER BY 5 DESC ;

CREATE TABLE DUPE_CART_ROWS AS SELECT * FROM OPN_USER_CARTS WHERE ROW_ID IN (
SELECT UC1.ROW_ID FROM OPN_USER_CARTS UC1,
(SELECT USERID, TOPICID, KEYID, COUNT(1) FROM OPN_USER_CARTS GROUP BY USERID, TOPICID, KEYID HAVING COUNT(1) > 1) UC2 
WHERE UC1.USERID = UC2.USERID AND UC1.TOPICID = UC2.TOPICID AND UC1.KEYID = UC2.KEYID
) ;
 
DELETE FROM OPN_USER_CARTS WHERE ROW_ID IN (SELECT ROW_ID FROM DUPE_CART_ROWS) ;

SELECT COUNT(1) FROM OPN_USER_CARTS ; -- 233826

TRUNCATE TABLE DUPE_CART_ROWS ;

-- 

-- Find Users who have no cart

SELECT * FROM OPN_USERLIST WHERE COUNTRY_CODE = 'USA' -- AND USERNAME LIKE '
AND USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE USERID IS NOT NULL) ; -- 17434
SELECT COUNT(DISTINCT USERID) FROM OPN_USER_CARTS ;

SELECT * FROM OPN_USER_CARTS WHERE USERID IN (1008922, 1009934, 1008031, 1009225, 1009553, 1009718, 1009719, 1009720) ;
