/* DEBUG MULTI INTERESTS IN PROFILE */
SELECT * FROM OPN_USERLIST order by USERID desc ; -- 1023365

SELECT * FROM OPN_USER_INTERESTS WHERE USERID = 1053689 ;
SELECT * FROM OPN_USER_CARTS WHERE USERID = 1053689 ;

INSERT INTO OPN_USER_INTERESTS(USERID, USER_UUID, INTEREST_ID, INTEREST_NAME, INTEREST_CODE, CREATION_DTM, SELECTED_KW_COUNT, USERNAME)
SELECT UI.USERID, U.USER_UUID, UI.INTEREST_ID, T.TOPIC, T.CODE INTEREST_CODE, NOW() CREATION_DTM, UI.SELECTED_KW_COUNT, U.USERNAME 
FROM (SELECT USERID, TOPICID INTEREST_ID, COUNT(DISTINCT KEYID) SELECTED_KW_COUNT FROM OPN_USER_CARTS WHERE USERID = 1053689 GROUP BY USERID, TOPICID) UI
, (SELECT USERID, USER_UUID, USERNAME FROM OPN_USERLIST WHERE USERID = 1053689) U, OPN_TOPICS T
WHERE UI.USERID = U.USERID AND UI.INTEREST_ID = T.TOPICID AND UI.USERID = 1053689 ;
