-- 

-- deleteBulkPosts

 DELIMITER //
DROP PROCEDURE IF EXISTS deleteBulkPosts //
CREATE PROCEDURE deleteBulkPosts(postidfrom INT, postidto INT)
BEGIN

DELETE FROM OPN_POSTS_RAW   WHERE OPN_POSTS_RAW.POST_ID BETWEEN postidfrom AND postidto ;

DELETE FROM OPN_POSTS   WHERE OPN_POSTS.POST_ID BETWEEN postidfrom AND postidto ;

DELETE FROM OPN_POST_COMMENTS_RAW  WHERE OPN_POST_COMMENTS_RAW.CAUSE_POST_ID BETWEEN postidfrom AND postidto ;

DELETE FROM OPN_POST_COMMENTS  WHERE OPN_POST_COMMENTS.CAUSE_POST_ID BETWEEN postidfrom AND postidto ;

DELETE FROM OPN_POST_COMMENTS_RAW  WHERE OPN_POST_COMMENTS_RAW.CAUSE_POST_ID BETWEEN postidfrom AND postidto ;

DELETE FROM OPN_USER_POST_ACTION  WHERE OPN_USER_POST_ACTION.CAUSE_POST_ID BETWEEN postidfrom AND postidto ;

DELETE FROM OPN_USER_USER_ACTION  WHERE OPN_USER_USER_ACTION.CAUSE_POST_ID BETWEEN postidfrom AND postidto ;

DELETE FROM OPN_UPA_DELETED  WHERE OPN_UPA_DELETED.CAUSE_POST_ID BETWEEN postidfrom AND postidto ;


END //
DELIMITER ;

-- 