-- deleteUserByUsername

DELIMITER //
DROP PROCEDURE IF EXISTS deleteUserByUsername //
CREATE PROCEDURE deleteUserByUsername(uname varchar(30))
BEGIN

SET SQL_SAFE_UPDATES = 0;

DELETE FROM OPN_NC_CLUSTERS WHERE USERID = (SELECT USERID FROM OPN_USERLIST WHERE UPPER(USERNAME) = UPPER(uname));

DELETE FROM OPN_POSTS_RAW WHERE POST_BY_USERID = (SELECT USERID FROM OPN_USERLIST WHERE UPPER(USERNAME) = UPPER(uname));

DELETE FROM OPN_POSTS WHERE POST_BY_USERID = (SELECT USERID FROM OPN_USERLIST WHERE UPPER(USERNAME) = UPPER(uname));

DELETE FROM OPN_POST_COMMENTS_RAW WHERE COMMENT_BY_USERID = (SELECT USERID FROM OPN_USERLIST WHERE UPPER(USERNAME) = UPPER(uname));

DELETE FROM OPN_POST_COMMENTS WHERE COMMENT_BY_USERID = (SELECT USERID FROM OPN_USERLIST WHERE UPPER(USERNAME) = UPPER(uname));

DELETE FROM OPN_USER_POST_ACTION WHERE ACTION_BY_USERID = (SELECT USERID FROM OPN_USERLIST WHERE UPPER(USERNAME) = UPPER(uname));

DELETE FROM OPN_USER_USER_ACTION WHERE BY_USERID = (SELECT USERID FROM OPN_USERLIST WHERE UPPER(USERNAME) = UPPER(uname));

DELETE FROM OPN_USER_CARTS WHERE USERID = (SELECT USERID FROM OPN_USERLIST WHERE UPPER(USERNAME) = UPPER(uname));

DELETE FROM OPN_USERLIST WHERE UPPER(USERNAME) = UPPER(uname);

  
END //
DELIMITER ;

-- 