-- deleteCartByUIDTID

-- PROC TO KILL A USER'S CART BY UID, TID

DELIMITER //
DROP PROCEDURE IF EXISTS deleteCartByUIDTID //
CREATE PROCEDURE deleteCartByUIDTID(uid INT, tid INT)
BEGIN

SET SQL_SAFE_UPDATES = 0;

DELETE FROM OPN_NC_CLUSTERS WHERE USERID = uid AND TOPICID = tid ;

DELETE FROM OPN_USER_CARTS WHERE USERID = uid AND TOPICID = tid ;

DELETE FROM OPN_CART_ARCHIVE WHERE USERID = uid AND TOPICID = tid ;
  
END //
DELIMITER ;

-- 