/* SCRIPT TO DELETE OLD POSTS - TO REDUCE THE POST VOLUME */

/* STEP 1.1: disable the POST_DELETE trigger from OPN_POSTS */

DROP TRIGGER IF EXISTS POST_DELETE ;

/* STEP 1.2: Also disable the other triggers from the tables that we are going to delete from manually */

DROP TRIGGER IF EXISTS POST_COMMENT_DELETE ;

/* STEP 2: Prepare the DELETE statements that were part of the POST_DELETE trigger */

DELETE FROM OPN_POST_COMMENTS WHERE OPN_POST_COMMENTS.CAUSE_POST_ID = OLD.POST_ID ;

DELETE FROM OPN_USER_POST_ACTION WHERE OPN_USER_POST_ACTION.CAUSE_POST_ID = OLD.POST_ID ;

DELETE FROM OPN_POST_SEARCH_T WHERE OPN_POST_SEARCH_T.POST_ID = OLD.POST_ID ;

/* STEP 3: Start with deleting very old Bot posts */

SELECT * FROM OPN_POSTS_RAW WHERE POST_ID < 201 ;
SELECT * FROM OPN_POSTS WHERE POST_ID < 201 ;


SELECT COUNT(1) FROM OPN_POSTS_RAW WHERE POST_DATETIME < CURRENT_DATE - INTERVAL 12 MONTH ;
SELECT * FROM OPN_POST_COMMENTS WHERE CAUSE_POST_ID < 201 ;
SELECT * FROM OPN_USER_POST_ACTION WHERE CAUSE_POST_ID < 201 ;

SELECT * FROM OPN_POSTS WHERE KEYID IS NOT NULL ;