SELECT * FROM OPN_POSTS ORDER BY POST_ID DESC ;
SELECT * FROM OPN_USER_CARTS ORDER BY ROW_ID DESC ;
SELECT * FROM OPN_P_KW ORDER BY KEYID DESC ;
SELECT * FROM OPN_SFC_CONTENT ORDER BY ROW_ID DESC ;
SELECT * FROM OPN_SFC_CONTENT WHERE ROW_ID = 11203 ; ;
SELECT * FROM OPN_USER_POST_ACTION ORDER BY ROW_ID DESC ;
SELECT * FROM OPN_POST_COMMENTS ORDER BY ROW_ID DESC ;
CALL createTCCDiscussion(11232) ;
DELETE FROM OPN_SFC_CONTENT WHERE ROW_ID = 11205 ;
DELETE FROM OPN_POSTS WHERE POST_ID = 1645160 ;

 SELECT TOPICID, COUNTRY_CODE, TRUE_COUNTRY_CODE, CONTENT_TITLE, CASE WHEN CONTENT_TONE = 'LOVE' THEN 'L1' ELSE 'H1' END 
 , CONTENT_CAMP, CONTENT_URL, COMMENT1_TEXT, COMMENT1_CAMP, CASE WHEN CONTENT_TONE = 'LOVE' THEN 'L1' ELSE 'H1' END
 , COMMENT2_TEXT, COMMENT2_CAMP, CASE WHEN CONTENT_TONE = 'LOVE' THEN 'H1' ELSE 'L1' END, CONVERTED_POST_ID FROM OPN_SFC_CONTENT WHERE ROW_ID = 11204 ;
 
 SELECT USERID, USER_UUID, USERNAME, COUNTRY_CODE, TRUE_COUNTRY_CODE, OPINION_CAMP FROM OPN_USERLIST WHERE USER_UUID = '06b3b485-2a40-11e7-a7ad-064c86fddcc0' ;
 
 SELECT USERID, USERNAME, USER_UUID, TRUE_COUNTRY_CODE, COUNTRY_CODE, OPINION_CAMP 
 FROM OPN_USERLIST WHERE OPINION_CAMP IS NOT NULL AND COUNTRY_CODE = 'USA' AND TRUE_COUNTRY_CODE = 'USA' AND OPINION_CAMP = 'REPUB' ORDER BY RAND() LIMIT 1 ;
 
 SELECT * FROM OPN_SFC_CONTENT WHERE CONVERTED_POST_ID IS NULL AND TRUE_COUNTRY_CODE = 'USA' ORDER BY ROW_ID DESC ;
 
 CALL userActionCommon('069a6abb-2a40-11e7-a7ad-064c86fddcc0', 'POST', 'L1', 1645417) ;
 
 SELECT TOPICID, POST_BY_USERID, IFNULL(KEYID, 0), SUBSTR(POST_CONTENT, 1, 100)  FROM OPN_POSTS WHERE POST_ID = 1645417 ;
 
 SELECT * FROM  OPN_POSTS WHERE POST_DATETIME > CURRENT_DATE() - INTERVAL 10 DAY ;
 

 SELECT KEYID, POSTOR_COUNTRY_CODE, POSTOR_TCC, POST_BY_USERID, POST_CONTENT, POST_DATETIME, POST_ID, POST_URL, STP_PROC_NAME, TOPICID, URL_TITLE
FROM OPN_POSTS WHERE POST_DATETIME > CURRENT_DATE() - INTERVAL 100 DAY ;

SELECT COMMENT_ID, CAUSE_POST_ID, POST_BY_USERID, TOPICID, PARENT_COMMENT_ID, PARENT_COMMENT_CONTENT,  PARENT_COMMENT_BYUID, PARENT_COMMENT_DTM, PARENT_COMMENT_UNAME
, COMMENT_CONTENT, COMMENT_BY_USERID, COMMENT_BY_UNAME, COMMENT_DTM, COMMENT_TYPE
FROM OPN_POST_COMMENTS WHERE COMMENT_DTM > CURRENT_DATE() - INTERVAL 30 DAY ;

SELECT USERID, USER_UUID, USERNAME, CREATION_DATE, COUNTRY_CODE, TRUE_COUNTRY_CODE, OPINION_CAMP FROM OPN_USERLIST WHERE BOT_FLAG = 'Y'  ;

SELECT  ROW_ID, TOPICID, INTEREST, COUNTRY_CODE, TRUE_COUNTRY_CODE, TRUE_COUNTRY_NAME, CONTENT_DTM, NEWS_TITLE, CONTENT_TITLE, CONTENT_URL
, CONTENT_TONE, CONTENT_CAMP, COMMENT1_TEXT, COMMENT1_TONE, COMMENT1_CAMP, COMMENT2_TEXT, COMMENT2_TONE, COMMENT2_CAMP, CONVERTED_POST_ID
FROM OPN_SFC_CONTENT WHERE CONVERTED_POST_ID IS NOT NULL AND CONTENT_DATE > CURRENT_DATE() - INTERVAL 50 DAY  ;

SELECT ROW_ID,  FROM OPN_USER_POST_ACTION ORDER BY ROW_ID DESC LIMIT 100 ;

CREATE TABLE `OPN_POSTS` (
  `ROW_ID` int NOT NULL AUTO_INCREMENT,
  `POST_ID` int NOT NULL,
  `TOPICID` int DEFAULT NULL,
  `POST_DATETIME` datetime DEFAULT NULL,
  `POST_BY_USERID` int DEFAULT NULL,
  `POST_CONTENT` varchar(10000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POST_URL` longtext COLLATE utf8mb4_unicode_ci,
  `EMBEDDED_CONTENT` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EMBEDDED_FLAG` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TAG1_KEYID` int DEFAULT NULL,
  `TAG2_KEYID` int DEFAULT NULL,
  `TAG3_KEYID` int DEFAULT NULL,
  `CLEAN_POST_FLAG` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'N',
  `POST_UPDATE_DTM` datetime DEFAULT NULL,
  `DEMO_POST_FLAG` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'Y',
  `POSTOR_COUNTRY_CODE` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POSTOR_TCC` varchar(5) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POSTOR_TYPE_TAG` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POST_PROCESSED_FLAG` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'N',
  `POST_PROCESSED_DTM` datetime DEFAULT NULL,
  `SCRAPE_ROW_ID` int DEFAULT NULL,
  `STP_PROC_NAME` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MEDIA_CONTENT` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MEDIA_FLAG` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `URL_TITLE` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `URL_EXCERPT` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SEARCH_STRING` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `DELETED_FLAG` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POST_SCORE` smallint DEFAULT NULL,
  `POST_QUALITY` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `KEYID` int DEFAULT NULL,
  `SCRAPE_TYPE` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SCRAPE_SOURCE` varchar(85) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EXTRA_ATTRIB1` varchar(145) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EXTRA_ATTRIB2` int DEFAULT NULL,
  `EXTRA_ATTRIB3` datetime DEFAULT NULL,
  `EXTRA_ATTRIB4` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `EXTRA_ATTRIB5` float DEFAULT NULL,
  PRIMARY KEY (`ROW_ID`,`POST_ID`),
  KEY `POST_UI` (`POST_BY_USERID`),
  KEY `POST_DT` (`POST_DATETIME`),
  KEY `POST_T` (`TOPICID`),
  KEY `POST_CC` (`POSTOR_COUNTRY_CODE`),
  KEY `POST_CF` (`CLEAN_POST_FLAG`),
  KEY `POST_SCRID` (`SCRAPE_ROW_ID`),
  KEY `POST_POSTID` (`POST_ID`),
  KEY `POST_UIT` (`POST_BY_USERID`,`TOPICID`),
  KEY `POST_TAG1` (`TAG1_KEYID`),
  KEY `POST_PROC_DTM` (`POST_PROCESSED_DTM`),
  KEY `POST_QUALITY` (`POST_QUALITY`),
  KEY `DEMO_POST` (`DEMO_POST_FLAG`),
  KEY `STP_PROC` (`STP_PROC_NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=1531766 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



 