
-- findCartByUName

 DELIMITER //
DROP PROCEDURE IF EXISTS findCartByUName //
CREATE PROCEDURE findCartByUName(TID INT, UName varchar(50))
BEGIN

CASE WHEN TID = 0 THEN

SELECT K.TOPICID, K.KEYID, K.KEYWORDS, C.CART, K.COUNTRY_CODE
FROM OPN_P_KW K, OPN_USER_CARTS C, OPN_USERLIST U
WHERE U.USERNAME = UName
AND U.USERID = C.USERID
AND U.COUNTRY_CODE = K.COUNTRY_CODE
AND C.KEYID = K.KEYID
ORDER BY K.TOPICID, C.CART, K.KEYWORDS;

WHEN TID > 0 THEN

SELECT K.TOPICID, K.KEYID, K.KEYWORDS, C.CART, K.COUNTRY_CODE
FROM OPN_P_KW K, OPN_USER_CARTS C, OPN_USERLIST U
WHERE U.USERNAME = UName
AND U.USERID = C.USERID
AND U.COUNTRY_CODE = K.COUNTRY_CODE
AND C.KEYID = K.KEYID AND C.TOPICID = TID
ORDER BY K.TOPICID, C.CART, K.KEYWORDS;

END CASE;


END //
DELIMITER ;

-- 