-- findCartByUID

 DELIMITER //
DROP PROCEDURE IF EXISTS findCartByUID //
CREATE PROCEDURE findCartByUID(TID INT, UID INT)
BEGIN

CASE WHEN TID = 0 THEN

SELECT C.TOPICID, C.KEYID, K.KEYWORDS, C.CART, K.COUNTRY_CODE, U.USERNAME
FROM OPN_P_KW K, OPN_USER_CARTS C, OPN_USERLIST U
WHERE U.USERID = UID
AND U.USERID = C.USERID
-- AND U.COUNTRY_CODE = K.COUNTRY_CODE
AND C.KEYID = K.KEYID
ORDER BY C.TOPICID, C.CART, K.KEYWORDS;

WHEN TID > 0 THEN

SELECT C.TOPICID, C.KEYID, K.KEYWORDS, C.CART, K.COUNTRY_CODE, U.USERNAME
FROM OPN_P_KW K, OPN_USER_CARTS C, OPN_USERLIST U
WHERE U.USERID = UID
AND U.USERID = C.USERID
-- AND U.COUNTRY_CODE = K.COUNTRY_CODE
AND C.KEYID = K.KEYID AND C.TOPICID = TID
ORDER BY C.TOPICID, C.CART, K.KEYWORDS;

END CASE;


END //
DELIMITER ;

-- 