-- findLatestCarts

 DELIMITER //
DROP PROCEDURE IF EXISTS findLatestCarts //
CREATE PROCEDURE findLatestCarts(rcounts INT)
BEGIN

DECLARE rc INT;

SET rc = (SELECT CASE WHEN rcounts > 30 THEN 30 ELSE rcounts END) ;

SELECT DISTINCT T.TOPIC, UC.USERID, U.USERNAME, U.COUNTRY_CODE, U.USER_TYPE, DATE(UC.CREATION_DTM) CDATE, U.LAST_USED_PLATFORM
FROM OPN_USER_CARTS UC, OPN_USERLIST U, OPN_TOPICS T
WHERE UC.ROW_ID > ((SELECT MAX(ROW_ID) FROM OPN_USER_CARTS) - rc )
AND UC.USERID = U.USERID AND UC.TOPICID = T.TOPICID ORDER BY UC.CREATION_DTM DESC;



END //
DELIMITER ;

-- 