INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105087, USERID, 1, NOW(),NOW() FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND TOPICID = 1 ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105653, USERID, 4, NOW(),NOW() FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND TOPICID = 4 ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105089, USERID, 10, NOW(),NOW() FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND TOPICID = 10 ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105654, USERID, 2, NOW(),NOW() FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND TOPICID = 2 ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105655, USERID, 5, NOW(),NOW() FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND TOPICID = 5 ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105087, USERID, 1, NOW(),NOW() FROM OPN_MAIN_BOTS WHERE TCCODE = 'IND' AND TOPICID = 1 ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105653, USERID, 4, NOW(),NOW() FROM OPN_MAIN_BOTS WHERE TCCODE = 'IND' AND TOPICID = 4 ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105089, USERID, 10, NOW(),NOW() FROM OPN_MAIN_BOTS WHERE TCCODE = 'IND' AND TOPICID = 10 ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105654, USERID, 2, NOW(),NOW() FROM OPN_MAIN_BOTS WHERE TCCODE = 'IND' AND TOPICID = 2 ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105655, USERID, 5, NOW(),NOW() FROM OPN_MAIN_BOTS WHERE TCCODE = 'IND' AND TOPICID = 5 ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105087, USERID, 1, NOW(),NOW() FROM OPN_MAIN_BOTS WHERE TCCODE = 'USA' AND TOPICID = 1 ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105653, USERID, 4, NOW(),NOW() FROM OPN_MAIN_BOTS WHERE TCCODE = 'USA' AND TOPICID = 4 ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105089, USERID, 10, NOW(),NOW() FROM OPN_MAIN_BOTS WHERE TCCODE = 'USA' AND TOPICID = 10 ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105654, USERID, 2, NOW(),NOW() FROM OPN_MAIN_BOTS WHERE TCCODE = 'USA' AND TOPICID = 2 ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105655, USERID, 5, NOW(),NOW() FROM OPN_MAIN_BOTS WHERE TCCODE = 'USA' AND TOPICID = 5 ;