/*  Finding just the instream volume numbers for any specific user */

SELECT * FROM OPN_USERLIST WHERE USERNAME LIKE 'NEWDB%' ; -- 1040252 NEWDBUSER

call getDiscussionsNW(bringuuid(1040252), 1, 0, 30) ;
call getInstreamNW(bringuuid(1040252), 1, 0, 30) ;
CALL getUserCarts(1, bringuuid(1040252), 'LATEST', 0, 100) ;

/* HOW TO FIND THE NUMBER OF KWS FOR A TOPICID IN THE CARTS OF THE LATEST USERS */

SELECT U.USERID, U.USERNAME, COUNT(C.KEYID) FROM 
OPN_USERLIST U, OPN_USER_CARTS C WHERE C.USERID = U.USERID AND U.BOT_FLAG = 'N' AND U.CREATION_DATE > CURRENT_DATE() - INTERVAL 100 day
AND C.TOPICID = 1 AND U.COUNTRY_CODE = 'GGG' GROUP BY U.USERID, U.USERNAME ORDER BY 1 DESC ; 

SELECT K.KEYID, K.KEYWORDS, COUNT(C.USERID) FROM OPN_P_KW K, OPN_USER_CARTS C, OPN_USERLIST U
WHERE C.KEYID = K.KEYID AND C.USERID = U.USERID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'USA'
AND K.KEYWORDS LIKE '%NEWS' AND K.NEWS_ONLY_FLAG = 'Y' GROUP BY K.KEYID, K.KEYWORDS ORDER BY K.KEYID ;

105087
105088
105089
105108
105653
105654
105655
105667



