-- DEBUG THE ABSENCE OF XYZ KIDS IN BOTS AS WELL AS USERS
SELECT USERID, USERNAME, TRUE_COUNTRY_CODE, OPINION_CAMP FROM OPN_USERLIST WHERE BOT_FLAG = 'Y' AND TRUE_COUNTRY_CODE = 'NGA' AND USERID <> 1021662 ;
-- DO BOTS HAVE THESE KIDS - YES THEY HAVE BEEN ASSIGNED THESE KWS RECENTLY ?
SELECT TOPICID, KEYID, COUNT(USERID) FROM OPN_USER_CARTS WHERE KEYID IN (105653,105089,105655,105087,105108,105654)
AND USERID IN (SELECT USERID FROM OPN_USERLIST WHERE BOT_FLAG = 'Y' AND TRUE_COUNTRY_CODE = 'NGA' ) GROUP BY  TOPICID, KEYID ORDER BY  TOPICID, KEYID ;

SELECT * FROM OPN_USER_CARTS WHERE KEYID IN (105087) AND USERID IN (
SELECT USERID FROM OPN_USERLIST WHERE BOT_FLAG = 'Y' AND TRUE_COUNTRY_CODE = 'NGA') 
AND USERID IN (SELECT USERID FROM OPN_USER_INTERESTS WHERE INTEREST_ID = 1);

SELECT USERID, TOPICID, COUNT(1) FROM OPN_USER_CARTS WHERE USERID IN (
SELECT USERID FROM OPN_USERLIST WHERE BOT_FLAG = 'Y' AND TRUE_COUNTRY_CODE = 'NGA') 
AND USERID IN (SELECT USERID FROM OPN_USER_INTERESTS WHERE INTEREST_ID IN (1,2,3,4,5,10)) 
GROUP BY USERID, TOPICID ORDER BY USERID, TOPICID ;

SELECT * FROM OPN_USERLIST WHERE USERID = 1021662 ;