-- DEBUG THE ABSENCE OF XYZ KIDS IN BOTS AS WELL AS USERS
SELECT USERID, USERNAME, TRUE_COUNTRY_CODE, OPINION_CAMP FROM OPN_USERLIST WHERE BOT_FLAG = 'Y' AND TRUE_COUNTRY_CODE = 'IND' AND USERID <> 1021662 ;
-- DO BOTS HAVE THESE KIDS - YES THEY HAVE BEEN ASSIGNED THESE KWS RECENTLY ?
SELECT TOPICID, KEYID, COUNT(USERID) FROM OPN_USER_CARTS WHERE KEYID IN (105653,105089,105655,105087,105108,105654)
AND USERID IN (SELECT USERID FROM OPN_USERLIST WHERE BOT_FLAG = 'Y' AND TRUE_COUNTRY_CODE = 'USA' ) GROUP BY  TOPICID, KEYID ORDER BY  TOPICID, KEYID ;

SELECT * FROM OPN_USER_CARTS WHERE KEYID IN (105087) AND USERID IN (
SELECT USERID FROM OPN_USERLIST WHERE BOT_FLAG = 'Y' AND TRUE_COUNTRY_CODE = 'NGA') 
AND USERID IN (SELECT USERID FROM OPN_USER_INTERESTS WHERE INTEREST_ID = 1);

SELECT USERID, TOPICID, COUNT(1) FROM OPN_USER_CARTS WHERE USERID IN (
SELECT USERID FROM OPN_USERLIST WHERE BOT_FLAG = 'Y' AND TRUE_COUNTRY_CODE = 'NGA') 
AND USERID IN (SELECT USERID FROM OPN_USER_INTERESTS WHERE INTEREST_ID IN (1,2,3,4,5,10)) 
GROUP BY USERID, TOPICID ORDER BY USERID, TOPICID ;

SELECT * FROM OPN_USERLIST WHERE USERID = 1021662 ;

SELECT * FROM OPN_USER_INTERESTS WHERE USERID IN (SELECT USERID FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND OPINION_CAMP = 'REFORM') ;

-- 03/14/2025

SELECT C.ROW_ID, C.USERID, U.USERNAME, U.COUNTRY_CODE, C.TOPICID, C.KEYID, C.CREATION_DTM FROM OPN_USER_CARTS C, OPN_USERLIST U
WHERE C.USERID = U.USERID AND C.KEYID IN (105653,105089,105655,105087,105108,105654, 105088, 105709, 105708, 105667) AND U.BOT_FLAG <> 'Y' ORDER BY 2,5;

DELETE FROM OPN_USER_CARTS C WHERE C.KEYID IN (105653,105089,105655,105087,105108,105654, 105088, 105709, 105708, 105667) 
AND C.USERID IN (SELECT USERID FROM OPN_USERLIST WHERE BOT_FLAG <> 'Y');

INSERT INTO OPN_USER_CARTS (CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105087, U.USERID, 1, NOW(), NOW()FROM OPN_USERLIST U WHERE U.BOT_FLAG <> 'Y' ;

INSERT INTO OPN_USER_CARTS (CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105654, U.USERID, 2, NOW(), NOW()FROM OPN_USERLIST U WHERE U.BOT_FLAG <> 'Y' ;

INSERT INTO OPN_USER_CARTS (CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105108, U.USERID, 3, NOW(), NOW()FROM OPN_USERLIST U WHERE U.BOT_FLAG <> 'Y' ;

INSERT INTO OPN_USER_CARTS (CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105653, U.USERID, 4, NOW(), NOW()FROM OPN_USERLIST U WHERE U.BOT_FLAG <> 'Y' ;

INSERT INTO OPN_USER_CARTS (CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105655, U.USERID, 5, NOW(), NOW()FROM OPN_USERLIST U WHERE U.BOT_FLAG <> 'Y' ;

INSERT INTO OPN_USER_CARTS (CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', 105089, U.USERID, 10, NOW(), NOW()FROM OPN_USERLIST U WHERE U.BOT_FLAG <> 'Y' ;

SELECT COUNT(1) FROM OPN_USER_CARTS ; -- 632010
SELECT COUNT(1) FROM OPN_USERLIST U WHERE U.BOT_FLAG <> 'Y' ; -- 28313

/* BASED ON THIS, HERE IS THE PLAN OF ACTION: FIRST CHECK IF THE OPN_USER_INTERESTSIS IN SYNC WITH THE 
1. DELETE THE XYZ KWS FROM ALL NON-BOT USERS 2. INSERT XYZ KWS FOR TID 1,2,3,4,5,10 INTO */

SELECT TOPICID, COUNT(USERID) FROM OPN_USER_CARTS WHERE TOPICID IN (6,7,8,9) 
AND USERID IN (SELECT USERID FROM OPN_USERLIST WHERE BOT_FLAG <> 'Y') GROUP BY TOPICID ;

TRUNCATE TABLE OPN_USER_INTERESTS ;

INSERT INTO OPN_USER_INTERESTS(USERID, USER_UUID, INTEREST_ID, INTEREST_NAME, INTEREST_CODE, CREATION_DTM, SELECTED_KW_COUNT, USERNAME)
WITH CART AS (SELECT USERID, TOPICID, COUNT(DISTINCT KEYID) SELECTED_KW_COUNT, MIN(CREATION_DTM) CREATION_DTM FROM OPN_USER_CARTS GROUP BY USERID, TOPICID)
SELECT CART.USERID, U.USER_UUID, CART.TOPICID INTEREST_ID, T.TOPIC INTEREST_NAME, T.CODE INTEREST_CODE, CART.CREATION_DTM, CART.SELECTED_KW_COUNT, U.USERNAME
FROM CART, OPN_TOPICS T, OPN_USERLIST U 
WHERE CART.USERID = U.USERID AND CART.TOPICID = T.TOPICID ;

/* WHY DOES 1020656 NOT HAVE 105655 KID IN CART ? HOW MANY OCAMP BOTS HAVE NO XYZ KIDS IN THEIR CARTS AND FOR WHICH TIDS
this is beccause so far, the MAIN BOTS have been assigned primary INTERESTS - thus, there are specific NGA OCMP bots that are dedicated to TID 5 and so on
hence, if we want to see the coverage (where enough NW or ANTI discussions are there was a typical user, you need to check the BOTs that
arre dedicated to those specific TIDs 
*/

SELECT USERID, COUNT(KEYID) FROM OPN_USER_CARTS C WHERE USERID IN (SELECT USERID FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND OPINION_CAMP IS NOT NULL)
AND KEYID IN (105087, 105654, 105653, 105655, 105089) GROUP BY USERID ;