WITH SOMECOMMON AS 
(SELECT C1.USERID,  C2.USERID U2, COUNT(C2.KEYID) KMATCH FROM OPN_USER_CARTS C1, OPN_USER_CARTS C2 
WHERE C1.KEYID = C2.KEYID AND C1.USERID = 1019174 AND C1.TOPICID = 1 AND C1.KEYID NOT IN (105087) GROUP BY C1.USERID, C2.USERID),
MATCHCNT AS (
SELECT C1.USERID,  C2.USERID MATCHU2, C1.KEYID C1KEY, C1.CART C1CART, C2.KEYID, C2.CART, CASE WHEN C1.KEYID = C2.KEYID AND C1.CART = C2.CART THEN 1 ELSE 0 END MATCHLH
FROM OPN_USER_CARTS C1, OPN_USER_CARTS C2 
WHERE C1.KEYID = C2.KEYID AND C1.USERID = 1019174 AND C1.TOPICID = 1 -- AND C1.KEYID NOT IN (105087) -- AND C1.USERID = SOMECOMMON.U2
ORDER BY C1.USERID,  C2.USERID),
NW AS (
SELECT MATCHU2, COUNT(KEYID), SUM(MATCHLH), SOMECOMMON.KMATCH, ROUND(SUM(MATCHLH)*100/COUNT(KEYID)) MATCHPCNT
FROM MATCHCNT, SOMECOMMON WHERE MATCHCNT.MATCHU2 = SOMECOMMON.U2 GROUP BY MATCHU2 HAVING ROUND(SUM(MATCHLH)*100/COUNT(KEYID)) >= 50 ORDER BY 4 DESC),
U AS (SELECT USERID, USERNAME, BOT_FLAG, TRUE_COUNTRY_CODE FROM OPN_USERLIST),
P AS (
SELECT POST_ID, POST_BY_USERID, DATE(POST_DATETIME) PDATE, POST_DATETIME, POST_CONTENT, DEMO_POST_FLAG from OPN_POSTS WHERE TOPICID = 1 AND DEMO_POST_FLAG <> 'Y' AND STP_PROC_NAME = 'TCC_DISCUSSION' )
SELECT P.POST_ID, U.USERNAME, U.BOT_FLAG, U.TRUE_COUNTRY_CODE, P.DEMO_POST_FLAG, P.POST_CONTENT, P.PDATE, P.POST_DATETIME, P.POST_BY_USERID, NW.MATCHPCNT 
FROM P, NW, U WHERE P.POST_BY_USERID = NW.MATCHU2 AND P.POST_BY_USERID = U.USERID
ORDER BY P.PDATE DESC, NW.MATCHPCNT DESC ;

SELECT * FROM OPN_POSTS WHERE POST_ID IN (1630015, 1630156) ;



