-- Try out the STP_REMAINDER_NONXYZ and STP_REMAINDER scripts. 
-- First check the base state - last posts and the WSR counts

SELECT SCRAPE_TOPIC, COUNTRY_CODE, COUNT(1)  FROM WEB_SCRAPE_RAW where SCRAPE_DATE >= CURRENT_DATE() - INTERVAL 3 DAY AND IFNULL(MOVED_TO_POST_FLAG, 'N') = 'N'
GROUP BY SCRAPE_TOPIC, COUNTRY_CODE ORDER BY 1, 2, 3 DESC ;

SELECT * FROM OPN_POSTS ORDER BY POST_ID DESC ; -- 1493281/5/2024-10-05 16:31:18
SELECT * FROM OPN_POSTS_RAW ORDER BY POST_ID DESC ; -- 1493281/5/2024-10-05 16:31:18

-- 

CALL STP_REMAINDER('POLITICS', 1, 105087, 'GGG', 3, 300) ;
CALL STP_REMAINDER_NONXYZ('POLITICS', 1, 105087, 'IND', 3, 300) ;

call getInstreamNW(bringUUID(1018956) , 1, 0, 100) ;

SELECT * FROM OPN_USERLIST WHERE USERNAME LIKE 'INCOPN%' ;

SELECT SCRAPE_TOPIC, COUNTRY_CODE, COUNT(1)  FROM WEB_SCRAPE_RAW where SCRAPE_DATE >= CURRENT_DATE() - INTERVAL 3 DAY AND IFNULL(MOVED_TO_POST_FLAG, 'N') = 'N'
GROUP BY SCRAPE_TOPIC, COUNTRY_CODE ORDER BY 1, 2, 3 DESC ;

SELECT  P.TOPICID, P.POSTOR_COUNTRY_CODE, SUM(CASE WHEN U.BOT_FLAG = 'Y' AND P.DEMO_POST_FLAG = 'Y' THEN 1 ELSE 0 END)  POSTCNT
, SUM(CASE WHEN U.BOT_FLAG = 'Y' AND P.DEMO_POST_FLAG = 'N' THEN 1 ELSE 0 END)  DISCCNT
, SUM(CASE WHEN U.BOT_FLAG <> 'Y' THEN 1 ELSE 0 END) REALPOSTS
FROM OPN_POSTS P, OPN_USERLIST U WHERE P.POST_BY_USERID = U.USERID 
AND P.POST_DATETIME > CURRENT_DATE() - INTERVAL 1 DAY GROUP BY P.TOPICID, P.POSTOR_COUNTRY_CODE;

