-- NWByUIDTID

DELIMITER //
DROP PROCEDURE IF EXISTS NWByUIDTID //
CREATE PROCEDURE NWByUIDTID(UID INT, TID INT)
BEGIN


SELECT C.USERID, C.TOPICID, SUM(B.NET_STRENGTH) NET_STRENGTH, D.USERNAME, bringCartDate(C.USERID, C.TOPICID) IN_NW_SINCE
FROM OPN_NC_CLUSTERS A, OPN_CLUSTER_RELATIONSHIPS B, OPN_NC_CLUSTERS C, OPN_USERLIST D
WHERE A.CLUSTER_ID = B.CLUSTER_ID AND B.RELATED_CLUSTER_ID = C.CLUSTER_ID
AND C.USERID = D.USERID
AND A.USERID = UID  AND A.TOPICID = TID
AND D.USERID NOT IN (SELECT ON_USERID FROM OPN_USER_USER_ACTION WHERE BY_USERID = UID 
AND TOPICID = TID AND ACTION_TYPE = 'KO')
GROUP BY C.USERID, C.TOPICID ORDER BY bringCartDate(C.USERID, C.TOPICID) DESC,  SUM(B.NET_STRENGTH) DESC;

END //
DELIMITER ;

-- 