SET SQL_SAFE_UPDATES = 0;

SELECT * FROM OPN_USERLIST order by USERID desc ; -- 1023365
SELECT UP.ROW_ID, UP.ACTION_BY_USERID, U.USERNAME, U.TRUE_COUNTRY_CODE, UP.POST_ACTION_DTM, UP.POST_ACTION_TYPE FROM OPN_USER_POST_ACTION UP, OPN_USERLIST U
WHERE UP.ACTION_BY_USERID = U.USERID AND U.BOT_FLAG <> 'Y' ORDER BY UP.ROW_ID DESC ;
SELECT ROW_ID, USERID, USERNAME, LOGIN_DTM, API_CALL, CONCAT_PARAMS FROM OPN_USER_BHV_LOG WHERE USERID NOT IN (SELECT USERID FROM OPN_USERLIST WHERE BOT_FLAG = 'Y' AND TRUE_COUNTRY_CODE IN ('IND', 'USA'))
ORDER BY ROW_ID DESC ;

SELECT * FROM OPN_USERLIST WHERE USERNAME LIKE 'myopin%' order by USERID desc ; -- 1023365
SELECT * FROM OPN_P_KW ORDER BY KEYID DESC ;
SELECT * FROM OPN_P_KW WHERE KEYWORDS LIKE '%MODI%' ;
SELECT * FROM OPN_KW_TAGS ORDER BY KEYID DESC ; 
SELECT * FROM OPN_USER_BHV_LOG ORDER BY ROW_ID DESC ; -- 47772
SELECT * FROM OPN_USER_CARTS WHERE USERID IN (1022725, 1006539) AND TOPICID = 9 ;
SELECT * FROM OPN_USER_DEVICE_LOG ORDER BY ROW_ID DESC ;
SELECT * FROM OPN_P_KW WHERE KEYID NOT IN (SELECT KEYID FROM OPN_KW_TAGS) ORDER BY KEYID DESC ;
SELECT * FROM OPN_USER_INTERESTS WHERE USERID IN (1002398, 1006539) ORDER BY ROW_ID DESC ;
SELECT * FROM OPN_USERLIST WHERE USERID IN (1002397, 1006539, 1022725) ;

SELECT * FROM OPN_POSTS ORDER BY POST_ID DESC ;
SELECT TIME_TO_SEC(TIMEDIFF(NOW(), POST_DATETIME)) diff FROM OPN_POSTS WHERE POST_ID = 722598 ;
SELECT * FROM OPN_USERLIST  WHERE USER_UUID = '9399eff5-7019-11eb-961c-06500c451eb8' ; 
SELECT * FROM OPN_INVITE_ACCEPT_LOG ;
SELECT * FROM OPN_POSTS WHERE POST_ID = 722375 ;
SELECT ROUTINE_TYPE, ROUTINE_NAME FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'opntprodd' AND ROUTINE_DEFINITION LIKE '%POSTOR_TCC%' ;

SELECT  ROUTINE_NAME, LAST_ALTERED, LENGTH(ROUTINE_DEFINITION) RLEN FROM INFORMATION_SCHEMA.ROUTINES 
WHERE ROUTINE_SCHEMA = 'opntprodd' and LAST_ALTERED > '2024-03-26 07:12:27' ORDER BY 1  ;

SELECT MONTH(CREATION_DATE) MTH, COUNTRY_CODE, USER_TYPE, COUNT(1) FROM OPN_USERLIST WHERE CREATION_DATE > CURRENT_DATE - INTERVAL 200 DAY GROUP BY MONTH(CREATION_DATE), COUNTRY_CODE, USER_TYPE ORDER BY 1;
SELECT MONTH(CREATION_DATE) MTH,  COUNT(1) FROM OPN_USERLIST WHERE USER_TYPE in ('USER', 'GUEST') AND CREATION_DATE > CURRENT_DATE - INTERVAL 60 DAY GROUP BY MONTH(CREATION_DATE) ORDER BY 1;
SELECT MONTH(CREATION_DATE) MTH, TRUE_COUNTRY_CODE,  COUNT(1) FROM OPN_USERLIST WHERE USER_TYPE = 'USER' 
AND CREATION_DATE > CURRENT_DATE - INTERVAL 10 DAY GROUP BY MONTH(CREATION_DATE), TRUE_COUNTRY_CODE ORDER BY 1;

SELECT cast(CREATION_DATE as date),  COUNT(1) FROM OPN_USERLIST WHERE USER_TYPE in ('USER', 'GUEST') AND CREATION_DATE > CURRENT_DATE - INTERVAL 15 DAY GROUP BY cast(CREATION_DATE as date) ORDER BY 1;


SELECT TOPICID, POSTOR_COUNTRY_CODE, SUM(CASE WHEN STP_PROC_NAME = 'STP_REMAINDER' THEN 1 ELSE 0 END) RMND_CNT 
, SUM(CASE WHEN STP_PROC_NAME = 'STP_STAG23_MICRO' THEN 1 ELSE 0 END) MACRO_CNT
FROM OPN_POSTS WHERE POST_DATETIME > CURRENT_DATE() - INTERVAL 2 DAY  GROUP BY TOPICID, POSTOR_COUNTRY_CODE ;
 
SELECT K.KEYID, K.KEYWORDS, T.TOPICID, T.TOPIC, CAST(P.POST_PROCESSED_DTM AS DATE) PPDT, P.POSTOR_COUNTRY_CODE, COUNT(P.POST_ID)
FROM OPN_P_KW K, OPN_TOPICS T, OPN_POSTS P
WHERE P.TAG1_KEYID = K.KEYID AND P.POST_PROCESSED_DTM > CURRENT_DATE() - INTERVAL 1 DAY
AND P.TOPICID = T.TOPICID AND K.KEYWORDS LIKE '%NEWS%'
GROUP BY K.KEYID, K.KEYWORDS, T.TOPICID, T.TOPIC, CAST(P.POST_PROCESSED_DTM AS DATE), P.POSTOR_COUNTRY_CODE ORDER  BY T.TOPICID, CAST(P.POST_PROCESSED_DTM AS DATE);

-- 1033268 'Love Your Lord' is the last common user between prod and dev. after that, dev was separated

SELECT * FROM OPN_USERLIST WHERE USER_TYPE = 'USER' AND USERID > 1033268 ;
SELECT * FROM OPN_POSTS WHERE POST_ID > 1330647 AND TOPICID = 1 AND POSTOR_COUNTRY_CODE = 'USA' ORDER BY POST_ID DESC LIMIT 100 ;

SELECT * FROM OPN_PUSH_LAUNCH ;

SELECT COUNTRY_CODE, SCRAPE_TOPIC, COUNT(1) FROM WSR_CONVERTED WHERE ROW_ID > 915000 AND  SCRAPE_DATE > '2023-09-08' GROUP BY COUNTRY_CODE, SCRAPE_TOPIC ORDER BY 1, 2 ;
SELECT SCRAPE_SOURCE, COUNT(1) FROM WSR_CONVERTED WHERE ROW_ID > 915000 AND  NEWS_DATE > '2023-09-08' AND SCRAPE_TOPIC IN ('BUSINESS')
AND COUNTRY_CODE = 'IND' GROUP BY SCRAPE_SOURCE ORDER BY 1, 2 ;
SELECT SCRAPE_SOURCE, COUNT(1) FROM WSR_CONVERTED WHERE ROW_ID > 915000 AND  NEWS_DATE > '2023-09-08' AND COUNTRY_CODE = 'IND' GROUP BY SCRAPE_SOURCE ORDER BY 1, 2 ;

SELECT cast(POST_DATETIME as date) PDT, COUNT(1) FROM OPN_POSTS WHERE POST_DATETIME > CURRENT_DATE() - INTERVAL 5 DAY GROUP BY cast(POST_DATETIME as date) ;
SELECT * FROM OPN_POSTS WHERE OPN_POSTS.URL_EXCERPT IS NOT NULL ORDER BY POST_ID DESC LIMIT 100 ;

DROP TABLE OPN_30DAYS_POST_CONTENT ;

CREATE TABLE OPN_30DAYS_POST_CONTENT 
SELECT POST_CONTENT, MIN(POST_DATETIME) LOAD_DTM FROM OPN_POSTS WHERE POST_DATETIME > CURRENT_DATE() - INTERVAL 30 DAY 
AND STP_PROC_NAME IS NOT NULL GROUP BY POST_CONTENT ; 

CALL callSTDbyTCC(1, 'USA');
CALL callSTDbyTCC(2, 'USA');
CALL callSTDbyTCC(4, 'USA');
CALL callSTDbyTCC(5, 'USA');
CALL callSTDbyTCC(10, 'USA');
CALL callSTDbyTCC(1, 'IND');
CALL callSTDbyTCC(2, 'IND');
CALL callSTDbyTCC(4, 'IND');
CALL callSTDbyTCC(5, 'IND');
CALL callSTDbyTCC(10, 'IND');
CALL callSTDbyTCC(1, 'NGA');
CALL callSTDbyTCC(2, 'NGA');
CALL callSTDbyTCC(4, 'NGA');
CALL callSTDbyTCC(5, 'NGA');
CALL callSTDbyTCC(10, 'NGA');


