SELECT K.TOPICID, U.COUNTRY_CODE, K.KEYID, COUNT(DISTINCT C.USERID) FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_P_KW K 
WHERE C.USERID = U.USERID AND C.KEYID = K.KEYID AND C.KEYID IN (105087, 105088, 105089, 105654, 105108, 105653, 105655, 80005) AND U.BOT_FLAG = 'Y'
GROUP BY K.TOPICID, U.COUNTRY_CODE, K.KEYID ORDER BY 1 ;

SELECT * FROM OPN_MAIN_BOTS ;
SELECT CCODE, TOPICID, KEYID, COUNT(1) FROM OPN_MAIN_BOTS GROUP BY CCODE, TOPICID, KEYID ORDER BY 1,2 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, 1, 105087, 'POLITICS', 'GGG'
FROM OPN_USER_CARTS C, OPN_USERLIST U WHERE C.USERID = U.USERID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'GGG' 
AND C.TOPICID = 1 AND C.KEYID = 105087 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, 1, 105087, 'POLITICS', 'USA'
FROM OPN_USER_CARTS C, OPN_USERLIST U WHERE C.USERID = U.USERID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'USA' 
AND C.TOPICID = 1 AND C.KEYID = 105087 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, 1, 105087, 'POLITICS', 'IND'
FROM OPN_USER_CARTS C, OPN_USERLIST U WHERE C.USERID = U.USERID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'IND' 
AND C.TOPICID = 1 AND C.KEYID = 105087 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'GGG' 
AND C.KEYID = 105654 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'USA' 
AND C.KEYID = 105654 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'IND' 
AND C.KEYID = 105654 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'GGG' 
AND C.KEYID = 105108 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'USA' 
AND C.KEYID = 105108 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'IND' 
AND C.KEYID = 105108 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'GGG' 
AND C.KEYID = 105653 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'USA' 
AND C.KEYID = 105653 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'IND' 
AND C.KEYID = 105653 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'GGG' 
AND C.KEYID = 105655 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'USA' 
AND C.KEYID = 105655 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'IND' 
AND C.KEYID = 105655 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'GGG' 
AND C.KEYID = 105089 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'USA' 
AND C.KEYID = 105089 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'IND' 
AND C.KEYID = 105089 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'IND' 
AND C.KEYID = 105088 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;