INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, 1, 105087, 'POLITICS', 'GGG'
FROM OPN_USER_CARTS C, OPN_USERLIST U WHERE C.USERID = U.USERID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'GGG' 
AND C.TOPICID = 1 AND C.KEYID = 105087 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, 1, 105087, 'POLITICS', 'USA'
FROM OPN_USER_CARTS C, OPN_USERLIST U WHERE C.USERID = U.USERID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'USA' 
AND C.TOPICID = 1 AND C.KEYID = 105087 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, 1, 105087, 'POLITICS', 'IND'
FROM OPN_USER_CARTS C, OPN_USERLIST U WHERE C.USERID = U.USERID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'IND' 
AND C.TOPICID = 1 AND C.KEYID = 105087 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'GGG' 
AND C.KEYID = 105654 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'USA' 
AND C.KEYID = 105654 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'IND' 
AND C.KEYID = 105654 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'GGG' 
AND C.KEYID = 105108 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'USA' 
AND C.KEYID = 105108 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'IND' 
AND C.KEYID = 105108 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'GGG' 
AND C.KEYID = 105653 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'USA' 
AND C.KEYID = 105653 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'IND' 
AND C.KEYID = 105653 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'GGG' 
AND C.KEYID = 105655 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'USA' 
AND C.KEYID = 105655 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'IND' 
AND C.KEYID = 105655 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'GGG' 
AND C.KEYID = 105089 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'USA' 
AND C.KEYID = 105089 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'IND' 
AND C.KEYID = 105089 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;

INSERT INTO OPN_MAIN_BOTS(USERID, USER_UUID, USERNAME, TOPICID, KEYID, TOPICNAME, CCODE)
SELECT C.USERID, U.USER_UUID, U.USERNAME, C.TOPICID, C.KEYID, T.TOPIC, U.COUNTRY_CODE
FROM OPN_USER_CARTS C, OPN_USERLIST U, OPN_TOPICS T WHERE C.USERID = U.USERID AND C.TOPICID = T.TOPICID AND U.BOT_FLAG = 'Y' AND U.COUNTRY_CODE = 'IND' 
AND C.KEYID = 105088 AND C.CART = 'L' ORDER BY RAND() LIMIT 100 ;