SET SQL_SAFE_UPDATES = 0;
SELECT * FROM OPN_MAIN_BOTS ;
SELECT TOPICID, COUNT(1) FROM OPN_MAIN_BOTS WHERE CCODE = 'GGG' GROUP BY TOPICID ;
SELECT TOPICID, COUNT(1) FROM OPN_MAIN_BOTS WHERE CCODE = 'GGG' GROUP BY TOPICID ;
SELECT * FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND OPINION_CAMP IN ('ELITES', 'REFORM') ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'ELITES' WHERE CCODE = 'GGG' AND TOPICID = 1 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'ELITES' WHERE CCODE = 'GGG' AND TOPICID = 2 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'ELITES' WHERE CCODE = 'GGG' AND TOPICID = 4 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'ELITES' WHERE CCODE = 'GGG' AND TOPICID = 5 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'ELITES' WHERE CCODE = 'GGG' AND TOPICID = 10 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = NULL, OPINION_CAMP = NULL WHERE TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES';

SELECT * FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES' AND TOPICID = 1 AND USERID IN 
(SELECT USERID FROM OPN_MAIN_BOTS WHERE TOPICID = 10);

SELECT USERID, COUNT(1) FROM OPN_MAIN_BOTS WHERE USERID IN (SELECT USERID FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES' AND TOPICID = 1) GROUP BY USERID ;

UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES' WHERE USERID IN (SELECT USERID FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES') ;

WITH BASE AS (SELECT USERID FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES')
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES' WHERE USERID IN (SELECT USERID FROM BASE) ;

SELECT TOPICID, COUNT(1) FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES' GROUP BY TOPICID ;

UPDATE OPN_MAIN_BOTS SET TCCODE = NULL,  OPINION_CAMP = NULL ;
SELECT COUNT(DISTINCT USERID) FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES' ;

UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'REFORM' WHERE CCODE = 'GGG' AND TOPICID = 1 AND IFNULL(TCCODE, 'ABC') <> 'NGA' ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'REFORM' WHERE CCODE = 'GGG' AND TOPICID = 2 AND IFNULL(TCCODE, 'ABC') <> 'NGA' ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'REFORM' WHERE CCODE = 'GGG' AND TOPICID = 4 AND IFNULL(TCCODE, 'ABC') <> 'NGA' ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'REFORM' WHERE CCODE = 'GGG' AND TOPICID = 5 AND IFNULL(TCCODE, 'ABC') <> 'NGA' ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'REFORM' WHERE CCODE = 'GGG' AND TOPICID = 10 AND IFNULL(TCCODE, 'ABC') <> 'NGA' ORDER BY RAND() LIMIT 10 ;

