SET SQL_SAFE_UPDATES = 0;
SELECT * FROM OPN_MAIN_BOTS ;
SELECT TOPICID, COUNT(1) FROM OPN_MAIN_BOTS WHERE CCODE = 'GGG' GROUP BY TOPICID ;
SELECT TOPICID, COUNT(1) FROM OPN_MAIN_BOTS WHERE CCODE = 'GGG' GROUP BY TOPICID ;
SELECT * FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND OPINION_CAMP IN ('ELITES', 'REFORM') ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'ELITES' WHERE CCODE = 'GGG' AND TOPICID = 1 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'ELITES' WHERE CCODE = 'GGG' AND TOPICID = 2 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'ELITES' WHERE CCODE = 'GGG' AND TOPICID = 4 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'ELITES' WHERE CCODE = 'GGG' AND TOPICID = 5 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'ELITES' WHERE CCODE = 'GGG' AND TOPICID = 10 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = NULL, OPINION_CAMP = NULL WHERE TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES';

SELECT * FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES' AND TOPICID = 1 AND USERID IN 
(SELECT USERID FROM OPN_MAIN_BOTS WHERE TOPICID = 10);

SELECT USERID, COUNT(1) FROM OPN_MAIN_BOTS WHERE USERID IN (SELECT USERID FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES' AND TOPICID = 1) GROUP BY USERID ;

UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES' WHERE USERID IN (SELECT USERID FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES') ;

WITH BASE AS (SELECT USERID FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES')
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES' WHERE USERID IN (SELECT USERID FROM BASE) ;

SELECT TOPICID, COUNT(1) FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES' GROUP BY TOPICID ;

UPDATE OPN_MAIN_BOTS SET TCCODE = NULL,  OPINION_CAMP = NULL ;
SELECT COUNT(DISTINCT USERID) FROM OPN_MAIN_BOTS WHERE TCCODE = 'NGA' AND OPINION_CAMP = 'ELITES' ;

UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'REFORM' WHERE CCODE = 'GGG' AND TOPICID = 1 AND IFNULL(TCCODE, 'ABC') <> 'NGA' ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'REFORM' WHERE CCODE = 'GGG' AND TOPICID = 2 AND IFNULL(TCCODE, 'ABC') <> 'NGA' ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'REFORM' WHERE CCODE = 'GGG' AND TOPICID = 4 AND IFNULL(TCCODE, 'ABC') <> 'NGA' ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'REFORM' WHERE CCODE = 'GGG' AND TOPICID = 5 AND IFNULL(TCCODE, 'ABC') <> 'NGA' ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA', OPINION_CAMP = 'REFORM' WHERE CCODE = 'GGG' AND TOPICID = 10 AND IFNULL(TCCODE, 'ABC') <> 'NGA' ORDER BY RAND() LIMIT 10 ;

-- NOW PREPARING THE USA AND IND MAIN BOTS

UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'DEM' WHERE TCCODE = 'USA' AND TOPICID = 1 AND USERID < 1004000 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'REPUB' WHERE TCCODE = 'USA' AND TOPICID = 1 AND USERID BETWEEN 1004001 AND 1008000 ORDER BY RAND() LIMIT 10 ;

WITH BASE AS (SELECT USERID FROM OPN_MAIN_BOTS WHERE TCCODE = 'USA' AND OPINION_CAMP = 'DEM' AND TOPICID = 1)
UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'DEM' WHERE USERID IN (SELECT USERID FROM BASE) AND TOPICID IN (2,4,5,10) ;

WITH BASE AS (SELECT USERID FROM OPN_MAIN_BOTS WHERE TCCODE = 'USA' AND OPINION_CAMP = 'REPUB' AND TOPICID = 1)
UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'REPUB' WHERE USERID IN (SELECT USERID FROM BASE) AND TOPICID IN (2,4,5,10) ;

WITH BASE AS (SELECT USERID FROM OPN_MAIN_BOTS WHERE TCCODE = 'USA' AND OPINION_CAMP = 'DEM' AND TOPICID = 2)
UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'DEM' WHERE USERID IN (SELECT USERID FROM BASE) AND TOPICID IN (1,4,5,10) ;

WITH BASE AS (SELECT USERID FROM OPN_MAIN_BOTS WHERE TCCODE = 'USA' AND OPINION_CAMP = 'REPUB' AND TOPICID = 1)
UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'REPUB' WHERE USERID IN (SELECT USERID FROM BASE) AND TOPICID IN (2,4,5,10) ;

UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'DEM' WHERE TCCODE = 'USA' AND TOPICID = 2 AND USERID < 1004000 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'REPUB' WHERE TCCODE = 'USA' AND TOPICID = 2 AND USERID BETWEEN 1004001 AND 1008000 ORDER BY RAND() LIMIT 10 ;

UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'DEM' WHERE TCCODE = 'USA' AND TOPICID = 4 AND USERID < 1004000 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'REPUB' WHERE TCCODE = 'USA' AND TOPICID = 4 AND USERID BETWEEN 1004001 AND 1008000 ORDER BY RAND() LIMIT 10 ;

UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'DEM' WHERE TCCODE = 'USA' AND TOPICID = 5 AND USERID < 1004000 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'REPUB' WHERE TCCODE = 'USA' AND TOPICID = 5 AND USERID BETWEEN 1004001 AND 1008000 ORDER BY RAND() LIMIT 10 ;

UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'DEM' WHERE TCCODE = 'USA' AND TOPICID = 10 AND USERID < 1004000 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'REPUB' WHERE TCCODE = 'USA' AND TOPICID = 10 AND USERID BETWEEN 1004001 AND 1008000 ORDER BY RAND() LIMIT 10 ;
-- - 
SELECT * FROM OPN_MAIN_BOTS  WHERE TCCODE = 'IND' AND TOPICID = 1 AND USERID BETWEEN 1016000 AND 1019000  ;
SELECT * FROM OPN_MAIN_BOTS  WHERE TCCODE = 'IND' AND TOPICID = 1 AND USERID BETWEEN 1019001 AND 1022000 ;

UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'PROMODI' WHERE TCCODE = 'IND' AND TOPICID = 1 AND USERID BETWEEN 1016000 AND 1019000 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'ANTIMODI' WHERE TCCODE = 'IND' AND TOPICID = 1 AND USERID BETWEEN 1019001 AND 1022000 ORDER BY RAND() LIMIT 10 ;

UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'PROMODI' WHERE TCCODE = 'IND' AND TOPICID = 2 AND USERID BETWEEN 1016000 AND 1019000 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'ANTIMODI' WHERE TCCODE = 'IND' AND TOPICID = 2 AND USERID BETWEEN 1019001 AND 1022000 ORDER BY RAND() LIMIT 10 ;

UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'PROMODI' WHERE TCCODE = 'IND' AND TOPICID = 4 AND USERID BETWEEN 1016000 AND 1019000 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'ANTIMODI' WHERE TCCODE = 'IND' AND TOPICID = 4 AND USERID BETWEEN 1019001 AND 1022000 ORDER BY RAND() LIMIT 10 ;

UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'PROMODI' WHERE TCCODE = 'IND' AND TOPICID = 5 AND USERID BETWEEN 1016000 AND 1019000 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'ANTIMODI' WHERE TCCODE = 'IND' AND TOPICID = 5 AND USERID BETWEEN 1019001 AND 1022000 ORDER BY RAND() LIMIT 10 ;

UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'PROMODI' WHERE TCCODE = 'IND' AND TOPICID = 10 AND USERID BETWEEN 1016000 AND 1019000 ORDER BY RAND() LIMIT 10 ;
UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'ANTIMODI' WHERE TCCODE = 'IND' AND TOPICID = 10 AND USERID BETWEEN 1019001 AND 1022000 ORDER BY RAND() LIMIT 10 ;

