/* Complete testing with logging of procs */

SELECT * FROM OPN_USERLIST WHERE EMAIL_ADDR = 'opinito.inc@gmail.com' ;
CALL deleteUserByUID(1053975) ;
/* Latest userid =  1053976 (abNakkiChala) -- it took a long time to fetch the showSFCContent -- let's look at all the procs that were called from the user creation to the SFC call */

SELECT ROW_ID, USERID, USERNAME, LOGIN_DTM, API_CALL, CONCAT_PARAMS FROM OPN_USER_BHV_LOG WHERE USERID NOT IN (SELECT USERID FROM OPN_USERLIST WHERE BOT_FLAG = 'Y' AND TRUE_COUNTRY_CODE IN ('IND', 'USA'))
ORDER BY ROW_ID DESC ;
SELECT * FROM OPN_PROC_LOG ORDER BY ROW_ID DESC ;
SELECT * FROM WEB_SCRAPE_RAW_L ;

SELECT * FROM OPN_POSTS ORDER BY POST_ID DESC ;
SELECT * FROM OPN_POSTS_RAW ORDER BY POST_ID DESC ;

SELECT * FROM OPN_USERLIST WHERE USERID = 1053689 ;

CALL getTCCDiscussionsNW(BRINGuuid(1053689), 1, 0, 30) ;

SELECT * FROM OPN_API_DEBUG_LOGS ORDER BY ROW_ID DESC ;
