-- First check if the main bots are correct in the dev - do they have 1:1 for userid:username, and userid:camp ?

SELECT USERNAME, TOPICID, COUNT(1) FROM OPN_MAIN_BOTS WHERE OPINION_CAMP IS NOT NULL GROUP BY USERNAME, TOPICID HAVING COUNT(1) > 1 ;
SELECT USERID, COUNT(DISTINCT USERNAME) FROM OPN_MAIN_BOTS GROUP BY USERID HAVING COUNT(DISTINCT USERNAME) > 1 ;
SELECT USERID, COUNT(DISTINCT OPINION_CAMP ) FROM OPN_MAIN_BOTS GROUP BY USERID HAVING COUNT(DISTINCT OPINION_CAMP) > 1 ; -- FOUND 4 1020732,1020863,1020877,1021211
SELECT * FROM OPN_MAIN_BOTS WHERE OPINION_CAMP IS NOT NULL AND USERID IN (SELECT USERID FROM OPN_MAIN_BOTS WHERE OPINION_CAMP IS NULL) ; -- FOUND 40 -- WHY ?

-- LET'S FIRST FIX THE 4 WITH DIFFERING CAMPS

SELECT USERID, TOPICID, OPINION_CAMP FROM OPN_MAIN_BOTS omb WHERE USERID IN (1020914,1020657,1021247) ORDER BY USERID, TOPICID ;

UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'REFORM' WHERE ROW_ID IN (72, 1091, 1443) ;
UPDATE OPN_MAIN_BOTS SET OPINION_CAMP = 'ELITES' WHERE ROW_ID IN (1082, 1048) ;

UPDATE OPN_MAIN_BOTS AS target
JOIN (
    -- Subquery to find the non-NULL OPINION_CAMP for each USERID
    SELECT USERID, OPINION_CAMP
    FROM OPN_MAIN_BOTS
    WHERE OPINION_CAMP IS NOT NULL
    GROUP BY USERID
) AS source
ON target.USERID = source.USERID
SET target.OPINION_CAMP = source.OPINION_CAMP
WHERE target.OPINION_CAMP IS NULL;

-- now let's find if USERID:USERNAME ARE EXACTLY 1:1

SELECT USERNAME, COUNT(DISTINCT USERID) FROM OPN_MAIN_BOTS GROUP BY USERNAME HAVING COUNT(DISTINCT USERID) > 1 ;

SELECT * FROM OPN_MAIN_BOTS omb WHERE USERNAME = 'frostZoya'

UPDATE OPN_MAIN_BOTS SET USERNAME = 'ZoraFrosty' WHERE USERID = 1019667 ;

-- With the above step, now the main bots are all correctly defined in terms of camp - now let's check if they all have actual usernames

-- Now we find if all the OCAMP users have the TCCODE populated and in sync with camps

SELECT * FROM OPN_MAIN_BOTS WHERE OPINION_CAMP IS NOT NULL AND TCCODE IS NULL ;

UPDATE OPN_MAIN_BOTS SET TCCODE = 'NGA' WHERE CCODE = 'GGG' AND OPINION_CAMP IS NOT NULL ;

SELECT * FROM OPN_MAIN_BOTS WHERE OPINION_CAMP IS NOT NULL AND CCODE = 'GGG' 

-- NOW CHECK IF THE OU TCCODE MATCHES WITH OMB TCCODE

SELECT B.USERID, B.USERNAME, U.USERNAME UNAME, B.TCCODE, U.TRUE_COUNTRY_CODE, B.OPINION_CAMP, U.OPINION_CAMP UCAMP
FROM OPN_MAIN_BOTS B, OPN_USERLIST U WHERE B.USERID = U.USERID AND B.OPINION_CAMP IS NOT NULL AND B.CCODE = 'GGG' AND B.USERNAME <> U.USERNAME

-- NOW FIXING THE MISMATCH IN THE OCAMPS - TAKING UL AS THE DRIVER

WITH BASE AS (SELECT B.USERID, B.USERNAME, U.USERNAME UNAME, B.TCCODE, U.TRUE_COUNTRY_CODE, B.OPINION_CAMP, U.OPINION_CAMP UCAMP
FROM OPN_MAIN_BOTS B, OPN_USERLIST U WHERE B.USERID = U.USERID AND B.OPINION_CAMP IS NOT NULL AND B.CCODE = 'GGG' AND B.OPINION_CAMP <> U.OPINION_CAMP)
UPDATE OPN_MAIN_BOTS OB JOIN BASE ON OB.USERID  = BASE.USERID SET OB.OPINION_CAMP = BASE.UCAMP

-- NOW WE UPDATE THE OMB USERNAME WITH UL USERNAME

WITH BASE AS (SELECT B.USERID, B.USERNAME, U.USERNAME UNAME, B.TCCODE, U.TRUE_COUNTRY_CODE, B.OPINION_CAMP, U.OPINION_CAMP UCAMP
FROM OPN_MAIN_BOTS B, OPN_USERLIST U WHERE B.USERID = U.USERID AND B.OPINION_CAMP IS NOT NULL AND B.CCODE = 'GGG' AND B.USERNAME <> U.USERNAME)
UPDATE OPN_MAIN_BOTS OB JOIN BASE ON OB.USERID  = BASE.USERID SET OB.USERNAME = BASE.UNAME

-- NOW THE OMB IS FULLY CORRECTED

SELECT TCCODE, OPINION_CAMP, COUNT(DISTINCT USERID) FROM OPN_MAIN_BOTS WHERE OPINION_CAMP IS NOT NULL GROUP BY TCCODE, OPINION_CAMP ORDER BY 1,2 ;
SELECT TRUE_COUNTRY_CODE, OPINION_CAMP, COUNT(1) FROM OPN_USERLIST WHERE OPINION_CAMP IS NOT NULL GROUP BY TRUE_COUNTRY_CODE, OPINION_CAMP ORDER BY 1,2 ;

SELECT * FROM OPN_MAIN_BOTS omb WHERE OPINION_CAMP IS NOT NULL AND USERNAME LIKE 'TLR%' OR USERNAME LIKE 'GG%'; -- 291
SELECT * FROM OPN_USERLIST WHERE USERID IN (SELECT DISTINCT USERID FROM OPN_MAIN_BOTS omb WHERE OPINION_CAMP IS NOT NULL AND USERNAME LIKE 'TLR%' OR USERNAME LIKE 'GG%') ; -- 291
SELECT U.USERID, USERNAME, U.TRUE_COUNTRY_CODE, U.OPINION_CAMP FROM OPN_USERLIST U, (select distinct USERID, USERNAME, TCCODE, OPINION_CAMP FROM OPN_MAIN_BOTS omb WHERE OPINION_CAMP IS NOT NULL)


SELECT CCODE, TOPICID, TCCODE, COUNT(1) FROM OPN_MAIN_BOTS group by CCODE, TOPICID, TCCODE ORDER BY CCODE, TOPICID, TCCODE  ;
SELECT * FROM OPN_MAIN_BOTS WHERE TCCODE = 'IND' AND OPINION_CAMP IS NOT NULL ;
SELECT * FROM OPN_USERLIST WHERE TRUE_COUNTRY_CODE = 'NGA' AND BOT_FLAG = 'Y' ;
SELECT USERID, USERNAME, TOPICID, OPINION_CAMP FROM OPN_MAIN_BOTS WHERE TCCODE = 'IND' AND OPINION_CAMP IS NOT NULL  ORDER BY USERID ;
SELECT USERNAME, TOPICID, COUNT(1) FROM OPN_MAIN_BOTS WHERE TCCODE = 'IND' AND OPINION_CAMP IS NOT NULL GROUP BY USERNAME, TOPICID HAVING COUNT(1) > 1 ;
SELECT USERID, USERNAME, TOPICID, OPINION_CAMP FROM OPN_MAIN_BOTS WHERE USERNAME = 'ninjaSimran' ;

UPDATE OPN_MAIN_BOTS SET USERNAME = 'SoniyaandSimran' where USERID = 1019714 ;
-- Randomly select 10 ANTIMODI rows and update them to PROMODI
UPDATE OPN_MAIN_BOTS
SET OPINION_CAMP = 'ANTIMODI'
WHERE USERID IN (
    SELECT USERID FROM (
        SELECT USERID
        FROM OPN_MAIN_BOTS
        WHERE OPINION_CAMP = 'PROMODI'
        ORDER BY RAND()
        LIMIT 2
    ) AS TEMP
);

-- Update PROMODI usernames
-- Update PROMODI usernames
UPDATE OPN_MAIN_BOTS
SET USERNAME = CASE
    WHEN OPINION_CAMP = 'PROMODI' THEN ELT(FLOOR(1 + RAND() * 60),
        'sureshReddy', 'lakshmiNair', 'rajeshIyer', 'anjaliMenon', 'naiduKumar', 'divyaShetty', 'arunRao', 'krishnaPillai', 
        'maliniChetty', 'sreeRam', 'ajayGupta', 'priyaSharma', 'rahulVerma', 'anitaJain', 'vikramPatel', 'meeraDesai', 
        'amitMishra', 'reenaSaxena', 'sanjayAgarwal', 'nehaTiwari', 'jaspreetSingh', 'gurdeepKaur', 'manpreetBrar', 
        'harmanjeetSandhu', 'navjotDhillon', 'sureshPhoenix', 'lakshmiShadow', 'rajeshBlaze', 'anjaliAce', 'naiduNinja', 
        'lhouVang', 'tsheringDorji', 'neilLepcha', 'sangmaBoro', 'adiThong', 'marakMomin', 'birenSingh', 'nagaAo', 
        'konyakPhom', 'jamirZeliang', 'shadowRajiv', 'blazeAnkit', 'ninjaSimran', 'frostZoya', 'aceKumar', 'sureshReddy7', 
        'lakshmiNair12', 'rajeshIyer8', 'anjaliMenon4', 'naiduKumar9', 'divyaShetty6', 'arunRao11', 'krishnaPillai3', 
        'maliniChetty5', 'sreeRam7', 'lhouVang10', 'tsheringDorji8', 'neilLepcha4', 'sangmaBoro3', 'adiThong9'
    )
END
WHERE OPINION_CAMP = 'PROMODI';
-- Update ANTIMODI usernames
-- Update ANTIMODI usernames
UPDATE OPN_MAIN_BOTS
SET USERNAME = CASE
    WHEN OPINION_CAMP = 'ANTIMODI' THEN ELT(FLOOR(1 + RAND() * 40),
        'anjaliSharma', 'priyaVerma', 'rahulAgarwal', 'nehaPatel', 'sanjayMishra', 'amitKumar', 'divyaGupta', 'arunSingh', 
        'krishnaReddy', 'maliniIyer', 'sreeMenon', 'rajeshNair', 'zoyaBegum', 'aliRizvi', 'simranSheikh', 'farhanAkhtar', 
        'ayeshaAnsari', 'imranMalik', 'naseemKhan', 'michaelRodrigues', 'elizabethD’Souza', 'josephFernandes', 
        'rachelMascarenhas', 'anthonyPinto', 'frostZoya', 'shadowAyesha', 'blazeFarhan', 'aceKrishna', 'ninjaSimran', 
        'anjaliSharma4', 'priyaVerma7', 'rahulAgarwal11', 'nehaPatel3', 'sanjayMishra9', 'amitKumar6', 'divyaGupta8', 
        'arunSingh12', 'krishnaReddy5', 'maliniIyer10', 'sreeMenon2'
    )
END
WHERE OPINION_CAMP = 'ANTIMODI';
select count(1) from OPN_MAIN_BOTS WHERE TCCODE = 'IND' AND OPINION_CAMP= 'ANTIMODI' ;
