SELECT USERID, USER_UUID, USERNAME, CREATION_DATE, COUNTRY_CODE, FB_USER_FLAG, EMAIL_ADDR FROM OPN_USERLIST WHERE EMAIL_ADDR = 'opntnewuser@gmail.com' ;

CALL getDiscussionsNW(bringUUID(1053689), 1, 0, 30) ;
CALL getUserCarts(1, BRINGUUID(1053689), 'LATEST', 0, 400) ;

SELECT * FROM OPN_USER_CARTS WHERE USERID = 1042834 AND TOPICID = 1 ;
SELECT * FROM OPN_POSTS WHERE POST_ID = 1459463 ;

SELECT * FROM OPN_P_KW WHERE KEYID = 193100 ;

SELECT COUNT(1) FROM OPN_PUSH_LAUNCH ;

ALTER TABLE `opntprodd`.`OPN_SFC_CONTENT` 
CHANGE COLUMN `CONTENT1_CAMP` `COMMENT1_CAMP` VARCHAR(45) NULL DEFAULT NULL ;


