-- STP Analysis Often Used SQL
SET SQL_SAFE_UPDATES = 0;

SELECT * FROM OPN_POSTS ORDER BY POST_ID DESC ;
SELECT * FROM OPN_POSTS where STP_PROC_NAME IS NULL ORDER BY POST_ID DESC ;

SELECT * FROM OPN_USERLIST WHERE USERNAME LIKE 'ASTOPNT1U' ;

SELECT ROUTINE_TYPE, ROUTINE_NAME FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'opntprod' AND ROUTINE_DEFINITION LIKE '%OPN_POST_SEARCH_T%' ;
SELECT ROUTINE_TYPE, ROUTINE_NAME, LAST_ALTERED, LENGTH(ROUTINE_DEFINITION) RLEN FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'opntprod' AND ROUTINE_NAME LIKE 'STP%'  ORDER BY 3 DESC LIMIT 30 ;

SELECT TOPICID, POSTOR_COUNTRY_CODE, SUM(CASE WHEN STP_PROC_NAME = 'STP_REMAINDER' THEN 1 ELSE 0 END) RMND_CNT 
, SUM(CASE WHEN STP_PROC_NAME = 'STP_STAG23_MICRO' THEN 1 ELSE 0 END) MACRO_CNT
FROM OPN_POSTS WHERE POST_DATETIME > CURRENT_DATE() - INTERVAL 1 DAY  GROUP BY TOPICID, POSTOR_COUNTRY_CODE ;

SELECT * FROM WEB_SCRAPE_RAW ;
DELETE FROM WEB_SCRAPE_RAW ;

CALL STP_REMAINDER('SPORTS', 2, 'GGG') ;

  SELECT W.ROW_ID, IFNULL(STR_TO_DATE(W.NEWS_DATE, '%b %d, %Y %H:%i:%s'), W.SCRAPE_DATE) SCRAPE_DATE, STR_TO_DATE(W.NEWS_DATE, '%b %d, %Y %H:%i:%s' ) DTDT
  , W.SCRAPE_TOPIC, SUBSTR(W.NEWS_URL, 1, 499) NEWS_URL, SUBSTR(W.NEWS_HEADLINE, 1, 499) NEWS_HEADLINE
  , SUBSTR(W.NEWS_EXCERPT, 1, 499) NEWS_EXCERPT, W.COUNTRY_CODE   FROM WEB_SCRAPE_RAW W
  WHERE W.SCRAPE_TOPIC = 'SPORTS' AND W.MOVED_TO_POST_FLAG = 'N' AND W.COUNTRY_CODE = 'GGG'
  AND IFNULL(NEWS_DATE, SCRAPE_DATE) IS NOT NULL 
  AND IFNULL(STR_TO_DATE(W.NEWS_DATE, '%b %d, %Y %H:%i:%s' ), SCRAPE_DATE) > CURRENT_DATE() - INTERVAL 5 DAY LIMIT 100 ;

