-- STP MACRO and REMAINDER PROCESS OUTCOME ANALYSIS

-- STEP 1: FIND OUT HOW MANY POSTS WERE MADE WITH STP_REMAINDER VS STP_STAG23_MACRO

SELECT TOPICID, POSTOR_COUNTRY_CODE, SUM(CASE WHEN STP_PROC_NAME = 'STP_REMAINDER' THEN 1 ELSE 0 END) RMND_CNT 
, SUM(CASE WHEN STP_PROC_NAME = 'STP_STAG23_MICRO' THEN 1 ELSE 0 END) MACRO_CNT
FROM OPN_POSTS WHERE POST_DATETIME > CURRENT_DATE() - INTERVAL 1 DAY  GROUP BY TOPICID, POSTOR_COUNTRY_CODE ;

-- STEP 2: IF THE RMND COUNT IS VERY LOW, THEN DO THE NEXT FEW STEPS: FIRST, FIND OUT WHAT KEYWORDS HAVE BEEN TAGGED TO THE POSTS

SELECT K.KEYWORDS, T.LIKE1, T.LIKE2, T.LIKE3, COUNT(P.POST_ID)
FROM OPN_POSTS P, OPN_P_KW K, OPN_KW_TAGS T WHERE P.TAG1_KEYID = K.KEYID AND K.KEYID = T.KEYID AND P.CLEAN_POST_FLAG = 'Y'
AND P.POSTOR_COUNTRY_CODE = 'USA' AND P.TOPICID = 2 AND P.POST_DATETIME > CURRENT_DATE() - INTERVAL 10 DAY 
GROUP BY K.KEYWORDS, T.LIKE1, T.LIKE2, T.LIKE3 ORDER BY 5 DESC ;

-- CHECK IF THE STP_MONITOR IS SHOWING THE SAME DATA AS STEP 1 AND ALSO CHECK THE OPN_STP_LOG

SELECT  STP_MONITOR_PROCESS, SUM(POST_COUNT) FROM OPN_STP_MONITOR WHERE WSR_FILE_DATE = '2023-07-08' GROUP BY STP_MONITOR_PROCESS ;
SELECT * FROM OPN_STP_LOG ORDER BY ROW_ID DESC ;

CALL getUserCarts(5, BRINGUUID(1023879), 'LATEST', 0, 400) ;
SELECT * FROM OPN_USERLIST WHERE USERNAME = 'ASTOPNT1U' ;

SELECT * FROM OPN_POSTS WHERE TOPICID = 2 AND STP_PROC_NAME = 'STP_REMAINDER' AND POSTOR_COUNTRY_CODE = 'USA' AND POST_CONTENT LIKE '%ESPN%' 
AND POST_DATETIME > CURRENT_DATE() - INTERVAL 2 DAY ORDER BY POST_ID DESC ;

UPDATE OPN_POSTS SET CLEAN_POST_FLAG = 'Z' WHERE TOPICID = 2 AND STP_PROC_NAME = 'STP_REMAINDER' AND POSTOR_COUNTRY_CODE = 'USA' AND POST_CONTENT LIKE '%ESPN%' 
AND POST_DATETIME > CURRENT_DATE() - INTERVAL 2 DAY ORDER BY POST_ID DESC ;