-- SIMULATING THE NEW STP_MANAGER - WITH ONLY REMAINDER CALLS
SET SQL_SAFE_UPDATES = 0;
-- CHECKING THE WSR AND WSRL VOLUMES FOR 1/USA

SELECT SCRAPE_TOPIC, COUNTRY_CODE, COUNT(1)  FROM WEB_SCRAPE_RAW_L where SCRAPE_DATE >= CURRENT_DATE() - INTERVAL 10 DAY AND IFNULL(MOVED_TO_POST_FLAG, 'N') = 'N'
GROUP BY SCRAPE_TOPIC, COUNTRY_CODE ORDER BY 1, 2 DESC ; -- 0 ON 1/USA

SELECT SCRAPE_TOPIC, COUNTRY_CODE, COUNT(1)  FROM WEB_SCRAPE_RAW where SCRAPE_DATE >= CURRENT_DATE() - INTERVAL 3 DAY AND IFNULL(MOVED_TO_POST_FLAG, 'N') = 'N'
GROUP BY SCRAPE_TOPIC, COUNTRY_CODE ORDER BY 1, 2 DESC ; -- 473 ON 1/USA

SELECT * FROM WEB_SCRAPE_RAW wsr WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'IND' ;

-- KILLING THE OLD DATA

DELETE FROM WEB_SCRAPE_RAW where SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'USA' AND SCRAPE_DATE < CURRENT_DATE() - INTERVAL 3 DAY ;

-- LET'S CHECK THE DATE DATA QUALITY

SELECT COUNT(1) FROM WEB_SCRAPE_RAW where SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'USA' ;
SELECT COUNT(1) FROM WEB_SCRAPE_RAW where SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'USA' AND SCRAPE_DATE < CURRENT_DATE() - INTERVAL 3 DAY ;

-- VISUAL INSPECTION SHOWS SATISFACTORY DQ OF NEWS_DATE

-- LETS DEDUPE NOW

CALL WSR_DEDUPE_ALL() ;
CALL WSRL_DEDUPE_ALL() ;

-- SINCE SCRCOUNT << BOTCOUNT, WE CALL ONLY THE STP

CALL STP_REMAINDER(:interest, :TID, :xyzkid, :ccode, :numdays, :scrcount) ;
CALL STP_REMAINDER('POLITICS', 1, 105087, 'USA', 3, 220) ;
CALL STP_REMAINDER('POLITICS', 1, 105087, 'IND', 3, 66) ;
CALL STP_REMAINDER('POLITICS', 1, 105087, 'GGG', 3, 100) ;

/* FOUND THAT ind STP_REMAINDER POL IS ALSO BEING ASSIGNED TO USA BOTS - WHY ?
 * 
 * 
 * 
 */

SELECT * FROM OPN_XYZNEWS_BOTS WHERE TOPICID = 1 AND CCODE = 'IND' ;

SELECT * FROM OPN_XYZNEWS_BOTS WHERE USERID IN (1004116, 1003835, 1006333) ;

SELECT * FROM OPN_POSTS ORDER BY POST_ID DESC ; -- 1504167
SELECT * FROM OPN_POSTS_RAW WHERE POST_ID IN (1504427, 1504426) ;

SELECT POST_CONTENT, COUNT(1) FROM OPN_POSTS WHERE POST_ID < 1400000 AND POST_ID > 1300000 GROUP BY POST_CONTENT HAVING COUNT(1) > 1 ;

SELECT W.ROW_ID, IFNULL(W.NEWS_DATE, W.SCRAPE_DATE) SCRAPE_DATE
  , W.SCRAPE_TOPIC, SUBSTR(W.NEWS_URL, 1, 499) NEWS_URL, SUBSTR(W.NEWS_HEADLINE, 1, 499) NEWS_HEADLINE
  , SUBSTR(W.NEWS_EXCERPT, 1, 499) NEWS_EXCERPT, W.COUNTRY_CODE 
  FROM WEB_SCRAPE_RAW W
  WHERE W.SCRAPE_TOPIC = 'POLITICS' AND IFNULL(W.MOVED_TO_POST_FLAG, 'N') = 'N' AND W.COUNTRY_CODE = 'IND'
  AND IFNULL(NEWS_DATE, SCRAPE_DATE) IS NOT NULL 
  AND IFNULL(NEWS_DATE, SCRAPE_DATE)   > CURRENT_DATE() - INTERVAL 3 DAY LIMIT 10;




