SELECT * FROM OPN_USERLIST WHERE TRUE_COUNTRY_CODE = 'SLE' AND BOT_FLAG = 'Y' AND USERID NOT IN (SELECT USERID FROM OPN_BOT_NAMES WHERE TRUE_COUNTRY_CODE = 'SLE') ;

SELECT TRUE_COUNTRY_CODE, COUNT(1) FROM OPN_BOT_NAMES GROUP BY TRUE_COUNTRY_CODE ;

SELECT TRUE_COUNTRY_CODE, COUNT(1) FROM OPN_BOT_NAMES GROUP BY TRUE_COUNTRY_CODE ;

SELECT TRUE_COUNTRY_CODE, COUNT(1) FROM OPN_USERLIST 
WHERE BOT_FLAG = 'Y' AND TRUE_COUNTRY_CODE IN (SELECT DISTINCT TRUE_COUNTRY_CODE FROM OPN_BOT_NAMES) GROUP BY TRUE_COUNTRY_CODE ;

SELECT USERID, USERNAME, COUNTRY_CODE, TRUE_COUNTRY_CODE, OPINION_CAMP FROM OPN_USERLIST 
WHERE BOT_FLAG = 'Y' AND OPINION_CAMP IS NULL AND COUNTRY_CODE = 'GGG';

UPDATE OPN_USERLIST SET USERNAME = CONCAT('GGST', USERID), OPINION_CAMP = NULL, TRUE_COUNTRY_CODE = NULL
WHERE COUNTRY_CODE = 'GGG' AND BOT_FLAG = 'Y' AND TRUE_COUNTRY_CODE IN (SELECT DISTINCT TRUE_COUNTRY_CODE FROM OPN_BOT_NAMES) ;

SELECT USERID, USERNAME, COUNTRY_CODE, TRUE_COUNTRY_CODE, OPINION_CAMP FROM OPN_USERLIST 
WHERE COUNTRY_CODE = 'GGG' AND BOT_FLAG = 'Y' AND TRUE_COUNTRY_CODE IN (SELECT DISTINCT TRUE_COUNTRY_CODE FROM OPN_BOT_NAMES) ;

CALL assignBotNamesToUsers() ;

SELECT * FROM OPN_BOT_NAMES obn WHERE TRUE_COUNTRY_CODE IN ('PAK', 'BGD') ;

SELECT * FROM OPN_USERLIST WHERE USERID IN (1021314,1021198,1020982) ;

SELECT TCCODE, COUNT(DISTINCT USERID) FROM OPN_MAIN_BOTS GROUP BY TCCODE ;
SELECT * FROM OPN_MAIN_BOTS WHERE TCCODE IS NULL AND USERID  IN (SELECT USERID FROM OPN_BOT_NAMES);

UPDATE OPN_MAIN_BOTS AS bots
JOIN OPN_USERLIST AS users
  ON bots.USERID = users.USERID
SET 
  bots.USERNAME = users.USERNAME,
  bots.TCCODE = users.TRUE_COUNTRY_CODE,
  bots.OPINION_CAMP = users.OPINION_CAMP
WHERE users.TRUE_COUNTRY_CODE IN (
  SELECT DISTINCT TRUE_COUNTRY_CODE 
  FROM OPN_BOT_NAMES
);