-- TCC complete testing - including sfc, disucssion clicks, adding/removing interests, new user etc

-- case 1: Creating a new user:

SELECT * FROM OPN_USERLIST ORDER BY USERID DESC ;
SELECT * FROM OPN_API_DEBUG_LOGS ORDER BY ROW_ID DESC ;

SELECT * FROM OPN_USER_BHV_LOG ORDER BY ROW_ID DESC ;

SELECT * FROM OPN_USER_INTERESTS WHERE USERID IN (1053979)  ;

SELECT * FROM OPN_USER_CARTS WHERE USERID IN (1053979)   ;

SELECT ROUTINE_TYPE, ROUTINE_NAME FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'opntprodd' AND ROUTINE_DEFINITION LIKE '%userPostLH%' ;

