-- TCC complete testing - including sfc, disucssion clicks, adding/removing interests, new user etc

-- case 1: Creating a new user:
SET SQL_SAFE_UPDATES = 0;
SELECT * FROM OPN_USERLIST ORDER BY USERID DESC ;
SELECT * FROM OPN_API_DEBUG_LOGS ORDER BY ROW_ID DESC ;

SELECT * FROM OPN_USER_BHV_LOG ORDER BY ROW_ID DESC ;

SELECT * FROM OPN_USER_INTERESTS WHERE USERID IN (1053979)  ;

SELECT * FROM OPN_USER_CARTS WHERE USERID IN (1053979)   ;

SELECT ROUTINE_TYPE, ROUTINE_NAME FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'opntprodd' AND ROUTINE_DEFINITION LIKE '%userPostLH%' ;

SELECT ROW_ID, NEWS_TITLE, CONTENT_URL, CONTENT_TITLE, CONTENT_TONE, CONTENT_CAMP, COMMENT1_TEXT, COMMENT1_TONE, COMMENT1_CAMP, COMMENT2_TEXT, COMMENT2_TONE, COMMENT2_CAMP
FROM OPN_SFC_CONTENT WHERE TRUE_COUNTRY_CODE = 'USA' AND TOPICID = 1 AND CONVERTED_POST_ID IS NULL ORDER BY ROW_ID DESC ;

DELETE FROM OPN_SFC_CONTENT WHERE CONVERTED_POST_ID IS NULL AND CONTENT_TITLE IN (SELECT KEYWORDS FROM OPN_P_KW WHERE CREATION_DTM > CURRENT_DATE() - INTERVAL 30 DAY) ;

CALL callSTDbyTCC(1, 'USA');
CALL callSTDbyTCC(2, 'USA');
CALL callSTDbyTCC(4, 'USA');
CALL callSTDbyTCC(5, 'USA');
CALL callSTDbyTCC(10, 'USA');
CALL callSTDbyTCC(1, 'IND');
CALL callSTDbyTCC(2, 'IND');
CALL callSTDbyTCC(4, 'IND');
CALL callSTDbyTCC(5, 'IND');
CALL callSTDbyTCC(10, 'IND');
CALL callSTDbyTCC(1, 'NGA');
CALL callSTDbyTCC(2, 'NGA');
CALL callSTDbyTCC(4, 'NGA');
CALL callSTDbyTCC(5, 'NGA');
CALL callSTDbyTCC(10, 'NGA');
CALL callSTDbyTCC(1, 'GHA');
CALL callSTDbyTCC(2, 'GHA');
CALL callSTDbyTCC(4, 'GHA');
CALL callSTDbyTCC(5, 'GHA');
CALL callSTDbyTCC(10, 'GHA');

-- Error Code: 1062. Duplicate entry '"Who knew playing it safe could be so deadly for your brand?!"-4' for key 'OPN_P_KW.PRIMARY'
SELECT * FROM OPN_SFC_CONTENT WHERE TOPICID = 4 AND TRUE_COUNTRY_CODE = 'GHA' AND CONVERTED_POST_ID IS NULL ;

DELETE FROM OPN_SFC_CONTENT WHERE ROW_ID IN (10840) ;

SELECT * FROM OPN_SFC_CONTENT WHERE CONVERTED_POST_ID IS NULL AND CONTENT_TITLE IN (SELECT KEYWORDS FROM OPN_P_KW WHERE CREATION_DTM > CURRENT_DATE() - INTERVAL 30 DAY) ;

