SELECT 
        B.USERID, B.BOT_FLAG, B.TRUE_COUNTRY_CODE, A.TOPICID, COUNT(*) TOTAL_NS
    FROM
        (SELECT 
        C1.USERID, C1.TOPICID, C1.CART, C1.KEYID
    FROM
        OPN_USER_CARTS C1
    WHERE
        C1.USERID = 1020656) A, (SELECT 
        C2.USERID,
            CU.BOT_FLAG,
            C2.TOPICID,
            C2.CART,
            C2.KEYID,
            C2.CREATION_DTM,
            CU.TRUE_COUNTRY_CODE
    FROM
        OPN_USER_CARTS C2, OPN_USERLIST CU
    WHERE
        C2.USERID = CU.USERID
            AND C2.USERID NOT IN (SELECT 
                OUUA.ON_USERID
            FROM
                OPN_USER_USER_ACTION OUUA
            WHERE
                OUUA.BY_USERID = 1020656
                    AND OUUA.TOPICID = 1
                    AND OUUA.ACTION_TYPE = 'KO')) B
    WHERE
        A.TOPICID = B.TOPICID
			AND A.KEYID = B.KEYID
            AND A.CART <> B.CART
           AND B.USERID NOT IN 
(SELECT DISTINCT D.USERID FROM 
(SELECT C1.USERID, C1.TOPICID, C1.CART, C1.KEYID FROM OPN_USER_CARTS C1 WHERE C1.USERID = 1020656 AND C1.TOPICID = 1) C ,
(SELECT C2.USERID, C2.TOPICID, C2.CART, C2.KEYID FROM OPN_USER_CARTS C2 ) D
WHERE C.KEYID = D.KEYID AND C.CART = D.CART ) 
            AND A.TOPICID = 1
    GROUP BY B.USERID , B.BOT_FLAG, B.TRUE_COUNTRY_CODE , A.TOPICID
    ORDER BY COUNT(*) DESC