<?php

// include ('dbconnection.inc');
// include('util.php');
include('includeHeader.inc.php');


$headers = parseRequestHeaders();

if (!authenticateGet($headers)){
  header("HTTP/1.1 401 Unauthorized");
  exit;
}
   
$postData = getPostData();

$topicid = $postData['topicid'];
$userid = $postData['userid'];


if (!$topicid || $topicid == "" || !$userid || $userid == "" ){
  $response = "{\"status\": \"error\"}";
die($response);
}
else{


$json_arry = array();
$q = "SELECT POST_ID, TOPICID, POST_BY_USERID, USERNAME, POST_DATETIME, POST_CONTENT, CART, NET_STRENGTH
, LCOUNT, HCOUNT, POST_ACTION_TYPE FROM (
SELECT POST.POST_ID, POST.TOPICID, POST.POST_BY_USERID, U.USERNAME, POST.POST_DATETIME, POST.POST_CONTENT, UN.CART, UN.NET_STRENGTH
, OPAC.LCOUNT, OPAC.HCOUNT, UP.POST_ACTION_TYPE
FROM OPN_POSTS POST
INNER JOIN (SELECT SQ1.TOPICID, SQ1.USERID, SQ1.CLUSTER_ID, SQ1.CART, SQ1.UCART_SIZE CONNECTED_CSIZE, SQ1.CLUSTER_SIZE, SQ2.USER_CARTSZ
, CASE WHEN SQ1.UCART_SIZE <= SQ2.USER_CARTSZ THEN SQ1.UCART_SIZE/SQ2.USER_CARTSZ ELSE 1/(SQ1.UCART_SIZE/SQ2.USER_CARTSZ) END NET_STRENGTH
FROM
(SELECT B.TOPICID, B.USERID, B.CLUSTER_ID, B.CART, B.UCART_SIZE, B.CLUSTER_SIZE FROM OPN_USER_CLUSTERS B WHERE B.CLUSTER_ID IN (
SELECT A.CLUSTER_ID FROM OPN_USER_CLUSTERS A WHERE A.TOPICID = B.TOPICID
AND A.USERID = \"$userid\" AND A.TOPICID = \"$topicid\" AND  (A.UCART_SIZE = A.CLUSTER_SIZE AND A.DEFAULT_UC_COMBO ='N'))
UNION ALL
SELECT B.TOPICID, B.USERID, B.CLUSTER_ID, B.CART, B.UCART_SIZE, B.CLUSTER_SIZE FROM OPN_USER_CLUSTERS B WHERE B.CLUSTER_ID IN (
SELECT A.CLUSTER_ID FROM OPN_USER_CLUSTERS A WHERE A.TOPICID = B.TOPICID
AND A.USERID = \"$userid\" AND A.TOPICID = \"$topicid\" AND (A.UCART_SIZE +1 = A.CLUSTER_SIZE AND A.DEFAULT_UC_COMBO ='N'))
AND B.UCART_SIZE = B.CLUSTER_SIZE
UNION ALL
SELECT B.TOPICID, B.USERID, B.CLUSTER_ID, B.CART, B.UCART_SIZE, B.CLUSTER_SIZE FROM OPN_USER_CLUSTERS B WHERE B.CLUSTER_ID IN (
SELECT A.CLUSTER_ID FROM OPN_USER_CLUSTERS A WHERE A.TOPICID = B.TOPICID
AND A.USERID = \"$userid\" AND A.TOPICID = \"$topicid\" AND  (A.UCART_SIZE +2 = A.CLUSTER_SIZE AND A.DEFAULT_UC_COMBO ='N'))
AND B.UCART_SIZE = B.CLUSTER_SIZE) SQ1, (SELECT TOPICID, USERID, CART, USER_CARTSZ FROM OPN_USER_CARTSIZE
WHERE USERID = \"$userid\" AND TOPICID = \"$topicid\") SQ2
WHERE SQ1.TOPICID = SQ2.TOPICID AND SQ1.CART = SQ2.CART) UN
ON POST.POST_BY_USERID = UN.USERID AND POST.TOPICID = UN.TOPICID
INNER JOIN OPN_USERLIST U
ON POST.POST_BY_USERID = U.USERID
AND POST.POST_BY_USERID NOT IN (SELECT ON_USERID FROM OPN_USER_USER_ACTION WHERE ACTION_TYPE = 'KO')
LEFT OUTER JOIN OPNV_POST_ACTION_CNT OPAC ON POST.POST_ID = OPAC.CAUSE_POST_ID
LEFT OUTER JOIN OPN_USER_POST_ACTION UP ON POST.POST_ID = UP.CAUSE_POST_ID AND UP.ACTION_BY_USERID = \"$userid\"
-- ORDER BY POST.POST_DATETIME DESC, UN.CART DESC, UN.NET_STRENGTH DESC
UNION ALL
SELECT P.POST_ID, P.TOPICID, P.POST_BY_USERID, U.USERNAME, P.POST_DATETIME, P.POST_CONTENT, 'L' CART, 1 NETSTRENGTH
, OPAC.LCOUNT, OPAC.HCOUNT, UP2.POST_ACTION_TYPE
FROM OPN_POSTS P INNER JOIN OPN_USERLIST U ON P.POST_BY_USERID = U.USERID
LEFT OUTER JOIN OPN_USER_POST_ACTION UP2 ON P.POST_ID = UP2.CAUSE_POST_ID AND UP2.ACTION_BY_USERID = \"$userid\"
LEFT OUTER JOIN OPNV_POST_ACTION_CNT OPAC ON P.POST_ID = OPAC.CAUSE_POST_ID
WHERE P.TOPICID = \"$topicid\" AND P.POST_BY_USERID IN 
(SELECT DISTINCT USERID FROM OPN_USER_CLUSTERS WHERE CLUSTER_ID IN (SELECT CLUSTER_ID FROM OPN_USER_CLUSTERS
WHERE USERID = \"$userid\" AND TOPICID = \"$topicid\" AND DEFAULT_UC_COMBO = 'Y'))
AND P.POST_BY_USERID NOT IN (SELECT ON_USERID FROM OPN_USER_USER_ACTION WHERE ACTION_TYPE = 'KO')
)SQ
ORDER BY POST_DATETIME DESC, CART DESC, NET_STRENGTH DESC";

//              echo $q;
$result = mysqli_query($db,$q);
if($result == TRUE){
while (($row = mysqli_fetch_assoc($result))){
        $json_arry[] =  $row;
 }
$r =  json_encode($json_arry);
echo $r;
}
else{
$response = "{\"status\": \"error\"}";
echo $r;
}
}

?>
