ELECT POST.POST_ID, POST.TOPICID, POST.POST_BY_USERID, U.USERNAME, POST.POST_DATETIME, POST.POST_CONTENT
, OPAC.LCOUNT, OPAC.HCOUNT
FROM OPN_POSTS POST
INNER JOIN (SELECT SQ1.TOPICID, SQ1.USERID, SQ1.CLUSTER_ID, SQ1.CART, SQ1.UCART_SIZE CONNECTED_CSIZE, SQ1.CLUSTER_SIZE, SQ2.USER_CARTSZ
, CASE WHEN SQ1.UCART_SIZE <= SQ2.USER_CARTSZ THEN SQ1.UCART_SIZE/SQ2.USER_CARTSZ ELSE 1/(SQ1.UCART_SIZE/SQ2.USER_CARTSZ) END NET_STRENGTH
FROM
(SELECT B.TOPICID, B.USERID, B.CLUSTER_ID, B.CART, B.UCART_SIZE, B.CLUSTER_SIZE FROM OPN_USER_CLUSTERS B WHERE B.CLUSTER_ID IN (
SELECT A.CLUSTER_ID FROM OPN_USER_CLUSTERS A WHERE A.TOPICID = B.TOPICID AND A.USERID = 1003969 AND  A.UCART_SIZE = A.CLUSTER_SIZE)
UNION ALL
SELECT B.TOPICID, B.USERID, B.CLUSTER_ID, B.CART, B.UCART_SIZE, B.CLUSTER_SIZE FROM OPN_USER_CLUSTERS B WHERE B.CLUSTER_ID IN (
SELECT A.CLUSTER_ID FROM OPN_USER_CLUSTERS A WHERE A.TOPICID = B.TOPICID AND A.USERID = 1003969 AND  A.UCART_SIZE +1 = A.CLUSTER_SIZE)
AND B.UCART_SIZE = B.CLUSTER_SIZE
UNION ALL
SELECT B.TOPICID, B.USERID, B.CLUSTER_ID, B.CART, B.UCART_SIZE, B.CLUSTER_SIZE FROM OPN_USER_CLUSTERS B WHERE B.CLUSTER_ID IN (
SELECT A.CLUSTER_ID FROM OPN_USER_CLUSTERS A WHERE A.TOPICID = B.TOPICID AND A.USERID = 1003969 AND  A.UCART_SIZE +2 = A.CLUSTER_SIZE)
AND B.UCART_SIZE = B.CLUSTER_SIZE) SQ1, (SELECT TOPICID, USERID, CART, USER_CARTSZ FROM OPN_USER_CARTSIZE
WHERE USERID = 1003969) SQ2
WHERE SQ1.TOPICID = SQ2.TOPICID AND SQ1.CART = SQ2.CART) UN
ON POST.POST_BY_USERID = UN.USERID AND POST.TOPICID = UN.TOPICID
INNER JOIN OPN_USERLIST U
ON POST.POST_BY_USERID = U.USERID
 AND POST.POST_BY_USERID NOT IN (SELECT ON_USERID FROM OPN_USER_USER_ACTION WHERE ACTION_TYPE = 'KO')
 LEFT OUTER JOIN OPNV_POST_ACTION_CNT OPAC
 ON POST.POST_ID = OPAC.CAUSE_POST_ID
ORDER BY POST.POST_DATETIME DESC, UN.CART DESC, UN.NET_STRENGTH DESC;
