-- -- 

DELIMITER //
DROP PROCEDURE IF EXISTS ADD_NUSERS_4K1 //
CREATE PROCEDURE ADD_NUSERS_4K1(K1 INT, CCODE VARCHAR(5),  TID INT)


thisProc: BEGIN

/* for loading demo users carts with the new KW that is crated by a user

07/24/2019 AST: Changing the random user KW->cart assignment logic - 
replacing AND USERID < 1020000 AND TAILORED_USER_FLAG = 'N' with BOT_FLAG = 'Y'

	07/01/2020 AST: Adding the steps where each new KW will create some BOT users
    in all the CCODES - not just the CCODE of the origin user.
    
        06/18/2023 AST: Added the Raw Loggin portion for analysis of convertPostToKW

*/

DECLARE  HCOUNT, LCOUNT INT ;

/* Added on 07/01/2020 AST */

DECLARE CCD2, CCD3 VARCHAR(5) ;

CASE WHEN CCODE = 'USA' THEN SET CCD2 = 'IND' ;
	SET CCD3 = 'GGG' ;
    WHEN CCODE = 'IND' THEN SET CCD2 = 'USA' ;
	SET CCD3 = 'GGG' ;
    WHEN CCODE = 'GGG' THEN SET CCD2 = 'IND' ;
	SET CCD3 = 'USA' ;
    
    END CASE ;

/* End of 07/01/2020 addition */

SET HCOUNT = FLOOR(RAND()* (25-15) +15) ;

SET LCOUNT = FLOOR(RAND()* (40-25) +25) ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'H', K1, USERID, TID, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (K1))
AND BOT_FLAG = 'Y' AND COUNTRY_CODE IN (CCODE) ORDER BY RAND() LIMIT HCOUNT)Q ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', K1, USERID, TID, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (K1))
AND BOT_FLAG = 'Y' AND COUNTRY_CODE IN (CCODE) ORDER BY RAND() LIMIT LCOUNT)Q ;

-- CALL NEWCART_TOP_NOTAILOR(UUID, TID1) ;

/* Added on 07/01/2020 AST */

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'H', K1, USERID, TID, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (K1))
AND BOT_FLAG = 'Y' AND COUNTRY_CODE IN (CCD2) ORDER BY RAND() LIMIT HCOUNT )Q ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', K1, USERID, TID, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (K1))
AND BOT_FLAG = 'Y' AND COUNTRY_CODE IN (CCD2) ORDER BY RAND() LIMIT LCOUNT )Q ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'H', K1, USERID, TID, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (K1))
AND BOT_FLAG = 'Y' AND COUNTRY_CODE IN (CCD3) ORDER BY RAND() LIMIT HCOUNT)Q ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', K1, USERID, TID, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (K1))
AND BOT_FLAG = 'Y' AND COUNTRY_CODE IN (CCD3) ORDER BY RAND() LIMIT LCOUNT)Q ;

/* End of 07/01/2020 addition */

INSERT INTO OPN_RAW_LOGS(KEYVALUE_KEY, KEYVALUE_VALUE, LOG_DTM) VALUES(
'ADD_NUSERS_4K1-KEYID-CCODE1-HCOUNT-LCOUNT'
, CONCAT(K1, '-', CCODE,'-',HCOUNT,'-', LCOUNT), NOW() ) ;

 
END; //
 DELIMITER ;
 
 -- 