-- -- 

DELIMITER //
DROP PROCEDURE IF EXISTS ADD_NUSERS_4K1 //
CREATE PROCEDURE ADD_NUSERS_4K1(K1 INT, CCODE VARCHAR(5),  TID INT)


thisProc: BEGIN

/* for loading demo users carts with the new KW that is crated by a user

07/14/2024 AST: Changing the random ranges for HCOUNT AND LCOUNT. This is becuase 
the CART table has become huge and each bot has hundred+ KWs in the cart.
We don't need a large number random bots for each new post that is converted to KW

07/24/2019 AST: Changing the random user KW->cart assignment logic - 
replacing AND USERID < 1020000 AND TAILORED_USER_FLAG = 'N' with BOT_FLAG = 'Y'

	07/01/2020 AST: Adding the steps where each new KW will create some BOT users
    in all the CCODES - not just the CCODE of the origin user.
    
        06/18/2023 AST: Added the Raw Loggin portion for analysis of convertPostToKW
        
	08/29/2025 AST: Making major changes to this:
    1. Remove the section that inserts the KW into carts of users (bots) that do not belong to the same CCODE
    2. treating the TCC STD differently compared to the STD or STP creations: TCC should be allocating the ADD users that match the H and L of the original CONTENT_CAMP and TONE
    Also: we pick BOTs for ADD from the same TCC --> in order to keep the discussions localized to the same TCC where they were scraped from
    3. For now, we will leave the reswt of the STD process same - but we may discontinue the regular STD because it has no TONE and CAMP assignments
    4. Also: changing the ADD counts -- from around 5 to around 10

*/

DECLARE  HCOUNT, LCOUNT, TCCUCOUNT, TCCOPPOCOUNT INT ;

/* Added on 07/01/2020 AST */

DECLARE CCD2, CCD3, TCC, UCART, OPPOCART VARCHAR(5) ;
DECLARE CONTCAMP, CONTTONE, OPPOCAMP, PROC VARCHAR(25) ;
/*
CASE WHEN CCODE = 'USA' THEN SET CCD2 = 'IND' ;
	SET CCD3 = 'GGG' ;
    WHEN CCODE = 'IND' THEN SET CCD2 = 'USA' ;
	SET CCD3 = 'GGG' ;
    WHEN CCODE = 'GGG' THEN SET CCD2 = 'IND' ;
	SET CCD3 = 'USA' ;
    
    END CASE ; */

/* End of 07/01/2020 addition */

SET HCOUNT = FLOOR(RAND()* (5-2) +2) ;

SET LCOUNT = FLOOR(RAND()* (8-2) +2) ;

SET TCCUCOUNT = FLOOR(RAND()* (5-2) +2) ;

SET TCCOPPOCOUNT = FLOOR(RAND()* (5-2) +2) ;

/* START bifurcating the TCC vs non-TCC behavior here: if STP_PROC from OPN_P_KW is TCC_DISCUSSION then:
Read the KW_TONE, KW_CAMP from OPN_P_KW. These two have to be matched from OU when selecting the random BOTs to insert the cart

*/

SELECT KW_TCC, STP_PROC, KW_TONE, KW_CAMP INTO TCC, PROC, CONTTONE, CONTCAMP FROM OPN_P_KW WHERE KEYID = K1 ;

CASE WHEN PROC = 'TCC_DISCUSSION' THEN

/* START HANDLING THE TCC CASE */

CASE WHEN CONTCAMP = 'DEM' THEN SET OPPOCAMP = 'REPUB';
WHEN CONTCAMP = 'REPUB' THEN SET OPPOCAMP = 'DEM';
WHEN CONTCAMP = 'ELITES' THEN SET OPPOCAMP = 'REFORM' ;
WHEN CONTCAMP = 'REFORM' THEN SET OPPOCAMP = 'ELITES' ;
WHEN CONTCAMP = 'PROMODI' THEN SET OPPOCAMP = 'ANTIMODI' ;
WHEN CONTCAMP = 'ANTIMODI' THEN SET OPPOCAMP = 'PROMODI' ;
WHEN CONTCAMP = 'ISLAMIST' THEN SET OPPOCAMP = 'MODERN' ;
WHEN CONTCAMP = 'MODERN' THEN SET OPPOCAMP = 'ISLAMIST' ;
END CASE ;

CASE WHEN CONTTONE = 'LOVE' THEN SET UCART = 'L', OPPOCART = 'H' ;
WHEN CONTTONE = 'HATE' THEN SET UCART = 'H', OPPOCART = 'L' ;
END CASE ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT UCART, K1, USERID, TID, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE BOT_FLAG = 'Y' AND TRUE_COUNTRY_CODE = TCC AND OPINION_CAMP = CONTCAMP
  AND USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (K1))
ORDER BY RAND() LIMIT TCCUCOUNT)Q ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT OPPOCART, K1, USERID, TID, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE BOT_FLAG = 'Y' AND TRUE_COUNTRY_CODE = TCC AND OPINION_CAMP = OPPOCAMP
  AND USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (K1))
ORDER BY RAND() LIMIT TCCOPPOCOUNT)Q ;

INSERT INTO OPN_RAW_LOGS(KEYVALUE_KEY, KEYVALUE_VALUE, LOG_DTM) VALUES(
'ADD_NUSERS_4K1-KEYID-CCODE1-TCCUCOUNT-TCCOPPOCOUNT'
, CONCAT(K1, '-', TCC,'-',TCCUCOUNT,'-', TCCOPPOCOUNT), NOW() ) ;

WHEN PROC <> 'TCC_DISCUSSION' THEN

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'H', K1, USERID, TID, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (K1))
AND BOT_FLAG = 'Y' AND COUNTRY_CODE IN (CCODE) ORDER BY RAND() LIMIT HCOUNT)Q ;

INSERT INTO OPN_USER_CARTS(CART, KEYID, USERID, TOPICID, CREATION_DTM, LAST_UPDATE_DTM)
SELECT 'L', K1, USERID, TID, NOW(), NOW() FROM 
(SELECT USERID FROM OPN_USERLIST 
  WHERE USERID NOT IN (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE KEYID  IN (K1))
AND BOT_FLAG = 'Y' AND COUNTRY_CODE IN (CCODE) ORDER BY RAND() LIMIT LCOUNT)Q ;

-- CALL NEWCART_TOP_NOTAILOR(UUID, TID1) ;

/* Added on 07/01/2020 AST 

REMOVED ON 08/29/2025  because we don't want non-matching CCODE carts

 End of 07/01/2020 addition */

INSERT INTO OPN_RAW_LOGS(KEYVALUE_KEY, KEYVALUE_VALUE, LOG_DTM) VALUES(
'ADD_NUSERS_4K1-KEYID-CCODE1-HCOUNT-LCOUNT'
, CONCAT(K1, '-', CCODE,'-',HCOUNT,'-', LCOUNT), NOW() ) ;

END CASE ; -- END OF CASE WHEN PROC = 'TCC_DISCUSSION'

 
END; //
 DELIMITER ;
 
 -- 