
-- bringPostCountNW

DELIMITER //
DROP FUNCTION IF EXISTS bringPostCountNW //
CREATE FUNCTION bringPostCountNW(UUID VARCHAR(45),  TID INT) RETURNS INT
BEGIN

/* 05/03/2020 AST: Post COunt after rebuild of getPostsByUserNameNW 

	07/12/2020 AST: Added the changes needed to handle the BOT posts */
    
/* 	11/08/2020 AST: Now the non-clean posts are being changed to a standard warning replacement. 
	Hence, removing the filter AND CLEAN_POST_FLAG = 'Y' from all cases below */

  DECLARE PostCOUNT, UID INT ;
  DECLARE CCODE VARCHAR(5) ;
  
  SELECT USERID, COUNTRY_CODE INTO UID, CCODE FROM OPN_USERLIST WHERE USER_UUID = UUID ;

SET PostCOUNT = (SELECT COUNT(1)
FROM OPN_POSTS P
, (SELECT DISTINCT B.USERID, B.BOT_FLAG, A.TOPICID FROM
(SELECT C1.USERID, C1.TOPICID, C1.CART, C1.KEYID FROM OPN_USER_CARTS C1 
WHERE C1.USERID = UID) A ,
(SELECT C2.USERID, CU.BOT_FLAG, C2.TOPICID, C2.CART, C2.KEYID, C2.CREATION_DTM 
FROM OPN_USER_CARTS C2, OPN_USERLIST CU WHERE C2.USERID = CU.USERID AND
 C2.USERID NOT IN (SELECT OUUA.ON_USERID FROM OPN_USER_USER_ACTION OUUA 
 WHERE OUUA.BY_USERID = UID 
AND OUUA.TOPICID = TID AND OUUA.ACTION_TYPE = 'KO')) B 
WHERE A.TOPICID = B.TOPICID AND A.CART = B.CART 
AND A.KEYID = B.KEYID AND A.TOPICID = TID ) UN
WHERE UN.USERID = P.POST_BY_USERID
AND P.POST_DATETIME > CURRENT_DATE() - INTERVAL 30 DAY
AND UN.TOPICID = P.TOPICID
AND (P.TAG1_KEYID IS NULL OR P.TAG1_KEYID IN 
(SELECT KK.KEYID FROM OPN_USER_CARTS KK WHERE KK.USERID = UID))
AND ( -- P.CLEAN_POST_FLAG = 'Y' AND 
(CASE WHEN UN.BOT_FLAG = 'Y' 
THEN  P.POSTOR_COUNTRY_CODE IN ( CCODE, 'GGG' ) ELSE P.POSTOR_COUNTRY_CODE NOT IN ('PQR')  END ) ));

  RETURN PostCOUNT;
  
END;//

-- 