-- bringUUID

DELIMITER //
DROP FUNCTION IF EXISTS bringUUID //
CREATE FUNCTION bringUUID(UID INT) RETURNS VARCHAR(45)
BEGIN

/* 04/25/2020 AST: Rebuilt: brought the comment inside the body
 SELECT bringUUID(UID INT) */

  DECLARE userUUID VARCHAR(45) ;

SET userUUID := (SELECT USER_UUID FROM OPN_USERLIST WHERE USERID = UID);

  RETURN userUUID;
END;//

-- 