-- bringCartDate

DELIMITER //
DROP FUNCTION IF EXISTS bringCartDate //
CREATE FUNCTION bringCartDate(UID INT, TID INT) RETURNS DATE
BEGIN

/* 04/25/2020 AST: Rebuilt: Removed the @ from the var CART_DATE 
 SELECT bringCartDate(UID INT, TID INT) */

  DECLARE CART_DATE DATE ;

SET CART_DATE = (SELECT Q1.CART_DATE FROM (
   SELECT OUC.USERID, OUC.TOPICID, MAX(DATE(OUC.CREATION_DTM)) CART_DATE FROM OPN_USER_CARTS OUC
WHERE USERID = UID AND TOPICID = TID
GROUP BY USERID, TOPICID ) Q1);
  RETURN CART_DATE;
  
END;//

-- 