-- bringPostCountALL

DELIMITER //
DROP FUNCTION IF EXISTS bringPostCountALL //
CREATE FUNCTION bringPostCountALL(UUID VARCHAR(45),  TID INT) RETURNS INT
BEGIN

/* 05/03/2020 AST: Post COunt after rebuild of getPostsByUserNameALL */

  DECLARE PostCOUNT, UID INT ;
  
  SET UID = (SELECT USERID FROM OPN_USERLIST WHERE USER_UUID = UUID) ;

SET PostCOUNT = (SELECT COUNT(1) FROM 
OPN_POSTS P, (
SELECT DISTINCT B.TOPICID, B.USERID IN_NW_UID  FROM
(SELECT C1.USERID, C1.TOPICID, C1.CART, C1.KEYID FROM OPN_USER_CARTS C1
WHERE C1.TOPICID = TID AND C1.USERID = UID) A ,
(SELECT C2.USERID, C2.TOPICID, C2.CART, C2.KEYID FROM OPN_USER_CARTS C2
WHERE C2.TOPICID = TID  
AND C2.USERID NOT IN (SELECT OUA.ON_USERID FROM OPN_USER_USER_ACTION OUA
WHERE OUA.TOPICID = TID AND OUA.BY_USERID = UID AND OUA.ACTION_TYPE IN ('KO', 'CKO'))
) B
WHERE A.TOPICID = B.TOPICID AND A.KEYID = B.KEYID  ) NW1
WHERE P.POST_BY_USERID = NW1.IN_NW_UID AND P.TOPICID = NW1.TOPICID
AND P.POST_DATETIME > CURRENT_DATE() - INTERVAL 1 MONTH);

  RETURN PostCOUNT;
  
END;//

-- 