-- bringTK1Count

DELIMITER //
DROP FUNCTION IF EXISTS bringTK1Count //
CREATE FUNCTION bringTK1Count(KID INT) RETURNS INT
BEGIN

/*05/ */

  DECLARE PostLCOUNT INT ;

SET PostLCOUNT = (SELECT COUNT(1) 
FROM OPN_POSTS P WHERE P.TAG1_KEYID = KID) ;
  RETURN PostLCOUNT;
  
END;//

-- 