-- COMMENT_CONC_NOTIF_TRIGGER

DELIMITER $$
DROP TRIGGER IF EXISTS COMMENT_CONC_NOTIF_TRIGGER $$
CREATE DEFINER=`root`@`%` TRIGGER COMMENT_CONC_NOTIF_TRIGGER
AFTER INSERT ON OPN_POST_COMMENTS for each row
begin

/* 
    08/27/2020 AST: initial creation - to push notif users when there is a COMMENT OR CONC
    ON their post or comment resp.

*/

DECLARE POSTTOPIC, PBYUNAME VARCHAR(30) ;
DECLARE POST_EXCRPT VARCHAR(150) ;
DECLARE KW VARCHAR(300) ;
DECLARE CTYPE VARCHAR(10) ;


CASE WHEN NEW.TOPICID = 1 THEN SET POSTTOPIC = 'Politics' ;
WHEN NEW.TOPICID = 2 THEN SET POSTTOPIC = 'Sports/Games' ;
WHEN NEW.TOPICID = 3 THEN SET POSTTOPIC = 'Science/Tech' ;
WHEN NEW.TOPICID = 4 THEN SET POSTTOPIC = 'Business' ;
WHEN NEW.TOPICID = 5 THEN SET POSTTOPIC = 'Media/Ent.' ;
WHEN NEW.TOPICID = 6 THEN SET POSTTOPIC = 'Religion' ;
WHEN NEW.TOPICID = 7 THEN SET POSTTOPIC = 'Life' ;
WHEN NEW.TOPICID = 8 THEN SET POSTTOPIC = 'Miscellaneous' ;
WHEN NEW.TOPICID = 9 THEN SET POSTTOPIC = 'Trending' ;
WHEN NEW.TOPICID = 10 THEN SET POSTTOPIC = 'Celebrities' ;
WHEN NEW.TOPICID = 11 THEN SET POSTTOPIC = 'Health' ;

END CASE;

SET POST_EXCRPT = (SELECT substring(NEW.COMMENT_CONTENT, 1, 140));
-- SET PBYUNAME = (SELECT USERNAME FROM OPN_USERLIST WHERE USERID = NEW.POST_BY_USERID) ;

CASE WHEN NEW.COMMENT_TYPE = 'CONP' THEN

INSERT INTO OPN_PUSH_LAUNCH(USERID, USER_UUID, APP_TOKEN, USER_PLATFORM, PUSH_TYPE
, PUSH_COUNT, PUSH_TOPIC, SOURCE_ID, POST_EXCERPT, PUSH_TITLE)
SELECT U.USERID, U.USER_UUID, U.IDENTIFIER_TOKEN, U.LAST_USED_PLATFORM, 'COMMENT'
, 1 , POSTTOPIC, NEW.CAUSE_POST_ID, POST_EXCRPT, 'New comment/s on your post in'
FROM OPN_USERLIST U WHERE U.USERID = NEW.POST_BY_USERID;

WHEN NEW.COMMENT_TYPE = 'CONC' THEN

INSERT INTO OPN_PUSH_LAUNCH(USERID, USER_UUID, APP_TOKEN, USER_PLATFORM, PUSH_TYPE
, PUSH_COUNT, PUSH_TOPIC, SOURCE_ID, POST_EXCERPT, PUSH_TITLE)
SELECT U.USERID, U.USER_UUID, U.IDENTIFIER_TOKEN, U.LAST_USED_PLATFORM, 'CONC'
, 1 , POSTTOPIC, NEW.CAUSE_POST_ID, POST_EXCRPT, 'New comment/s on your comment in'
FROM OPN_USERLIST U WHERE U.USERID = NEW.PARENT_COMMENT_BYUID;

END CASE ;


END$$

DELIMITER ; 