-- getALLNWCount

DELIMITER //
DROP FUNCTION IF EXISTS getALLNWCount //
CREATE FUNCTION getALLNWCount(UID INT, TID INT) RETURNS INT
BEGIN

/* 06/20/2018 AST: Changed the NW algo to the newer one 
   04/25/2020 AST: ADDED CKO TO ACTION_TYPE */

  DECLARE ALLNCOUNT INT ;
 
   SET ALLNCOUNT = (SELECT COUNT(DISTINCT B.USERID)  FROM
(SELECT USERID, TOPICID, CART, KEYID FROM OPN_USER_CARTS WHERE TOPICID = TID AND USERID = UID) A ,
(SELECT USERID, TOPICID, CART, KEYID FROM OPN_USER_CARTS WHERE TOPICID = TID AND USERID <> UID 
AND USERID NOT IN (SELECT ON_USERID FROM OPN_USER_USER_ACTION 
WHERE TOPICID = TID AND BY_USERID = UID AND ACTION_TYPE IN ('KO', 'CKO'))
) B
WHERE A.TOPICID = B.TOPICID AND A.KEYID = B.KEYID )
 ;

  RETURN ALLNCOUNT;
  
END;//

-- 