-- getCartTopics

DELIMITER //
DROP PROCEDURE IF EXISTS getCartTopics //
CREATE PROCEDURE getCartTopics(uuid varchar(50))
BEGIN

-- 121817 TRYING THE RE-ORDER USING CODE COLUMN

-- SELECT * FROM OPN_TOPICS;
/* 
 08/11/2020 Kapil: Confirmed
 */

DECLARE UID INT ;
DECLARE UNAME, UTYPE VARCHAR(40) ;

SELECT USERID, USERNAME, USER_TYPE INTO UID, UNAME, UTYPE FROM OPN_USERLIST WHERE USER_UUID = uuid ;

SELECT DISTINCT C1.TOPICID CTOPIC , T.TOPIC, T.CODE, 'A' SRC
FROM OPN_USER_CARTS C1, OPN_TOPICS T WHERE C1.TOPICID = T.TOPICID AND C1.USERID = UID 
UNION ALL
SELECT TOPICID, TOPIC, CODE, 'B' SRC FROM OPN_TOPICS WHERE TOPICID NOT IN 
(SELECT DISTINCT TOPICID FROM OPN_USER_CARTS WHERE USERID = UID)
ORDER BY SRC, CODE
;



END //
DELIMITER ;

-- 