-- getKOContent

-- 

 DELIMITER //
DROP PROCEDURE IF EXISTS getKOContent //
CREATE PROCEDURE getKOContent(uname varchar(40) )
BEGIN

/* 
09/07/2020 AST: initial Creation
		this proc is used for getting the posts that resulted in KO for a user

 */

declare UID INT ;
DECLARE UUID VARCHAR(45) ;
DECLARE UTYPE VARCHAR(3) ;
DECLARE UDEVICE VARCHAR(200) ;
DECLARE UEMAIL, UFBID, UGID, UAID VARCHAR(100) ;

SELECT USERID, USER_UUID, FB_USER_FLAG, FB_USERID, IDENTIFIER_TOKEN, G_USERID, EMAIL_ADDR, A_USERID
INTO UID, UUID, UTYPE, UFBID, UDEVICE, UGID, UEMAIL, UAID FROM OPN_USERLIST  WHERE USERNAME = uname ;

SELECT ID, DTM, CONTENT, CTYPE FROM (
SELECT P.POST_ID ID, P.POST_DATETIME DTM, P.POST_CONTENT CONTENT, 'POST' CTYPE
FROM OPN_POSTS P 
, (SELECT DISTINCT CAUSE_POST_ID FROM OPN_USER_USER_ACTION WHERE ON_USERID = UID AND ACTION_COMMENT IN ('PKO') ) A2
WHERE A2.CAUSE_POST_ID = P.POST_ID 
UNION ALL
SELECT C.COMMENT_ID ID, C.COMMENT_DTM DTM, C.COMMENT_CONTENT CONTENT, 'COMMENT' CTYPE
FROM OPN_POST_COMMENTS C 
, (SELECT DISTINCT CAUSE_COMMENT_ID FROM OPN_USER_USER_ACTION WHERE ON_USERID = UID AND ACTION_COMMENT IN ('CKO') ) A2
WHERE A2.CAUSE_COMMENT_ID = C.COMMENT_ID 
)Q ORDER BY DTM DESC LIMIT 25
;
 



END //
DELIMITER ;

-- 