
-- getNWPCount

DELIMITER //
DROP FUNCTION IF EXISTS getNWPCount //
CREATE FUNCTION getNWPCount(UID INT, TID INT) RETURNS INT
BEGIN

/* 04/25/2020 AST: Rebuilt: brought the comment inside the body
this proc was still using the old network algo - changed it to the new
 SELECT getNWPCount(UID INT, TID INT) */

  DECLARE NWPCOUNT INT ;

  SET NWPCOUNT = (SELECT COUNT(1) FROM OPN_POSTS P 
  WHERE  P.CLEAN_POST_FLAG = 'Y' AND P.TOPICID = TID
 AND P.POST_BY_USERID IN(
SELECT DISTINCT B.USERID  FROM
(SELECT USERID, TOPICID, CART, KEYID FROM OPN_USER_CARTS 
WHERE TOPICID = TID AND USERID = UID) A ,
(SELECT USERID, TOPICID, CART, KEYID FROM OPN_USER_CARTS 
WHERE TOPICID = TID -- AND USERID <> UID 
AND USERID NOT IN (SELECT ON_USERID FROM OPN_USER_USER_ACTION 
WHERE TOPICID = TID AND BY_USERID = UID AND ACTION_TYPE IN ('KO', 'CKO'))
) B
WHERE A.TOPICID = B.TOPICID AND A.CART = B.CART AND A.KEYID = B.KEYID
) 

);

  RETURN NWPCOUNT;
END;//

-- 