-- getUserTopics

DELIMITER //
DROP PROCEDURE IF EXISTS getUserTopics //
CREATE PROCEDURE getUserTopics(userid VARCHAR(45))
BEGIN
/*
08/11/2020 Kapil: Confirmed
*/
declare  orig_uid INT;

SET orig_uid = (SELECT  bringUserid(userid));

SELECT DISTINCT A.TOPICID, B.TOPIC, B.CODE
FROM OPN_USER_CARTS A, OPN_TOPICS B

-- 121817 TRYING ALTERNATE ORDERING OF TOPICS
-- WHERE A.USERID = @orig_uid AND A.TOPICID = B.TOPICID ORDER BY A.TOPICID;

WHERE A.USERID = orig_uid AND A.TOPICID = B.TOPICID ORDER BY B.CODE;
  
END //
DELIMITER ;

-- 