-- getUserActivity

-- 

 DELIMITER //
DROP PROCEDURE IF EXISTS getUserActivity //
CREATE PROCEDURE getUserActivity(uname varchar(40) )
BEGIN

/* 
09/07/2020 AST: initial Creation
		this proc is used for getting the detailed activities of a specific username
		this is for determining whether to ban this user

 */

declare UID, PCNT7, CCNT7, RPCNT7, YPCNT, YCCNT, YRPCNT, YRCCNT, KOCNT INT ;
DECLARE UUID VARCHAR(45) ;
DECLARE UTYPE VARCHAR(3) ;
DECLARE UDEVICE VARCHAR(200) ;
DECLARE UEMAIL, UFBID, UGID, UAID VARCHAR(100) ;

SELECT USERID, USER_UUID, FB_USER_FLAG, FB_USERID, IDENTIFIER_TOKEN, G_USERID, EMAIL_ADDR, A_USERID
INTO UID, UUID, UTYPE, UFBID, UDEVICE, UGID, UEMAIL, UAID FROM OPN_USERLIST  WHERE USERNAME = uname ;

SELECT COUNT(1) INTO PCNT7 FROM OPN_POSTS WHERE POST_BY_USERID = UID 
AND POST_PROCESSED_DTM > CURRENT_DATE() - INTERVAL 7 DAY  ;

SELECT COUNT(1) INTO YPCNT FROM OPN_POSTS WHERE POST_BY_USERID = UID 
AND POST_PROCESSED_DTM > CURRENT_DATE() - INTERVAL 1 YEAR  ;

SELECT COUNT(1) INTO CCNT7 FROM OPN_POST_COMMENTS WHERE POST_BY_USERID = UID 
AND COMMENT_DTM > CURRENT_DATE() - INTERVAL 7 DAY  ;

SELECT COUNT(1) INTO YCCNT FROM OPN_POST_COMMENTS WHERE POST_BY_USERID = UID 
AND COMMENT_DTM > CURRENT_DATE() - INTERVAL 1 YEAR  ;

SELECT COUNT(1) INTO KOCNT FROM OPN_USER_USER_ACTION WHERE ON_USERID = UID ;

SELECT COUNT(1) INTO RPCNT7 FROM OPN_USER_REPORTED_CONTENT WHERE AGAINST_USERID = UID 
AND REPORTING_DTM > CURRENT_DATE() - INTERVAL 7 DAY ;

SELECT uname username, PCNT7 pcount_7day, YPCNT pcount_year
, CCNT7 ccount_7day, YCCNT ccount_year, KOCNT ko_count, RPCNT7 reported_count7 ;



END //
DELIMITER ;

-- 