-- 

DROP PROCEDURE IF EXISTS KILL_KEYWORD ;
DELIMITER $$
CREATE  PROCEDURE `KILL_KEYWORD`(ENTRYKEY VARCHAR(10), KID INT, TID INT)
THISPROC: BEGIN

/* THIS PROC IS INTENDED TO CLEANLY REMOVE AN EXISTING KEYWORD FOR WHICH THERE ARE ALREADY CARTS, CLUSTERS ETC.

ENTRYKEY is to ensure that only I can kill a KW even if somebody knows the call
12/11/2020 AST: Added UPDATE OPN_POSTS for matching TAG1_KEYID
12/15/2020 ast: added SQL_SAFE_UPDATES = 0
*/
SET SQL_SAFE_UPDATES = 0;

 CASE WHEN ENTRYKEY = 'kalyan' THEN
 
DELETE FROM OPN_USER_CARTS WHERE TOPICID = TID AND KEYID = KID ;

UPDATE OPN_POSTS SET CLEAN_POST_FLAG = 'N' WHERE TAG1_KEYID = KID AND TOPICID = TID ;

DELETE FROM OPN_KW_TAGS WHERE TOPICID = TID AND KEYID = KID ;

INSERT INTO OPN_KILLED_KW SELECT * FROM OPN_P_KW WHERE TOPICID = TID AND KEYID = KID ;

UPDATE OPN_KILLED_KW SET LAST_UPDATE_DTM = NOW() WHERE TOPICID = TID AND KEYID = KID ;

DELETE FROM OPN_P_KW WHERE TOPICID = TID AND KEYID = KID; 

WHEN ENTRYKEY <> 'kalyan' THEN

SELECT 'INTRUDER ALERT' FROM DUAL ;

END CASE ;




  
  
  
END$$
DELIMITER ;

-- 
