-- KOUserCommon

 DELIMITER //
DROP PROCEDURE IF EXISTS KOUserCommon //
CREATE PROCEDURE KOUserCommon(userid varchar(45), KOtype VARCHAR(10), KOSourceID INT)
BEGIN

/* 06/02/2020 AST: Adding the USR BHV Log  
08/11/2020 Kapil: Confirmed
*/


declare  ORIG_UID, causePostID, TID, causeCommentID, postByUID, commentUserid INT;

CASE WHEN KOtype = 'COMMENT' THEN

SET ORIG_UID = (SELECT  bringUserid(userid));

SELECT TOPICID, COMMENT_BY_USERID, CAUSE_POST_ID INTO TID, commentUserid, causePostID
FROM OPN_POST_COMMENTS WHERE COMMENT_ID = KOSourceID ;

/* Adding user action logging portion */

INSERT INTO OPN_USER_BHV_LOG(USERNAME, USERID, USER_UUID, LOGIN_DTM, API_CALL, CONCAT_PARAMS)
VALUES(bringUsernameByUID(ORIG_UID), ORIG_UID, userid, NOW(), 'KOUserCommon'
, CONCAT(ORIG_UID, ' - COMMENT KO -',commentUserid, ' FOR COMMENT_ID = ', KOSourceID));

INSERT INTO OPN_USER_BHV_LOG(USERNAME, USERID, USER_UUID, LOGIN_DTM, API_CALL, CONCAT_PARAMS)
VALUES(bringUsernameByUID(ORIG_UID), ORIG_UID, userid, NOW(), 'KOUserCommon'
, CONCAT(commentUserid, ' - REVERSE CKO -',ORIG_UID, ' FOR COMMENT_ID = ', KOSourceID));

/* end of use action tracking */

DELETE FROM OPN_USER_USER_ACTION WHERE OPN_USER_USER_ACTION.BY_USERID = ORIG_UID 
AND OPN_USER_USER_ACTION.TOPICID = TID
AND OPN_USER_USER_ACTION.ON_USERID =  commentUserid ;

DELETE FROM OPN_USER_USER_ACTION WHERE OPN_USER_USER_ACTION.BY_USERID = commentUserid 
AND OPN_USER_USER_ACTION.TOPICID = TID
AND OPN_USER_USER_ACTION.ON_USERID =  ORIG_UID ;

INSERT INTO OPN_USER_USER_ACTION (BY_USERID, ON_USERID, ACTION_TYPE, ACTION_DTM
, CAUSE_POST_ID, CAUSE_COMMENT_ID, ACTION_COMMENT, TOPICID) 
VALUES (ORIG_UID, commentUserid, 'KO', NOW(), causePostID, KOSourceID, 'CKO', TID) ;

INSERT INTO OPN_USER_USER_ACTION (BY_USERID, ON_USERID, ACTION_TYPE, ACTION_DTM
, CAUSE_POST_ID, CAUSE_COMMENT_ID, ACTION_COMMENT, TOPICID) 
VALUES (commentUserid, ORIG_UID, 'KO', NOW(), causePostID, KOSourceID, 'RCKO', TID) ;

WHEN KOtype = 'POST' THEN

SET ORIG_UID = (SELECT  bringUserid(userid));
SELECT TOPICID, POST_BY_USERID INTO TID, postByUID FROM OPN_POSTS WHERE POST_ID = KOSourceID ;

/* Adding user action logging portion */

INSERT INTO OPN_USER_BHV_LOG(USERNAME, USERID, USER_UUID, LOGIN_DTM, API_CALL, CONCAT_PARAMS)
VALUES(bringUsernameByUID(ORIG_UID), ORIG_UID, userid, NOW(), 'KOUserCommon'
, CONCAT(ORIG_UID, ' - POST KO -',postByUID, ' FOR POST_ID = ', KOSourceID));

INSERT INTO OPN_USER_BHV_LOG(USERNAME, USERID, USER_UUID, LOGIN_DTM, API_CALL, CONCAT_PARAMS)
VALUES(bringUsernameByUID(ORIG_UID), ORIG_UID, userid, NOW(), 'KOUserCommon'
, CONCAT(postByUID, ' - REVERSE PKO -',ORIG_UID, ' FOR POST_ID = ', KOSourceID));

/* end of use action tracking */

DELETE FROM OPN_USER_USER_ACTION WHERE OPN_USER_USER_ACTION.BY_USERID = ORIG_UID 
AND OPN_USER_USER_ACTION.TOPICID = TID
AND OPN_USER_USER_ACTION.ON_USERID =  postByUID ;

DELETE FROM OPN_USER_USER_ACTION WHERE OPN_USER_USER_ACTION.BY_USERID = ORIG_UID 
AND OPN_USER_USER_ACTION.TOPICID = TID
AND OPN_USER_USER_ACTION.ON_USERID =  postByUID ;

INSERT INTO OPN_USER_USER_ACTION (BY_USERID, ON_USERID, ACTION_TYPE, ACTION_DTM
, CAUSE_POST_ID, ACTION_COMMENT, TOPICID) 
VALUES (ORIG_UID, postByUID, 'KO', NOW(), KOSourceID, 'PKO', TID) ;

INSERT INTO OPN_USER_USER_ACTION (BY_USERID, ON_USERID, ACTION_TYPE, ACTION_DTM
, CAUSE_POST_ID, ACTION_COMMENT, TOPICID) 
VALUES (postByUID, ORIG_UID, 'KO', NOW(), KOSourceID,  'RPKO', TID) ;

END CASE ;

END //
DELIMITER ;

-- 
