-- logAPICalls

 DELIMITER //
DROP PROCEDURE IF EXISTS logAPICalls //
CREATE PROCEDURE logAPICalls(
    IN P_TIMESTAMP DATETIME,
    IN P_CLIENT_IP VARCHAR(45),
    IN P_API_NAME VARCHAR(100),
    IN P_HEADERS TEXT,
    IN P_RAW_INPUT TEXT,
    IN P_DECODED_JSON TEXT
)
BEGIN 
    INSERT INTO OPN_API_DEBUG_LOGS (TIMESTAMP, CLIENT_IP, API_NAME, HEADERS, RAW_INPUT, DECODED_JSON)
    VALUES (P_TIMESTAMP, P_CLIENT_IP, P_API_NAME, P_HEADERS, P_RAW_INPUT, P_DECODED_JSON);
END //

DELIMITER ;
