-- loginGuestUserApp

 DELIMITER //
DROP PROCEDURE IF EXISTS loginGuestUserApp //
CREATE PROCEDURE loginGuestUserApp(uname varchar(30), uuid varchar(45), device_serial VARCHAR(40))
BEGIN
/*  
 08/11/2020 Kapil: Confirmed
 */
CASE WHEN uuid = (SELECT U.USER_UUID FROM OPN_USERLIST U WHERE U.USERNAME = uname AND U.USER_TYPE = 'GUEST') THEN

INSERT INTO OPN_PROC_LOG(PROC_NAME, PROC_DTM, CONCAT_FIELDS, CONCAT_VALUES)
VALUES('loginGuestUserApp', NOW(), 'USERNAME', uname) ;

INSERT INTO OPN_USER_DEVICE_LOG(USERID, USER_UUID, LOGIN_DTM, DEVICE_ID, OK_FLAG)
VALUES(bringUserid(UUID), UUID, NOW(), device_serial, 'Y');

SELECT -- U.USERID, 
U.USER_UUID USERID, U.COUNTRY_CODE, U.USER_TYPE  , doesCartExist(uname) CARTORNOT
 from OPN_USERLIST U
 WHERE U.USERNAME = uname -- and AES_DECRYPT(U.password,'290317') = password
 ;

 WHEN uuid <> IFNULL((SELECT U.USER_UUID FROM OPN_USERLIST U WHERE U.USERNAME = uname AND U.USER_TYPE = 'GUEST'),'NONE') THEN

SELECT 'USERNAME DOES NOT MATCH' FROM DUAL ;
 
 END CASE ;
 

END //
DELIMITER ;

-- 