-- loginWithGoogleUserApp

DELIMITER //
DROP PROCEDURE IF EXISTS loginWithGoogleUserApp //
CREATE PROCEDURE loginWithGoogleUserApp(Google_userid VARCHAR(45), device_serial VARCHAR(45))
BEGIN

/* 02/17/2020 AST: INITIAL CREATION  
08/11/2020 Kapil: Confirmed
02/07/2024 AST:  Changed the login to use the EMAIL_ADDR instead of the G_USERID
*/

INSERT INTO OPN_PROC_LOG(PROC_NAME, PROC_DTM, CONCAT_FIELDS, CONCAT_VALUES)
VALUES('loginWithGoogleUserApp', NOW(), 'G_USERID', Google_userid) ;

SELECT OU.USER_UUID USERID, OU.USERNAME, OU.COUNTRY_CODE 
FROM OPN_USERLIST OU WHERE OU.EMAIL_ADDR = Google_userid 
/* 04/06/2021 INSERTING THE SUSPENDED USER EXCLUSION BELOW */
AND  OU.USER_SUSPEND_FLAG = 'N'
/* 04/06/2021 END OF THE SUSPENDED USER EXCLUSION */
LIMIT 5;
  
END //
DELIMITER ;

-- 