-- loginWithFBUser

DELIMITER //
DROP PROCEDURE IF EXISTS loginWithFBUserApp //
CREATE PROCEDURE loginWithFBUserApp(fbuserid VARCHAR(25), device_serial VARCHAR(45))
BEGIN

/* 04012018 AST: Added insret into proc log 
08/11/2020 Kapil: Confirmed
*/

DECLARE UUID VARCHAR(45);
DECLARE UNAME VARCHAR(30);
DECLARE CCODE VARCHAR(5);


/* INSERT INTO OPN_PROC_LOG(PROC_NAME, PROC_DTM, CONCAT_FIELDS, CONCAT_VALUES)
VALUES('loginWithFBUser', NOW(), 'FB_USERID', fbuserid) ;

INSERT INTO OPN_USER_DEVICE_LOG(USERID, USER_UUID, LOGIN_DTM, DEVICE_ID, OK_FLAG)
VALUES(bringUserid(UUID), UUID, NOW(), device_serial, 'Y');

*/

SELECT USER_UUID USERID, USERNAME, COUNTRY_CODE FROM OPN_USERLIST WHERE FB_USERID = fbuserid 
/* 04/06/2021 INSERTING THE SUSPENDED USER EXCLUSION BELOW */
AND  USER_SUSPEND_FLAG = 'N'
/* 04/06/2021 END OF THE SUSPENDED USER EXCLUSION */
LIMIT 5;
  
END //
DELIMITER ;

-- 