-- ludtmUpdate

 DELIMITER //
DROP PROCEDURE IF EXISTS ludtmUpdate //
CREATE PROCEDURE ludtmUpdate(userid varchar(45), topicid INT)
BEGIN

/* 070517 AST
 THIS PROC IS FOR UPDATING THE LUDTM OF THE CART ROWS THAT HAVE NOT BEEN CHANGED
 THIS IS USED IN MAKING THE LUDTM AS THE BASIS FOR CLUSTERING (RATHER THAN THE ARBITRARY IRANK COLUMN THAT IS USED CURRENTLY)
 08/11/2020 Kapil: Confirmed
*/

declare  orig_uid INT;

SET orig_uid := (SELECT  bringUserid(userid));

UPDATE OPN_CART_ARCHIVE ARCH, OPN_USER_CARTS CURR
SET CURR.LAST_UPDATE_DTM = ARCH.CREATION_DTM
WHERE ARCH.KEYID = CURR.KEYID AND ARCH.CART = CURR.CART
AND ARCH.USERID = CURR.USERID
AND ARCH.USERID = orig_uid and ARCH.TOPICID = topicid ;


END //
DELIMITER ;

-- 