-- myActivity

DELIMITER //
DROP PROCEDURE IF EXISTS myActivity //
CREATE PROCEDURE myActivity(UUID varchar(45) )
BEGIN

/*  
 08/11/2020 Kapil: Confirmed
 08/20/2020 AST: Added OPN_USERLIST.CHAT_FLAG to turn the chat icon on/off

 */

declare  UID INT;
DECLARE CHF VARCHAR(3) ;
DECLARE UNAME VARCHAR(40) ;

SELECT UL.USERID, UL.USERNAME, UL.CHAT_FLAG INTO UID, UNAME, CHF FROM OPN_USERLIST UL WHERE UL.USER_UUID = UUID ;

 CALL networkUpdate(UUID) ;
 
 INSERT INTO OPN_USER_BHV_LOG(USERNAME, USERID, USER_UUID, LOGIN_DTM, API_CALL, CONCAT_PARAMS)
 VALUES(UNAME, UID, UUID, NOW(), 'myActivity', UID);

/* 

06/04/2020 AST: Initial Creation - profilephp with bookmark_count addition

*/


SELECT PP.TOPICID, PP.TOPIC, PP.PC_DELTA, PP.NETSIZE
, IFNULL(P.PCOUNT,0) POST_COUNT , IFNULL(CCNT.CCOUNT,0) COMMENT_COUNT
, CHF,  IFNULL(BK2.BKC, 0) BKMK_COUNT
FROM 
(SELECT NWS.TOPICID, T.TOPIC, (CASE WHEN (NWS.NWP_COUNT_T2 - NWS.NWP_COUNT_T1) <= 0 THEN 0 
WHEN (NWS.NWP_COUNT_T2 - NWS.NWP_COUNT_T1) BETWEEN 1 AND 999 THEN (NWS.NWP_COUNT_T2 - NWS.NWP_COUNT_T1) 
WHEN (NWS.NWP_COUNT_T2 - NWS.NWP_COUNT_T1) > 999 THEN 999
END ) PC_DELTA, NW_COUNT_T2 NETSIZE FROM 
OPN_NW_STATS NWS, OPN_TOPICS T
WHERE NWS.TOPICID = T.TOPICID AND NWS.NW_COUNT_T2 <> 0 AND NWS.USERID = UID) PP
LEFT OUTER JOIN ( SELECT OP.TOPICID, COUNT(1) PCOUNT FROM OPN_POSTS OP 
WHERE OP.POST_BY_USERID = UID GROUP BY OP.TOPICID) P
ON PP.TOPICID = P.TOPICID 
LEFT OUTER JOIN (SELECT OPC.TOPICID, COUNT(1) CCOUNT FROM OPN_POST_COMMENTS OPC 
WHERE OPC.COMMENT_BY_USERID = UID GROUP BY OPC.TOPICID) CCNT
ON PP.TOPICID = CCNT.TOPICID 
/* 04/19/2021 AST: The portion below was added to bring the bookmarks count.
	It also checks whether the POST_BYUID of the bookmarked post is in network
    with the logged in user
 */
LEFT OUTER JOIN (SELECT BK.TOPICID, COUNT(BK.POST_ID) BKC FROM OPN_POST_BOOKMARKS BK 
WHERE 1=1 AND BK.USERID = UID 
GROUP BY BK.TOPICID) BK2
ON PP.TOPICID = BK2.TOPICID
;

END //
DELIMITER ;

-- 