-- NEW_USER_CART_DELETE

DELIMITER $$
DROP TRIGGER IF EXISTS NEW_USER_CART_DELETE $$
CREATE DEFINER=`root`@`%` TRIGGER NEW_USER_CART_DELETE 
AFTER DELETE ON OPN_USER_CARTS for each row
begin

/* 06/14/2020 AST : removed the final Cluster Line from below */
-- DELETE FROM OPN_NEW_USER_CARTS WHERE OPN_NEW_USER_CARTS.OUC_ROW_ID = OLD.ROW_ID;

-- DELETE FROM OPN_NC_CLUSTERS WHERE OPN_NC_CLUSTERS.USERID = OLD.USERID AND OPN_NC_CLUSTERS.TOPICID = OLD.TOPICID;

-- DELETE FROM OPN_USER_CLUSTERS WHERE OPN_USER_CLUSTERS.USERID = OLD.USERID AND OPN_USER_CLUSTERS.TOPICID = OLD.TOPICID;

INSERT INTO OPN_CART_ARCHIVE(OLD_CART_ID, USERID, TOPICID, CART, KEYID, CREATION_DTM, DELETE_DTM)
VALUES(OLD.ROW_ID, OLD.USERID, OLD.TOPICID, OLD.CART, OLD.KEYID, OLD.CREATION_DTM, NOW());

END$$

DELIMITER ; 

-- 