-- NEW_POST_CLEAN_FLAG

DELIMITER $$
DROP TRIGGER IF EXISTS NEW_POST_CLEAN_FLAG $$
CREATE TRIGGER NEW_POST_CLEAN_FLAG 
AFTER INSERT ON OPN_POSTS_RAW for each row
begin

/*
-- THE LOGIC IS AS FOLLOWS: IF THERE IS NO EMBEDDED CONTENT (URL) IN THE 
POST THEN WE AUTOMATICALLY DEEM THE POST TO BE CLEAN

-- IF THE EMBEDDED CONTENT IS THERE (THAT MEANS THE POST CONTAINS SOME URL LINK/S) 
THEN WE AUTOMATICALLY DEEM THE POST TO BE NON-CLEAN
-- AND THEN WE CALL THE CLEAN_POST_FLG PROC TO DECIDE IF THE EMBEDDED CONETNT IS CLEAN OR NOT.

-- HENCE THE ELSE INSERT HAS CLEAN_POST_FLAG = 'N' AND POST_PROOCESSED_FLAG = 'N'
-- CLEAN_POST_FLAG WILL BE TURNED INTO 'Y' OR REMAIN 'N' BASED ON THE DECISION 
FROM THE CLEAN_POST_FLG PROC
-- IN EITHER CASE, THEN CLEAN_POST_FLG PROC WILL TURN THE POST_PROCESSED_FLAG = 'Y' 
AFTER IT IS DONE PROCESSING THIS POST

-- CHANGE LOG
-- AT 04062017 ADDED POST_UPDATE_DTM (= POST_DATETIME) TO INSERT STATEMENTS
-- AT 01312018 ADDED TAG1_KEYID TO INSERT STATEMENT

04/17/2019 AST: Added STP_PROC_NAME column to the INSERT
04/09/2020 AST: Added MEDIA_CONTENT, MEDIA_FLAG

05/10/2020 AST:  Added DEMO_POST_FLAG
06/15/2020 AST: Trying to remove the UPDATE for country code

10/20/2023 AST: Adding the new columns (NEW.SCRAPE_SOURCE, NEW.SCRAPE_TYPE) in the POST tables in the update/insert statement
 
 */
 

 IF NEW.EMBEDDED_FLAG = 'N' THEN 
INSERT INTO OPN_POSTS(POST_ID, TOPICID, POST_DATETIME, POST_UPDATE_DTM, POSTOR_COUNTRY_CODE
, POST_BY_USERID, POST_CONTENT, DEMO_POST_FLAG, EMBEDDED_CONTENT, EMBEDDED_FLAG
, CLEAN_POST_FLAG, POST_PROCESSED_FLAG, POST_PROCESSED_DTM, SCRAPE_ROW_ID, URL_TITLE
, TAG1_KEYID, STP_PROC_NAME, MEDIA_CONTENT, MEDIA_FLAG, SCRAPE_SOURCE, SCRAPE_TYPE)
VALUES(NEW.POST_ID, NEW.TOPICID, NEW.POST_DATETIME, NEW.POST_DATETIME, NEW.POSTOR_COUNTRY_CODE
, NEW.POST_BY_USERID, NEW.POST_CONTENT, NEW.DEMO_POST_FLAG, NULL, 'N'
, 'Y', 'Y', NOW(), NEW.SCRAPE_ROW_ID, NEW.URL_TITLE
, NEW.TAG1_KEYID, NEW.STP_PROC_NAME, NEW.MEDIA_CONTENT, NEW.MEDIA_FLAG, NEW.SCRAPE_SOURCE, NEW.SCRAPE_TYPE);
-- 032717 ADDING POSTOR_COUNTRY_CODE UPDATE STMNT
/*UPDATE OPN_POSTS OP SET OP.POSTOR_COUNTRY_CODE = 
(SELECT COUNTRY_CODE FROM OPN_USERLIST WHERE USERID = NEW.POST_BY_USERID) 
WHERE OP.POST_ID = NEW.POST_ID; */

ELSE 
INSERT INTO OPN_POSTS(POST_ID, TOPICID, POST_DATETIME, POST_UPDATE_DTM, POSTOR_COUNTRY_CODE
, POST_BY_USERID, POST_CONTENT, DEMO_POST_FLAG, EMBEDDED_CONTENT, EMBEDDED_FLAG
, CLEAN_POST_FLAG, POST_PROCESSED_FLAG, POST_PROCESSED_DTM, SCRAPE_ROW_ID, URL_TITLE
, TAG1_KEYID, STP_PROC_NAME, MEDIA_CONTENT, MEDIA_FLAG, SCRAPE_SOURCE, SCRAPE_TYPE)
VALUES(NEW.POST_ID, NEW.TOPICID, NEW.POST_DATETIME, NEW.POST_DATETIME, NEW.POSTOR_COUNTRY_CODE
, NEW.POST_BY_USERID, NEW.POST_CONTENT, NEW.DEMO_POST_FLAG, NEW.EMBEDDED_CONTENT, 'Y'
, 'N', 'N', NOW(), NEW.SCRAPE_ROW_ID, NEW.URL_TITLE
, NEW.TAG1_KEYID, NEW.STP_PROC_NAME, NEW.MEDIA_CONTENT, NEW.MEDIA_FLAG, NEW.SCRAPE_SOURCE, NEW.SCRAPE_TYPE);
-- 032717 ADDING POSTOR_COUNTRY_CODE UPDATE STMNT
/*UPDATE OPN_POSTS OP SET OP.POSTOR_COUNTRY_CODE = 
(SELECT COUNTRY_CODE FROM OPN_USERLIST WHERE USERID = NEW.POST_BY_USERID) 
WHERE OP.POST_ID = NEW.POST_ID; */

CALL CLEAN_POST_FLG(NEW.POST_ID);
END IF;


END$$

DELIMITER ;

-- 