-- 
 
 
DELIMITER //
DROP PROCEDURE IF EXISTS OPN_UKW_TAGGING //
CREATE PROCEDURE OPN_UKW_TAGGING(TID INT)
BEGIN

/* 07/12/2018 AST: 

11/20/2018 AST: added AND SCRAPE_DESIGN_DONE = 'Y' to the cursor

*/

DECLARE WSRID, VA1 INT;
DECLARE NURL VARCHAR(500) ;
DECLARE L1,L2,L3,L4,L5,L6,NL1,NL2, NL3, STAG2, SCR_TOPIC VARCHAR(60) ;
  DECLARE DONE INT DEFAULT FALSE;
  DECLARE CURSOR_I CURSOR FOR  SELECT IFNULL(LIKE1, 'JQXXWZ'), IFNULL(LIKE2, 'JQXXWZ'), IFNULL(LIKE3, 'JQXXWZ')
  , IFNULL(LIKE4, 'JQXXWZ'), IFNULL(LIKE5, 'JQXXWZ'), IFNULL(LIKE6, 'JQXXWZ')
  , IFNULL(NOT_LIKE1, 'JQXXWZ'), IFNULL(NOT_LIKE2, 'JQXXWZ'), IFNULL(NOT_LIKE3, 'JQXXWZ'), SCRAPE_TAG2 FROM OPN_KW_TAGS 
  WHERE TOPICID = TID  AND SCRAPE_DESIGN_DONE = 'Y' ORDER BY KW_DTM DESC;

   DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
  OPEN CURSOR_I;
   READ_LOOP: LOOP
    FETCH CURSOR_I INTO L1,L2,L3,L4,L5,L6, NL1,NL2, NL3, STAG2;
     IF DONE THEN
      LEAVE READ_LOOP;
      END IF;
      
-- SET NURL = (SELECT UPPER(NEWS_URL) FROM WEB_SCRAPE_RAW WHERE ROW_ID = 687) ;
-- SET @VA1 := FLOOR(RAND()*(2-1+1))+1 ;

/* 
 03/12/2019 Adding condition for handling the SCRAPE_TOPIC. This is because some keywords get covered in news of multiple topics
 For ex. Jussie Smollett is covered in POLITICS, CELEB & ENT. The purpose of this change is to ensure that we only tag those news items that pertain to 
 the TID that is being called. Since Jussie Smollett is added as a KW in Celeb (TID=10) we should only push the CELEB news to the CELEB interest (INTEREST = TOPIC)
 
 03/14/2019 TID 9 (TRENDING) is a special case. It can have news from many diff topics - mainly POLITICS, SPORTS, CELEB, ENT, BUSINESS. 
 So we will ad a case statement to handle this.
 
 03/15/2019: Also handled CELEB and ENT (TID 5,10)
 
 04/23/2019 AST: removing the OCCODE from the entire Proc. This is because many KWs are covered in all three country codes 
 (E.g. maduro is covered extensively in USA, IND, GGG. When we impose the OCCODE on OPN_UKW_TAGGING, we miss out on the coverage
 in other countries.
 
 The STP_STAG23_MICRO proc simply goes by STAG2. Thus it doesn't care for OCCODE or CCODE anyway
 
 */
 
 CASE WHEN TID = 1 THEN SET SCR_TOPIC = 'POLITICS';
 WHEN TID = 2 THEN SET SCR_TOPIC = 'SPORTS' ;
 WHEN TID = 3 THEN SET SCR_TOPIC = 'SCIENCE' ;
 WHEN TID = 4 THEN SET SCR_TOPIC = 'BUSINESS' ;
 WHEN TID = 5 THEN SET SCR_TOPIC = 'ENT' ;
 WHEN TID = 6 THEN SET SCR_TOPIC = 'RELIGION' ;
 WHEN TID = 7 THEN SET SCR_TOPIC = 'LIFE' ;
 WHEN TID = 8 THEN SET SCR_TOPIC = 'MISC' ;
 WHEN TID = 9 THEN SET SCR_TOPIC = 'TREND' ;
 WHEN TID = 10 THEN SET SCR_TOPIC = 'CELEB' ;
 END CASE ;
 
 CASE WHEN TID = 9 THEN 
 
UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = STAG2, SCRAPE_TAG3 = (CASE WHEN  MOD(ROW_ID, 2) = 0 THEN 'L' 
WHEN   MOD(ROW_ID, 2) = 1 THEN 'H' END ), TAG_DONE_FLAG = 'Y'
WHERE 1=1 AND TAG_DONE_FLAG = 'N'  AND  MOVED_TO_POST_FLAG = 'N'
AND SCRAPE_TOPIC IN ('POLITICS', 'SPORTS', 'CELEB', 'ENT', 'BUSINESS') AND
(
UPPER(NEWS_URL) LIKE L1 OR UPPER(NEWS_URL) LIKE L2 OR UPPER(NEWS_URL) LIKE L3 
OR UPPER(NEWS_URL) LIKE L4 OR UPPER(NEWS_URL) LIKE L5 OR UPPER(NEWS_URL) LIKE L6 
)
AND 
(
UPPER(NEWS_URL) NOT LIKE NL1 AND UPPER(NEWS_URL) NOT LIKE NL2 AND UPPER(NEWS_URL) NOT LIKE NL3   
) ;

WHEN TID IN (5,10) THEN

 
UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = STAG2, SCRAPE_TAG3 = (CASE WHEN  MOD(ROW_ID, 2) = 0 THEN 'L' 
WHEN   MOD(ROW_ID, 2) = 1 THEN 'H' END ), TAG_DONE_FLAG = 'Y'
WHERE 1=1 AND TAG_DONE_FLAG = 'N'  AND  MOVED_TO_POST_FLAG = 'N'
AND SCRAPE_TOPIC IN ('CELEB', 'ENT') AND
(
UPPER(NEWS_URL) LIKE L1 OR UPPER(NEWS_URL) LIKE L2 OR UPPER(NEWS_URL) LIKE L3 
OR UPPER(NEWS_URL) LIKE L4 OR UPPER(NEWS_URL) LIKE L5 OR UPPER(NEWS_URL) LIKE L6 
)
AND 
(
UPPER(NEWS_URL) NOT LIKE NL1 AND UPPER(NEWS_URL) NOT LIKE NL2 AND UPPER(NEWS_URL) NOT LIKE NL3   
) ;

WHEN TID NOT IN (9,5,10) THEN

 
UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = STAG2, SCRAPE_TAG3 = (CASE WHEN  MOD(ROW_ID, 2) = 0 THEN 'L' 
WHEN   MOD(ROW_ID, 2) = 1 THEN 'H' END ), TAG_DONE_FLAG = 'Y'
WHERE 1=1 AND TAG_DONE_FLAG = 'N'  AND  MOVED_TO_POST_FLAG = 'N'
AND SCRAPE_TOPIC =  SCR_TOPIC AND
(
UPPER(NEWS_URL) LIKE L1 OR UPPER(NEWS_URL) LIKE L2 OR UPPER(NEWS_URL) LIKE L3 
OR UPPER(NEWS_URL) LIKE L4 OR UPPER(NEWS_URL) LIKE L5 OR UPPER(NEWS_URL) LIKE L6 
)
AND 
(
UPPER(NEWS_URL) NOT LIKE NL1 AND UPPER(NEWS_URL) NOT LIKE NL2 AND UPPER(NEWS_URL) NOT LIKE NL3   
) ;


END CASE ;

CALL STP_STAG23_MICRO(STAG2, 'H') ;
CALL STP_STAG23_MICRO(STAG2, 'L') ;

INSERT INTO WSR_CONVERTED(SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE)
SELECT SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE FROM WEB_SCRAPE_RAW
WHERE  MOVED_TO_POST_FLAG = 'Y' ;

DELETE FROM WEB_SCRAPE_RAW WHERE  MOVED_TO_POST_FLAG = 'Y' ;

        END LOOP;
  CLOSE CURSOR_I;
END; //
 DELIMITER ;
 
 -- 