-- 
 
 
DELIMITER //
DROP PROCEDURE IF EXISTS OPN_UKW_TAGGINGKW //
CREATE PROCEDURE OPN_UKW_TAGGINGKW(TID INT, KID INT)
BEGIN


DECLARE WSRID, VA1 INT;
DECLARE NURL VARCHAR(500) ;
DECLARE L1,L2,L3,L4,L5,L6,NL1,NL2, NL3, STAG2, SCR_TOPIC VARCHAR(60) ;
  DECLARE DONE INT DEFAULT FALSE;
  DECLARE CURSOR_I CURSOR FOR  SELECT IFNULL(LIKE1, 'JQXXWZ'), IFNULL(LIKE2, 'JQXXWZ'), IFNULL(LIKE3, 'JQXXWZ')
  , IFNULL(LIKE4, 'JQXXWZ'), IFNULL(LIKE5, 'JQXXWZ'), IFNULL(LIKE6, 'JQXXWZ')
  , IFNULL(NOT_LIKE1, 'JQXXWZ'), IFNULL(NOT_LIKE2, 'JQXXWZ'), IFNULL(NOT_LIKE3, 'JQXXWZ'), SCRAPE_TAG2 FROM OPN_KW_TAGS 
  WHERE KEYID = KID  AND SCRAPE_DESIGN_DONE = 'Y' ;

   DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
  OPEN CURSOR_I;
   READ_LOOP: LOOP
    FETCH CURSOR_I INTO L1,L2,L3,L4,L5,L6, NL1,NL2, NL3, STAG2;
     IF DONE THEN
      LEAVE READ_LOOP;
      END IF;

/* 

05/14/2019 AST: This proc is the KID version of the OPN_UKW_TAGGING. THis is built only to be used
with the createOPNTSearchKW2W call.

Trying to find the UNTAGGED posts and sweep them into WSR prior to Tagging and STP.

05/15/2019 AST: Adding the DELETE for scrapes that were swept from WSRU to WSR. 

07/24/2019 AST: Adding NEWS_HEADLINE and NEWS_EXCERPT  for possible matches with the new KW. Also adding post-dedupe

09/13/2019 AST: Adding 'SPORT' and 'SPORTS' to topic list in tid not in (1,5,9,10) case. this was forgotten earlier and hence the new Sports 
KWs were getting no posts created through OPN_UKW_TAGGINGKW
 
 */
 
 CASE WHEN TID = 1 THEN SET SCR_TOPIC = 'POLITICS';
 WHEN TID = 2 THEN SET SCR_TOPIC = 'SPORTS' ;
 WHEN TID = 3 THEN SET SCR_TOPIC = 'SCIENCE' ;
 WHEN TID = 4 THEN SET SCR_TOPIC = 'BUSINESS' ;
 WHEN TID = 5 THEN SET SCR_TOPIC = 'ENT' ;
 WHEN TID = 6 THEN SET SCR_TOPIC = 'RELIGION' ;
 WHEN TID = 7 THEN SET SCR_TOPIC = 'LIFE' ;
 WHEN TID = 8 THEN SET SCR_TOPIC = 'MISC' ;
 WHEN TID = 9 THEN SET SCR_TOPIC = 'TREND' ;
 WHEN TID = 10 THEN SET SCR_TOPIC = 'CELEB' ;
 END CASE ;
 
 CASE WHEN TID IN (1,9) THEN 
 
 INSERT INTO WEB_SCRAPE_RAW (SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_PIC_URL, NEWS_DATE
, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, SCRAPE_TAG1, SCRAPE_TAG2, SCRAPE_TAG3)
SELECT DISTINCT CURRENT_DATE(), SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_PIC_URL, NEWS_DATE, NEWS_HEADLINE
, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, SCRAPE_TAG1, SCRAPE_TAG2, SCRAPE_TAG3
FROM WSR_UNTAGGED WHERE SCRAPE_TOPIC IN ('POLITICS', 'SPORTS', 'CELEB', 'ENT', 'BUSINESS') 
AND SCRAPE_DATE > NOW()- INTERVAL 1 MONTH
AND ( (NEWS_URL LIKE L1 OR NEWS_URL LIKE L2 OR NEWS_URL LIKE L3 OR NEWS_URL LIKE L4 OR NEWS_URL LIKE L5 OR NEWS_URL LIKE L6)
OR (NEWS_HEADLINE LIKE L1 OR NEWS_HEADLINE LIKE L2 OR NEWS_HEADLINE LIKE L3 OR NEWS_HEADLINE LIKE L4 OR NEWS_HEADLINE LIKE L5 OR NEWS_HEADLINE LIKE L6)
OR (NEWS_EXCERPT LIKE L1 OR NEWS_EXCERPT LIKE L2 OR NEWS_EXCERPT LIKE L3 OR NEWS_EXCERPT LIKE L4 OR NEWS_EXCERPT LIKE L5 OR NEWS_EXCERPT LIKE L6) );

/* 05/15/2019 AST: Adding the DELETE */

DELETE FROM WSR_UNTAGGED WHERE SCRAPE_TOPIC IN ('POLITICS', 'SPORTS', 'CELEB', 'ENT', 'BUSINESS') 
AND SCRAPE_DATE > NOW()- INTERVAL 1 MONTH
AND ( (NEWS_URL LIKE L1 OR NEWS_URL LIKE L2 OR NEWS_URL LIKE L3 OR NEWS_URL LIKE L4 OR NEWS_URL LIKE L5 OR NEWS_URL LIKE L6)
OR (NEWS_HEADLINE LIKE L1 OR NEWS_HEADLINE LIKE L2 OR NEWS_HEADLINE LIKE L3 OR NEWS_HEADLINE LIKE L4 OR NEWS_HEADLINE LIKE L5 OR NEWS_HEADLINE LIKE L6)
OR (NEWS_EXCERPT LIKE L1 OR NEWS_EXCERPT LIKE L2 OR NEWS_EXCERPT LIKE L3 OR NEWS_EXCERPT LIKE L4 OR NEWS_EXCERPT LIKE L5 OR NEWS_EXCERPT LIKE L6) );

 
UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = STAG2, SCRAPE_TAG3 = (CASE WHEN  MOD(ROW_ID, 2) = 0 THEN 'L' 
WHEN   MOD(ROW_ID, 2) = 1 THEN 'H' END ), TAG_DONE_FLAG = 'Y'
WHERE 1=1 AND TAG_DONE_FLAG = 'N'  AND  MOVED_TO_POST_FLAG = 'N'
AND SCRAPE_TOPIC IN ('POLITICS', 'SPORTS', 'CELEB', 'ENT', 'BUSINESS') AND
(
UPPER(NEWS_URL) LIKE L1 OR UPPER(NEWS_URL) LIKE L2 OR UPPER(NEWS_URL) LIKE L3 
OR UPPER(NEWS_URL) LIKE L4 OR UPPER(NEWS_URL) LIKE L5 OR UPPER(NEWS_URL) LIKE L6 
OR UPPER(NEWS_HEADLINE) LIKE L1 OR UPPER(NEWS_HEADLINE) LIKE L2 OR UPPER(NEWS_HEADLINE) LIKE L3 
OR UPPER(NEWS_HEADLINE) LIKE L4 OR UPPER(NEWS_HEADLINE) LIKE L5 OR UPPER(NEWS_HEADLINE) LIKE L6 
OR UPPER(NEWS_EXCERPT) LIKE L1 OR UPPER(NEWS_EXCERPT) LIKE L2 OR UPPER(NEWS_EXCERPT) LIKE L3 
OR UPPER(NEWS_EXCERPT) LIKE L4 OR UPPER(NEWS_EXCERPT) LIKE L5 OR UPPER(NEWS_EXCERPT) LIKE L6 
)
AND 
(
UPPER(NEWS_URL) NOT LIKE NL1 AND UPPER(NEWS_URL) NOT LIKE NL2 AND UPPER(NEWS_URL) NOT LIKE NL3   
) ;

WHEN TID IN (5,10) THEN

 INSERT INTO WEB_SCRAPE_RAW (SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_PIC_URL, NEWS_DATE
, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, SCRAPE_TAG1, SCRAPE_TAG2, SCRAPE_TAG3)
SELECT DISTINCT CURRENT_DATE(), SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_PIC_URL, NEWS_DATE, NEWS_HEADLINE
, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, SCRAPE_TAG1, SCRAPE_TAG2, SCRAPE_TAG3
FROM WSR_UNTAGGED WHERE SCRAPE_TOPIC IN ( 'CELEB', 'ENT') AND SCRAPE_DATE > NOW()- INTERVAL 1 MONTH
AND ( (NEWS_URL LIKE L1 OR NEWS_URL LIKE L2 OR NEWS_URL LIKE L3 OR NEWS_URL LIKE L4 OR NEWS_URL LIKE L5 OR NEWS_URL LIKE L6)
OR (NEWS_HEADLINE LIKE L1 OR NEWS_HEADLINE LIKE L2 OR NEWS_HEADLINE LIKE L3 OR NEWS_HEADLINE LIKE L4 OR NEWS_HEADLINE LIKE L5 OR NEWS_HEADLINE LIKE L6)
OR (NEWS_EXCERPT LIKE L1 OR NEWS_EXCERPT LIKE L2 OR NEWS_EXCERPT LIKE L3 OR NEWS_EXCERPT LIKE L4 OR NEWS_EXCERPT LIKE L5 OR NEWS_EXCERPT LIKE L6) );

/* 05/15/2019 AST: Adding the DELETE */ 

DELETE FROM WSR_UNTAGGED WHERE SCRAPE_TOPIC IN ( 'CELEB', 'ENT') AND SCRAPE_DATE > NOW()- INTERVAL 1 MONTH
AND ( (NEWS_URL LIKE L1 OR NEWS_URL LIKE L2 OR NEWS_URL LIKE L3 OR NEWS_URL LIKE L4 OR NEWS_URL LIKE L5 OR NEWS_URL LIKE L6)
OR (NEWS_HEADLINE LIKE L1 OR NEWS_HEADLINE LIKE L2 OR NEWS_HEADLINE LIKE L3 OR NEWS_HEADLINE LIKE L4 OR NEWS_HEADLINE LIKE L5 OR NEWS_HEADLINE LIKE L6)
OR (NEWS_EXCERPT LIKE L1 OR NEWS_EXCERPT LIKE L2 OR NEWS_EXCERPT LIKE L3 OR NEWS_EXCERPT LIKE L4 OR NEWS_EXCERPT LIKE L5 OR NEWS_EXCERPT LIKE L6) );
 
UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = STAG2, SCRAPE_TAG3 = (CASE WHEN  MOD(ROW_ID, 2) = 0 THEN 'L' 
WHEN   MOD(ROW_ID, 2) = 1 THEN 'H' END ), TAG_DONE_FLAG = 'Y'
WHERE 1=1 AND TAG_DONE_FLAG = 'N'  AND  MOVED_TO_POST_FLAG = 'N'
AND SCRAPE_TOPIC IN ('CELEB', 'ENT') AND
(
UPPER(NEWS_URL) LIKE L1 OR UPPER(NEWS_URL) LIKE L2 OR UPPER(NEWS_URL) LIKE L3 
OR UPPER(NEWS_URL) LIKE L4 OR UPPER(NEWS_URL) LIKE L5 OR UPPER(NEWS_URL) LIKE L6 
OR UPPER(NEWS_HEADLINE) LIKE L1 OR UPPER(NEWS_HEADLINE) LIKE L2 OR UPPER(NEWS_HEADLINE) LIKE L3 
OR UPPER(NEWS_HEADLINE) LIKE L4 OR UPPER(NEWS_HEADLINE) LIKE L5 OR UPPER(NEWS_HEADLINE) LIKE L6 
OR UPPER(NEWS_EXCERPT) LIKE L1 OR UPPER(NEWS_EXCERPT) LIKE L2 OR UPPER(NEWS_EXCERPT) LIKE L3 
OR UPPER(NEWS_EXCERPT) LIKE L4 OR UPPER(NEWS_EXCERPT) LIKE L5 OR UPPER(NEWS_EXCERPT) LIKE L6 
)
AND 
(
UPPER(NEWS_URL) NOT LIKE NL1 AND UPPER(NEWS_URL) NOT LIKE NL2 AND UPPER(NEWS_URL) NOT LIKE NL3   
) ;

WHEN TID NOT IN (1,9,5,10) THEN

 INSERT INTO WEB_SCRAPE_RAW (SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_PIC_URL, NEWS_DATE
, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, SCRAPE_TAG1, SCRAPE_TAG2, SCRAPE_TAG3)
SELECT DISTINCT CURRENT_DATE(), SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_PIC_URL, NEWS_DATE, NEWS_HEADLINE
, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, SCRAPE_TAG1, SCRAPE_TAG2, SCRAPE_TAG3
FROM WSR_UNTAGGED WHERE SCRAPE_TOPIC IN ('SCIENCE', 'LIFE', 'MISC', 'RELIGION', 'BUSINESS', 'SPORTS', 'SPORT') 
AND SCRAPE_DATE > NOW()- INTERVAL 1 MONTH
AND ( (NEWS_URL LIKE L1 OR NEWS_URL LIKE L2 OR NEWS_URL LIKE L3 OR NEWS_URL LIKE L4 OR NEWS_URL LIKE L5 OR NEWS_URL LIKE L6)
OR (NEWS_HEADLINE LIKE L1 OR NEWS_HEADLINE LIKE L2 OR NEWS_HEADLINE LIKE L3 OR NEWS_HEADLINE LIKE L4 OR NEWS_HEADLINE LIKE L5 OR NEWS_HEADLINE LIKE L6)
OR (NEWS_EXCERPT LIKE L1 OR NEWS_EXCERPT LIKE L2 OR NEWS_EXCERPT LIKE L3 OR NEWS_EXCERPT LIKE L4 OR NEWS_EXCERPT LIKE L5 OR NEWS_EXCERPT LIKE L6) );

/* 05/15/2019 AST: Adding the DELETE */ 

DELETE FROM WSR_UNTAGGED WHERE SCRAPE_TOPIC IN ('SCIENCE', 'LIFE', 'MISC', 'RELIGION', 'BUSINESS', 'SPORTS', 'SPORT') 
AND SCRAPE_DATE > NOW()- INTERVAL 1 MONTH
AND ( (NEWS_URL LIKE L1 OR NEWS_URL LIKE L2 OR NEWS_URL LIKE L3 OR NEWS_URL LIKE L4 OR NEWS_URL LIKE L5 OR NEWS_URL LIKE L6)
OR (NEWS_HEADLINE LIKE L1 OR NEWS_HEADLINE LIKE L2 OR NEWS_HEADLINE LIKE L3 OR NEWS_HEADLINE LIKE L4 OR NEWS_HEADLINE LIKE L5 OR NEWS_HEADLINE LIKE L6)
OR (NEWS_EXCERPT LIKE L1 OR NEWS_EXCERPT LIKE L2 OR NEWS_EXCERPT LIKE L3 OR NEWS_EXCERPT LIKE L4 OR NEWS_EXCERPT LIKE L5 OR NEWS_EXCERPT LIKE L6) );

 
UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = STAG2, SCRAPE_TAG3 = (CASE WHEN  MOD(ROW_ID, 2) = 0 THEN 'L' 
WHEN   MOD(ROW_ID, 2) = 1 THEN 'H' END ), TAG_DONE_FLAG = 'Y'
WHERE 1=1 AND TAG_DONE_FLAG = 'N'  AND  MOVED_TO_POST_FLAG = 'N'
AND SCRAPE_TOPIC =  SCR_TOPIC AND
(
UPPER(NEWS_URL) LIKE L1 OR UPPER(NEWS_URL) LIKE L2 OR UPPER(NEWS_URL) LIKE L3 
OR UPPER(NEWS_URL) LIKE L4 OR UPPER(NEWS_URL) LIKE L5 OR UPPER(NEWS_URL) LIKE L6 
OR UPPER(NEWS_HEADLINE) LIKE L1 OR UPPER(NEWS_HEADLINE) LIKE L2 OR UPPER(NEWS_HEADLINE) LIKE L3 
OR UPPER(NEWS_HEADLINE) LIKE L4 OR UPPER(NEWS_HEADLINE) LIKE L5 OR UPPER(NEWS_HEADLINE) LIKE L6 
OR UPPER(NEWS_EXCERPT) LIKE L1 OR UPPER(NEWS_EXCERPT) LIKE L2 OR UPPER(NEWS_EXCERPT) LIKE L3 
OR UPPER(NEWS_EXCERPT) LIKE L4 OR UPPER(NEWS_EXCERPT) LIKE L5 OR UPPER(NEWS_EXCERPT) LIKE L6 
)
AND 
(
UPPER(NEWS_URL) NOT LIKE NL1 AND UPPER(NEWS_URL) NOT LIKE NL2 AND UPPER(NEWS_URL) NOT LIKE NL3   
) ;


END CASE ;

CALL STP_STAG23_MICRO(STAG2, 'H') ;
CALL STP_STAG23_MICRO(STAG2, 'L') ;
CALL OPN_SUPPRESS_DUPES(1, 1 , 'DAY');

INSERT INTO WSR_CONVERTED(SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE
, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE)
SELECT SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE
, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE FROM WEB_SCRAPE_RAW
WHERE  MOVED_TO_POST_FLAG = 'Y' ;

DELETE FROM WEB_SCRAPE_RAW WHERE  MOVED_TO_POST_FLAG = 'Y' ;

        END LOOP;
  CLOSE CURSOR_I;
END; //
 DELIMITER ;
 
 -- 