 -- OPN_POST_QUALITY
 
 DELIMITER //
DROP PROCEDURE IF EXISTS OPN_POST_QUALITY //
CREATE PROCEDURE OPN_POST_QUALITY(PCON VARCHAR(1000))
thisproc:BEGIN

DECLARE POSTID, WORDCNT, SKIPSCORE, WORDCNTSCORE, CHARCOUNTSCORE, TOTALSCORE, BADWORDSCORE, VERBO INT;
DECLARE FIRST100 VARCHAR(100) ;
-- DECLARE GOODWORD, CHKWORD VARCHAR(10) ;

SET FIRST100 = SUBSTR(PCON, 1, 100) ;
SET WORDCNTSCORE = (SELECT wordCount(PCON) * 2 ) ;
SET SKIPSCORE = (SELECT postSkipScore(FIRST100) * 3 ) ;
-- SET KWTRIM = UPPER(removeAlpha(PCON)) ;
-- SET VPHWILD = CONCAT("'%", VPH, "%'") ;
SET VERBO = (SELECT IFNULL(MAX(INSTR(PCON, VERBOTEN_PHRASE) ), 0) FROM OPN_VERBOTEN )  ;

SELECT WORDCNTSCORE, SKIPSCORE, VERBO ;



  
END ; //
 DELIMITER ;
 
 -- 