-- POST_COMMENT_DELETE

-- TRIGGER TO INSERT DELETED POST COMMENTS INTO OPN_COMMENTS_DELETED

DELIMITER $$
DROP TRIGGER IF EXISTS POST_COMMENT_DELETE $$
CREATE TRIGGER POST_COMMENT_DELETE 
AFTER DELETE ON OPN_POST_COMMENTS for each row
begin

/*

	07/17/2020 AST: Adding the DELETE from OPN_POST_SEARCH_T to ensure that 
					deleted posts don't show up in search results

*/

INSERT INTO OPN_COMMENTS_DELETED(COMMENT_ID, CAUSE_POST_ID, POST_BY_USERID, TOPICID
, PARENT_COMMENT_ID, COMMENT_SEQ, COMMENT_CONTENT
, COMMENT_BY_USERID, COMMENT_DTM, EMBEDDED_CONTENT, CLEAN_COMMENT_FLAG, UPDATE_DTM ) 
VALUES (OLD.COMMENT_ID, OLD.CAUSE_POST_ID, OLD.POST_BY_USERID, OLD.TOPICID
, OLD.PARENT_COMMENT_ID, OLD.COMMENT_SEQ, OLD.COMMENT_CONTENT
, OLD.COMMENT_BY_USERID, OLD.COMMENT_DTM, OLD.EMBEDDED_CONTENT, OLD.CLEAN_COMMENT_FLAG, NOW());


END$$

DELIMITER ; 

-- 