-- profilePosts

DELIMITER //
DROP PROCEDURE IF EXISTS profilePosts //
CREATE PROCEDURE profilePosts(userid varchar(45), topicid INT, fromindex INT, toindex INT)
BEGIN

/* 	06/02/2020 AST: Rebuilding with removal of @  
	06/12/2020 AST: Added back the OU.DP_URL and P.MEDIA_CONTENT, P.MEDIA_FLAG
	
	08/11/2020 Kapil: Confirmed
*/

declare  orig_uid INT;

SET orig_uid = (SELECT  bringUserid(userid));

SELECT P.POST_ID, OU.USERNAME POST_BY_USERNAME, OU.DP_URL, P.TOPICID, P.POST_DATETIME, P.POST_CONTENT
, P.MEDIA_CONTENT, P.MEDIA_FLAG, IFNULL(POST_LHC.LCOUNT,0) LCOUNT
, IFNULL(POST_LHC.HCOUNT,0) HCOUNT, IFNULL(OPC.POST_COMMENT_COUNT, 0) POST_COMMENT_COUNT
FROM OPN_POSTS P
INNER JOIN OPN_USERLIST OU ON P.POST_BY_USERID = OU.USERID
LEFT OUTER JOIN 
(SELECT CAUSE_POST_ID, SUM(CASE WHEN POST_ACTION_TYPE = 'L' THEN 1 ELSE 0 END) LCOUNT 
, SUM(CASE WHEN POST_ACTION_TYPE = 'H' THEN 1 ELSE 0 END) HCOUNT 
FROM OPN_USER_POST_ACTION GROUP BY CAUSE_POST_ID) POST_LHC
ON P.POST_ID = POST_LHC.CAUSE_POST_ID
LEFT OUTER JOIN (SELECT CAUSE_POST_ID, COUNT(*) POST_COMMENT_COUNT FROM OPN_POST_COMMENTS 
WHERE CLEAN_COMMENT_FLAG = 'Y' GROUP BY CAUSE_POST_ID) OPC 
ON P.POST_ID = OPC.CAUSE_POST_ID
WHERE P.TOPICID = topicid AND P.POST_BY_USERID =  orig_uid
ORDER BY P.POST_DATETIME DESC LIMIT fromindex, toindex;

END //
DELIMITER ;

-- 
