-- 

 DELIMITER //
DROP PROCEDURE IF EXISTS saveLastPlatform //
CREATE PROCEDURE saveLastPlatform(UID varchar(45), LASTPLTFRM varchar(100))
BEGIN
/*
 08/11/2020 Kapil: Confirmed
 */
UPDATE OPN_USERLIST SET LAST_USED_PLATFORM = LASTPLTFRM, LAST_PLATFORM_DTM = NOW()
WHERE USER_UUID = UID;

  
END //
DELIMITER ;

-- 