-- showTCCContent

 DELIMITER //
DROP PROCEDURE IF EXISTS showTCCContent //
CREATE PROCEDURE showTCCContent(uuid varchar(45) , fromIndex INT, toIndex INT
)
BEGIN

/*
02/28/2025 AST: This proc is for showing the latest/active/interesting discussions BASED ON THEIR TCC
For the specific TCCs (currently NGA, IND, USA) we are building the latest discussions using OpenAI 
This proc will bring those discussions and show them as SFC based on the INTEREST  selections.

*/

declare  uid, tid, PCNT INT ;
DECLARE ccode, tcc VARCHAR(5) ;
DECLARE UNAME VARCHAR(50) ;

SELECT USERID, COUNTRY_CODE, TRUE_COUNTRY_CODE, USERNAME INTO uid, ccode, tcc, UNAME FROM OPN_USERLIST WHERE USER_UUID = uuid ;

SET PCNT = (SELECT COUNT(1) FROM OPN_POSTS P WHERE P.CLEAN_POST_FLAG = 'Y' AND IFNULL(P.DELETED_FLAG, 'N') <> 'Y' 
AND P.POST_DATETIME > CURRENT_DATE() - INTERVAL 3 DAY  AND P.DEMO_POST_FLAG <> 'Y' 
and POSTOR_TCC = tcc
AND P.TOPICID IN (SELECT INTEREST_ID FROM OPN_USER_INTERESTS WHERE USERID = uid) 
AND P.KEYID NOT IN (SELECT KEYID FROM OPN_USER_CARTS WHERE USERID = uid)) ;

/* Adding user action logging portion */

INSERT INTO OPN_USER_BHV_LOG(USERNAME, USERID, USER_UUID, LOGIN_DTM, API_CALL, CONCAT_PARAMS)
VALUES(UNAME, uid, uuid, NOW(), 'showTCCContent', CONCAT(uid,'-',tcc, '-', PCNT));

/* end of use action tracking */

CASE WHEN PCNT >= 30 THEN


CASE 
        WHEN EXISTS (SELECT 1 
                     FROM OPN_USER_INTERESTS  I
                     WHERE I.USERID = uid 
                       AND I.INTEREST_ID = 3) 
        THEN 
        
        SELECT P.TOPICID, IFNULL(P.URL_TITLE, P.POST_CONTENT) SHOW_CONTENT, P.POST_CONTENT, P.POSTOR_COUNTRY_CODE, P.POST_ID
        , P.KEYID, COUNT(C.USERID) USERCOUNT FROM OPN_POSTS P, OPN_USER_CARTS C
WHERE P.KEYID = C.KEYID AND P.CLEAN_POST_FLAG = 'Y' AND IFNULL(P.DELETED_FLAG, 'N') <> 'Y'
AND P.POST_DATETIME > CURRENT_DATE() - INTERVAL 3 DAY  AND P.DEMO_POST_FLAG <> 'Y' 
AND P.KEYID NOT IN (SELECT KEYID FROM OPN_USER_CARTS WHERE USERID = uid)
AND P.TOPICID <> 3 AND P.TOPICID IN (SELECT INTEREST_ID FROM OPN_USER_INTERESTS WHERE USERID = uid) 
AND P.POSTOR_TCC = tcc GROUP BY P.TOPICID, IFNULL(P.URL_TITLE, P.POST_CONTENT) 
, P.POST_CONTENT, P.POSTOR_COUNTRY_CODE, P.POST_ID, P.KEYID  
UNION ALL 
SELECT P.TOPICID, IFNULL(P.URL_TITLE, P.POST_CONTENT) SHOW_CONTENT, P.POST_CONTENT, P.POSTOR_COUNTRY_CODE, P.POST_ID
, P.KEYID, COUNT(C.USERID) USERCOUNT FROM OPN_POSTS P, OPN_USER_CARTS C
WHERE P.KEYID = C.KEYID AND P.CLEAN_POST_FLAG = 'Y' AND IFNULL(P.DELETED_FLAG, 'N') <> 'Y'
AND P.POST_DATETIME > CURRENT_DATE() - INTERVAL 3 DAY  AND P.DEMO_POST_FLAG <> 'Y' 
AND P.KEYID NOT IN (SELECT KEYID FROM OPN_USER_CARTS WHERE USERID = uid)
AND P.TOPICID = 3  AND P.POSTOR_COUNTRY_CODE = 'GGG' GROUP BY P.TOPICID, IFNULL(P.URL_TITLE, P.POST_CONTENT)
, P.POST_CONTENT, P.POSTOR_COUNTRY_CODE, P.POST_ID, P.KEYID
 ORDER BY RAND() LIMIT 30 ;
 
 ELSE 
	SELECT P.TOPICID, IFNULL(P.URL_TITLE, P.POST_CONTENT) SHOW_CONTENT, P.POST_CONTENT, P.POSTOR_COUNTRY_CODE
    , P.POST_ID,P.KEYID, COUNT(C.USERID) USERCOUNT FROM OPN_POSTS P, OPN_USER_CARTS C
WHERE P.KEYID = C.KEYID AND P.CLEAN_POST_FLAG = 'Y' AND IFNULL(P.DELETED_FLAG, 'N') <> 'Y'
AND P.POST_DATETIME > CURRENT_DATE() - INTERVAL 3 DAY  AND P.DEMO_POST_FLAG <> 'Y' 
AND P.KEYID NOT IN (SELECT KEYID FROM OPN_USER_CARTS WHERE USERID = uid)
AND P.TOPICID NOT IN (3) AND P.TOPICID IN (SELECT INTEREST_ID FROM OPN_USER_INTERESTS WHERE USERID = uid) 
AND P.POSTOR_TCC = tcc GROUP BY P.TOPICID, IFNULL(P.URL_TITLE, P.POST_CONTENT) 
, P.POST_CONTENT, P.POSTOR_COUNTRY_CODE, P.POST_ID, P.KEYID
ORDER BY RAND() LIMIT 30 ;

END CASE ;

ELSE 

	CASE 
        WHEN EXISTS (SELECT 1 
                     FROM OPN_USER_INTERESTS  I
                     WHERE I.USERID = uid 
                       AND I.INTEREST_ID = 3) 
        THEN 
        SELECT P.TOPICID, IFNULL(P.URL_TITLE, P.POST_CONTENT) SHOW_CONTENT, P.POST_CONTENT, P.POSTOR_COUNTRY_CODE
        , P.POST_ID, P.KEYID, COUNT(C.USERID) FROM OPN_POSTS P, OPN_USER_CARTS C
WHERE P.KEYID = C.KEYID AND P.CLEAN_POST_FLAG = 'Y' AND IFNULL(P.DELETED_FLAG, 'N') <> 'Y'
AND P.POST_DATETIME > CURRENT_DATE() - INTERVAL 10 DAY  AND P.DEMO_POST_FLAG <> 'Y' 
AND P.TOPICID NOT IN (3) AND P.TOPICID IN (SELECT INTEREST_ID FROM OPN_USER_INTERESTS WHERE USERID = uid) 
AND P.POSTOR_TCC = tcc 
GROUP BY P.TOPICID, IFNULL(P.URL_TITLE, P.POST_CONTENT) , P.POST_CONTENT, P.POSTOR_COUNTRY_CODE, P.POST_ID, P.KEYID
UNION ALL 
SELECT P.TOPICID, IFNULL(P.URL_TITLE, P.POST_CONTENT) SHOW_CONTENT, P.POST_CONTENT, P.POSTOR_COUNTRY_CODE
, P.POST_ID, P.KEYID, COUNT(C.USERID) FROM OPN_POSTS P, OPN_USER_CARTS C
WHERE P.KEYID = C.KEYID AND P.CLEAN_POST_FLAG = 'Y' AND IFNULL(P.DELETED_FLAG, 'N') <> 'Y'
AND P.POST_DATETIME > CURRENT_DATE() - INTERVAL 10 DAY  AND P.DEMO_POST_FLAG <> 'Y' 
AND P.TOPICID IN (3)  AND P.POSTOR_COUNTRY_CODE = 'GGG' 
GROUP BY P.TOPICID, IFNULL(P.URL_TITLE, P.POST_CONTENT), P.POST_CONTENT, P.POSTOR_COUNTRY_CODE, P.POST_ID, P.KEYID
 ORDER BY RAND() LIMIT 30 ;
 
 ELSE 
	SELECT P.TOPICID, IFNULL(P.URL_TITLE, P.POST_CONTENT) SHOW_CONTENT, P.POST_CONTENT, P.POSTOR_COUNTRY_CODE
    , P.POST_ID, P.KEYID, COUNT(C.USERID) FROM OPN_POSTS P, OPN_USER_CARTS C
WHERE P.KEYID = C.KEYID AND P.CLEAN_POST_FLAG = 'Y' AND IFNULL(P.DELETED_FLAG, 'N') <> 'Y'
AND P.POST_DATETIME > CURRENT_DATE() - INTERVAL 10 DAY  AND P.DEMO_POST_FLAG <> 'Y' 
AND P.TOPICID NOT IN (3) AND P.TOPICID IN (SELECT INTEREST_ID FROM OPN_USER_INTERESTS WHERE USERID = uid) 
AND P.POSTOR_TCC = tcc 
GROUP BY P.TOPICID, IFNULL(P.URL_TITLE, P.POST_CONTENT) , P.POST_CONTENT, P.POSTOR_COUNTRY_CODE, P.POST_ID, P.KEYID
ORDER BY RAND() LIMIT 30 ;

END CASE ;

END CASE ;


END //
DELIMITER ;

-- 
