-- STD_MANAGER

-- 

 DELIMITER //
DROP PROCEDURE IF EXISTS STD_MANAGER //
CREATE PROCEDURE STD_MANAGER(TID INT, CCD VARCHAR(5), SCRTPC VARCHAR(20))
THISPROC: BEGIN

/* 
08/30/2023 AST: This proc is created to manage the end-to-end Scrape To Discussion STD process.
It will : 	1. Create the discussion posts for each CCODE/SCRAPE_TOPIC combination
			2. It will dedupe the created discussion posts 
            3. It will sweep the remaining scrapes into the WEB_SCRAPE_RAW table so that the STP process can take over.
            
            TBD: Need to create OPN_STD_MONITOR just like the way STP Monitor keeps the STP records
            
            10/28/2023 AST: Removing the scrapes that have useless URLs such as www.washingtonpost.com - and nothing
            else. no actual url of the news item. Need to remove such scrapes.
            
            10/02/2024 AST: Changing the treatment of USA CELEB/ENT: need to divert some of it into GGG CELEB/ENT 
            Need to combine the CELEB/ENT just like IND

*/


DECLARE SCRCOUNT, STDNUM, COUNTNUMDIFF, ONETHIRD, GENT, GCELEB, UENT, UCELEB, GENTP, GCELEBP, UENTP, UCELEBP, POSTCOUNT, DISCCOUNT INT;

SET SQL_SAFE_UPDATES = 0;

DELETE FROM WEB_SCRAPE_RAW_L where LENGTH(NEWS_URL) < 50 ;

CASE WHEN CCD = 'IND' AND SCRTPC IN ('ENT', 'CELEB') THEN

SET SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND') ;

CASE WHEN SCRCOUNT BETWEEN 1 AND 10 THEN 
CALL callSTDbyENTCELEBIND(SCRCOUNT) ;
CALL OPN_SUPPRESS_DUPES(1, 3 , 'DAY');

WHEN SCRCOUNT BETWEEN 11 AND 20 THEN
SET STDNUM = SCRCOUNT DIV 2 ;
CALL callSTDbyENTCELEBIND(STDNUM) ;
CALL OPN_SUPPRESS_DUPES(1, 3 , 'DAY');

INSERT INTO WEB_SCRAPE_RAW(SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG)
SELECT SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG FROM WEB_SCRAPE_RAW_L
WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND' ;

DELETE FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND' ;

WHEN SCRCOUNT > 20 THEN
SET STDNUM = SCRCOUNT DIV 3 ;
CALL callSTDbyENTCELEBIND(STDNUM) ;
CALL OPN_SUPPRESS_DUPES(1, 3 , 'DAY');

INSERT INTO WEB_SCRAPE_RAW(SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG)
SELECT SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG FROM WEB_SCRAPE_RAW_L
WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND' ;

DELETE FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND' ;

WHEN SCRCOUNT = 0 THEN 
BEGIN
END ;
END CASE ;

/* END OF : CCD = 'IND' AND SCRTPC IN ('ENT', 'CELEB')  */

/* START OF : CCD = 'USA' AND SCRTPC IN ('ENT', 'CELEB')  */

WHEN CCD = 'USA' AND SCRTPC IN ('ENT', 'CELEB') THEN

SET SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'USA') ;

CASE WHEN SCRCOUNT < 20 THEN

/* When the count is < 20 then there is no point in splitting for GGG - hence only do the USA 5, 10 */

CALL callSTDbyIntCcode(5, 'USA', 'ENT' , SCRCOUNT DIV 2) ; 
CALL callSTDbyIntCcode(10, 'USA', 'CELEB' , SCRCOUNT - (SCRCOUNT DIV 2)) ; 

ELSE 

SET DISCCOUNT = SCRCOUNT DIV 2 ;
SET POSTCOUNT = SCRCOUNT - DISCCOUNT ;

/* calculate the numbers that will be converted to GGG/USA, 5/10 and DISC/POST combos   */

SELECT DISCCOUNT DIV 4 DIV 2, DISCCOUNT DIV 4 DIV 2, (DISCCOUNT - DISCCOUNT DIV 4) DIV 2
, (DISCCOUNT - ((DISCCOUNT - DISCCOUNT DIV 4) DIV 2) - DISCCOUNT DIV 4 DIV 2 - DISCCOUNT DIV 4 DIV 2 ) INTO GENT, GCELEB, UENT, UCELEB ;
SELECT POSTCOUNT DIV 4 DIV 2, DISCCOUNT DIV 4 DIV 2, (POSTCOUNT - POSTCOUNT DIV 4) DIV 2
, (POSTCOUNT - ((POSTCOUNT - POSTCOUNT DIV 4) DIV 2) - POSTCOUNT DIV 4 DIV 2 - POSTCOUNT DIV 4 DIV 2 ) INTO GENTP, GCELEBP, UENTP, UCELEBP ;

/* GENT, GCELEB, UENT, UCELEB ARE for converting the scrapes to Discussions
	GENTP, GCELEBP, UENTP, UCELEBP are for converting the scrapes to Posts - by simply pushing them into the WEB_SCRAPE_RAW
 */

UPDATE WEB_SCRAPE_RAW_L SET SCRAPE_TOPIC = 'ENT', COUNTRY_CODE = 'GGG' WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'USA' ORDER BY RAND() LIMIT GENT ;
CALL callSTDbyIntCcode(5, 'GGG', 'ENT' , GENT) ; 

UPDATE WEB_SCRAPE_RAW_L SET SCRAPE_TOPIC = 'CELEB', COUNTRY_CODE = 'GGG' WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'USA' ORDER BY RAND() LIMIT GCELEB ;
CALL callSTDbyIntCcode(10, 'GGG', 'CELEB' , GCELEB) ; 

UPDATE WEB_SCRAPE_RAW_L SET SCRAPE_TOPIC = 'CELEB' WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'USA' ;
/*
The above line is inserted for the following reason: Before that line, USA ENT/CELEB has unknown proportion of ENt and CELEB.
In order to make the remaining UPDATEs actually work, we need to have a clean slate - but instead of having blank SCRAPE_TOPIC
It is better to have all as CELEB

*/

UPDATE WEB_SCRAPE_RAW_L SET SCRAPE_TOPIC = 'ENT' WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'USA' ORDER BY RAND() LIMIT UENT ;
CALL callSTDbyIntCcode(5, 'USA', 'ENT' , UENT) ; 

UPDATE WEB_SCRAPE_RAW_L SET SCRAPE_TOPIC = 'CELEB' WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'USA' ORDER BY RAND() LIMIT UCELEB ;
CALL callSTDbyIntCcode(10, 'USA', 'CELEB' , UCELEB) ; 

UPDATE WEB_SCRAPE_RAW_L SET SCRAPE_TOPIC = 'ENT', COUNTRY_CODE = 'GGG' WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'USA' ORDER BY RAND() LIMIT GENTP ;
UPDATE WEB_SCRAPE_RAW_L SET SCRAPE_TOPIC = 'CELEB', COUNTRY_CODE = 'GGG' WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'USA' ORDER BY RAND() LIMIT GCELEBP ;
UPDATE WEB_SCRAPE_RAW_L SET SCRAPE_TOPIC = 'ENT' WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'USA' ORDER BY RAND() LIMIT UENTP ;
UPDATE WEB_SCRAPE_RAW_L SET SCRAPE_TOPIC = 'CELEB' WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'USA' ORDER BY RAND() LIMIT UCELEBP ;

INSERT INTO WEB_SCRAPE_RAW(SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG)
SELECT SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG FROM WEB_SCRAPE_RAW_L
WHERE SCRAPE_TOPIC IN ('CELEB', 'ENT') AND COUNTRY_CODE IN ('GGG', 'USA') ;

DELETE FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC IN ('CELEB', 'ENT') AND COUNTRY_CODE IN ('GGG', 'USA') ;

END CASE ;

WHEN SCRTPC NOT IN ('ENT', 'CELEB') THEN 

SET SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC = SCRTPC AND COUNTRY_CODE = CCD) ;

CASE WHEN SCRCOUNT BETWEEN 1 AND 10 THEN 
CALL callSTDbyIntCcode(TID, CCD, SCRTPC , SCRCOUNT) ;
CALL OPN_SUPPRESS_DUPES(1, 3 , 'DAY');

WHEN SCRCOUNT BETWEEN 11 AND 20 THEN
SET STDNUM = SCRCOUNT DIV 2 ;
CALL callSTDbyIntCcode(TID, CCD, SCRTPC, STDNUM) ;
CALL OPN_SUPPRESS_DUPES(1, 3 , 'DAY');

INSERT INTO WEB_SCRAPE_RAW(SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG)
SELECT SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG FROM WEB_SCRAPE_RAW_L
WHERE SCRAPE_TOPIC = SCRTPC AND COUNTRY_CODE = CCD ;

DELETE FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC = SCRTPC AND COUNTRY_CODE = CCD ;

WHEN SCRCOUNT > 20 THEN
SET STDNUM = SCRCOUNT DIV 3 ;
CALL callSTDbyIntCcode(TID, CCD, SCRTPC, STDNUM) ;
CALL OPN_SUPPRESS_DUPES(1, 3 , 'DAY');

INSERT INTO WEB_SCRAPE_RAW(SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG)
SELECT SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG FROM WEB_SCRAPE_RAW_L
WHERE SCRAPE_TOPIC = SCRTPC AND COUNTRY_CODE = CCD ;

DELETE FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC = SCRTPC AND COUNTRY_CODE = CCD ;

WHEN SCRCOUNT = 0 THEN 
BEGIN
END ;
END CASE ;

/* END OF OTHER INTERESTS  */

END CASE ;

END //
DELIMITER ;

-- 