-- STD_MANAGER

-- 

 DELIMITER //
DROP PROCEDURE IF EXISTS STD_MANAGER //
CREATE PROCEDURE STD_MANAGER(TID INT, CCD VARCHAR(5), SCRTPC VARCHAR(20))
THISPROC: BEGIN

/* 
08/30/2023 AST: This proc is created to manage the end-to-end Scrape To Discussion STD process.
It will : 	1. Create the discussion posts for each CCODE/SCRAPE_TOPIC combination
			2. It will dedupe the created discussion posts 
            3. It will sweep the remaining scrapes into the WEB_SCRAPE_RAW table so that the STP process can take over.
            
            TBD: Need to create OPN_STD_MONITOR just like the way STP Monitor keeps the STP records

*/


DECLARE SCRCOUNT, STDNUM, COUNTNUMDIFF, ONETHIRD INT;

SET SQL_SAFE_UPDATES = 0;

CASE WHEN CCD = 'IND' AND SCRTPC IN ('ENT', 'CELEB') THEN

SET SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND') ;

CASE WHEN SCRCOUNT BETWEEN 1 AND 10 THEN 
CALL callSTDbyENTCELEBIND(SCRCOUNT) ;
CALL OPN_SUPPRESS_DUPES(1, 3 , 'DAY');

WHEN SCRCOUNT BETWEEN 11 AND 20 THEN
SET STDNUM = SCRCOUNT DIV 2 ;
CALL callSTDbyENTCELEBIND(STDNUM) ;
CALL OPN_SUPPRESS_DUPES(1, 3 , 'DAY');

INSERT INTO WEB_SCRAPE_RAW(SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG)
SELECT SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG FROM WEB_SCRAPE_RAW_L
WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND' ;

DELETE FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND' ;

WHEN SCRCOUNT > 20 THEN
SET STDNUM = SCRCOUNT DIV 3 ;
CALL callSTDbyENTCELEBIND(STDNUM) ;
CALL OPN_SUPPRESS_DUPES(1, 3 , 'DAY');

INSERT INTO WEB_SCRAPE_RAW(SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG)
SELECT SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG FROM WEB_SCRAPE_RAW_L
WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND' ;

DELETE FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND' ;

WHEN SCRCOUNT = 0 THEN 
BEGIN
END ;
END CASE ;

/* END OF : CCD = 'IND' AND SCRTPC IN ('ENT', 'CELEB')  */

/* START OF : CCD = 'USA' AND SCRTPC IN ('ENT')  */

WHEN CCD = 'USA' AND SCRTPC IN ('ENT') THEN

SET SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC IN ('ENT') AND COUNTRY_CODE = 'USA') ;

CASE WHEN SCRCOUNT BETWEEN 1 AND 10 THEN 
CALL callSTDbyIntCcode(5, 'USA', 'ENT' , SCRCOUNT) ; 
CALL OPN_SUPPRESS_DUPES(1, 3 , 'DAY');

WHEN SCRCOUNT > 20 THEN
SET STDNUM = SCRCOUNT DIV 3 ;
SET ONETHIRD = (SCRCOUNT-STDNUM) DIV 2 ;
CALL callSTDbyIntCcode(5, 'USA', 'ENT' , STDNUM) ; 

UPDATE WEB_SCRAPE_RAW_L SET COUNTRY_CODE = 'GGG' WHERE SCRAPE_TOPIC = 'ENT' AND COUNTRY_CODE = 'USA' ORDER BY RAND() LIMIT ONETHIRD ;

CALL callSTDbyIntCcode(5, 'GGG', 'ENT' , ONETHIRD) ; 
CALL OPN_SUPPRESS_DUPES(1, 3 , 'DAY');

INSERT INTO WEB_SCRAPE_RAW(SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG)
SELECT SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG FROM WEB_SCRAPE_RAW_L
WHERE SCRAPE_TOPIC IN ('ENT') AND COUNTRY_CODE = 'USA' ;

DELETE FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC IN ('ENT') AND COUNTRY_CODE = 'USA' ;

WHEN SCRCOUNT = 0 THEN 
BEGIN
END ;
END CASE ;

/* END OF : CCD = 'USA' AND SCRTPC IN ('ENT')  */
/* START OF : CCD = 'USA' AND SCRTPC IN ('CELEB')  */

WHEN CCD = 'USA' AND SCRTPC IN ('CELEB') THEN

SET SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC IN ('CELEB') AND COUNTRY_CODE = 'USA') ;

CASE WHEN SCRCOUNT BETWEEN 1 AND 10 THEN 
CALL callSTDbyIntCcode(10, 'USA', 'CELEB' , SCRCOUNT) ; 
CALL OPN_SUPPRESS_DUPES(1, 3 , 'DAY');

WHEN SCRCOUNT > 20 THEN
SET STDNUM = SCRCOUNT DIV 3 ;
SET ONETHIRD = (SCRCOUNT-STDNUM) DIV 2 ;
CALL callSTDbyIntCcode(10, 'USA', 'CELEB' , STDNUM) ; 

UPDATE WEB_SCRAPE_RAW_L SET COUNTRY_CODE = 'GGG' WHERE SCRAPE_TOPIC = 'CELEB' AND COUNTRY_CODE = 'USA' ORDER BY RAND() LIMIT ONETHIRD ;

CALL callSTDbyIntCcode(10, 'GGG', 'CELEB' , ONETHIRD) ; 
CALL OPN_SUPPRESS_DUPES(1, 3 , 'DAY');

INSERT INTO WEB_SCRAPE_RAW(SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG)
SELECT SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG FROM WEB_SCRAPE_RAW_L
WHERE SCRAPE_TOPIC IN ('CELEB') AND COUNTRY_CODE = 'USA' ;

DELETE FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC IN ('CELEB') AND COUNTRY_CODE = 'USA' ;

WHEN SCRCOUNT = 0 THEN 
BEGIN
END ;
END CASE ;

/* END OF : CCD = 'USA' AND SCRTPC IN ('ENT')  */
/* START OF ALL OTHER INTERESTS  */

WHEN SCRTPC NOT IN ('ENT', 'CELEB') THEN 

SET SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC = SCRTPC AND COUNTRY_CODE = CCD) ;

CASE WHEN SCRCOUNT BETWEEN 1 AND 10 THEN 
CALL callSTDbyIntCcode(TID, CCD, SCRTPC , SCRCOUNT) ;
CALL OPN_SUPPRESS_DUPES(1, 3 , 'DAY');

WHEN SCRCOUNT BETWEEN 11 AND 20 THEN
SET STDNUM = SCRCOUNT DIV 2 ;
CALL callSTDbyIntCcode(TID, CCD, SCRTPC, STDNUM) ;
CALL OPN_SUPPRESS_DUPES(1, 3 , 'DAY');

INSERT INTO WEB_SCRAPE_RAW(SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG)
SELECT SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG FROM WEB_SCRAPE_RAW_L
WHERE SCRAPE_TOPIC = SCRTPC AND COUNTRY_CODE = CCD ;

DELETE FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC = SCRTPC AND COUNTRY_CODE = CCD ;

WHEN SCRCOUNT > 20 THEN
SET STDNUM = SCRCOUNT DIV 3 ;
CALL callSTDbyIntCcode(TID, CCD, SCRTPC, STDNUM) ;
CALL OPN_SUPPRESS_DUPES(1, 3 , 'DAY');

INSERT INTO WEB_SCRAPE_RAW(SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG)
SELECT SCRAPE_DATE, SCRAPE_SOURCE, SCRAPE_TOPIC, NEWS_URL, NEWS_DTM_RAW, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, COUNTRY_CODE, MOVED_TO_POST_FLAG, TAG_DONE_FLAG FROM WEB_SCRAPE_RAW_L
WHERE SCRAPE_TOPIC = SCRTPC AND COUNTRY_CODE = CCD ;

DELETE FROM WEB_SCRAPE_RAW_L WHERE SCRAPE_TOPIC = SCRTPC AND COUNTRY_CODE = CCD ;

WHEN SCRCOUNT = 0 THEN 
BEGIN
END ;
END CASE ;

/* END OF OTHER INTERESTS  */

END CASE ;

END //
DELIMITER ;

-- 