
-- 

DELIMITER //
DROP PROCEDURE IF EXISTS STP_GRAND_USA //
CREATE PROCEDURE STP_GRAND_USA()
THISPROC: BEGIN

/* 
08/24/2018 AST: changed the order to do all the USA dedupes first - otherwise we were getting tons of dupes due to mismatch of the topic order
*/

SET SQL_SAFE_UPDATES = 0;

/*UPDATE WEB_SCRAPE_RAW SET NEWS_URL = CONCAT('https://www.eonline.com', NEWS_URL) 
WHERE NEWS_URL LIKE '/%' AND SCRAPE_SOURCE = 'EONLINE/CELEB'; 

04042019 AST: THE ABOVE LINE IS REMOVED BECAUSE THE SCRAPER HAS BEEN FIXED TO BRING THE CORRECT URLS
ALSO, ADDED CNN/ENT TO DEDUPE LIST*/

/* 06/12/2019 AST: Replaced the indiv dedupe calls with WSR_DEDUPE_ALL 
            Also added the EX and HL calls of the MLB, NBA, NFL */

/*
CALL WSR_DEDUPE('CNBC/BIZ') ;
CALL WSR_DEDUPE('USATODAY/BIZ') ;

CALL WSR_DEDUPE('CNN/POLITICS') ;
CALL WSR_DEDUPE('FOX/POLITICS') ;
CALL WSR_DEDUPE('RCP/POLITICS') ;
CALL WSR_DEDUPE('YAHOO/POLITICS') ;

CALL WSR_DEDUPE('CNN/CELEB') ; -- 'EONLINE/CELEB'
CALL WSR_DEDUPE('EONLINE/CELEB') ; 
CALL WSR_DEDUPE('ETONLINE/CELEB') ; 
CALL WSR_DEDUPE('CNNTV/ENT') ; 
CALL WSR_DEDUPE('CNN/ENT') ; 
CALL WSR_DEDUPE('HOLLY/ENT') ;

CALL WSR_DEDUPE('ESPN/NFL') ;
CALL WSR_DEDUPE('ESPN/NBA') ;
CALL WSR_DEDUPE('ESPN/MLB') ;

CALL WSR_DEDUPE('USATODAY/MLB') ;
CALL WSR_DEDUPE('USATODAY/NBA') ;
CALL WSR_DEDUPE('USATODAY/NFL') ;
*/

CALL WSR_DEDUPE_ALL() ;

CALL STP_GRAND_T4USA() ;
DELETE FROM OPN_POSTS WHERE POST_CONTENT IS NULL;

CALL STP_GRAND_T9USA() ;
DELETE FROM OPN_POSTS WHERE POST_CONTENT IS NULL;

CALL STP_GRAND_T1USA() ;
DELETE FROM OPN_POSTS WHERE POST_CONTENT IS NULL;

CALL STP_GRAND_T10USA() ;
DELETE FROM OPN_POSTS WHERE POST_CONTENT IS NULL;

CALL STP_GRAND_T5USA() ;
DELETE FROM OPN_POSTS WHERE POST_CONTENT IS NULL;

CALL STP_GRAND_T2MLBUSA() ;

CALL STP_GRAND_T2MLBUSA_HL() ;
CALL STP_GRAND_T2MLBUSA_EX() ;

CALL STP_GRAND_T2NBAUSA() ;

CALL STP_GRAND_T2NBAUSA_HL() ;
CALL STP_GRAND_T2NBAUSA_EX() ;

CALL STP_GRAND_T2NFLUSA() ;

CALL STP_GRAND_T2NFLUSA_HL() ;
CALL STP_GRAND_T2NFLUSA_EX() ;

DELETE FROM OPN_POSTS WHERE LENGTH(POST_CONTENT) < 4 AND POST_DATETIME > NOW()- INTERVAL 5 DAY ;


  
  
  
END; //
 DELIMITER ;
 
 -- 