
-- 

DELIMITER //
DROP PROCEDURE IF EXISTS STP_GRAND_XYZNEWS_IND //
CREATE PROCEDURE STP_GRAND_XYZNEWS_IND()
THISPROC: BEGIN

/* 

10/10/2020 AST: this proc is being built to run ust the XYzNEWS STP process
This will run prior to all other STPs so that the XYZNEWS will always have some data

10/11/2020 AST: Corrected various small mistakes (that were causing 0 rows updated) 
	mostly SCRAPE_TAG1 = 'POLITICS' changed to SCRAPE_TOPIC = 'POLITICS'
    ALSO CCODE MISMATCHES IN A FEW PLACES
    
    12/30/2020 AST: Tagging the IND POL news with INDPOLLW OR INDPOLRW
    Adding the STP for Politics News (Right) and (Left)

*/

DECLARE POSTCOUNT, UNTAGCOUNT INT ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 = 'INDPOLRW', SCRAPE_TAG2 = 'INDPOLRW', SCRAPE_TAG3 = 'INDPOLRW' 
WHERE (SCRAPE_SOURCE LIKE 'DP%' OR SCRAPE_SOURCE LIKE 'OPINDIA%' ) 
AND SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'IND' ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 = 'INDPOLLW', SCRAPE_TAG2 = 'INDPOLLW', SCRAPE_TAG3 = 'INDPOLLW' 
WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 <> 'INDPOLRW' ;

-- 

/* Adding 'Trendingnews9' at the top - from all the scraped interests */


UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'trendingnews9' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDPOLLW' AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DATE, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 3   ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'trendingnews9' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDPOLRW' AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DATE, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 3   ;

-- END OF TRENDING NEWS - POLITICS - START OF TRENDING NEWS - SPORTS


UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'trendingnews9' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'USA' AND SCRAPE_SOURCE LIKE ('%MLB%') AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 2   ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'trendingnews9' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'IND' AND SCRAPE_TOPIC IN ('SPORTS') AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 3   ;

-- END OF TRENDING NEWS - SPORTS - START OF SCIENCE NEWS

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'trendingnews9'    , SCRAPE_TAG3 = 'L'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND TAG_DONE_FLAG = 'N' AND SCRAPE_TOPIC = 'SCIENCE' 
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 3 ;

-- END OF TRENDING NEWS - SCIENCE - START OF TRENDING NEWS BUSINESS

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'trendingnews9' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y'  
WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TOPIC = 'BUSINESS' AND TAG_DONE_FLAG = 'N'  AND COUNTRY_CODE = 'IND' 
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
AND NEWS_URL NOT LIKE ('%STOCK%MARKET%') AND  NEWS_URL NOT LIKE ('%MARKET%STOCK%')
ORDER BY RAND() LIMIT 3 ;

-- END OF TRENDING NEWS - BUSINESS - START OF TRENDING NEWS - ENT AND CELEB COMBINED

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'trendingnews9' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'IND' AND SCRAPE_TOPIC IN ('CELEB', 'ENT') AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 6   ;

/* END OF TRENDING NEWS INSERTION */

/*  adding 10 politicsnews(right)/(left) SCRAPES FOR L for COUNTRY_CODE = 'USA' */

/*  End of adding 10 politicsnews(right)/(left) SCRAPES FOR L for COUNTRY_CODE = 'USA'   */

/*  adding 5 POLNEWS SCRAPES FOR L AND  1 POLNEWS SCRAPES FOR H  */

/*  END OF adding 5 POLNEWS SCRAPES FOR L AND  1 POLNEWS SCRAPES FOR H   */

/*  adding 10 politicsnews(right)/30 (left) SCRAPES FOR L for COUNTRY_CODE = 'IND' */

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'politicsnews(right)1' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDPOLRW' AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DATE, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 10   ;



UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'politicsnews(left)1' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDPOLLW' AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DATE, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 30  ;



/*  End of adding 10 politicsnews(right)/30 (left) SCRAPES FOR L for COUNTRY_CODE = 'IND'   */

/*  adding 5 POLNEWS SCRAPES FOR MODI  */

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'POLNEWS' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%NARENDRA%MODI%'     
OR NEWS_HEADLINE LIKE     '%PM%MODI%' OR NEWS_HEADLINE LIKE     '%NAMO%' OR NEWS_EXCERPT LIKE     '%MODI%GOV%'
) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TOPIC = 'POLITICS' 
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 5   ;

/*  END OF adding 5 POLNEWS SCRAPES FOR MODI  */

/*  adding 15 POLNEWS SCRAPES FOR L AND  5 POLNEWS SCRAPES FOR H  */

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'POLNEWS' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'IND' AND SCRAPE_TOPIC = 'POLITICS' AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 15   ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'POLNEWS' , SCRAPE_TAG3 = 'H', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'IND' AND SCRAPE_TOPIC = 'POLITICS' AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 1   ;

/*  END OF adding 15 POLNEWS SCRAPES FOR L AND  5 POLNEWS SCRAPES FOR H   */

/*  adding 15 POLNEWS SCRAPES FOR L AND  5 sportsnews2 SCRAPES FOR H  */

/*  END OF adding 15 sportsnews2 SCRAPES FOR L AND  5 POLNEWS SCRAPES FOR H   */

/*  adding 15 POLNEWS SCRAPES FOR L AND  5 sportsnews2 SCRAPES FOR H  */

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'sportsnews2' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'IND' AND SCRAPE_TOPIC IN ('SPORTS') AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 5   ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'sportsnews2' , SCRAPE_TAG3 = 'H', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'IND' AND SCRAPE_TOPIC IN ('SPORTS') AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 1   ;

/*  END OF adding 15 sportsnews2 SCRAPES FOR L AND  5 POLNEWS SCRAPES FOR H   */

/*  START OF SCIENCENEWS3 ADDITION */

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'sciencenews3'    , SCRAPE_TAG3 = 'L'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND TAG_DONE_FLAG = 'N' AND SCRAPE_TOPIC = 'SCIENCE' 
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 5 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'sciencenews3'    , SCRAPE_TAG3 = 'H'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND TAG_DONE_FLAG = 'N' AND SCRAPE_TOPIC = 'SCIENCE' 
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 1 ;

/*  END OF SCIENCENEWS3 ADDITION */

/* businessnews4 added for STP */

/* END OF businessnews4 added for STP */

/* businessnews4 added for STP */

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'businessnews4' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y'  
WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TOPIC = 'BUSINESS' AND TAG_DONE_FLAG = 'N'  AND COUNTRY_CODE = 'IND' 
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
AND NEWS_URL NOT LIKE ('%STOCK%MARKET%') AND  NEWS_URL NOT LIKE ('%MARKET%STOCK%')
ORDER BY RAND() LIMIT 30 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'businessnews4' , SCRAPE_TAG3 = 'H'  , TAG_DONE_FLAG = 'Y'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TOPIC = 'BUSINESS'
AND TAG_DONE_FLAG = 'N' AND COUNTRY_CODE = 'IND' 
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
AND NEWS_URL NOT LIKE ('%STOCK%MARKET%') AND  NEWS_URL NOT LIKE ('%MARKET%STOCK%')
ORDER BY RAND() LIMIT 2 ;

/* END OF businessnews4 added for STP */

/*  adding 15 POLNEWS SCRAPES FOR L AND  5 entertainmentnews5 SCRAPES FOR H  */

/*  END OF adding 15 entertainmentnews5 SCRAPES FOR L AND  5 POLNEWS SCRAPES FOR H   */

/*  adding 15 POLNEWS SCRAPES FOR L AND  5 entertainmentnews5 SCRAPES FOR H  */

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'entertainmentnews5' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'IND' AND SCRAPE_TOPIC IN ('CELEB', 'ENT') AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 20   ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'entertainmentnews5' , SCRAPE_TAG3 = 'H', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'IND' AND SCRAPE_TOPIC IN ('CELEB', 'ENT') AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 2   ;

/*  END OF adding 15 entertainmentnews5 SCRAPES FOR L AND  5 POLNEWS SCRAPES FOR H   */

/*  adding 15 CELEBNEWS SCRAPES FOR L AND  5 POLNEWS SCRAPES FOR H  */

/*  END OF adding 15 CELEBNEWS SCRAPES FOR L AND  5 POLNEWS SCRAPES FOR H   */

/*  adding 15 POLNEWS SCRAPES FOR L AND  5 POLNEWS SCRAPES FOR H  */

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'CELEBNEWS' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'IND' AND SCRAPE_TOPIC IN ('CELEB', 'ENT') AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 20   ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'CELEBNEWS' , SCRAPE_TAG3 = 'H', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'IND' AND SCRAPE_TOPIC IN ('CELEB', 'ENT') AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 5   ;

/*  END OF adding 15 POLNEWS SCRAPES FOR L AND  5 POLNEWS SCRAPES FOR H   */


/*	07/19/2020 AST: Added the TAG_DONE_FLAG = 'Y' to make it compatible with the new STP_STAG23_MICRO */

-- UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y' WHERE MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG3 IN ('L', 'H') ;

/* 	END OF 07/19/2020 AST ADDITION */

/*  Completing the POLNEWS addition with STp MICRo call  */

CALL STP_STAG23_MICRO('trendingnews9', 'L') ;

CALL STP_STAG23_MICRO('politicsnews(left)1', 'L') ;

CALL STP_STAG23_MICRO('politicsnews(right)1', 'L') ;

CALL STP_STAG23_MICRO('POLNEWS', 'H') ;

CALL STP_STAG23_MICRO('POLNEWS', 'L') ;

CALL STP_STAG23_MICRO('sportsnews2', 'H') ;

CALL STP_STAG23_MICRO('sportsnews2', 'L') ;

CALL STP_STAG23_MICRO('sciencenews3', 'H') ;

CALL STP_STAG23_MICRO('sciencenews3', 'L') ;

CALL STP_STAG23_MICRO('businessnews4', 'H') ;

CALL STP_STAG23_MICRO('businessnews4', 'L') ;

CALL STP_STAG23_MICRO('entertainmentnews5', 'H') ;

CALL STP_STAG23_MICRO('entertainmentnews5', 'L') ;

CALL STP_STAG23_MICRO('CELEBNEWS', 'H') ;

CALL STP_STAG23_MICRO('CELEBNEWS', 'L') ;

/*  END OF Completing the POLNEWS addition with STp MICRo call  */

/* 05/26/2018 AST: adding below: After this proc is executed, the scrapes that were converted into posts
should be swept into the WSR_CONVERTED table 

And the scrapes that remained untagged (and specific to IND, OLITICS should be swept to WSR_UNTAGGED 
This kind of step should be taken at the end of each topic STP - but combo topics
such as trending + politics, celeb + media become an issue. We will deal with it later.
*/

INSERT INTO WSR_CONVERTED(SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE
, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE)
SELECT SCRAPE_TOPIC, SCRAPE_SOURCE,  SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT
, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE FROM WEB_SCRAPE_RAW
WHERE  MOVED_TO_POST_FLAG = 'Y' ;

/* 10/10/2020 AST: COMMENTING OUT THE INSERT INTO OPN_WEB_LINKS - BECAUSE WE DON'T NEED ANYMORE 

INSERT INTO OPN_WEB_LINKS(WEB_URL, URL_TITLE, URL_DESCRIPTION, IMAGE_URL, CREATION_DTM, CLEAN_FLAG)
SELECT NEWS_URL, IFNULL(NEWS_HEADLINE, NEWS_EXCERPT), IFNULL(NEWS_EXCERPT, NEWS_HEADLINE), NEWS_PIC_URL, NOW(), 'Y'
FROM WEB_SCRAPE_RAW WHERE NEWS_PIC_URL IS NOT NULL AND SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'USA' ;

 END OF COMMENTING OUT THE INSERT INTO OPN_WEB_LINKS */

SET POSTCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW
WHERE  MOVED_TO_POST_FLAG = 'Y') ;

DELETE FROM WEB_SCRAPE_RAW WHERE  MOVED_TO_POST_FLAG = 'Y' ;

INSERT INTO OPN_STP_LOG(PROC_NAME, STP_TOPIC, STP_COUNTRY_CODE, POST_COUNT, UNTAG_COUNT, STP_PROC_DTM)
VALUES('STP_GRAND_XYZNEWS_IND', 'XYZ', 'ALL', POSTCOUNT, 0, NOW()) ;

/* End of STP logging */
  
  
  
END; //
 DELIMITER ;
 
 -- 