
-- STP_BOLO_INDPOL

DELIMITER //
DROP PROCEDURE IF EXISTS STP_BOLO_INDPOL //
CREATE PROCEDURE STP_BOLO_INDPOL()
THISPROC: BEGIN

/* 

10/10/2020 AST: this proc is being built to run ust the XYzNEWS STP process
This will run prior to all other STPs so that the XYZNEWS will always have some data

10/11/2020 AST: Corrected various small mistakes (that were causing 0 rows updated) 
	mostly SCRAPE_TAG1 = 'POLITICS' changed to SCRAPE_TOPIC = 'POLITICS'
    ALSO CCODE MISMATCHES IN A FEW PLACES
    
    12/30/2020 AST: Tagging the IND POL news with INDPOLLW OR INDPOLRW
    Adding the STP for Politics News (Right) and (Left)

*/

DECLARE POSTCOUNT, UNTAGCOUNT INT ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 = 'INDPOLRW', SCRAPE_TAG2 = 'INDPOLRW', SCRAPE_TAG3 = 'INDPOLRW' 
WHERE (SCRAPE_SOURCE LIKE 'DP%' OR SCRAPE_SOURCE LIKE 'OPINDIA%' ) 
AND SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'IND' ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 = 'INDPOLLW', SCRAPE_TAG2 = 'INDPOLLW', SCRAPE_TAG3 = 'INDPOLLW' 
WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 <> 'INDPOLRW' ;

-- 

/*

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'politicsnews(right)1' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDPOLRW' AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DATE, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 10   ;



UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'politicsnews(left)1' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDPOLLW' AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DATE, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 30  ;

*/

/*  End of adding 10 politicsnews(right)/30 (left) SCRAPES FOR L for COUNTRY_CODE = 'IND'   */

/*  adding 5 POLNEWS SCRAPES FOR MODI  */

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'politicsnews1' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%NARENDRA%MODI%'     
OR NEWS_HEADLINE LIKE     '%PM%MODI%' OR NEWS_HEADLINE LIKE     '%NAMO%' OR NEWS_EXCERPT LIKE     '%MODI%GOV%'
) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TOPIC = 'POLITICS' 
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 5   ;

/*  END OF adding 5 POLNEWS SCRAPES FOR MODI  */

/*  adding 15 POLNEWS SCRAPES FOR L AND  5 POLNEWS SCRAPES FOR H  */

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'politicsnews1' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'IND' AND SCRAPE_TOPIC = 'POLITICS' AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND STR_TO_DATE(SUBSTRING(NEWS_DTM_RAW, 1, 10), '%Y-%m-%d') >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 15   ;


/*  END OF adding 15 POLNEWS SCRAPES FOR L AND  5 POLNEWS SCRAPES FOR H   */

-- CALL STP_STAG23_MICRO('politicsnews(left)1', 'L') ;

-- CALL STP_STAG23_MICRO('politicsnews(right)1', 'L') ;

-- CALL STP_STAG23_MICRO('POLNEWS', 'H') ;

CALL STP_STAG23_MICRO('politicsnews1', 'L') ;

INSERT INTO WSR_CONVERTED(SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE
, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE)
SELECT SCRAPE_TOPIC, SCRAPE_SOURCE,  SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT
, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE FROM WEB_SCRAPE_RAW
WHERE  MOVED_TO_POST_FLAG = 'Y' ;

/* 10/10/2020 AST: COMMENTING OUT THE INSERT INTO OPN_WEB_LINKS - BECAUSE WE DON'T NEED ANYMORE 

INSERT INTO OPN_WEB_LINKS(WEB_URL, URL_TITLE, URL_DESCRIPTION, IMAGE_URL, CREATION_DTM, CLEAN_FLAG)
SELECT NEWS_URL, IFNULL(NEWS_HEADLINE, NEWS_EXCERPT), IFNULL(NEWS_EXCERPT, NEWS_HEADLINE), NEWS_PIC_URL, NOW(), 'Y'
FROM WEB_SCRAPE_RAW WHERE NEWS_PIC_URL IS NOT NULL AND SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'USA' ;

 END OF COMMENTING OUT THE INSERT INTO OPN_WEB_LINKS */

SET POSTCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW
WHERE  MOVED_TO_POST_FLAG = 'Y') ;

DELETE FROM WEB_SCRAPE_RAW WHERE  MOVED_TO_POST_FLAG = 'Y' ;

INSERT INTO OPN_STP_LOG(PROC_NAME, STP_TOPIC, STP_COUNTRY_CODE, POST_COUNT, UNTAG_COUNT, STP_PROC_DTM)
VALUES('STP_BOLO_INDPOL', 'XYZ', 'ALL', POSTCOUNT, 0, NOW()) ;

/* End of STP logging */
  
  
  
END; //
 DELIMITER ;
 
 -- 