
-- 

DELIMITER //
DROP PROCEDURE IF EXISTS STP_GRAND_T1IND //
CREATE PROCEDURE STP_GRAND_T1IND()
THISPROC: BEGIN

/* 
12/13/2018 AST: Added sweep into OPN_WEB_LINKS

INSERT INTO OPN_WEB_LINKS(WEB_URL, URL_TITLE, URL_DESCRIPTION, IMAGE_URL, CREATION_DTM, CLEAN_FLAG)
SELECT NEWS_URL, IFNULL(NEWS_HEADLINE, NEWS_EXCERPT), IFNULL(NEWS_EXCERPT, NEWS_HEADLINE), NEWS_PIC_URL, NOW(), 'Y'
FROM WEB_SCRAPE_RAW WHERE NEWS_PIC_URL IS NOT NULL AND SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'IND'

08/30/2019 AST: Adding back NaMo

    	07/19/2020 AST: ADDED TAG_DONE_FLAG = 'Y' AFTER UPDATE
        
        09/05/2020 AST: Adding the tagging of 25 untagged scrapes to POLITICS NEWS KW
		10/04/2020 AST: adding filter to XYZNEWS to avoid: old news, stock market update, SHOPPING ADS ETC.
        10/09/2020 AST: fixing the date issue in XYZNEWS  addition - also moving it to the front of the UPDATE
    10/10/2020 AST: removed the above - as a new proc was created for this purpose
    
        06/24/2023: AST: Introducing the STP_REMAINDER proc 

*/

DECLARE POSTCOUNT, UNTAGCOUNT INT ;

-- 

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'fad'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%DEVENDRA%NAVIS%'     
OR UPPER(NEWS_URL) LIKE     '%MAH%GOV%' OR UPPER(NEWS_URL) LIKE     '%DNAVIS%') 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'fad'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%DEVENDRA%NAVIS%'     
OR UPPER(NEWS_URL) LIKE     '%MAH%GOV%' OR UPPER(NEWS_URL) LIKE     '%DNAVIS%') 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'yogi'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%YOGI%'     
OR UPPER(NEWS_URL) LIKE     '%ADITYA%NATH%' )
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'       AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'yogi'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%YOGI%'     
OR UPPER(NEWS_URL) LIKE     '%ADITYA%NATH%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'       AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'jetley'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%JAITLEY%'     
OR UPPER(NEWS_URL) LIKE     '%MIN%FIN%' OR UPPER(NEWS_URL) LIKE     '%FIN%MIN%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'jetley'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%JAITLEY%'     
OR UPPER(NEWS_URL) LIKE     '%MIN%FIN%' OR UPPER(NEWS_URL) LIKE     '%FIN%MIN%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'swaraj'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%SUSHMA%'     
OR UPPER(NEWS_URL) LIKE     '%SWARAJ%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'swaraj'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%SUSHMA%'     
OR UPPER(NEWS_URL) LIKE     '%SWARAJ%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'arnab'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%ARNAB%'     
OR UPPER(NEWS_URL) LIKE     '%GOSWAMI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'arnab'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%ARNAB%'     
OR UPPER(NEWS_URL) LIKE     '%GOSWAMI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'smriti'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%SMRITI%'     
OR UPPER(NEWS_URL) LIKE     '%IRANI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'smriti'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%SMRITI%'     
OR UPPER(NEWS_URL) LIKE     '%IRANI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'parrikar'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%PARRIKAR%'     
OR UPPER(NEWS_URL) LIKE     '%GOA%CM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'parrikar'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%PARRIKAR%'     
OR UPPER(NEWS_URL) LIKE     '%GOA%CM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'amitshah'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%AMIT%SHAH%'     
OR UPPER(NEWS_URL) LIKE     '%AMIT%SHAH%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'amitshah'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%AMIT%SHAH%'     
OR UPPER(NEWS_URL) LIKE     '%AMIT%SHAH%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'rss'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%RSS%'     
OR UPPER(NEWS_URL) LIKE     '%RASH%SANGH%' OR UPPER(NEWS_URL) LIKE     '%MOHAN%BHAG%'  )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'rss'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%RSS%'     
OR UPPER(NEWS_URL) LIKE     '%RASH%SANGH%' OR UPPER(NEWS_URL) LIKE     '%MOHAN%BHAG%'  )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'lalu'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%LALU%'     
OR UPPER(NEWS_URL) LIKE     '%RJD%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'lalu'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%LALU%'     
OR UPPER(NEWS_URL) LIKE     '%RJD%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'tharoor'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%THAROOR%'     
OR UPPER(NEWS_URL) LIKE     '%THAROOR%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'tharoor'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%THAROOR%'     
OR UPPER(NEWS_URL) LIKE     '%THAROOR%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'pawar'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%SHARAD%PAWAR%'     
OR UPPER(NEWS_URL) LIKE     '%PAWAR%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'pawar'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%SHARAD%PAWAR%'     
OR UPPER(NEWS_URL) LIKE     '%PAWAR%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'aap'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%-AAP-%'     
OR UPPER(NEWS_URL) LIKE     '%AAM%ADMI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'aap'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%-AAP-%'     
OR UPPER(NEWS_URL) LIKE     '%AAM%ADMI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'chidu'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%CHIDAMBARAM%'     
OR UPPER(NEWS_URL) LIKE     '%CHIDAMBARAM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'chidu'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%CHIDAMBARAM%'     
OR UPPER(NEWS_URL) LIKE     '%CHIDAMBARAM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'didi'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%DIDI%'     
OR UPPER(NEWS_URL) LIKE     '%MAMATA%' OR UPPER(NEWS_URL) LIKE     '%BENGAL%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'didi'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%DIDI%'     
OR UPPER(NEWS_URL) LIKE     '%MAMATA%' OR UPPER(NEWS_URL) LIKE     '%BENGAL%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'owaisi'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%OWAISI%'     
OR UPPER(NEWS_URL) LIKE     '%MIM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'owaisi'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%OWAISI%'     
OR UPPER(NEWS_URL) LIKE     '%MIM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'dick'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%HARDIK%'     
OR UPPER(NEWS_URL) LIKE     '%HARDIK%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'dick'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%HARDIK%'     
OR UPPER(NEWS_URL) LIKE     '%HARDIK%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'uddu'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%UDDHAV%'     
OR UPPER(NEWS_URL) LIKE     '%THAKREY%' OR UPPER(NEWS_URL) LIKE     '%SHIV%SENA%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'uddu'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%UDDHAV%'     
OR UPPER(NEWS_URL) LIKE     '%THAKREY%' OR UPPER(NEWS_URL) LIKE     '%SHIV%SENA%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'sonia'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%sonia%'     
OR UPPER(NEWS_URL) LIKE     '%PRIYANKA%' OR UPPER(NEWS_URL) LIKE     '%GANDHI%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'sonia'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%sonia%'     
OR UPPER(NEWS_URL) LIKE     '%PRIYANKA%' OR UPPER(NEWS_URL) LIKE     '%GANDHI%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'kejri'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%KEJRI%'     
OR UPPER(NEWS_URL) LIKE     '%KEJRI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'kejri'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%KEJRI%'     
OR UPPER(NEWS_URL) LIKE     '%KEJRI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'raga'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%RAHUL%GANDHI%'     
OR UPPER(NEWS_URL) LIKE     '%RAHUL%GANDHI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'raga'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%RAHUL%GANDHI%'     
OR UPPER(NEWS_URL) LIKE     '%RAHUL%GANDHI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'congress'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%CONGRESS%'     
OR UPPER(NEWS_URL) LIKE     '%CONGRESS%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'congress'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%CONGRESS%'     
OR UPPER(NEWS_URL) LIKE     '%CONGRESS%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;



UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'modi'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%NARENDRA%MODI%'     
OR UPPER(NEWS_URL) LIKE     '%PM%MODI%' OR UPPER(NEWS_URL) LIKE     '%NAMO%' OR UPPER(NEWS_URL) LIKE     '%MODI%GOV%'
) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'modi'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%NARENDRA%MODI%'     
OR UPPER(NEWS_URL) LIKE     '%PM%MODI%' OR UPPER(NEWS_URL) LIKE     '%NAMO%' OR UPPER(NEWS_URL) LIKE     '%MODI%GOV%'
)
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 0 ;



UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'bjp'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%BJP%'     
OR UPPER(NEWS_URL) LIKE     '%BHAR%JANAT%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'bjp'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%BJP%'     
OR UPPER(NEWS_URL) LIKE     '%BHAR%JANAT%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

/*

09/03/2019 AST: Adding NEWS_HEADLINE LIKE

*/

--
/* 05/25/2018 AST: removing the section below - because all kinds of crap news gets posted in politics
and we don't want to spam the instream with that 

start of the removal section */

/*

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 = 'NDA', SCRAPE_TAG2 = 'NDA', SCRAPE_TAG3 = 'NDA' 
WHERE SCRAPE_SOURCE = 'DP/POLITICS' AND MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG1 = 'POLITICS' AND SCRAPE_TAG2 = SCRAPE_TAG3 ;

--

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 = 'UPA', SCRAPE_TAG2 = 'UPA', SCRAPE_TAG3 = 'UPA' 
WHERE SCRAPE_SOURCE <> 'DP/POLITICS' AND MOVED_TO_POST_FLAG = 'N' 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS' AND SCRAPE_TAG2 = SCRAPE_TAG3 ;

--

--

CALL STP_STAG1_1KW(1, 'NDA', 'IND') ;
CALL STP_MOP_UP('NDA') ;

CALL STP_STAG1_1KW(1, 'UPA', 'IND') ;
CALL STP_MOP_UP('UPA') ;

*/

/* end of crap news removal section */

--

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'fad'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%DEVENDRA%NAVIS%'     
OR NEWS_HEADLINE LIKE     '%MAH%GOV%' OR NEWS_HEADLINE LIKE     '%DNAVIS%') 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'fad'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%DEVENDRA%NAVIS%'     
OR NEWS_HEADLINE LIKE     '%MAH%GOV%' OR NEWS_HEADLINE LIKE     '%DNAVIS%') 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'yogi'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%YOGI%'     
OR NEWS_HEADLINE LIKE     '%ADITYA%NATH%' )
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'       AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'yogi'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%YOGI%'     
OR NEWS_HEADLINE LIKE     '%ADITYA%NATH%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'       AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'jetley'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%JAITLEY%'     
OR NEWS_HEADLINE LIKE     '%MIN%FIN%' OR NEWS_HEADLINE LIKE     '%FIN%MIN%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'jetley'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%JAITLEY%'     
OR NEWS_HEADLINE LIKE     '%MIN%FIN%' OR NEWS_HEADLINE LIKE     '%FIN%MIN%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'swaraj'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%SUSHMA%'     
OR NEWS_HEADLINE LIKE     '%SWARAJ%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'swaraj'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%SUSHMA%'     
OR NEWS_HEADLINE LIKE     '%SWARAJ%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'arnab'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%ARNAB%'     
OR NEWS_HEADLINE LIKE     '%GOSWAMI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'arnab'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%ARNAB%'     
OR NEWS_HEADLINE LIKE     '%GOSWAMI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'smriti'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%SMRITI%'     
OR NEWS_HEADLINE LIKE     '%IRANI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'smriti'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%SMRITI%'     
OR NEWS_HEADLINE LIKE     '%IRANI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'parrikar'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%PARRIKAR%'     
OR NEWS_HEADLINE LIKE     '%GOA%CM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'parrikar'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%PARRIKAR%'     
OR NEWS_HEADLINE LIKE     '%GOA%CM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'amitshah'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%AMIT%SHAH%'     
OR NEWS_HEADLINE LIKE     '%AMIT%SHAH%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'amitshah'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%AMIT%SHAH%'     
OR NEWS_HEADLINE LIKE     '%AMIT%SHAH%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'rss'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%RSS%'     
OR NEWS_HEADLINE LIKE     '%RASH%SANGH%' OR NEWS_HEADLINE LIKE     '%MOHAN%BHAG%'  )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'rss'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%RSS%'     
OR NEWS_HEADLINE LIKE     '%RASH%SANGH%' OR NEWS_HEADLINE LIKE     '%MOHAN%BHAG%'  )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'lalu'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%LALU%'     
OR NEWS_HEADLINE LIKE     '%RJD%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'lalu'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%LALU%'     
OR NEWS_HEADLINE LIKE     '%RJD%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'tharoor'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%THAROOR%'     
OR NEWS_HEADLINE LIKE     '%THAROOR%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'tharoor'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%THAROOR%'     
OR NEWS_HEADLINE LIKE     '%THAROOR%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'pawar'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%SHARAD%PAWAR%'     
OR NEWS_HEADLINE LIKE     '%PAWAR%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'pawar'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%SHARAD%PAWAR%'     
OR NEWS_HEADLINE LIKE     '%PAWAR%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'aap'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%-AAP-%'     
OR NEWS_HEADLINE LIKE     '%AAM%ADMI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'aap'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%-AAP-%'     
OR NEWS_HEADLINE LIKE     '%AAM%ADMI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'chidu'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%CHIDAMBARAM%'     
OR NEWS_HEADLINE LIKE     '%CHIDAMBARAM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'chidu'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%CHIDAMBARAM%'     
OR NEWS_HEADLINE LIKE     '%CHIDAMBARAM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'didi'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%DIDI%'     
OR NEWS_HEADLINE LIKE     '%MAMATA%' OR NEWS_HEADLINE LIKE     '%BENGAL%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'didi'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%DIDI%'     
OR NEWS_HEADLINE LIKE     '%MAMATA%' OR NEWS_HEADLINE LIKE     '%BENGAL%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'owaisi'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%OWAISI%'     
OR NEWS_HEADLINE LIKE     '%MIM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'owaisi'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%OWAISI%'     
OR NEWS_HEADLINE LIKE     '%MIM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'dick'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%HARDIK%'     
OR NEWS_HEADLINE LIKE     '%HARDIK%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'dick'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%HARDIK%'     
OR NEWS_HEADLINE LIKE     '%HARDIK%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'uddu'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%UDDHAV%'     
OR NEWS_HEADLINE LIKE     '%THAKREY%' OR NEWS_HEADLINE LIKE     '%SHIV%SENA%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'uddu'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%UDDHAV%'     
OR NEWS_HEADLINE LIKE     '%THAKREY%' OR NEWS_HEADLINE LIKE     '%SHIV%SENA%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'sonia'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%sonia%'     
OR NEWS_HEADLINE LIKE     '%PRIYANKA%' OR NEWS_HEADLINE LIKE     '%GANDHI%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'sonia'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%sonia%'     
OR NEWS_HEADLINE LIKE     '%PRIYANKA%' OR NEWS_HEADLINE LIKE     '%GANDHI%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'kejri'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%KEJRI%'     
OR NEWS_HEADLINE LIKE     '%KEJRI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'kejri'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%KEJRI%'     
OR NEWS_HEADLINE LIKE     '%KEJRI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'raga'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%RAHUL%GANDHI%'     
OR NEWS_HEADLINE LIKE     '%RAHUL%GANDHI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'raga'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%RAHUL%GANDHI%'     
OR NEWS_HEADLINE LIKE     '%RAHUL%GANDHI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'congress'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%CONGRESS%'     
OR NEWS_HEADLINE LIKE     '%CONGRESS%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'congress'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%CONGRESS%'     
OR NEWS_HEADLINE LIKE     '%CONGRESS%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'modi'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%NARENDRA%MODI%'     
OR NEWS_HEADLINE LIKE     '%PM%MODI%' OR NEWS_HEADLINE LIKE     '%NAMO%' OR NEWS_HEADLINE LIKE     '%MODI%GOV%'
) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS' AND TAG_DONE_FLAG = 'N'    AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'modi'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%NARENDRA%MODI%'     
OR NEWS_HEADLINE LIKE     '%PM%MODI%' OR NEWS_HEADLINE LIKE     '%NAMO%' OR NEWS_HEADLINE LIKE     '%MODI%GOV%'
)
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'  AND TAG_DONE_FLAG = 'N'   AND MOD(ROW_ID, 2) = 0 ;



UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'bjp'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%BJP%'     
OR NEWS_HEADLINE LIKE     '%BHAR%JANAT%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'bjp'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_HEADLINE LIKE     '%BJP%'     
OR NEWS_HEADLINE LIKE     '%BHAR%JANAT%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

-- END OF 'NEWS_HEADLINE LIKE' Addition

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'fad'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%DEVENDRA%NAVIS%'     
OR NEWS_EXCERPT LIKE     '%MAH%GOV%' OR NEWS_EXCERPT LIKE     '%DNAVIS%') 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'fad'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%DEVENDRA%NAVIS%'     
OR NEWS_EXCERPT LIKE     '%MAH%GOV%' OR NEWS_EXCERPT LIKE     '%DNAVIS%') 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'yogi'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%YOGI%'     
OR NEWS_EXCERPT LIKE     '%ADITYA%NATH%' )
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'       AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'yogi'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%YOGI%'     
OR NEWS_EXCERPT LIKE     '%ADITYA%NATH%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'       AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'jetley'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%JAITLEY%'     
OR NEWS_EXCERPT LIKE     '%MIN%FIN%' OR NEWS_EXCERPT LIKE     '%FIN%MIN%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'jetley'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%JAITLEY%'     
OR NEWS_EXCERPT LIKE     '%MIN%FIN%' OR NEWS_EXCERPT LIKE     '%FIN%MIN%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'swaraj'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%SUSHMA%'     
OR NEWS_EXCERPT LIKE     '%SWARAJ%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'swaraj'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%SUSHMA%'     
OR NEWS_EXCERPT LIKE     '%SWARAJ%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'arnab'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%ARNAB%'     
OR NEWS_EXCERPT LIKE     '%GOSWAMI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'arnab'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%ARNAB%'     
OR NEWS_EXCERPT LIKE     '%GOSWAMI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'smriti'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%SMRITI%'     
OR NEWS_EXCERPT LIKE     '%IRANI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'smriti'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%SMRITI%'     
OR NEWS_EXCERPT LIKE     '%IRANI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'parrikar'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%PARRIKAR%'     
OR NEWS_EXCERPT LIKE     '%GOA%CM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'parrikar'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%PARRIKAR%'     
OR NEWS_EXCERPT LIKE     '%GOA%CM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'amitshah'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%AMIT%SHAH%'     
OR NEWS_EXCERPT LIKE     '%AMIT%SHAH%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'amitshah'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%AMIT%SHAH%'     
OR NEWS_EXCERPT LIKE     '%AMIT%SHAH%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'rss'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%RSS%'     
OR NEWS_EXCERPT LIKE     '%RASH%SANGH%' OR NEWS_EXCERPT LIKE     '%MOHAN%BHAG%'  )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'rss'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%RSS%'     
OR NEWS_EXCERPT LIKE     '%RASH%SANGH%' OR NEWS_EXCERPT LIKE     '%MOHAN%BHAG%'  )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'lalu'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%LALU%'     
OR NEWS_EXCERPT LIKE     '%RJD%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'lalu'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%LALU%'     
OR NEWS_EXCERPT LIKE     '%RJD%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'tharoor'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%THAROOR%'     
OR NEWS_EXCERPT LIKE     '%THAROOR%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'tharoor'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%THAROOR%'     
OR NEWS_EXCERPT LIKE     '%THAROOR%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'pawar'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%SHARAD%PAWAR%'     
OR NEWS_EXCERPT LIKE     '%PAWAR%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'pawar'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%SHARAD%PAWAR%'     
OR NEWS_EXCERPT LIKE     '%PAWAR%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'aap'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%-AAP-%'     
OR NEWS_EXCERPT LIKE     '%AAM%ADMI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'aap'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%-AAP-%'     
OR NEWS_EXCERPT LIKE     '%AAM%ADMI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'chidu'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%CHIDAMBARAM%'     
OR NEWS_EXCERPT LIKE     '%CHIDAMBARAM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'chidu'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%CHIDAMBARAM%'     
OR NEWS_EXCERPT LIKE     '%CHIDAMBARAM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'didi'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%DIDI%'     
OR NEWS_EXCERPT LIKE     '%MAMATA%' OR NEWS_EXCERPT LIKE     '%BENGAL%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'didi'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%DIDI%'     
OR NEWS_EXCERPT LIKE     '%MAMATA%' OR NEWS_EXCERPT LIKE     '%BENGAL%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'owaisi'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%OWAISI%'     
OR NEWS_EXCERPT LIKE     '%MIM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'owaisi'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%OWAISI%'     
OR NEWS_EXCERPT LIKE     '%MIM%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'dick'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%HARDIK%'     
OR NEWS_EXCERPT LIKE     '%HARDIK%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'dick'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%HARDIK%'     
OR NEWS_EXCERPT LIKE     '%HARDIK%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'uddu'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%UDDHAV%'     
OR NEWS_EXCERPT LIKE     '%THAKREY%' OR NEWS_EXCERPT LIKE     '%SHIV%SENA%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'uddu'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%UDDHAV%'     
OR NEWS_EXCERPT LIKE     '%THAKREY%' OR NEWS_EXCERPT LIKE     '%SHIV%SENA%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'sonia'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%sonia%'     
OR NEWS_EXCERPT LIKE     '%PRIYANKA%' OR NEWS_EXCERPT LIKE     '%GANDHI%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'sonia'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%sonia%'     
OR NEWS_EXCERPT LIKE     '%PRIYANKA%' OR NEWS_EXCERPT LIKE     '%GANDHI%')  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'kejri'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%KEJRI%'     
OR NEWS_EXCERPT LIKE     '%KEJRI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'kejri'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%KEJRI%'     
OR NEWS_EXCERPT LIKE     '%KEJRI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'raga'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%RAHUL%GANDHI%'     
OR NEWS_EXCERPT LIKE     '%RAHUL%GANDHI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'raga'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%RAHUL%GANDHI%'     
OR NEWS_EXCERPT LIKE     '%RAHUL%GANDHI%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'congress'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%CONGRESS%'     
OR NEWS_EXCERPT LIKE     '%CONGRESS%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'congress'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%CONGRESS%'     
OR NEWS_EXCERPT LIKE     '%CONGRESS%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;


UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'modi'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%NARENDRA%MODI%'     
OR NEWS_EXCERPT LIKE     '%PM%MODI%' OR NEWS_EXCERPT LIKE     '%NAMO%' OR NEWS_EXCERPT LIKE     '%MODI%GOV%'
) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'modi'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%NARENDRA%MODI%'     
OR NEWS_EXCERPT LIKE     '%PM%MODI%' OR NEWS_EXCERPT LIKE     '%NAMO%' OR NEWS_EXCERPT LIKE     '%MODI%GOV%'
)
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 0 ;



UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'bjp'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%BJP%'     
OR NEWS_EXCERPT LIKE     '%BHAR%JANAT%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'bjp'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (NEWS_EXCERPT LIKE     '%BJP%'     
OR NEWS_EXCERPT LIKE     '%BHAR%JANAT%' )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;


-- END OF 'NEWS_EXCERPT LIKE' ADDITION

/*	07/19/2020 AST: Added the TAG_DONE_FLAG = 'Y' to make it compatible with the new STP_STAG23_MICRO */

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y' WHERE SCRAPE_TAG3 IN ('L', 'H') ;

/* 	END OF 07/19/2020 AST ADDITION */

-- CALL STP_STAG23_1KWINSERT('modi', 'H', 5) ;
 CALL STP_STAG23_MICRO('modi', 'H') ;

-- CALL STP_STAG23_1KWINSERT('modi', 'L', 5) ;
 CALL STP_STAG23_MICRO('modi', 'L') ;

-- CALL STP_STAG23_1KWINSERT('congress', 'H', 5) ;
CALL STP_STAG23_MICRO('congress', 'H') ;

-- CALL STP_STAG23_1KWINSERT('congress', 'L', 5) ;
CALL STP_STAG23_MICRO('congress', 'L') ;

-- CALL STP_STAG23_1KWINSERT('raga', 'H', 5) ;
CALL STP_STAG23_MICRO('raga', 'H') ;

-- CALL STP_STAG23_1KWINSERT('raga', 'L', 5) ;
CALL STP_STAG23_MICRO('raga', 'L') ;

-- CALL STP_STAG23_1KWINSERT('kejri', 'H', 3) ;
CALL STP_STAG23_MICRO('kejri', 'H') ;

-- CALL STP_STAG23_1KWINSERT('kejri', 'L', 3) ;
CALL STP_STAG23_MICRO('kejri', 'L') ;

-- CALL STP_STAG23_1KWINSERT('sonia', 'H', 3) ;
CALL STP_STAG23_MICRO('sonia', 'H') ;

-- CALL STP_STAG23_1KWINSERT('sonia', 'L', 3) ;
CALL STP_STAG23_MICRO('sonia', 'L') ;

-- CALL STP_STAG23_1KWINSERT('uddu', 'H', 2) ;
CALL STP_STAG23_MICRO('uddu', 'H') ;

-- CALL STP_STAG23_1KWINSERT('uddu', 'L', 3) ;
CALL STP_STAG23_MICRO('uddu', 'L') ;

-- CALL STP_STAG23_1KWINSERT('dick', 'H', 2) ;
CALL STP_STAG23_MICRO('dick', 'H') ;

-- CALL STP_STAG23_1KWINSERT('dick', 'L', 3) ;
CALL STP_STAG23_MICRO('dick', 'L') ;

-- CALL STP_STAG23_1KWINSERT('owaisi', 'H', 2) ;
CALL STP_STAG23_MICRO('owaisi', 'H') ;

-- CALL STP_STAG23_1KWINSERT('owaisi', 'L', 3) ;
CALL STP_STAG23_MICRO('owaisi', 'L') ;

-- CALL STP_STAG23_1KWINSERT('chidu', 'H', 2) ;
CALL STP_STAG23_MICRO('chidu', 'H') ;

-- CALL STP_STAG23_1KWINSERT('chidu', 'L', 3) ;
CALL STP_STAG23_MICRO('chidu', 'L') ;

-- CALL STP_STAG23_1KWINSERT('didi', 'H', 2) ;
CALL STP_STAG23_MICRO('didi', 'H') ;

-- CALL STP_STAG23_1KWINSERT('didi', 'L', 3) ;
CALL STP_STAG23_MICRO('didi', 'L') ;

-- CALL STP_STAG23_1KWINSERT('aap', 'H', 2) ;
CALL STP_STAG23_MICRO('aap', 'H') ;

-- CALL STP_STAG23_1KWINSERT('aap', 'L', 3) ;
CALL STP_STAG23_MICRO('aap', 'L') ;

-- CALL STP_STAG23_1KWINSERT('pawar', 'H', 2) ;
CALL STP_STAG23_MICRO('pawar', 'H') ;

-- CALL STP_STAG23_1KWINSERT('pawar', 'L', 3) ;
CALL STP_STAG23_MICRO('pawar', 'L') ;

-- CALL STP_STAG23_1KWINSERT('tharoor', 'H', 2) ;
CALL STP_STAG23_MICRO('tharoor', 'H') ;

-- CALL STP_STAG23_1KWINSERT('tharoor', 'L', 3) ;
CALL STP_STAG23_MICRO('tharoor', 'L') ;

-- CALL STP_STAG23_1KWINSERT('lalu', 'H', 2) ;
CALL STP_STAG23_MICRO('lalu', 'H') ;

-- CALL STP_STAG23_1KWINSERT('lalu', 'L', 3) ;
CALL STP_STAG23_MICRO('lalu', 'L') ;

-- CALL STP_STAG23_1KWINSERT('bjp', 'H', 5) ;
CALL STP_STAG23_MICRO('bjp', 'H') ;

-- CALL STP_STAG23_1KWINSERT('bjp', 'L', 5) ;
CALL STP_STAG23_MICRO('bjp', 'L') ;

-- CALL STP_STAG23_1KWINSERT('rss', 'H', 2) ;
CALL STP_STAG23_MICRO('rss', 'H') ;

-- CALL STP_STAG23_1KWINSERT('rss', 'L', 3) ;
CALL STP_STAG23_MICRO('rss', 'L') ;

-- CALL STP_STAG23_1KWINSERT('amitshah', 'H', 2) ;
CALL STP_STAG23_MICRO('amitshah', 'H') ;

-- CALL STP_STAG23_1KWINSERT('amitshah', 'L', 3) ;
CALL STP_STAG23_MICRO('amitshah', 'L') ;


-- CALL STP_STAG23_1KWINSERT('parrikar', 'H', 2) ;
CALL STP_STAG23_MICRO('parrikar', 'H') ;

-- CALL STP_STAG23_1KWINSERT('parrikar', 'L', 3) ;
CALL STP_STAG23_MICRO('parrikar', 'L') ;


-- CALL STP_STAG23_1KWINSERT('smriti', 'H', 2) ;
CALL STP_STAG23_MICRO('smriti', 'H') ;

-- CALL STP_STAG23_1KWINSERT('smriti', 'L', 3) ;
CALL STP_STAG23_MICRO('smriti', 'L') ;


-- CALL STP_STAG23_1KWINSERT('arnab', 'H', 2) ;
CALL STP_STAG23_MICRO('arnab', 'H') ;

-- CALL STP_STAG23_1KWINSERT('arnab', 'L', 3) ;
CALL STP_STAG23_MICRO('arnab', 'L') ;


-- CALL STP_STAG23_1KWINSERT('fad', 'H', 2) ;
CALL STP_STAG23_MICRO('fad', 'H') ;

-- CALL STP_STAG23_1KWINSERT('fad', 'L', 3) ;
CALL STP_STAG23_MICRO('fad', 'L') ;

-- CALL STP_STAG23_1KWINSERT('yogi', 'H', 2) ;
CALL STP_STAG23_MICRO('yogi', 'H') ;

-- CALL STP_STAG23_1KWINSERT('yogi', 'L', 1) ;
CALL STP_STAG23_MICRO('yogi', 'L') ;

-- CALL STP_STAG23_1KWINSERT('jetley', 'H', 3) ;
CALL STP_STAG23_MICRO('jetley', 'H') ;

-- CALL STP_STAG23_1KWINSERT('jetley', 'L', 3) ;
CALL STP_STAG23_MICRO('jetley', 'L') ;

-- CALL STP_STAG23_1KWINSERT('swaraj', 'H', 3) ;
CALL STP_STAG23_MICRO('swaraj', 'H') ;

-- CALL STP_STAG23_1KWINSERT('swaraj', 'L', 3) ;
CALL STP_STAG23_MICRO('swaraj', 'L') ;


/* 05/26/2018 AST: adding below: After this proc is executed, the scrapes that were converted into posts
should be swept into the WSR_CONVERTED table 

And the scrapes that remained untagged (and specific to IND, OLITICS should be swept to WSR_UNTAGGED 
This kind of step should be taken at the end of each topic STP - but combo topics
such as trending + politics, celeb + media become an issue. We will deal with it later.
*/

INSERT INTO WSR_CONVERTED(SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE
, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE)
SELECT SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE
, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'IND' AND MOVED_TO_POST_FLAG = 'Y' ;

INSERT INTO OPN_WEB_LINKS(WEB_URL, URL_TITLE, URL_DESCRIPTION, IMAGE_URL, CREATION_DTM, CLEAN_FLAG)
SELECT NEWS_URL, IFNULL(NEWS_HEADLINE, NEWS_EXCERPT), IFNULL(NEWS_EXCERPT, NEWS_HEADLINE), NEWS_PIC_URL, NOW(), 'Y'
FROM WEB_SCRAPE_RAW WHERE NEWS_PIC_URL IS NOT NULL AND SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'IND' ;

SET POSTCOUNT = (SELECT COUNT(*) FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'IND' AND MOVED_TO_POST_FLAG = 'Y') ;

DELETE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'IND' AND MOVED_TO_POST_FLAG = 'Y' ;

/* 06/24/2023: AST: Introducing the STP_REMAINDER proc - instead of sweeping the untagged 
scrapes to WSR_UNTAGGED, they will be distributed among the BOTs that have received 
KWs in their carts recently. This will change the UNTAGGED calc - it will be the 
STP_REMAINDER count.

*/

SET UNTAGCOUNT = (SELECT COUNT(*) FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'IND' AND MOVED_TO_POST_FLAG = 'N') ;

CALL STP_REMAINDER('POLITICS', 1, 'IND') ;

INSERT INTO WSR_CONVERTED(STP_PROCESS, SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE)
SELECT 'STP_REMAINDER', SCRAPE_TOPIC, SCRAPE_SOURCE,  SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC IN ('POLITICS') AND COUNTRY_CODE = 'IND'   AND MOVED_TO_POST_FLAG = 'Y' ;

DELETE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'IND' AND MOVED_TO_POST_FLAG = 'Y' ;  

INSERT INTO OPN_STP_LOG(PROC_NAME, STP_TOPIC, STP_COUNTRY_CODE, POST_COUNT, UNTAG_COUNT, STP_PROC_DTM)
VALUES('STP_GRAND_T9IND', 'TRENDING', 'IND', POSTCOUNT, UNTAGCOUNT, NOW()) ;

INSERT INTO OPN_STP_LOG(PROC_NAME, STP_TOPIC, STP_COUNTRY_CODE, POST_COUNT, UNTAG_COUNT, STP_PROC_DTM)
VALUES('STP_GRAND_T1IND', 'POLITICS', 'IND', POSTCOUNT, UNTAGCOUNT, NOW()) ;
  
  
END

; //
 DELIMITER ;
 
 -- 