
-- 

DELIMITER //
DROP PROCEDURE IF EXISTS STP_GRAND_IND //
CREATE PROCEDURE STP_GRAND_IND()
THISPROC: BEGIN

/* 
08/24/2018 AST: changed the order to do all the IND dedupes first - otherwise we were getting tons of dupes due to mismatch of the topic order

04/04/2019 AST: Added OPINDIA sources to dedupe list

12/13/2020 AST: Removed the DEDUPE calls because the STP_MONITOR calls the WSR_DEDUPE_ALL 

*/

SET SQL_SAFE_UPDATES = 0;

-- CALL WSR_DEDUPE('ET/BIZ') ;


DELETE FROM WEB_SCRAPE_RAW WHERE UPPER(NEWS_URL) LIKE '%MARKETS/STOCKS%'  AND SCRAPE_SOURCE = 'ET/BIZ';

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 = 'INDSPORTS' WHERE SCRAPE_SOURCE = 'ET/BIZ'
AND UPPER(NEWS_URL) LIKE '%NEWS/SPORTS%' ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 = 'POLITICS' WHERE SCRAPE_SOURCE = 'ET/BIZ'
AND UPPER(NEWS_URL) LIKE '%NEWS/POLITICS%' ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 = 'INDBIZ' , SCRAPE_TAG2 = 'INDBIZ' , SCRAPE_TAG3 = 'INDBIZ' 
WHERE SCRAPE_SOURCE = 'ET/BIZ' AND SCRAPE_TAG1 = 'BUSINESS';

/*
CALL WSR_DEDUPE('DP/POLITICS') ;
CALL WSR_DEDUPE('IE/POLITICS') ;
CALL WSR_DEDUPE('REDIFF/POL') ; 

CALL WSR_DEDUPE('OPINDIA/MEDIA') ;
CALL WSR_DEDUPE('OPINDIA/OPED') ;
CALL WSR_DEDUPE('OPINDIA/POL') ; 
*/

CALL STP_GRAND_T9IND() ;
DELETE FROM OPN_POSTS WHERE POST_CONTENT IS NULL;

CALL STP_GRAND_T1IND() ;
DELETE FROM OPN_POSTS WHERE POST_CONTENT IS NULL;

/*
CALL WSR_DEDUPE('IE/ENT') ;
CALL WSR_DEDUPE('REDIFF/ENT') ;
CALL WSR_DEDUPE('TOI/ENT') ;
*/

CALL STP_GRAND_T10IND() ;
DELETE FROM OPN_POSTS WHERE POST_CONTENT IS NULL;

CALL STP_GRAND_T5IND() ;
DELETE FROM OPN_POSTS WHERE POST_CONTENT IS NULL;

-- CALL WSR_DEDUPE('DP/BIZ') ;


CALL STP_GRAND_T4IND() ;
DELETE FROM OPN_POSTS WHERE POST_CONTENT IS NULL;

-- CALL WSR_DEDUPE('IE/SPORTS') ;
-- CALL WSR_DEDUPE('DP/SPORT') ;

CALL STP_GRAND_T2IND() ;
DELETE FROM OPN_POSTS WHERE LENGTH(POST_CONTENT) < 4 ;


  
  
  
END; //
 DELIMITER ;
 
 -- 