
-- 

DELIMITER //
DROP PROCEDURE IF EXISTS STP_GRAND_T2MLBUSA_HL //
CREATE PROCEDURE STP_GRAND_T2MLBUSA_HL()
THISPROC: BEGIN

/*

    07/19/2020 AST: ADDED TAG_DONE_FLAG = 'Y' AFTER UPDATE
    10/04/2020 AST: adding filter to XYZNEWS to avoid: old news, stock market update, SHOPPING ADS ETC.

*/

DECLARE POSTCOUNT, UNTAGCOUNT INT ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'orioles'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%orioles%' OR NEWS_HEADLINE LIKE  '-orioles%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'orioles'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%orioles%' OR NEWS_HEADLINE LIKE  '-orioles%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'red-sox'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%red%sox%' OR NEWS_HEADLINE LIKE  '-red-sox%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'red-sox'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%red%sox%' OR NEWS_HEADLINE LIKE  '-red-sox%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'yankees'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%yankees%' OR NEWS_HEADLINE LIKE  '-yankees%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'yankees'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%yankees%' OR NEWS_HEADLINE LIKE  '-yankees%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'rays'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%rays%' OR NEWS_HEADLINE LIKE  '-rays%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'rays'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%rays%' OR NEWS_HEADLINE LIKE  '-rays%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'jays'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%jays%' OR NEWS_HEADLINE LIKE  '-jays%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'jays'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%jays%' OR NEWS_HEADLINE LIKE  '-jays%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'white-sox'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%white%sox%' OR NEWS_HEADLINE LIKE  '-white-sox%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'white-sox'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%white%sox%' OR NEWS_HEADLINE LIKE  '-white-sox%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'indians'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%indians%' OR NEWS_HEADLINE LIKE  '-indians%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'indians'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%indians%' OR NEWS_HEADLINE LIKE  '-indians%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'tigers'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%tigers%' OR NEWS_HEADLINE LIKE  '-tigers%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'tigers'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%tigers%' OR NEWS_HEADLINE LIKE  '-tigers%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'royals'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%royals%' OR NEWS_HEADLINE LIKE  '-royals%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'royals'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%royals%' OR NEWS_HEADLINE LIKE  '-royals%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'twins'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%twins%' OR NEWS_HEADLINE LIKE  '-twins%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'twins'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%twins%' OR NEWS_HEADLINE LIKE  '-twins%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'astros'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%astros%' OR NEWS_HEADLINE LIKE  '-astros%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'astros'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%astros%' OR NEWS_HEADLINE LIKE  '-astros%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'angels'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%angels%' OR NEWS_HEADLINE LIKE  '-angels%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'angels'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%angels%' OR NEWS_HEADLINE LIKE  '-angels%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'athletics'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%athletics%' OR NEWS_HEADLINE LIKE  '-athletics%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'athletics'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%athletics%' OR NEWS_HEADLINE LIKE  '-athletics%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'mariners'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%mariners%' OR NEWS_HEADLINE LIKE  '-mariners%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'mariners'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%mariners%' OR NEWS_HEADLINE LIKE  '-mariners%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'rangers'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%rangers%' OR NEWS_HEADLINE LIKE  '-rangers%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'rangers'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%rangers%' OR NEWS_HEADLINE LIKE  '-rangers%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;


UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'braves'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%braves%' OR NEWS_HEADLINE LIKE  '-braves%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'braves'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%braves%' OR NEWS_HEADLINE LIKE  '-braves%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'marlins'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%marlins%' OR NEWS_HEADLINE LIKE  '-marlins%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'marlins'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%marlins%' OR NEWS_HEADLINE LIKE  '-marlins%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'mets'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%mets%' OR NEWS_HEADLINE LIKE  '-mets%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'mets'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%mets%' OR NEWS_HEADLINE LIKE  '-mets%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'phillies'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%phillies%' OR NEWS_HEADLINE LIKE  '-phillies%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'phillies'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%phillies%' OR NEWS_HEADLINE LIKE  '-phillies%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'nationals'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%nationals%' OR NEWS_HEADLINE LIKE  '-nationals%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'nationals'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%nationals%' OR NEWS_HEADLINE LIKE  '-nationals%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'cubs'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%cubs%' OR NEWS_HEADLINE LIKE  '-cubs%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'cubs'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%cubs%' OR NEWS_HEADLINE LIKE  '-cubs%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'reds'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%reds%' OR NEWS_HEADLINE LIKE  '-reds%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'reds'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%reds%' OR NEWS_HEADLINE LIKE  '-reds%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'brewers'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%brewers%' OR NEWS_HEADLINE LIKE  '-brewers%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'brewers'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%brewers%' OR NEWS_HEADLINE LIKE  '-brewers%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'pirates'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%pirates%' OR NEWS_HEADLINE LIKE  '-pirates%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'pirates'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%pirates%' OR NEWS_HEADLINE LIKE  '-pirates%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;


UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'mlbcardinals'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%cardinals%' OR NEWS_HEADLINE LIKE  '-cardinals%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'mlbcardinals'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%cardinals%' OR NEWS_HEADLINE LIKE  '-cardinals%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'diamondbacks'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%diamondbacks%' OR NEWS_HEADLINE LIKE  '-diamondbacks%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'diamondbacks'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%diamondbacks%' OR NEWS_HEADLINE LIKE  '-diamondbacks%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'rockies'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%rockies%' OR NEWS_HEADLINE LIKE  '-rockies%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'rockies'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%rockies%' OR NEWS_HEADLINE LIKE  '-rockies%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'dodgers'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%dodgers%' OR NEWS_HEADLINE LIKE  '-dodgers%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'dodgers'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%dodgers%' OR NEWS_HEADLINE LIKE  '-dodgers%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'padres'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%padres%' OR NEWS_HEADLINE LIKE  '-padres%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'padres'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%padres%' OR NEWS_HEADLINE LIKE  '-padres%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'sfgiants'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%giants%' ) AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'sfgiants'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%giants%' ) AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'fantasymlb'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%fantasy%' OR NEWS_HEADLINE LIKE  '-fantasy%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'fantasymlb'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%fantasy%' OR NEWS_HEADLINE LIKE  '-fantasy%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'MLB'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%MLB%' OR NEWS_HEADLINE LIKE  '-MLB%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'MLB'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE  '%MLB%' OR NEWS_HEADLINE LIKE  '-MLB%') AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB'     AND MOD(ROW_ID, 2) = 0 ;

/*  adding 15 POLNEWS SCRAPES FOR L AND  5 sportsnews2 SCRAPES FOR H  */

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'sportsnews2' , SCRAPE_TAG3 = 'L', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'USA' AND SCRAPE_TOPIC IN ('SPORTS') AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND DATE(NEWS_DTM_RAW) >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 50   ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'sportsnews2' , SCRAPE_TAG3 = 'H', TAG_DONE_FLAG = 'Y' 
WHERE  MOVED_TO_POST_FLAG = 'N' AND COUNTRY_CODE = 'USA' AND SCRAPE_TOPIC IN ('SPORTS') AND TAG_DONE_FLAG = 'N'
AND LENGTH(NEWS_DTM_RAW) > 2 AND DATE(NEWS_DTM_RAW) >= CURRENT_DATE() - INTERVAL 1 DAY
ORDER BY RAND() LIMIT 5   ;

/*  END OF adding 15 sportsnews2 SCRAPES FOR L AND  5 POLNEWS SCRAPES FOR H   */

/*	07/19/2020 AST: Added the TAG_DONE_FLAG = 'Y' to make it compatible with the new STP_STAG23_MICRO */

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y' WHERE SCRAPE_TAG3 IN ('L', 'H') ;

/* 	END OF 07/19/2020 AST ADDITION */

-- CALL STP_STAG23_1KWINSERT('fantasymlb', 'H', 5) ;
CALL STP_STAG23_MICRO('fantasymlb', 'H') ;

-- CALL STP_STAG23_1KWINSERT('fantasymlb', 'L', 5) ;
CALL STP_STAG23_MICRO('fantasymlb', 'L') ;


-- CALL STP_STAG23_1KWINSERT('MLB', 'H', 5) ;
CALL STP_STAG23_MICRO('MLB', 'H') ;

-- CALL STP_STAG23_1KWINSERT('MLB', 'L', 5) ;
CALL STP_STAG23_MICRO('MLB', 'L') ;

-- CALL STP_STAG23_1KWINSERT('sfgiants', 'H', 3) ;
CALL STP_STAG23_MICRO('sfgiants', 'H') ;

-- CALL STP_STAG23_1KWINSERT('sfgiants', 'L', 3) ;
CALL STP_STAG23_MICRO('sfgiants', 'L') ;

-- CALL STP_STAG23_1KWINSERT('orioles', 'H', 3) ;
CALL STP_STAG23_MICRO('orioles', 'H') ;

-- CALL STP_STAG23_1KWINSERT('orioles', 'L', 3) ;
CALL STP_STAG23_MICRO('orioles', 'L') ;

-- CALL STP_STAG23_1KWINSERT('jays', 'H', 3) ;
CALL STP_STAG23_MICRO('jays', 'H') ;

-- CALL STP_STAG23_1KWINSERT('jays', 'L', 3) ;
CALL STP_STAG23_MICRO('jays', 'L') ;

-- CALL STP_STAG23_1KWINSERT('red-sox', 'H', 3) ;
CALL STP_STAG23_MICRO('red-sox', 'H') ;

-- CALL STP_STAG23_1KWINSERT('red-sox', 'L', 3) ;
CALL STP_STAG23_MICRO('red-sox', 'L') ;

-- CALL STP_STAG23_1KWINSERT('braves', 'H', 3) ;
CALL STP_STAG23_MICRO('braves', 'H') ;

-- CALL STP_STAG23_1KWINSERT('braves', 'L', 3) ;
CALL STP_STAG23_MICRO('braves', 'L') ;

-- CALL STP_STAG23_1KWINSERT('pirates', 'H', 3) ;
CALL STP_STAG23_MICRO('pirates', 'H') ;

-- CALL STP_STAG23_1KWINSERT('pirates', 'L', 3) ;
CALL STP_STAG23_MICRO('pirates', 'L') ;

-- CALL STP_STAG23_1KWINSERT('yankees', 'H', 3) ;
CALL STP_STAG23_MICRO('yankees', 'H') ;

-- CALL STP_STAG23_1KWINSERT('yankees', 'L', 3) ;
CALL STP_STAG23_MICRO('yankees', 'L') ;

-- CALL STP_STAG23_1KWINSERT('rangers', 'H', 3) ;
CALL STP_STAG23_MICRO('rangers', 'H') ;

-- CALL STP_STAG23_1KWINSERT('rangers', 'L', 3) ;
CALL STP_STAG23_MICRO('rangers', 'L') ;

-- CALL STP_STAG23_1KWINSERT('dodgers', 'H', 3) ;
CALL STP_STAG23_MICRO('dodgers', 'H') ;

-- CALL STP_STAG23_1KWINSERT('dodgers', 'L', 3) ;
CALL STP_STAG23_MICRO('dodgers', 'L') ;


-- CALL STP_STAG23_1KWINSERT('rockies', 'H', 3) ;
CALL STP_STAG23_MICRO('rockies', 'H') ;

-- CALL STP_STAG23_1KWINSERT('rockies', 'L', 3) ;
CALL STP_STAG23_MICRO('rockies', 'L') ;

-- CALL STP_STAG23_1KWINSERT('mlbcardinals', 'H', 3) ;
CALL STP_STAG23_MICRO('mlbcardinals', 'H') ;

-- CALL STP_STAG23_1KWINSERT('mlbcardinals', 'L', 3) ;
CALL STP_STAG23_MICRO('mlbcardinals', 'L') ;

-- CALL STP_STAG23_1KWINSERT('royals', 'H', 3) ;
CALL STP_STAG23_MICRO('royals', 'H') ;

-- CALL STP_STAG23_1KWINSERT('royals', 'L', 3) ;
CALL STP_STAG23_MICRO('royals', 'L') ;

-- CALL STP_STAG23_1KWINSERT('nationals', 'H', 3) ;
CALL STP_STAG23_MICRO('nationals', 'H') ;

-- CALL STP_STAG23_1KWINSERT('nationals', 'L', 3) ;
CALL STP_STAG23_MICRO('nationals', 'L') ;

-- CALL STP_STAG23_1KWINSERT('marlins', 'H', 3) ;
CALL STP_STAG23_MICRO('marlins', 'H') ;

-- CALL STP_STAG23_1KWINSERT('marlins', 'L', 3) ;
CALL STP_STAG23_MICRO('marlins', 'L') ;

-- CALL STP_STAG23_1KWINSERT('reds', 'H', 3) ;
CALL STP_STAG23_MICRO('reds', 'H') ;

-- CALL STP_STAG23_1KWINSERT('reds', 'L', 3) ;
CALL STP_STAG23_MICRO('reds', 'L') ;

-- CALL STP_STAG23_1KWINSERT('angels', 'H', 3) ;
CALL STP_STAG23_MICRO('angels', 'H') ;

-- CALL STP_STAG23_1KWINSERT('angels', 'L', 3) ;
CALL STP_STAG23_MICRO('angels', 'L') ;

-- CALL STP_STAG23_1KWINSERT('cubs', 'H', 3) ;
CALL STP_STAG23_MICRO('cubs', 'H') ;

-- CALL STP_STAG23_1KWINSERT('cubs', 'L', 3) ;
CALL STP_STAG23_MICRO('cubs', 'L') ;

-- CALL STP_STAG23_1KWINSERT('twins', 'H', 3) ;
CALL STP_STAG23_MICRO('twins', 'H') ;

-- CALL STP_STAG23_1KWINSERT('twins', 'L', 3) ;
CALL STP_STAG23_MICRO('twins', 'L') ;

-- CALL STP_STAG23_1KWINSERT('phillies', 'H', 3) ;
CALL STP_STAG23_MICRO('phillies', 'H') ;

-- CALL STP_STAG23_1KWINSERT('phillies', 'L', 3) ;
CALL STP_STAG23_MICRO('phillies', 'L') ;

-- CALL STP_STAG23_1KWINSERT('white-sox', 'H', 3) ;
CALL STP_STAG23_MICRO('white-sox', 'H') ;

-- CALL STP_STAG23_1KWINSERT('white-sox', 'L', 3) ;
CALL STP_STAG23_MICRO('white-sox', 'L') ;

-- CALL STP_STAG23_1KWINSERT('indians', 'H', 3) ;
CALL STP_STAG23_MICRO('indians', 'H') ;

-- CALL STP_STAG23_1KWINSERT('indians', 'L', 3) ;
CALL STP_STAG23_MICRO('indians', 'L') ;

-- CALL STP_STAG23_1KWINSERT('athletics', 'H', 3) ;
CALL STP_STAG23_MICRO('athletics', 'H') ;

-- CALL STP_STAG23_1KWINSERT('athletics', 'L', 3) ;
CALL STP_STAG23_MICRO('athletics', 'L') ;

-- CALL STP_STAG23_1KWINSERT('mets', 'H', 3) ;
CALL STP_STAG23_MICRO('mets', 'H') ;

-- CALL STP_STAG23_1KWINSERT('mets', 'L', 3) ;
CALL STP_STAG23_MICRO('mets', 'L') ;

-- CALL STP_STAG23_1KWINSERT('diamondbacks', 'H', 3) ;
CALL STP_STAG23_MICRO('diamondbacks', 'H') ;

-- CALL STP_STAG23_1KWINSERT('diamondbacks', 'L', 3) ;
CALL STP_STAG23_MICRO('diamondbacks', 'L') ;

-- CALL STP_STAG23_1KWINSERT('padres', 'H', 3) ;
CALL STP_STAG23_MICRO('padres', 'H') ;

-- CALL STP_STAG23_1KWINSERT('padres', 'L', 3) ;
CALL STP_STAG23_MICRO('padres', 'L') ;


-- CALL STP_STAG23_1KWINSERT('brewers', 'H', 3) ;
CALL STP_STAG23_MICRO('brewers', 'H') ;

-- CALL STP_STAG23_1KWINSERT('brewers', 'L', 3) ;
CALL STP_STAG23_MICRO('brewers', 'L') ;

-- CALL STP_STAG23_1KWINSERT('mariners', 'H', 3) ;
CALL STP_STAG23_MICRO('mariners', 'H') ;

-- CALL STP_STAG23_1KWINSERT('mariners', 'L', 3) ;
CALL STP_STAG23_MICRO('mariners', 'L') ;


-- CALL STP_STAG23_1KWINSERT('rays', 'H', 3) ;
CALL STP_STAG23_MICRO('rays', 'H') ;

-- CALL STP_STAG23_1KWINSERT('rays', 'L', 3) ;
CALL STP_STAG23_MICRO('rays', 'L') ;

-- CALL STP_STAG23_1KWINSERT('tigers', 'H', 3) ;
CALL STP_STAG23_MICRO('tigers', 'H') ;

-- CALL STP_STAG23_1KWINSERT('tigers', 'L', 3) ;
CALL STP_STAG23_MICRO('tigers', 'L') ;

-- CALL STP_STAG23_1KWINSERT('astros', 'H', 3) ;
CALL STP_STAG23_MICRO('astros', 'H') ;

-- CALL STP_STAG23_1KWINSERT('astros', 'L', 3) ;
CALL STP_STAG23_MICRO('astros', 'L') ;

/*  Completing the sportsnews2 addition with STp MICRo call  */

CALL STP_STAG23_MICRO('sportsnews2', 'H') ;

CALL STP_STAG23_MICRO('sportsnews2', 'L') ;

/*  END OF Completing the sportsnews2 addition with STp MICRo call  */

/* 05/26/2018 AST: adding below: After this proc is executed, the scrapes that were converted into posts
should be swept into the WSR_CONVERTED table 

And the scrapes that remained untagged (and specific to IND, OLITICS should be swept to WSR_UNTAGGED 
This kind of step should be taken at the end of each topic STP - but combo topics
such as trending + politics, celeb + media become an issue. We will deal with it later.
*/

INSERT INTO WSR_CONVERTED(SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE)
SELECT SCRAPE_TOPIC, SCRAPE_SOURCE,  SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC LIKE 'SPORT%' AND COUNTRY_CODE = 'USA'  AND SCRAPE_TAG1 = 'MLB' AND MOVED_TO_POST_FLAG = 'Y' ;

INSERT INTO OPN_WEB_LINKS(WEB_URL, URL_TITLE, URL_DESCRIPTION, IMAGE_URL, CREATION_DTM, CLEAN_FLAG)
SELECT NEWS_URL, IFNULL(NEWS_HEADLINE, NEWS_EXCERPT), IFNULL(NEWS_EXCERPT, NEWS_HEADLINE), NEWS_PIC_URL, NOW(), 'Y'
FROM WEB_SCRAPE_RAW WHERE NEWS_PIC_URL IS NOT NULL AND SCRAPE_TOPIC LIKE 'SPORT%' AND COUNTRY_CODE = 'USA'  AND SCRAPE_TAG1 = 'MLB' ;

SET POSTCOUNT = (SELECT COUNT(*) FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC LIKE 'SPORT%' AND COUNTRY_CODE = 'USA'  AND SCRAPE_TAG1 = 'MLB' AND MOVED_TO_POST_FLAG = 'Y') ;

DELETE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC LIKE 'SPORT%' AND COUNTRY_CODE = 'USA'  AND SCRAPE_TAG1 = 'MLB' AND MOVED_TO_POST_FLAG = 'Y' ;


INSERT INTO WSR_UNTAGGED(SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE)
SELECT SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC LIKE 'SPORT%' AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB' AND MOVED_TO_POST_FLAG = 'N' ;

SET UNTAGCOUNT = (SELECT COUNT(*) FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC LIKE 'SPORT%' AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB' AND MOVED_TO_POST_FLAG = 'N') ;

DELETE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC LIKE 'SPORT%' AND COUNTRY_CODE = 'USA' AND SCRAPE_TAG1 = 'MLB' AND MOVED_TO_POST_FLAG = 'N' ;  

INSERT INTO OPN_STP_LOG(PROC_NAME, STP_TOPIC, STP_COUNTRY_CODE, POST_COUNT, UNTAG_COUNT, STP_PROC_DTM)
VALUES('STP_GRAND_T2MLBUSA_HL', 'SPORT', 'USA', POSTCOUNT, UNTAGCOUNT, NOW()) ;

/* End of STP logging */


  
  
END; //
 DELIMITER ;
 
 -- 