-- STP_MONITOR

-- 

 DELIMITER //
DROP PROCEDURE IF EXISTS STP_MONITOR //
CREATE PROCEDURE STP_MONITOR(WSR_FILE VARCHAR(300))
THISPROC: BEGIN

/* 
10/07/2024 AST: Rebuilding this - to use only the STP_REMAINDER and STP_REMAINDER_NONXYZ procs
*/

DECLARE RAW_SCRCOUNT, BOTCOUNT, FORSTP_COUNT, FORSTPXYZ_COUNT INT ;

CALL WSR_DATE_MGMT() ;

CALL WSRL_DEDUPE_ALL() ;

CALL STD_MANAGER(1, 'GGG', 'POLITICS') ;
CALL STD_MANAGER(1, 'IND', 'POLITICS') ;
CALL STD_MANAGER(1, 'USA', 'POLITICS') ;
CALL STD_MANAGER(2, 'GGG', 'SPORTS') ;
CALL STD_MANAGER(2, 'IND', 'SPORTS') ;
CALL STD_MANAGER(2, 'USA', 'SPORTS') ;
CALL STD_MANAGER(3, 'GGG', 'SCIENCE') ;
CALL STD_MANAGER(4, 'GGG', 'BUSINESS') ;
CALL STD_MANAGER(4, 'IND', 'BUSINESS') ;
CALL STD_MANAGER(4, 'USA', 'BUSINESS') ;
CALL STD_MANAGER(5, 'IND', 'ENT') ;
CALL STD_MANAGER(5, 'USA', 'ENT') ;
CALL STD_MANAGER(10, 'USA', 'CELEB') ;

CALL WSR_DEDUPE_ALL() ;

/* At the end of each STD_MANAGER, the remaining scrapes are swept into WSR. We start from there. */

-- TID/CCODE = 1/USA

SET RAW_SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'USA') ;
SET BOTCOUNT = (SELECT COUNT(1) FROM OPN_XYZNEWS_BOTS WHERE TOPICID  = 1 AND CCODE = 'USA') ;
IF RAW_SCRCOUNT > BOTCOUNT 
THEN SET FORSTPXYZ_COUNT = RAW_SCRCOUNT - BOTCOUNT , FORSTP_COUNT = RAW_SCRCOUNT - FORSTPXYZ_COUNT ;
CALL STP_REMAINDER('POLITICS', 1, 105087, 'USA', 3, FORSTPXYZ_COUNT) ;
CALL STP_REMAINDER_NONXYZ('POLITICS', 1, 105087, 'USA', 3, FORSTP_COUNT) ;
ELSE SET FORSTPXYZ_COUNT = RAW_SCRCOUNT, FORSTP_COUNT = 0 ;
CALL STP_REMAINDER('POLITICS', 1, 105087, 'USA', 3, FORSTPXYZ_COUNT) ;
END IF ;



END //
DELIMITER ;

-- 