
-- 

DELIMITER //
DROP PROCEDURE IF EXISTS STP_GRAND_T9IND //
CREATE PROCEDURE STP_GRAND_T9IND()
THISPROC: BEGIN

/* 

07/19/2020 AST: ADDED TAG_DONE_FLAG = 'Y' AFTER UPDATE

*/
  
-- 

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'hpguj'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%HIMACHAL%'     
OR UPPER(NEWS_URL) LIKE     '%GUJARAT%' OR UPPER(NEWS_URL) LIKE     '%BJP%WIN%') AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'hpguj'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%HIMACHAL%'     
OR UPPER(NEWS_URL) LIKE     '%GUJARAT%' OR UPPER(NEWS_URL) LIKE     '%BJP%WIN%') AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'        AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'pawarmh'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%PAWAR%'     
OR UPPER(NEWS_URL) LIKE     '%RASHTRAVADI%' OR UPPER(NEWS_URL) LIKE     '%RCP%') AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'       AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'pawarmh'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%PAWAR%'     
OR UPPER(NEWS_URL) LIKE     '%RASHTRAVADI%' OR UPPER(NEWS_URL) LIKE     '%RCP%')  AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'judges'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%JUDGES%'     
OR UPPER(NEWS_URL) LIKE     '%SUPREME%COURT%' )  AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'judges'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%JUDGES%'     
OR UPPER(NEWS_URL) LIKE     '%SUPREME%COURT%' )  AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'budget'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%BUDGET%'     
OR UPPER(NEWS_URL) LIKE     '%JAITLEY%' )  AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'budget'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%BUDGET%'     
OR UPPER(NEWS_URL) LIKE     '%JAITLEY%' )   AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'naidu'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%V%NAIDU%'     
OR UPPER(NEWS_URL) LIKE     '%VICE%PRESI%' OR UPPER(NEWS_URL) LIKE     '%VP%')  AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'naidu'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%V%NAIDU%'     
OR UPPER(NEWS_URL) LIKE     '%VICE%PRESI%' OR UPPER(NEWS_URL) LIKE     '%VP%')  AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'padmaa'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%PADMAAVAT%'     
OR UPPER(NEWS_URL) LIKE     '%KARNI%SENA%' OR UPPER(NEWS_URL) LIKE     '%PADMA%VAT%')  AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'padmaa'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%PADMAAVAT%'     
OR UPPER(NEWS_URL) LIKE     '%KARNI%SENA%' OR UPPER(NEWS_URL) LIKE     '%PADMA%VAT%')  AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'raph'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%RAFAEL%'     
OR UPPER(NEWS_URL) LIKE     '%CORRUPTION%DEAL%' OR UPPER(NEWS_URL) LIKE     '%RAFALE%' )  AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'raph'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%RAFAEL%'     
OR UPPER(NEWS_URL) LIKE     '%CORRUPTION%DEAL%' OR UPPER(NEWS_URL) LIKE     '%RAFALE%')  AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'tiger'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%TIGER%'     
OR UPPER(NEWS_URL) LIKE     '%ZINDA%' )  AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'BOLLYWOOD'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'tiger'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%TIGER%'     
OR UPPER(NEWS_URL) LIKE     '%ZINDA%' )  AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'BOLLYWOOD'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'pad'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%PAD-MAN-%'     
OR UPPER(NEWS_URL) LIKE     '%-PAD-MAN%' OR UPPER(NEWS_URL) LIKE     '%PAD%MAN%')  AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'BOLLYWOOD'      AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'pad'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%PAD-MAN-%'     
OR UPPER(NEWS_URL) LIKE     '%-PAD-MAN%' OR UPPER(NEWS_URL) LIKE     '%PAD%MAN%')  AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'BOLLYWOOD'      AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'amujinnah'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%JINNA%'     
OR UPPER(NEWS_URL) LIKE     '%-AMU%' OR UPPER(NEWS_URL) LIKE     '%ALIGARH%'
OR UPPER(NEWS_URL) LIKE     '%AMU-%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'amujinnah'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%JINNA%'     
OR UPPER(NEWS_URL) LIKE     '%-AMU%' OR UPPER(NEWS_URL) LIKE     '%ALIGARH%'
OR UPPER(NEWS_URL) LIKE     '%AMU-%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'impeachcji'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%CJI%'     
OR UPPER(NEWS_URL) LIKE     '%IMPEACH%' OR UPPER(NEWS_URL) LIKE     '%DIPAK%MIS%%'
OR UPPER(NEWS_URL) LIKE     '%SUPRE%COURT%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'impeachcji'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%CJI%'     
OR UPPER(NEWS_URL) LIKE     '%IMPEACH%' OR UPPER(NEWS_URL) LIKE     '%DIPAK%MIS%%'
OR UPPER(NEWS_URL) LIKE     '%SUPRE%COURT%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'karnataka'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%KARNAT%'     
OR UPPER(NEWS_URL) LIKE     '%ASSEMBLY%' OR UPPER(NEWS_URL) LIKE     '%ELECTION%'
OR UPPER(NEWS_URL) LIKE     '%SIDDARA%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'karnataka'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%KARNAT%'     
OR UPPER(NEWS_URL) LIKE     '%ASSEMBLY%' OR UPPER(NEWS_URL) LIKE     '%ELECTION%'
OR UPPER(NEWS_URL) LIKE     '%SIDDARA%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'rapecult'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%KATHUA%'     
OR UPPER(NEWS_URL) LIKE     '%UNNAO%' OR UPPER(NEWS_URL) LIKE     '%RAPE%'
OR UPPER(NEWS_URL) LIKE     '%CULTU%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'rapecult'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%KATHUA%'     
OR UPPER(NEWS_URL) LIKE     '%UNNAO%' OR UPPER(NEWS_URL) LIKE     '%RAPE%'
OR UPPER(NEWS_URL) LIKE     '%CULTU%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'POLITICS'     AND MOD(ROW_ID, 2) = 0 ;

--
/*	07/19/2020 AST: Added the TAG_DONE_FLAG = 'Y' to make it compatible with the new STP_STAG23_MICRO */

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y' WHERE SCRAPE_TAG3 IN ('L', 'H') ;

/* 	END OF 07/19/2020 AST ADDITION */
--

-- CALL STP_STAG23_1KWINSERT('rapecult', 'H', 2) ;
CALL STP_STAG23_MICRO('rapecult', 'H') ;

-- CALL STP_STAG23_1KWINSERT('rapecult', 'L', 3) ;
CALL STP_STAG23_MICRO('rapecult', 'L') ;

-- CALL STP_STAG23_1KWINSERT('karnataka', 'H', 2) ;
CALL STP_STAG23_MICRO('karnataka', 'H') ;

-- CALL STP_STAG23_1KWINSERT('karnataka', 'L', 3) ;
CALL STP_STAG23_MICRO('karnataka', 'L') ;

-- CALL STP_STAG23_1KWINSERT('impeachcji', 'H', 2) ;
CALL STP_STAG23_MICRO('impeachcji', 'H') ;

-- CALL STP_STAG23_1KWINSERT('impeachcji', 'L', 3) ;
CALL STP_STAG23_MICRO('impeachcji', 'L') ;


-- CALL STP_STAG23_1KWINSERT('amujinnah', 'H', 2) ;
CALL STP_STAG23_MICRO('amujinnah', 'H') ;

-- CALL STP_STAG23_1KWINSERT('amujinnah', 'L', 3) ;
CALL STP_STAG23_MICRO('amujinnah', 'L') ;

-- CALL STP_STAG23_1KWINSERT('hpguj', 'H', 2) ;
CALL STP_STAG23_MICRO('hpguj', 'H') ;

-- CALL STP_STAG23_1KWINSERT('hpguj', 'L', 3) ;
CALL STP_STAG23_MICRO('hpguj', 'L') ;

-- CALL STP_STAG23_1KWINSERT('pawar', 'H', 2) ;
CALL STP_STAG23_MICRO('pawar', 'H') ;

-- CALL STP_STAG23_1KWINSERT('pawar', 'L', 1) ;
CALL STP_STAG23_MICRO('pawar', 'L') ;

-- CALL STP_STAG23_1KWINSERT('judges', 'H', 3) ;
CALL STP_STAG23_MICRO('judges', 'H') ;

-- CALL STP_STAG23_1KWINSERT('judges', 'L', 3) ;
CALL STP_STAG23_MICRO('judges', 'L') ;

-- CALL STP_STAG23_1KWINSERT('budget', 'H', 3) ;
CALL STP_STAG23_MICRO('budget', 'H') ;

-- CALL STP_STAG23_1KWINSERT('budget', 'L', 3) ;
CALL STP_STAG23_MICRO('budget', 'L') ;

-- CALL STP_STAG23_1KWINSERT('naidu', 'H', 3) ;
CALL STP_STAG23_MICRO('naidu', 'H') ;

-- CALL STP_STAG23_1KWINSERT('naidu', 'L', 3) ;
CALL STP_STAG23_MICRO('naidu', 'L') ;

-- CALL STP_STAG23_1KWINSERT('padmaa', 'H', 3) ;
CALL STP_STAG23_MICRO('padmaa', 'H') ;

-- CALL STP_STAG23_1KWINSERT('padmaa', 'L', 3) ;
CALL STP_STAG23_MICRO('padmaa', 'L') ;

-- CALL STP_STAG23_1KWINSERT('raph', 'H', 3) ;
CALL STP_STAG23_MICRO('raph', 'H') ;

-- CALL STP_STAG23_1KWINSERT('raph', 'L', 3) ;
CALL STP_STAG23_MICRO('raph', 'L') ;

-- CALL STP_STAG23_1KWINSERT('tiger', 'H', 3) ;
CALL STP_STAG23_MICRO('tiger', 'H') ;

-- CALL STP_STAG23_1KWINSERT('tiger', 'L', 3) ;
CALL STP_STAG23_MICRO('tiger', 'L') ;

-- CALL STP_STAG23_1KWINSERT('pad', 'H', 1) ;
CALL STP_STAG23_MICRO('pad', 'H') ;

-- CALL STP_STAG23_1KWINSERT('pad', 'L', 1) ;
CALL STP_STAG23_MICRO('pad', 'L') ;


  
  
  
END; //
 DELIMITER ;
 
 -- 