-- STP_MONITOR_REVAMP

-- 

 DELIMITER //
DROP PROCEDURE IF EXISTS STP_MONITOR_REVAMP //
CREATE PROCEDURE STP_MONITOR_REVAMP()
THISPROC: BEGIN

/* 
10/07/2024 AST: Rebuilding this - to use only the STP_REMAINDER and STP_REMAINDER_NONXYZ procs
*/

DECLARE RAW_SCRCOUNT, BOTCOUNT, FORSTP_COUNT, FORSTPXYZ_COUNT, ENTCELEBCOUNT, GENT, GCELEB, UENT, UCELEB, IENT, ICELEB, ECIND, ENTIND, CELEBIND INT ;

CALL WSR_DATE_MGMT() ;

CALL WSRL_DEDUPE_ALL() ;

CALL STD_MANAGER(1, 'GGG', 'POLITICS') ;
CALL STD_MANAGER(1, 'IND', 'POLITICS') ;
CALL STD_MANAGER(1, 'USA', 'POLITICS') ;
CALL STD_MANAGER(2, 'GGG', 'SPORTS') ;
CALL STD_MANAGER(2, 'IND', 'SPORTS') ;
CALL STD_MANAGER(2, 'USA', 'SPORTS') ;
CALL STD_MANAGER(3, 'GGG', 'SCIENCE') ;
CALL STD_MANAGER(4, 'GGG', 'BUSINESS') ;
CALL STD_MANAGER(4, 'IND', 'BUSINESS') ;
CALL STD_MANAGER(4, 'USA', 'BUSINESS') ;
CALL STD_MANAGER(5, 'IND', 'ENT') ;
CALL STD_MANAGER(5, 'USA', 'ENT') ;
CALL STD_MANAGER(10, 'USA', 'CELEB') ;

-- CALL WSR_DEDUPE_ALL() ;

/* At the end of each STD_MANAGER, the remaining scrapes are swept into WSR. We start from there. */

-- TID/CCODE = 1/USA

SET RAW_SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'USA') ;
SET BOTCOUNT = (SELECT COUNT(1) FROM OPN_XYZNEWS_BOTS WHERE TOPICID  = 1 AND CCODE = 'USA') ;
IF RAW_SCRCOUNT > BOTCOUNT 
THEN SET FORSTPXYZ_COUNT = RAW_SCRCOUNT - BOTCOUNT , FORSTP_COUNT = RAW_SCRCOUNT - FORSTPXYZ_COUNT ;
CALL STP_REMAINDER('POLITICS', 1, 105087, 'USA', 3, FORSTPXYZ_COUNT) ;
CALL STP_REMAINDER_NONXYZ('POLITICS', 1, 105087, 'USA', 3, FORSTP_COUNT) ;
ELSE SET FORSTPXYZ_COUNT = RAW_SCRCOUNT, FORSTP_COUNT = 0 ;
CALL STP_REMAINDER('POLITICS', 1, 105087, 'USA', 3, FORSTPXYZ_COUNT) ;
END IF ;

SET RAW_SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'IND') ;
SET BOTCOUNT = (SELECT COUNT(1) FROM OPN_XYZNEWS_BOTS WHERE TOPICID  = 1 AND CCODE = 'IND') ;
IF RAW_SCRCOUNT > BOTCOUNT 
THEN SET FORSTPXYZ_COUNT = RAW_SCRCOUNT - BOTCOUNT , FORSTP_COUNT = RAW_SCRCOUNT - FORSTPXYZ_COUNT ;
CALL STP_REMAINDER('POLITICS', 1, 105087, 'IND', 3, FORSTPXYZ_COUNT) ;
CALL STP_REMAINDER_NONXYZ('POLITICS', 1, 105087, 'IND', 3, FORSTP_COUNT) ;
ELSE SET FORSTPXYZ_COUNT = RAW_SCRCOUNT, FORSTP_COUNT = 0 ;
CALL STP_REMAINDER('POLITICS', 1, 105087, 'IND', 3, FORSTPXYZ_COUNT) ;
END IF ;

SET RAW_SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'GGG') ;
SET BOTCOUNT = (SELECT COUNT(1) FROM OPN_XYZNEWS_BOTS WHERE TOPICID  = 1 AND CCODE = 'GGG') ;
IF RAW_SCRCOUNT > BOTCOUNT 
THEN SET FORSTPXYZ_COUNT = RAW_SCRCOUNT - BOTCOUNT , FORSTP_COUNT = RAW_SCRCOUNT - FORSTPXYZ_COUNT ;
CALL STP_REMAINDER('POLITICS', 1, 105087, 'GGG', 3, FORSTPXYZ_COUNT) ;
CALL STP_REMAINDER_NONXYZ('POLITICS', 1, 105087, 'GGG', 3, FORSTP_COUNT) ;
ELSE SET FORSTPXYZ_COUNT = RAW_SCRCOUNT, FORSTP_COUNT = 0 ;
CALL STP_REMAINDER('POLITICS', 1, 105087, 'GGG', 3, FORSTPXYZ_COUNT) ;
END IF ;

SET RAW_SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW WHERE SCRAPE_TOPIC = 'SPORTS' AND COUNTRY_CODE = 'USA') ;
SET BOTCOUNT = (SELECT COUNT(1) FROM OPN_XYZNEWS_BOTS WHERE TOPICID  = 2 AND CCODE = 'USA') ;
IF RAW_SCRCOUNT > BOTCOUNT 
THEN SET FORSTPXYZ_COUNT = RAW_SCRCOUNT - BOTCOUNT , FORSTP_COUNT = RAW_SCRCOUNT - FORSTPXYZ_COUNT ;
CALL STP_REMAINDER('SPORTS', 2, 105654, 'USA', 3, FORSTPXYZ_COUNT) ;
CALL STP_REMAINDER_NONXYZ('SPORTS', 2, 105654, 'USA', 3, FORSTP_COUNT) ;
ELSE SET FORSTPXYZ_COUNT = RAW_SCRCOUNT, FORSTP_COUNT = 0 ;
CALL STP_REMAINDER('SPORTS', 2, 105654, 'USA', 3, FORSTPXYZ_COUNT) ;
END IF ;

SET RAW_SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW WHERE SCRAPE_TOPIC = 'SPORTS' AND COUNTRY_CODE = 'IND') ;
SET BOTCOUNT = (SELECT COUNT(1) FROM OPN_XYZNEWS_BOTS WHERE TOPICID  = 2 AND CCODE = 'IND') ;
IF RAW_SCRCOUNT > BOTCOUNT 
THEN SET FORSTPXYZ_COUNT = RAW_SCRCOUNT - BOTCOUNT , FORSTP_COUNT = RAW_SCRCOUNT - FORSTPXYZ_COUNT ;
CALL STP_REMAINDER('SPORTS', 2, 105654, 'IND', 3, FORSTPXYZ_COUNT) ;
CALL STP_REMAINDER_NONXYZ('SPORTS', 2, 105654, 'IND', 3, FORSTP_COUNT) ;
ELSE SET FORSTPXYZ_COUNT = RAW_SCRCOUNT, FORSTP_COUNT = 0 ;
CALL STP_REMAINDER('SPORTS', 2, 105654, 'IND', 3, FORSTPXYZ_COUNT) ;
END IF ;

SET RAW_SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW WHERE SCRAPE_TOPIC = 'SPORTS' AND COUNTRY_CODE = 'GGG') ;
SET BOTCOUNT = (SELECT COUNT(1) FROM OPN_XYZNEWS_BOTS WHERE TOPICID  = 2 AND CCODE = 'GGG') ;
IF RAW_SCRCOUNT > BOTCOUNT 
THEN SET FORSTPXYZ_COUNT = RAW_SCRCOUNT - BOTCOUNT , FORSTP_COUNT = RAW_SCRCOUNT - FORSTPXYZ_COUNT ;
CALL STP_REMAINDER('SPORTS', 2, 105654, 'GGG', 3, FORSTPXYZ_COUNT) ;
CALL STP_REMAINDER_NONXYZ('SPORTS', 2, 105654, 'GGG', 3, FORSTP_COUNT) ;
ELSE SET FORSTPXYZ_COUNT = RAW_SCRCOUNT, FORSTP_COUNT = 0 ;
CALL STP_REMAINDER('SPORTS', 2, 105654, 'GGG', 3, FORSTPXYZ_COUNT) ;
END IF ;

-- END OF SPORTS START OF SCIENCE

SET RAW_SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW WHERE SCRAPE_TOPIC = 'SCIENCE' AND COUNTRY_CODE = 'GGG') ;
SET BOTCOUNT = (SELECT COUNT(1) FROM OPN_XYZNEWS_BOTS WHERE TOPICID  = 3 AND CCODE = 'GGG') ;
IF RAW_SCRCOUNT > BOTCOUNT 
THEN SET FORSTPXYZ_COUNT = RAW_SCRCOUNT - BOTCOUNT , FORSTP_COUNT = RAW_SCRCOUNT - FORSTPXYZ_COUNT ;
CALL STP_REMAINDER('SCIENCE', 3, 105108, 'GGG', 3, FORSTPXYZ_COUNT) ;
CALL STP_REMAINDER_NONXYZ('SCIENCE', 3, 105108, 'GGG', 3, FORSTP_COUNT) ;
ELSE SET FORSTPXYZ_COUNT = RAW_SCRCOUNT, FORSTP_COUNT = 0 ;
CALL STP_REMAINDER('SCIENCE', 3, 105108, 'GGG', 3, FORSTPXYZ_COUNT) ;
END IF ;

-- END OF SCIENCE START OF BUSINESS

SET RAW_SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW WHERE SCRAPE_TOPIC = 'BUSINESS' AND COUNTRY_CODE = 'USA') ;
SET BOTCOUNT = (SELECT COUNT(1) FROM OPN_XYZNEWS_BOTS WHERE TOPICID  = 4 AND CCODE = 'USA') ;
IF RAW_SCRCOUNT > BOTCOUNT 
THEN SET FORSTPXYZ_COUNT = RAW_SCRCOUNT - BOTCOUNT , FORSTP_COUNT = RAW_SCRCOUNT - FORSTPXYZ_COUNT ;
CALL STP_REMAINDER('BUSINESS', 4, 105653, 'USA', 3, FORSTPXYZ_COUNT) ;
CALL STP_REMAINDER_NONXYZ('BUSINESS', 4, 105653, 'USA', 3, FORSTP_COUNT) ;
ELSE SET FORSTPXYZ_COUNT = RAW_SCRCOUNT, FORSTP_COUNT = 0 ;
CALL STP_REMAINDER('BUSINESS', 4, 105653, 'USA', 3, FORSTPXYZ_COUNT) ;
END IF ;

SET RAW_SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW WHERE SCRAPE_TOPIC = 'BUSINESS' AND COUNTRY_CODE = 'IND') ;
SET BOTCOUNT = (SELECT COUNT(1) FROM OPN_XYZNEWS_BOTS WHERE TOPICID  = 4 AND CCODE = 'IND') ;
IF RAW_SCRCOUNT > BOTCOUNT 
THEN SET FORSTPXYZ_COUNT = RAW_SCRCOUNT - BOTCOUNT , FORSTP_COUNT = RAW_SCRCOUNT - FORSTPXYZ_COUNT ;
CALL STP_REMAINDER('BUSINESS', 4, 105653, 'IND', 3, FORSTPXYZ_COUNT) ;
CALL STP_REMAINDER_NONXYZ('BUSINESS', 4, 105653, 'IND', 3, FORSTP_COUNT) ;
ELSE SET FORSTPXYZ_COUNT = RAW_SCRCOUNT, FORSTP_COUNT = 0 ;
CALL STP_REMAINDER('BUSINESS', 4, 105653, 'IND', 3, FORSTPXYZ_COUNT) ;
END IF ;

SET RAW_SCRCOUNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW WHERE SCRAPE_TOPIC = 'BUSINESS' AND COUNTRY_CODE = 'GGG') ;
SET BOTCOUNT = (SELECT COUNT(1) FROM OPN_XYZNEWS_BOTS WHERE TOPICID  = 4 AND CCODE = 'GGG') ;
IF RAW_SCRCOUNT > BOTCOUNT 
THEN SET FORSTPXYZ_COUNT = RAW_SCRCOUNT - BOTCOUNT , FORSTP_COUNT = RAW_SCRCOUNT - FORSTPXYZ_COUNT ;
CALL STP_REMAINDER('BUSINESS', 4, 105653, 'GGG', 3, FORSTPXYZ_COUNT) ;
CALL STP_REMAINDER_NONXYZ('BUSINESS', 4, 105653, 'GGG', 3, FORSTP_COUNT) ;
ELSE SET FORSTPXYZ_COUNT = RAW_SCRCOUNT, FORSTP_COUNT = 0 ;
CALL STP_REMAINDER('BUSINESS', 4, 105653, 'GGG', 3, FORSTPXYZ_COUNT) ;
END IF ;

-- END OF BUSINESS - START OF ENT/CELEB USA/GGG

SET ENTCELEBCOUNT = (SELECT  COUNT(1) FROM WEB_SCRAPE_RAW WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'USA') ;

CASE WHEN ENTCELEBCOUNT > 20 THEN
SET GENT = ENTCELEBCOUNT DIV 5, GCELEB = ENTCELEBCOUNT DIV 5, UENT = ENTCELEBCOUNT DIV 4, UCELEB = (ENTCELEBCOUNT - GENT - GCELEB - UENT) ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TOPIC = 'ENTCELEB' WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'USA' ;
UPDATE WEB_SCRAPE_RAW SET SCRAPE_TOPIC = 'ENT', COUNTRY_CODE = 'GGG' WHERE SCRAPE_TOPIC IN ('ENTCELEB') AND COUNTRY_CODE = 'USA' 
ORDER BY RAND() LIMIT GENT ;
UPDATE WEB_SCRAPE_RAW SET SCRAPE_TOPIC = 'CELEB', COUNTRY_CODE = 'GGG' WHERE SCRAPE_TOPIC IN ('ENTCELEB') AND COUNTRY_CODE = 'USA' 
ORDER BY RAND() LIMIT GCELEB ;
UPDATE WEB_SCRAPE_RAW SET SCRAPE_TOPIC = 'ENT' WHERE SCRAPE_TOPIC IN ('ENTCELEB') AND COUNTRY_CODE = 'USA' 
ORDER BY RAND() LIMIT UENT ;
UPDATE WEB_SCRAPE_RAW SET SCRAPE_TOPIC = 'CELEB' WHERE SCRAPE_TOPIC IN ('ENTCELEB') AND COUNTRY_CODE = 'USA' 
ORDER BY RAND() LIMIT UCELEB ;

CALL STP_REMAINDER('ENT', 5, 105655, 'GGG', 3, GENT) ;
CALL STP_REMAINDER('ENT', 5, 105655, 'USA', 3, UENT) ;
CALL STP_REMAINDER('CELEB', 10, 105089, 'GGG', 3, GCELEB) ;
CALL STP_REMAINDER('CELEB', 10, 105089, 'USA', 3, UCELEB) ;

WHEN ENTCELEBCOUNT <= 20 THEN
CALL STP_REMAINDER('ENT', 5, 105655, 'USA', 3, ENTCELEBCOUNT) ;

END CASE ;

-- END OF ENT/CELEB USA/GGG - START OF ENT/CELEB IND

SET ECIND = (SELECT  COUNT(1) FROM WEB_SCRAPE_RAW WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND') ;
SET ENTIND = ECIND DIV 2, CELEBIND = (ECIND - ENTIND) ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TOPIC = 'ENTCELEB' WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND' ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TOPIC = 'ENT' WHERE SCRAPE_TOPIC IN ('ENTCELEB') AND COUNTRY_CODE = 'USA' 
ORDER BY RAND() LIMIT ENTIND ;
UPDATE WEB_SCRAPE_RAW SET SCRAPE_TOPIC = 'CELEB' WHERE SCRAPE_TOPIC IN ('ENTCELEB') AND COUNTRY_CODE = 'USA' ;

CALL STP_REMAINDER('ENT', 5, 105655, 'IND', 3, ENTIND) ;
CALL STP_REMAINDER('CELEB', 10, 105089, 'IND', 3, CELEBIND) ;


END //
DELIMITER ;

-- 