
-- 

DELIMITER //
DROP PROCEDURE IF EXISTS STP_GRAND_T3 //
CREATE PROCEDURE STP_GRAND_T3()
THISPROC: BEGIN

/*

03/21/2019 ADDED THE SWEEP TO WSR_UNTAGGED AND WSR_CONVERTED

04/17/2019 AST: Added handling of SCIAM/CHEMISTRY source

04/19/2019 AST: Replaced AND UPPER(SCRAPE_TAG1) = UPPER('SCIENCE') AND UPPER(SCRAPE_TAG2) = UPPER('SCIENCE') 
with
 AND SCRAPE_TOPIC = 'SCIENCE'
 Also, Replaced COUNTRY_CODE = 'GGG' 
 WITH 1=1 (THIS IS because now any user with any country_code can create KWs. This interferes with STP.
 
 For ex. Black Hole Photographed KW is created by IND user. the STP was always looking for GGG and hence it did not tag 
 the relevant scrapes.
 
 04/24/2019 AST:  Added OR UPPER(NEWS_URL) LIKE  UPPER('%CRISPR%') to genetics
                  Added  OR UPPER(NEWS_URL) LIKE  UPPER('%neander%'), OR UPPER(NEWS_URL) LIKE  UPPER('%archeo%') to evolution
                  Added OR  UPPER(NEWS_URL) LIKE  UPPER('%conservation%') environment
                  
                  Added SET TAG_DONE_FLAG = 'Y', to UPDATE statement. This is done so that the untagged news items can be 
                  swept into tags for 'Science News', 'Technology News' etc.
                  
 04/27/2019 AST : Added UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'sciencenews3'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
                        TAG_DONE_FLAG = 'N' AND SCRAPE_SOURCE = 'Arstechnica/SCIENCE' AND NEWS_URL LIKE '%/SCIENCE/%' ;
                        
                    Added CALL STP_STAG23_MICRO('sciencenews3', 'L') ;
                    (these latest additions make it possible to distribute the science news to those that subscribe to the specific KW (Science News)
                    instead of randomly distributing it to all
                    
                    Same logic will be used for adding 'Technology News'
                    
07/11/2019 AST: Added handling of SCIAM/BIO source

09/19/2020 AST: Several Changes:
		1. Adding the NEWS_HEADLINE and NEWS_EXCERPT in the UPDATE
        2. Adding SCIENCENEWS3 for XYZNEWS handling
        
        09/20/2020 AST: Adding SCIENCENEWS3 for country_code IND and USA - ELSE IT WOULD NOT STP
        TO THE MAIN USERS

10/04/2020 AST: adding filter to XYZNEWS to avoid: old news, stock market update, SHOPPING ADS ETC.
 10/09/2020 AST: fixing the date issue in XYZNEWS  addition - also moving it to the front of the UPDATE
    10/10/2020 AST: removed the above - as a new proc was created for this purpose
    
    06/24/2023: AST: Introducing the STP_REMAINDER proc 
    
    05/18/2024 AST: Sinc eth current scrapers are mostly bringing URLs that have content in the NEWS_HEADLINE 
    OR NEWS_EXCERPT columns, we need to replace the current TAG scheme - replace the NEWS_URL with 
    these two columns

*/

DECLARE POSTCOUNT, UNTAGCOUNT INT ;


UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'physics'    , SCRAPE_TAG3 = 'H'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%physics%%') OR UPPER(NEWS_URL) 
LIKE  UPPER('%PARTICLE%%')  OR UPPER(NEWS_URL) LIKE  UPPER('%QUANTUM%%')
 OR UPPER(NEWS_URL) LIKE  UPPER('%PHYSICIS%%')  OR UPPER(NEWS_URL) LIKE  UPPER('%GRAVITY%%')  OR UPPER(NEWS_URL) LIKE  UPPER('%NEUTRIN%%') 
 OR UPPER(NEWS_URL) LIKE  UPPER('%ACCELERA%%')  OR UPPER(NEWS_URL) LIKE  UPPER('%HADRON%%')  OR UPPER(NEWS_URL) LIKE  UPPER('%CERN%%'))
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'physics'    , SCRAPE_TAG3 = 'L'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%physics%%') OR UPPER(NEWS_URL) 
LIKE  UPPER('%PARTICLE%%')  OR UPPER(NEWS_URL) LIKE  UPPER('%QUANTUM%%')
 OR UPPER(NEWS_URL) LIKE  UPPER('%PHYSICIS%%')  OR UPPER(NEWS_URL) LIKE  UPPER('%GRAVITY%%')  OR UPPER(NEWS_URL) LIKE  UPPER('%NEUTRIN%%') 
 OR UPPER(NEWS_URL) LIKE  UPPER('%ACCELERA%%')  OR UPPER(NEWS_URL) LIKE  UPPER('%HADRON%%')  OR UPPER(NEWS_URL) LIKE  UPPER('%CERN%%'))
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'chem'    , SCRAPE_TAG3 = 'H'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%chem%%') OR UPPER(NEWS_URL) LIKE  UPPER('%MATERIAL%') )
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'chem'    , SCRAPE_TAG3 = 'L'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%chem%%') OR UPPER(NEWS_URL) LIKE  UPPER('%MATERIAL%') )
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'chem'    , SCRAPE_TAG3 = 'L'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND 1=1  AND UPPER(SCRAPE_TAG1) = UPPER('CHEMISTRY') AND UPPER(SCRAPE_TAG2) = UPPER('CHEMISTRY');

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'math'    , SCRAPE_TAG3 = 'H'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%math%%') OR UPPER(NEWS_URL) LIKE  UPPER('%algo%') )
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'math'    , SCRAPE_TAG3 = 'L'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%math%%') OR UPPER(NEWS_URL) LIKE  UPPER('%algo%') )
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'bio'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%bio%chem%') OR UPPER(NEWS_URL) LIKE  UPPER('%biology%') OR  UPPER(NEWS_URL) LIKE  UPPER('%bio%chem%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%biology%') OR  UPPER(NEWS_URL) LIKE  UPPER('%insect%') OR  UPPER(NEWS_URL) LIKE  UPPER('%animal%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%fish%') OR  UPPER(NEWS_URL) LIKE  UPPER('%life%') OR  UPPER(NEWS_URL) LIKE  UPPER('%plant%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%tree%') OR  UPPER(NEWS_URL) LIKE  UPPER('%chimpa%') OR  UPPER(NEWS_URL) LIKE  UPPER('%monkey%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'bio'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%bio%chem%') OR UPPER(NEWS_URL) LIKE  UPPER('%biology%') OR  UPPER(NEWS_URL) LIKE  UPPER('%bio%chem%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%biology%') OR  UPPER(NEWS_URL) LIKE  UPPER('%insect%') OR  UPPER(NEWS_URL) LIKE  UPPER('%animal%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%fish%') OR  UPPER(NEWS_URL) LIKE  UPPER('%life%') OR  UPPER(NEWS_URL) LIKE  UPPER('%plant%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%tree%') OR  UPPER(NEWS_URL) LIKE  UPPER('%chimpa%') OR  UPPER(NEWS_URL) LIKE  UPPER('%monkey%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'engg'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%engineer%') OR UPPER(NEWS_URL) LIKE  UPPER('%techn%') OR  UPPER(NEWS_URL) LIKE  UPPER('%technolog%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%electronic%') OR  UPPER(NEWS_URL) LIKE  UPPER('%metallurg%') OR  UPPER(NEWS_URL) LIKE  UPPER('%mechanical%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'engg'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%engineer%') OR UPPER(NEWS_URL) LIKE  UPPER('%techn%') OR  UPPER(NEWS_URL) LIKE  UPPER('%technolog%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%electronic%') OR  UPPER(NEWS_URL) LIKE  UPPER('%metallurg%') OR  UPPER(NEWS_URL) LIKE  UPPER('%mechanical%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'compsci'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%comput%') OR UPPER(NEWS_URL) LIKE  UPPER('%microproc%') OR  UPPER(NEWS_URL) LIKE  UPPER('%big%data%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%byte%') OR  UPPER(NEWS_URL) LIKE  UPPER('%artif%intel%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'compsci'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%comput%') OR UPPER(NEWS_URL) LIKE  UPPER('%microproc%') OR  UPPER(NEWS_URL) LIKE  UPPER('%big%data%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%byte%') OR  UPPER(NEWS_URL) LIKE  UPPER('%artif%intel%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'genetics'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%genetic%') OR UPPER(NEWS_URL) LIKE  UPPER('%gene%') OR  UPPER(NEWS_URL) LIKE  UPPER('%genome%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%dna%') OR  UPPER(NEWS_URL) LIKE  UPPER('%chromoso%') OR  UPPER(NEWS_URL) LIKE  UPPER('%notype%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%CRISPR%')
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'genetics'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%genetic%') OR UPPER(NEWS_URL) LIKE  UPPER('%gene%') OR  UPPER(NEWS_URL) LIKE  UPPER('%genome%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%dna%') OR  UPPER(NEWS_URL) LIKE  UPPER('%chromoso%') OR  UPPER(NEWS_URL) LIKE  UPPER('%notype%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%CRISPR%')
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'med'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%medicin%') OR UPPER(NEWS_URL) LIKE  UPPER('%therapy%') OR  UPPER(NEWS_URL) LIKE  UPPER('%treatment%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%cure%') OR  UPPER(NEWS_URL) LIKE  UPPER('%disease%') OR  UPPER(NEWS_URL) LIKE  UPPER('%doctor%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%stem%cell%') OR  UPPER(NEWS_URL) LIKE  UPPER('%cancer%') OR  UPPER(NEWS_URL) LIKE  UPPER('%physician%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'med'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%medicin%') OR UPPER(NEWS_URL) LIKE  UPPER('%therapy%') OR  UPPER(NEWS_URL) LIKE  UPPER('%treatment%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%cure%') OR  UPPER(NEWS_URL) LIKE  UPPER('%disease%') OR  UPPER(NEWS_URL) LIKE  UPPER('%doctor%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%stem%cell%') OR  UPPER(NEWS_URL) LIKE  UPPER('%cancer%') OR  UPPER(NEWS_URL) LIKE  UPPER('%physician%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'evo'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%evolution%') OR UPPER(NEWS_URL) LIKE  UPPER('%darwin%') OR  UPPER(NEWS_URL) LIKE  UPPER('%fossil%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%saur%') OR  UPPER(NEWS_URL) LIKE  UPPER('%evolv%') OR UPPER(NEWS_URL) LIKE  UPPER('%neander%')
OR UPPER(NEWS_URL) LIKE  UPPER('%archeo%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'evo'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%evolution%') OR UPPER(NEWS_URL) LIKE  UPPER('%darwin%') OR  UPPER(NEWS_URL) LIKE  UPPER('%fossil%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%saur%') OR  UPPER(NEWS_URL) LIKE  UPPER('%evolv%') OR UPPER(NEWS_URL) LIKE  UPPER('%neander%')
OR UPPER(NEWS_URL) LIKE  UPPER('%archeo%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';


UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'robot'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%robot%') OR UPPER(NEWS_URL) LIKE  UPPER('%automat%') OR  UPPER(NEWS_URL) LIKE  UPPER('%self%drive%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'robot'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%robot%') OR UPPER(NEWS_URL) LIKE  UPPER('%automat%') OR  UPPER(NEWS_URL) LIKE  UPPER('%self%drive%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'sosci'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%social%') OR UPPER(NEWS_URL) LIKE  UPPER('%psych%') OR  UPPER(NEWS_URL) LIKE  UPPER('%sociolo%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%behavio%') OR UPPER(NEWS_URL) LIKE  UPPER('%communi%') OR  UPPER(NEWS_URL) LIKE  UPPER('%socie%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'sosci'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%social%') OR UPPER(NEWS_URL) LIKE  UPPER('%psych%') OR  UPPER(NEWS_URL) LIKE  UPPER('%sociolo%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%behavio%') OR UPPER(NEWS_URL) LIKE  UPPER('%communi%') OR  UPPER(NEWS_URL) LIKE  UPPER('%socie%')
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'env'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%environ%') OR UPPER(NEWS_URL) LIKE  UPPER('%climate%') OR  UPPER(NEWS_URL) LIKE  UPPER('%weather%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%storm%') OR UPPER(NEWS_URL) LIKE  UPPER('%warming%') OR  UPPER(NEWS_URL) LIKE  UPPER('%sierra%') 
OR  UPPER(NEWS_URL) LIKE  UPPER('%solar%') OR  UPPER(NEWS_URL) LIKE  UPPER('%energy%') OR  UPPER(NEWS_URL) LIKE  UPPER('%conservation%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'env'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%environ%') OR UPPER(NEWS_URL) LIKE  UPPER('%climate%') OR  UPPER(NEWS_URL) LIKE  UPPER('%weather%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%storm%') OR UPPER(NEWS_URL) LIKE  UPPER('%warming%') OR  UPPER(NEWS_URL) LIKE  UPPER('%sierra%') 
OR  UPPER(NEWS_URL) LIKE  UPPER('%solar%') OR  UPPER(NEWS_URL) LIKE  UPPER('%energy%') OR  UPPER(NEWS_URL) LIKE  UPPER('%conservation%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'space'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%space%') OR UPPER(NEWS_URL) LIKE  UPPER('%nasa%') OR  UPPER(NEWS_URL) LIKE  UPPER('%satelli%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%galax%') OR UPPER(NEWS_URL) LIKE  UPPER('%black%hole%') OR  UPPER(NEWS_URL) LIKE  UPPER('%mars%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%jupite%') OR UPPER(NEWS_URL) LIKE  UPPER('%saturn%') OR  UPPER(NEWS_URL) LIKE  UPPER('%venus%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%light%year%') OR UPPER(NEWS_URL) LIKE  UPPER('%planet%') OR  UPPER(NEWS_URL) LIKE  UPPER('%astrono%') 

)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'space'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_URL) LIKE  UPPER('%space%') OR UPPER(NEWS_URL) LIKE  UPPER('%nasa%') OR  UPPER(NEWS_URL) LIKE  UPPER('%satelli%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%galax%') OR UPPER(NEWS_URL) LIKE  UPPER('%black%hole%') OR  UPPER(NEWS_URL) LIKE  UPPER('%mars%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%jupite%') OR UPPER(NEWS_URL) LIKE  UPPER('%saturn%') OR  UPPER(NEWS_URL) LIKE  UPPER('%venus%') 
OR UPPER(NEWS_URL) LIKE  UPPER('%light%year%') OR UPPER(NEWS_URL) LIKE  UPPER('%planet%') OR  UPPER(NEWS_URL) LIKE  UPPER('%astrono%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'physics'    , SCRAPE_TAG3 = 'H'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_HEADLINE) LIKE  UPPER('%physics%%') OR UPPER(NEWS_HEADLINE) 
LIKE  UPPER('%PARTICLE%%')  OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%QUANTUM%%')
 OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%PHYSICIS%%')  OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%GRAVITY%%')  OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%NEUTRIN%%') 
 OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%ACCELERA%%')  OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%HADRON%%')  OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%CERN%%'))
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'physics'    , SCRAPE_TAG3 = 'L'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_HEADLINE) LIKE  UPPER('%physics%%') OR UPPER(NEWS_HEADLINE) 
LIKE  UPPER('%PARTICLE%%')  OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%QUANTUM%%')
 OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%PHYSICIS%%')  OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%GRAVITY%%')  OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%NEUTRIN%%') 
 OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%ACCELERA%%')  OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%HADRON%%')  OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%CERN%%'))
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'chem'    , SCRAPE_TAG3 = 'H'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_HEADLINE) LIKE  UPPER('%chem%%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%MATERIAL%') )
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'chem'    , SCRAPE_TAG3 = 'L'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_HEADLINE) LIKE  UPPER('%chem%%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%MATERIAL%') )
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'chem'    , SCRAPE_TAG3 = 'L'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND 1=1  AND UPPER(SCRAPE_TAG1) = UPPER('CHEMISTRY') AND UPPER(SCRAPE_TAG2) = UPPER('CHEMISTRY');

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'math'    , SCRAPE_TAG3 = 'H'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_HEADLINE) LIKE  UPPER('%math%%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%algo%') )
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'math'    , SCRAPE_TAG3 = 'L'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_HEADLINE) LIKE  UPPER('%math%%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%algo%') )
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'bio'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%bio%chem%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%biology%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%bio%chem%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%biology%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%insect%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%animal%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%fish%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%life%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%plant%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%tree%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%chimpa%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%monkey%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'bio'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%bio%chem%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%biology%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%bio%chem%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%biology%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%insect%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%animal%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%fish%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%life%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%plant%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%tree%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%chimpa%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%monkey%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'engg'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%engineer%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%techn%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%technolog%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%electronic%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%metallurg%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%mechanical%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'engg'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%engineer%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%techn%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%technolog%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%electronic%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%metallurg%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%mechanical%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'compsci'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%comput%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%microproc%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%big%data%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%byte%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%artif%intel%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'compsci'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%comput%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%microproc%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%big%data%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%byte%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%artif%intel%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'genetics'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%genetic%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%gene%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%genome%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%dna%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%chromoso%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%notype%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%CRISPR%')
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'genetics'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%genetic%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%gene%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%genome%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%dna%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%chromoso%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%notype%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%CRISPR%')
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'med'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%medicin%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%therapy%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%treatment%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%cure%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%disease%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%doctor%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%stem%cell%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%cancer%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%physician%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'med'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%medicin%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%therapy%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%treatment%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%cure%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%disease%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%doctor%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%stem%cell%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%cancer%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%physician%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'evo'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%evolution%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%darwin%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%fossil%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%saur%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%evolv%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%neander%')
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%archeo%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'evo'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%evolution%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%darwin%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%fossil%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%saur%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%evolv%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%neander%')
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%archeo%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';


UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'robot'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%robot%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%automat%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%self%drive%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'robot'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%robot%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%automat%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%self%drive%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'sosci'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%social%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%psych%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%sociolo%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%behavio%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%communi%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%socie%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'sosci'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%social%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%psych%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%sociolo%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%behavio%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%communi%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%socie%')
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'env'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%environ%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%climate%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%weather%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%storm%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%warming%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%sierra%') 
OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%solar%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%energy%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%conservation%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'env'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%environ%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%climate%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%weather%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%storm%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%warming%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%sierra%') 
OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%solar%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%energy%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%conservation%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'space'    , SCRAPE_TAG3 = 'H'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%space%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%nasa%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%satelli%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%galax%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%black%hole%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%mars%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%jupite%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%saturn%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%venus%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%light%year%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%planet%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%astrono%') 

)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE'  LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'space'    , SCRAPE_TAG3 = 'L'    WHERE  MOVED_TO_POST_FLAG = 'N' AND 
(UPPER(NEWS_HEADLINE) LIKE  UPPER('%space%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%nasa%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%satelli%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%galax%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%black%hole%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%mars%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%jupite%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%saturn%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%venus%') 
OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%light%year%') OR UPPER(NEWS_HEADLINE) LIKE  UPPER('%planet%') OR  UPPER(NEWS_HEADLINE) LIKE  UPPER('%astrono%') 
)
AND 1=1  AND SCRAPE_TOPIC = 'SCIENCE';

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'BIO'    , SCRAPE_TAG3 = 'L'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND 1=1  AND UPPER(SCRAPE_TAG1) = UPPER('BIOLOGY') AND UPPER(SCRAPE_TAG2) = UPPER('BIOLOGY');

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'EVO'    , SCRAPE_TAG3 = 'L'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND 1=1  AND UPPER(SCRAPE_TAG1) = UPPER('EVO') AND UPPER(SCRAPE_TAG2) = UPPER('EVO');

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'MATH'    , SCRAPE_TAG3 = 'L'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND 1=1  AND UPPER(SCRAPE_TAG1) = UPPER('MATH') AND UPPER(SCRAPE_TAG2) = UPPER('MATH');

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'SPACE'    , SCRAPE_TAG3 = 'L'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND 1=1  AND UPPER(SCRAPE_TAG1) = UPPER('SPACE') AND UPPER(SCRAPE_TAG2) = UPPER('SPACE');

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'MED'    , SCRAPE_TAG3 = 'L'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND 1=1  AND UPPER(SCRAPE_TAG1) = UPPER('MED') AND UPPER(SCRAPE_TAG2) = UPPER('MED');

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y', SCRAPE_TAG2 =     'biotech3'    , SCRAPE_TAG3 = 'L'    
WHERE  MOVED_TO_POST_FLAG = 'N' AND 1=1  AND UPPER(SCRAPE_TAG1) = UPPER('BIOTECH') AND UPPER(SCRAPE_TAG2) = UPPER('BIOTECH');


-- CALL STP_STAG23_1KWINSERT('space', 'H', 1) ;

-- CALL STP_STAG23_1KWINSERT('space', 'L', 3) ;
CALL STP_STAG23_MICRO('space', 'L') ;

-- CALL STP_STAG23_1KWINSERT('env', 'H', 1) ;

-- CALL STP_STAG23_1KWINSERT('env', 'L', 3) ;
CALL STP_STAG23_MICRO('env', 'L') ;

-- CALL STP_STAG23_1KWINSERT('sosci', 'H', 1) ;

-- CALL STP_STAG23_1KWINSERT('sosci', 'L', 3) ;
CALL STP_STAG23_MICRO('sosci', 'L') ;

-- CALL STP_STAG23_1KWINSERT('robot', 'H', 1) ;

-- CALL STP_STAG23_1KWINSERT('robot', 'L', 3) ;
CALL STP_STAG23_MICRO('robot', 'L') ;


-- CALL STP_STAG23_1KWINSERT('evo', 'H', 1) ;

-- CALL STP_STAG23_1KWINSERT('evo', 'L', 3) ;
CALL STP_STAG23_MICRO('evo', 'L') ;

-- CALL STP_STAG23_1KWINSERT('med', 'H', 1) ;

-- CALL STP_STAG23_1KWINSERT('med', 'L', 3) ;
CALL STP_STAG23_MICRO('med', 'L') ;

-- CALL STP_STAG23_1KWINSERT('genetics', 'H', 1) ;

-- CALL STP_STAG23_1KWINSERT('genetics', 'L', 3) ;
CALL STP_STAG23_MICRO('genetics', 'L') ;

-- CALL STP_STAG23_1KWINSERT('compsci', 'H', 1) ;

-- CALL STP_STAG23_1KWINSERT('compsci', 'L', 3) ;
CALL STP_STAG23_MICRO('compsci', 'L') ;

-- CALL STP_STAG23_1KWINSERT('engg', 'H', 1) ;

-- CALL STP_STAG23_1KWINSERT('engg', 'L', 2) ;
CALL STP_STAG23_MICRO('engg', 'L') ;

-- CALL STP_STAG23_1KWINSERT('bio', 'H', 3) ;

-- CALL STP_STAG23_1KWINSERT('bio', 'L', 6) ;
CALL STP_STAG23_MICRO('bio', 'L') ;

-- CALL STP_STAG23_1KWINSERT('math', 'H', 1) ;

-- CALL STP_STAG23_1KWINSERT('math', 'L', 2) ;
CALL STP_STAG23_MICRO('math', 'L') ;

-- CALL STP_STAG23_1KWINSERT('chem', 'H', 1) ;

-- CALL STP_STAG23_1KWINSERT('chem', 'L', 2) ;
CALL STP_STAG23_MICRO('chem', 'L') ;

-- CALL STP_STAG23_1KWINSERT('physics', 'H', 1) ;

-- CALL STP_STAG23_1KWINSERT('physics', 'L', 2) ;
CALL STP_STAG23_MICRO('physics', 'L') ;

CALL STP_STAG23_MICRO('biotech3', 'L') ;


INSERT INTO WSR_CONVERTED(SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE)
SELECT SCRAPE_TOPIC, SCRAPE_SOURCE,  SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC IN ('SCIENCE') AND 1=1  AND MOVED_TO_POST_FLAG = 'Y' ;

INSERT INTO OPN_WEB_LINKS(WEB_URL, URL_TITLE, URL_DESCRIPTION, IMAGE_URL, CREATION_DTM, CLEAN_FLAG)
SELECT NEWS_URL, IFNULL(NEWS_HEADLINE, NEWS_EXCERPT), IFNULL(NEWS_EXCERPT, NEWS_HEADLINE), NEWS_PIC_URL, NOW(), 'Y'
FROM WEB_SCRAPE_RAW WHERE NEWS_PIC_URL IS NOT NULL AND SCRAPE_TOPIC IN ('SCIENCE') AND 1=1  ;

SET POSTCOUNT = (SELECT COUNT(*) FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC IN ('SCIENCE') AND 1=1  AND MOVED_TO_POST_FLAG = 'Y') ;

DELETE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC IN ('SCIENCE') AND 1=1  AND MOVED_TO_POST_FLAG = 'Y' ;

INSERT INTO WSR_UNTAGGED(SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE)
SELECT SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC IN ('SCIENCE') AND 1=1  AND MOVED_TO_POST_FLAG = 'N' ;

SET UNTAGCOUNT = (SELECT COUNT(*) FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC IN ('SCIENCE') AND 1=1  AND MOVED_TO_POST_FLAG = 'N') ;

/* 06/24/2023 AST: Starting addition to insert the STP_REMAINDER 
This addition is inserted right after the SET UNTAGCOUNT = ...
And it replaces the DELETE FROM WEB_SCRAPE_RAW line with 3 statements
CALL, INSERT AND DELETE

*/
CALL STP_REMAINDER('SCIENCE', 3, 'GGG') ;

INSERT INTO WSR_CONVERTED(STP_PROCESS, SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE)
SELECT 'STP_REMAINDER', SCRAPE_TOPIC, SCRAPE_SOURCE,  SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC IN ('SCIENCE') AND COUNTRY_CODE = 'GGG'   AND MOVED_TO_POST_FLAG = 'Y' ;

DELETE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC = 'SCIENCE' AND COUNTRY_CODE = 'GGG' AND MOVED_TO_POST_FLAG = 'Y' ;  

/* 06/24/2023 AST: End of  addition to insert the STP_REMAINDER */

INSERT INTO OPN_STP_LOG(PROC_NAME, STP_TOPIC, STP_COUNTRY_CODE, POST_COUNT, UNTAG_COUNT, STP_PROC_DTM)
VALUES('STP_GRAND_T3', 'SCIENCE', 'GGG', POSTCOUNT, UNTAGCOUNT, NOW()) ;


  
  
END ; //
 DELIMITER ;
 
 -- 