
-- 

DELIMITER //
DROP PROCEDURE IF EXISTS STP_GRAND_GGG //
CREATE PROCEDURE STP_GRAND_GGG()
THISPROC: BEGIN

/* 
	10/09/2020 AST: removed the WSR_DEDUPE because it is being done in STP_MONITOR
    also changed the DELETE to capture the true null posts
*/

SET SQL_SAFE_UPDATES = 0;

CALL STP_GRAND_T1GGG() ;
DELETE FROM OPN_POSTS WHERE TOPICID = 1 AND POSTOR_COUNTRY_CODE = 'GGG' AND LENGTH(POST_CONTENT) < 5 ;

CALL STP_GRAND_T3() ;
DELETE FROM OPN_POSTS WHERE TOPICID = 3 AND POSTOR_COUNTRY_CODE = 'GGG' AND LENGTH(POST_CONTENT) < 5 ;


  
  
  
END; //
 DELIMITER ;
 
 -- 