
-- 

DELIMITER //
DROP PROCEDURE IF EXISTS STP_GRAND_T9USA //
CREATE PROCEDURE STP_GRAND_T9USA()
THISPROC: BEGIN

/* 
06/12/2018 Added bakergay, trumppardon, swimsuit
07/19/2020 AST: ADDED TAG_DONE_FLAG = 'Y' AFTER UPDATE


*/

-- PRIOR TO THIS, THE WEB_SCRAPE_RAW MUST BE DEDUPED
  
UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'qtrump', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%MUELLER%' OR UPPER(NEWS_URL) LIKE '%SPECIAL%COUNSEL%') -- AND UPPER(NEWS_URL) NOT LIKE '%BUFFET%' 
;
-- CALL STP_STAG23_1KWINSERT('qtrump', 'L', 3) ;
CALL STP_STAG23_MICRO('qtrump', 'L') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'qtrump', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%MUELLER%' OR UPPER(NEWS_URL) LIKE '%SPECIAL%COUNSEL%') -- AND UPPER(NEWS_URL) NOT LIKE '%BUFFET%' 
;
-- CALL STP_STAG23_1KWINSERT('qtrump', 'H', 5) ;
CALL STP_STAG23_MICRO('qtrump', 'H') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trumpimmi', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLLW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%TRUMP%IMMI%' OR UPPER(NEWS_URL) LIKE '%IMMI%PLAN%' OR UPPER(NEWS_URL) LIKE '%DACA%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;
-- CALL STP_STAG23_1KWINSERT('trumpimmi', 'H', 5) ;
CALL STP_STAG23_MICRO('trumpimmi', 'H') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trumpimmi', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%TRUMP%IMMI%' OR UPPER(NEWS_URL) LIKE '%IMMI%PLAN%' OR UPPER(NEWS_URL) LIKE '%DACA%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;
-- CALL STP_STAG23_1KWINSERT('trumpimmi', 'L', 3) ;
CALL STP_STAG23_MICRO('trumpimmi', 'L') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trumptax', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLLW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%TRUMP%TAX%' OR UPPER(NEWS_URL) LIKE '%GOP%TAX%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;
-- CALL STP_STAG23_1KWINSERT('trumptax', 'H', 5) ;
CALL STP_STAG23_MICRO('trumptax', 'H') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trumptax', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%TRUMP%TAX%' OR UPPER(NEWS_URL) LIKE '%GOP%TAX%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;
-- CALL STP_STAG23_1KWINSERT('trumptax', 'L', 3) ;
CALL STP_STAG23_MICRO('trumptax', 'L') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trumponfbi', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLLW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%TRUMP%FBI%' OR UPPER(NEWS_URL) LIKE '%FBI%TRUMP%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;
-- CALL STP_STAG23_1KWINSERT('trumponfbi', 'H', 5) ;
CALL STP_STAG23_MICRO('trumponfbi', 'H') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trumponfbi', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%TRUMP%FBI%' OR UPPER(NEWS_URL) LIKE '%FBI%TRUMP%')  -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;
-- CALL STP_STAG23_1KWINSERT('trumponfbi', 'L', 3) ;
CALL STP_STAG23_MICRO('trumponfbi', 'L') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trumputah', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLLW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%TRUMP%UTAH%' OR UPPER(NEWS_URL) LIKE '%TRUMP%MONUM%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;
-- CALL STP_STAG23_1KWINSERT('trumputah', 'H', 5) ;
CALL STP_STAG23_MICRO('trumputah', 'H') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trumputah', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%TRUMP%UTAH%' OR UPPER(NEWS_URL) LIKE '%TRUMP%MONUM%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;
-- CALL STP_STAG23_1KWINSERT('trumputah', 'L', 3) ;
CALL STP_STAG23_MICRO('trumputah', 'L') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'h1b', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLLW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%TRUMP%H1B%' OR UPPER(NEWS_URL) LIKE '%H1B%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;
-- CALL STP_STAG23_1KWINSERT('h1b', 'H', 5) ;
CALL STP_STAG23_MICRO('h1b', 'H') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'h1b', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%TRUMP%H1B%' OR UPPER(NEWS_URL) LIKE '%H1B%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;
-- CALL STP_STAG23_1KWINSERT('h1b', 'L', 3) ;
CALL STP_STAG23_MICRO('h1b', 'L') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'shithole', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLLW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%TRUMP%SHIT%' OR UPPER(NEWS_URL) LIKE '%TRUMP%AFRICA%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;
-- CALL STP_STAG23_1KWINSERT('shithole', 'H', 5) ;
CALL STP_STAG23_MICRO('shithole', 'H') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'shithole', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%TRUMP%SHIT%' OR UPPER(NEWS_URL) LIKE '%TRUMP%AFRICA%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;
-- CALL STP_STAG23_1KWINSERT('shithole', 'L', 3) ;
CALL STP_STAG23_MICRO('shithole', 'L') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'superbowl', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'NFL'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%SUPER%BOWL%' OR UPPER(NEWS_URL) LIKE '%LII%' ) -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;
-- CALL STP_STAG23_1KWINSERT('superbowl', 'L', 5) ;
CALL STP_STAG23_MICRO('superbowl', 'L') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'grammy', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'CELEB'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%GRAMM%' OR UPPER(NEWS_URL) LIKE '%AWARD%2018%' ) -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;
-- CALL STP_STAG23_1KWINSERT('grammy', 'L', 5) ;
CALL STP_STAG23_MICRO('grammy', 'L') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'jedi', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'CELEB'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%STAR%WAR%' OR UPPER(NEWS_URL) LIKE '%LAST%JEDI%' ) -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;
-- CALL STP_STAG23_1KWINSERT('jedi', 'L', 5) ;
CALL STP_STAG23_MICRO('jedi', 'L') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'parkland', SCRAPE_TAG3 = 'L'  WHERE COUNTRY_CODE = 'USA'  AND MOVED_TO_POST_FLAG = 'N'
AND ( SCRAPE_SOURCE LIKE '%CNN%' OR SCRAPE_SOURCE LIKE '%YAHOO%')
AND (UPPER(NEWS_URL) LIKE '%PARKLAND%' OR UPPER(NEWS_URL) LIKE '%STONEMAN%' OR UPPER(NEWS_URL) LIKE '%SCHOOL%SHOOT%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'parkland', SCRAPE_TAG3 = 'H'  WHERE COUNTRY_CODE = 'USA'  AND MOVED_TO_POST_FLAG = 'N'
AND ( SCRAPE_SOURCE LIKE '%RCP%' OR SCRAPE_SOURCE LIKE '%FOX%')
AND (UPPER(NEWS_URL) LIKE '%PARKLAND%' OR UPPER(NEWS_URL) LIKE '%STONEMAN%' OR UPPER(NEWS_URL) LIKE '%SCHOOL%SHOOT%' ) ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'teachers', SCRAPE_TAG3 = 'L'  WHERE COUNTRY_CODE = 'USA'  AND MOVED_TO_POST_FLAG = 'N'
AND ( SCRAPE_SOURCE LIKE '%CNN%' OR SCRAPE_SOURCE LIKE '%YAHOO%')
AND (UPPER(NEWS_URL) LIKE '%TEACHER%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'teachers', SCRAPE_TAG3 = 'H'  WHERE COUNTRY_CODE = 'USA'  AND MOVED_TO_POST_FLAG = 'N'
AND ( SCRAPE_SOURCE LIKE '%RCP%' OR SCRAPE_SOURCE LIKE '%FOX%')
AND (UPPER(NEWS_URL) LIKE '%TEACHER%' ) ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'cambridge', SCRAPE_TAG3 = 'L'  WHERE COUNTRY_CODE = 'USA'  AND MOVED_TO_POST_FLAG = 'N'
AND ( SCRAPE_SOURCE LIKE '%CNN%' OR SCRAPE_SOURCE LIKE '%YAHOO%')
AND (UPPER(NEWS_URL) LIKE '%CAMBRIDGE%' OR UPPER(NEWS_URL) LIKE '%FACEBOOK%' OR UPPER(NEWS_URL) LIKE '%ZUCKERB%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'cambridge', SCRAPE_TAG3 = 'H'  WHERE COUNTRY_CODE = 'USA'  AND MOVED_TO_POST_FLAG = 'N'
AND ( SCRAPE_SOURCE LIKE '%RCP%' OR SCRAPE_SOURCE LIKE '%FOX%')
AND (UPPER(NEWS_URL) LIKE '%CAMBRIDGE%' OR UPPER(NEWS_URL) LIKE '%FACEBOOK%' OR UPPER(NEWS_URL) LIKE '%ZUCKERB%' ) ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'syria', SCRAPE_TAG3 = 'H'  WHERE COUNTRY_CODE = 'USA'  AND MOVED_TO_POST_FLAG = 'N'
AND ( SCRAPE_SOURCE LIKE '%CNN%' OR SCRAPE_SOURCE LIKE '%YAHOO%')
AND (UPPER(NEWS_URL) LIKE '%TRUMP%SYRIA%' OR UPPER(NEWS_URL) LIKE '%ASSAD%' OR UPPER(NEWS_URL) LIKE '%SYRIA%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'syria', SCRAPE_TAG3 = 'L'  WHERE COUNTRY_CODE = 'USA'  AND MOVED_TO_POST_FLAG = 'N'
AND ( SCRAPE_SOURCE LIKE '%RCP%' OR SCRAPE_SOURCE LIKE '%FOX%')
AND (UPPER(NEWS_URL) LIKE '%TRUMP%SYRIA%' OR UPPER(NEWS_URL) LIKE '%ASSAD%' OR UPPER(NEWS_URL) LIKE '%SYRIA%' ) ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'tfirem', SCRAPE_TAG3 = 'H'  WHERE COUNTRY_CODE = 'USA'  AND MOVED_TO_POST_FLAG = 'N'
AND ( SCRAPE_SOURCE LIKE '%CNN%' OR SCRAPE_SOURCE LIKE '%YAHOO%')
AND (UPPER(NEWS_URL) LIKE '%TRUMP%MUELLER%' OR UPPER(NEWS_URL) LIKE '%MUELLER%TRUMP%' OR UPPER(NEWS_URL) LIKE '%SPECIAL%COUNSEL%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'tfirem', SCRAPE_TAG3 = 'L'  WHERE COUNTRY_CODE = 'USA'  AND MOVED_TO_POST_FLAG = 'N'
AND ( SCRAPE_SOURCE LIKE '%RCP%' OR SCRAPE_SOURCE LIKE '%FOX%')
AND (UPPER(NEWS_URL) LIKE '%TRUMP%MUELLER%' OR UPPER(NEWS_URL) LIKE '%MUELLER%TRUMP%' OR UPPER(NEWS_URL) LIKE '%SPECIAL%COUNSEL%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'bakergay', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLLW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%BAKER%' OR UPPER(NEWS_URL) LIKE '%WEDDING%CAKE%'
OR UPPER(NEWS_URL) LIKE '%JACK%PHILLIP%' OR UPPER(NEWS_URL) LIKE '%COLORADO%GAY%') -- AND UPPER(NEWS_URL) NOT LIKE '%BUFFET%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'bakergay', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%BAKER%' OR UPPER(NEWS_URL) LIKE '%WEDDING%CAKE%'
OR UPPER(NEWS_URL) LIKE '%JACK%PHILLIP%' OR UPPER(NEWS_URL) LIKE '%COLORADO%GAY%') -- AND UPPER(NEWS_URL) NOT LIKE '%BUFFET%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trumppardon', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%TRUMP%PARDON%' OR UPPER(NEWS_URL) LIKE '%PARDON%TRUMP%' )
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trumppardon', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLLW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%TRUMP%PARDON%' OR UPPER(NEWS_URL) LIKE '%PARDON%TRUMP%' ) 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'swimsuit', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%MISS%AMERICA%' OR UPPER(NEWS_URL) LIKE '%BEAUTY%PAGEANT%' OR UPPER(NEWS_URL) LIKE '%SCRAP%SWIMSUIT%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'swimsuit', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%MISS%AMERICA%' OR UPPER(NEWS_URL) LIKE '%BEAUTY%PAGEANT%' OR UPPER(NEWS_URL) LIKE '%SCRAP%SWIMSUIT%')
;

/*	07/19/2020 AST: Added the TAG_DONE_FLAG = 'Y' to make it compatible with the new STP_STAG23_MICRO */

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y' WHERE SCRAPE_TAG3 IN ('L', 'H') ;

/* 	END OF 07/19/2020 AST ADDITION */

-- CALL STP_STAG23_1KWINSERT('swimsuit', 'L', 3) ;
CALL STP_STAG23_MICRO('swimsuit', 'L') ;

-- CALL STP_STAG23_1KWINSERT('swimsuit', 'H', 5) ;
CALL STP_STAG23_MICRO('swimsuit', 'H') ;

-- CALL STP_STAG23_1KWINSERT('trumppardon', 'L', 3) ;
CALL STP_STAG23_MICRO('trumppardon', 'L') ;

-- CALL STP_STAG23_1KWINSERT('trumppardon', 'H', 5) ;
CALL STP_STAG23_MICRO('trumppardon', 'H') ;

-- CALL STP_STAG23_1KWINSERT('parkland', 'H', 5) ;
CALL STP_STAG23_MICRO('parkland', 'H') ;

-- CALL STP_STAG23_1KWINSERT('parkland', 'L', 5) ;
CALL STP_STAG23_MICRO('parkland', 'L') ;

-- CALL STP_STAG23_1KWINSERT('teachers', 'H', 5) ;
CALL STP_STAG23_MICRO('teachers', 'H') ;

-- CALL STP_STAG23_1KWINSERT('teachers', 'L', 5) ;
CALL STP_STAG23_MICRO('teachers', 'L') ;

-- CALL STP_STAG23_1KWINSERT('cambridge', 'H', 5) ;
CALL STP_STAG23_MICRO('cambridge', 'H') ;

-- CALL STP_STAG23_1KWINSERT('cambridge', 'L', 5) ;
CALL STP_STAG23_MICRO('cambridge', 'L') ;

-- CALL STP_STAG23_1KWINSERT('syria', 'H', 5) ;
CALL STP_STAG23_MICRO('syria', 'H') ;

-- CALL STP_STAG23_1KWINSERT('syria', 'L', 5) ;
CALL STP_STAG23_MICRO('syria', 'L') ;
	
-- CALL STP_STAG23_1KWINSERT('tfirem', 'H', 5) ;
CALL STP_STAG23_MICRO('tfirem', 'H') ;

-- CALL STP_STAG23_1KWINSERT('tfirem', 'L', 5) ;
CALL STP_STAG23_MICRO('tfirem', 'L') ;

-- CALL STP_STAG23_1KWINSERT('bakergay', 'L', 3) ;
CALL STP_STAG23_MICRO('bakergay', 'L') ;

-- CALL STP_STAG23_1KWINSERT('bakergay', 'H', 5) ;
CALL STP_STAG23_MICRO('bakergay', 'H') ;


  
  
  
END; //
 DELIMITER ;
 
 -- 