
-- 

DELIMITER //
DROP PROCEDURE IF EXISTS STP_GRAND_T1USA //
CREATE PROCEDURE STP_GRAND_T1USA()
THISPROC: BEGIN

/* 

12/13/2018 AST: Added sweep into OPN_WEB_LINKS

INSERT INTO OPN_WEB_LINKS(WEB_URL, URL_TITLE, URL_DESCRIPTION, IMAGE_URL, CREATION_DTM, CLEAN_FLAG)
SELECT NEWS_URL, IFNULL(NEWS_HEADLINE, NEWS_EXCERPT), IFNULL(NEWS_EXCERPT, NEWS_HEADLINE), NEWS_PIC_URL, NOW(), 'Y'
FROM WEB_SCRAPE_RAW WHERE NEWS_PIC_URL IS NOT NULL AND SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'USA'

12/18/2018 : AST :  ADDED SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL

06/07/2019 AST: Removing the 1KW STP Procs - because now they are not needed

CALL STP_STAG1_1KW(1, 'USAPOL', 'USA') ;

-- CALL STP_STAG23_1KWINSERT('hillary', 'L', 2) ;

06/12/2019 AST: Added NR to the USAPOLRW classification
08/29/2019 AST: Trump added back
09/03/2019 AST: Added NEWS_HEADLINE LIKE 

05/07/2020 AST: REMOVED %AR%15% AND REPLACED WITH %RIFLE% FOR GUN CONTROL

	07/19/2020 AST: ADDED TAG_DONE_FLAG = 'Y' AFTER UPDATE

09/05/2020 AST: Adding the tagging of 25 untagged scrapes to POLITICS NEWS KW
10/04/2020 AST: adding filter to XYZNEWS to avoid: old news, stock market update, SHOPPING ADS ETC.

10/07/2020 AST Added WAPO%, HILL%, BBRT% to the LW/RW classification
 10/09/2020 AST: fixing the date issue in XYZNEWS  addition - also moving it to the front of the UPDATE
    10/10/2020 AST: removed the above - as a new proc was created for this purpose
    
         06/24/2023: AST: Introducing the STP_REMAINDER proc 

*/

-- PRIOR TO THIS, THE WEB_SCRAPE_RAW MUST BE DEDUPED

DECLARE POSTCOUNT, UNTAGCOUNT INT ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 = 'USAPOLLW', SCRAPE_TAG2 = 'USAPOLLW', SCRAPE_TAG3 = 'USAPOLLW' 
WHERE (SCRAPE_SOURCE LIKE 'CNN%' OR SCRAPE_SOURCE LIKE 'YAHOO%' OR SCRAPE_SOURCE LIKE 'WAPO%' OR SCRAPE_SOURCE LIKE 'HILL%')
AND SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'USA' ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 = 'USAPOLRW', SCRAPE_TAG2 = 'USAPOLRW', SCRAPE_TAG3 = 'USAPOLRW' 
WHERE (SCRAPE_SOURCE LIKE 'FOX%' OR SCRAPE_SOURCE LIKE 'RCP%' OR SCRAPE_SOURCE LIKE 'NR%' OR SCRAPE_SOURCE LIKE 'BBRT%') 
AND SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'USA' ;

-- 

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'hillary', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%HILLARY%' OR UPPER(NEWS_URL) LIKE '%CLINTON%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'hillary', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%HILLARY%' OR UPPER(NEWS_URL) LIKE '%CLINTON%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'bernie', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%BERNIE%' OR UPPER(NEWS_URL) LIKE '%SANDERS%') AND UPPER(NEWS_URL) NOT LIKE '%SARA%' ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'bernie', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N' 
AND (UPPER(NEWS_URL) LIKE '%BERNIE%' OR UPPER(NEWS_URL) LIKE '%SANDERS%')  AND UPPER(NEWS_URL) NOT LIKE '%SARA%';

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'obama', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%OBAMA%' OR UPPER(NEWS_URL) LIKE '%BARACK%') AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%' ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'obama', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%OBAMA%' OR UPPER(NEWS_URL) LIKE '%BARACK%')  AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%';

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pelosi', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%PELOSI%' OR UPPER(NEWS_URL) LIKE '%HOUSE%MINORITY%') -- AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pelosi', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%PELOSI%' OR UPPER(NEWS_URL) LIKE '%HOUSE%MINORITY%') -- AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%'
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'schumer', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%SCHUMER%' OR UPPER(NEWS_URL) LIKE '%SENATE%MINORITY%') -- AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'schumer', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%SCHUMER%' OR UPPER(NEWS_URL) LIKE '%SENATE%MINORITY%') -- AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%'
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'warren', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%WARREN%' OR UPPER(NEWS_URL) LIKE '%LIZ%WARREN%')  AND UPPER(NEWS_URL) NOT LIKE '%BUFFET%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'warren', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N' 
AND (UPPER(NEWS_URL) LIKE '%WARREN%' OR UPPER(NEWS_URL) LIKE '%LIZ%WARREN%')  AND UPPER(NEWS_URL) NOT LIKE '%BUFFET%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mueller', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (UPPER(NEWS_URL) LIKE '%MUELLER%' OR UPPER(NEWS_URL) LIKE '%SPECIAL%COUNSEL%') AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mueller', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%MUELLER%' OR UPPER(NEWS_URL) LIKE '%SPECIAL%COUNSEL%') AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'kamala', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (UPPER(NEWS_URL) LIKE '%KAMALA%' OR UPPER(NEWS_URL) LIKE '%SENATOR%HARRIS%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'kamala', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%KAMALA%' OR UPPER(NEWS_URL) LIKE '%SENATOR%HARRIS%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'fein', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (UPPER(NEWS_URL) LIKE '%FEINSTEIN%' OR UPPER(NEWS_URL) LIKE '%SENATOR%DIANNE%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'fein', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%FEINSTEIN%' OR UPPER(NEWS_URL) LIKE '%SENATOR%DIANNE%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'deblasio', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (UPPER(NEWS_URL) LIKE '%DE%BLASIO%' OR UPPER(NEWS_URL) LIKE '%N%Y%%MAYOR%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'deblasio', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%DE%BLASIO%' OR UPPER(NEWS_URL) LIKE '%N%Y%%MAYOR%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'colbert', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (UPPER(NEWS_URL) LIKE '%COLBERT%' OR UPPER(NEWS_URL) LIKE '%LATE%%SHOW%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'colbert', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%COLBERT%' OR UPPER(NEWS_URL) LIKE '%LATE%%SHOW%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'path', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%PATH%CITIZ%' OR UPPER(NEWS_URL) LIKE '%IMMI%'  
OR UPPER(NEWS_URL) LIKE '%DREAMERS%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'path', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%PATH%CITIZ%' OR UPPER(NEWS_URL) LIKE '%IMMI%'  
OR UPPER(NEWS_URL) LIKE '%DREAMERS%'  OR UPPER(NEWS_URL) LIKE '%ILLEG%IMMI%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pp', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%PLANNED%PARENT%' OR UPPER(NEWS_URL) LIKE '%ABORTION%'  
OR UPPER(NEWS_URL) LIKE '%ROE%WADE%' OR UPPER(NEWS_URL) LIKE '%WOM%RIGHT%CHOOSE%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pp', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%PLANNED%PARENT%' OR UPPER(NEWS_URL) LIKE '%ABORTION%'  
OR UPPER(NEWS_URL) LIKE '%ROE%WADE%' OR UPPER(NEWS_URL) LIKE '%WOM%RIGHT%CHOOSE%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'antifa', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%ANTIFA%' OR UPPER(NEWS_URL) LIKE '%OCCUPY%' 
OR UPPER(NEWS_URL) LIKE '%FREE%SPEECH%' OR UPPER(NEWS_URL) LIKE '%BLM%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'antifa', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%ANTIFA%' OR UPPER(NEWS_URL) LIKE '%OCCUPY%'  
OR UPPER(NEWS_URL) LIKE '%FREE%SPEECH%' OR UPPER(NEWS_URL) LIKE '%BLM%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'lgbt', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%LGBT%' OR UPPER(NEWS_URL) LIKE '%GAY%'  OR UPPER(NEWS_URL) LIKE '%TRANSG%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'lgbt', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%LGBT%' OR UPPER(NEWS_URL) LIKE '%GAY%'  OR UPPER(NEWS_URL) LIKE '%TRANSG%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'clime', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%CLIMATE%' OR UPPER(NEWS_URL) LIKE '%GLOBAL%WARM%'  OR UPPER(NEWS_URL) LIKE '%RENEWAB%'  
OR UPPER(NEWS_URL) LIKE '%FOSSIL%FUEL%'  OR UPPER(NEWS_URL) LIKE '%KYOTO%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'clime', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%CLIMATE%' OR UPPER(NEWS_URL) LIKE '%GLOBAL%WARM%'  OR UPPER(NEWS_URL) LIKE '%RENEWAB%'  
OR UPPER(NEWS_URL) LIKE '%FOSSIL%FUEL%'  OR UPPER(NEWS_URL) LIKE '%KYOTO%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

--


--

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pence', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%PENCE%' OR UPPER(NEWS_URL) LIKE '%VICE%PRESI%' OR UPPER(NEWS_URL) LIKE '%VEEP%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trump', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%PENCE%' OR UPPER(NEWS_URL) LIKE '%VICE%PRESI%' OR UPPER(NEWS_URL) LIKE '%VEEP%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'bannon', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%BANNON%' ) 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'bannon', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%BANNON%' ) 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ryan', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%PAUL%RYAN%' OR UPPER(NEWS_URL) LIKE '%HOUSE%SPEAKER%' OR UPPER(NEWS_URL) LIKE '%SPEAKER%HOUSE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ryan', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%PAUL%RYAN%' OR UPPER(NEWS_URL) LIKE '%HOUSE%SPEAKER%' OR UPPER(NEWS_URL) LIKE '%SPEAKER%HOUSE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mconel', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%MITCH%MCCON%' OR UPPER(NEWS_URL) LIKE '%SENATE%LEADER%' OR UPPER(NEWS_URL) LIKE '%MCCONNE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mconel', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%MITCH%MCCON%' OR UPPER(NEWS_URL) LIKE '%SENATE%LEADER%' OR UPPER(NEWS_URL) LIKE '%MCCONNE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ivanka', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%IVANKA%' OR UPPER(NEWS_URL) LIKE '%KUSHNER%' ) 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ivanka', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%IVANKA%' OR UPPER(NEWS_URL) LIKE '%KUSHNER%' ) 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ssand', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%SARA%SANDER%' OR UPPER(NEWS_URL) LIKE '%SARA%HUCKAB%' OR UPPER(NEWS_URL) LIKE '%HUCKAB%SANDER%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ssand', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%SARA%SANDER%' OR UPPER(NEWS_URL) LIKE '%SARA%HUCKAB%' OR UPPER(NEWS_URL) LIKE '%HUCKAB%SANDER%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'sessions', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%JEFF%SESSION%' OR UPPER(NEWS_URL) LIKE '%SESSIONS%' OR UPPER(NEWS_URL) LIKE '%ATTORN%GENERAL%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'sessions', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%JEFF%SESSION%' OR UPPER(NEWS_URL) LIKE '%SESSIONS%' OR UPPER(NEWS_URL) LIKE '%ATTORN%GENERAL%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'devos', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%BETSY%DEVOS%' OR UPPER(NEWS_URL) LIKE '%DEVOS%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'devos', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%BETSY%DEVOS%' OR UPPER(NEWS_URL) LIKE '%DEVOS%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pruitt', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%SCOTT%PRUITT%' OR UPPER(NEWS_URL) LIKE '%PRUITT%'  OR UPPER(NEWS_URL) LIKE '%-EPA-%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pruitt', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%SCOTT%PRUITT%' OR UPPER(NEWS_URL) LIKE '%PRUITT%'  OR UPPER(NEWS_URL) LIKE '%-EPA-%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mnuchin', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%STEVE%MNUCHIN%' OR UPPER(NEWS_URL) LIKE '%MNUCHIN%'  OR UPPER(NEWS_URL) LIKE '%-TREASURY-%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mnuchin', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%STEVE%MNUCHIN%' OR UPPER(NEWS_URL) LIKE '%MNUCHIN%'  OR UPPER(NEWS_URL) LIKE '%-TREASURY-%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'haley', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%NIKKI%HALEY%' OR UPPER(NEWS_URL) LIKE '%AMBA%%HALEY%'  OR UPPER(NEWS_URL) LIKE '%UNITED%NATIONS%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'haley', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%NIKKI%HALEY%' OR UPPER(NEWS_URL) LIKE '%AMBA%%HALEY%'  OR UPPER(NEWS_URL) LIKE '%UNITED%NATIONS%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'tiller', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%REX%TILLER%' OR UPPER(NEWS_URL) LIKE '%TILLERSO%'  OR UPPER(NEWS_URL) LIKE '%SEC%STATE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'tiller', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%REX%TILLER%' OR UPPER(NEWS_URL) LIKE '%TILLERSO%'  OR UPPER(NEWS_URL) LIKE '%SEC%STATE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'rush', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%RUSH%LIMB%' OR UPPER(NEWS_URL) LIKE '%LIMBAU%'  OR UPPER(NEWS_URL) LIKE '%BLOWHARD%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'rush', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%RUSH%LIMB%' OR UPPER(NEWS_URL) LIKE '%LIMBAU%'  OR UPPER(NEWS_URL) LIKE '%BLOWHARD%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'hannity', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%HANNITY%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'hannity', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL)  LIKE '%HANNITY%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'coulter', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%COULTER%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'coulter', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL)  LIKE '%COULTER%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'fox', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%FOX%NEWS%' )
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'fox', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL)  LIKE '%FOX%NEWS%' ) AND UPPER(NEWS_URL) NOT LIKE '%HTTP%FOXNEWS%'
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'breit', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%BREIT%' )
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'breit', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL)  LIKE '%BREIT%' ) AND UPPER(NEWS_URL) NOT LIKE '%HTTP%BREIT%'
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'immi', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%IMMIGR%' OR UPPER(NEWS_URL) LIKE '%-VISA-%'  OR UPPER(NEWS_URL) LIKE '%AMNESTY%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'immi', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%IMMIGR%' OR UPPER(NEWS_URL) LIKE '%-VISA-%'  OR UPPER(NEWS_URL) LIKE '%AMNESTY%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'nra', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%-NRA-%' OR UPPER(NEWS_URL) LIKE '%RIFLE%'  OR UPPER(NEWS_URL) LIKE '%SHOOTING%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'nra', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%-NRA-%' OR UPPER(NEWS_URL) LIKE '%RIFLE%'  OR UPPER(NEWS_URL) LIKE '%SHOOTING%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'abortion', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%ABORTION%' OR UPPER(NEWS_URL) LIKE '%PLANNED%PARENT%'  OR UPPER(NEWS_URL) LIKE '%CONTRACEPT%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'abortion', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%ABORTION%' OR UPPER(NEWS_URL) LIKE '%PLANNED%PARENT%'  OR UPPER(NEWS_URL) LIKE '%CONTRACEPT%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'altright', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%ALT%RIGHT%' OR UPPER(NEWS_URL) LIKE '%WHITE%SUPREM%%'  OR UPPER(NEWS_URL) LIKE '%STORMFRONT%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'altright', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%altright%' '%ALT%RIGHT%' OR UPPER(NEWS_URL) LIKE '%WHITE%SUPREM%%'  OR UPPER(NEWS_URL) LIKE '%STORMFRONT%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'gwarm', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%GLOBAL%WARM%' OR UPPER(NEWS_URL) LIKE '%CLIMATE%SCI%%'  OR UPPER(NEWS_URL) LIKE '%POLLUTION%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'gwarm', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%GLOBAL%WARM%' OR UPPER(NEWS_URL) LIKE '%CLIMATE%SCI%%'  OR UPPER(NEWS_URL) LIKE '%POLLUTION%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'gun', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (UPPER(NEWS_URL) LIKE '%GUN%' OR UPPER(NEWS_URL) LIKE '%MASS%SHOOTI%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'gun', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%GUN%' OR UPPER(NEWS_URL) LIKE '%MASS%SHOOTI%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

--

/* 06/12/2019 - commenting out the trump part - just to research what drops out and can be captures by scrape_design_gen 
08/30/2019 AST: Adding back in */

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trump', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%TRUMP%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trump', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL) LIKE '%TRUMP%' ) ;
 
--

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'hillary', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%HILLARY%' OR NEWS_HEADLINE LIKE '%CLINTON%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'hillary', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%HILLARY%' OR NEWS_HEADLINE LIKE '%CLINTON%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'bernie', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%BERNIE%' OR NEWS_HEADLINE LIKE '%SANDERS%') AND UPPER(NEWS_URL) NOT LIKE '%SARA%' ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'bernie', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE '%BERNIE%' OR NEWS_HEADLINE LIKE '%SANDERS%')  AND UPPER(NEWS_URL) NOT LIKE '%SARA%';

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'obama', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%OBAMA%' OR NEWS_HEADLINE LIKE '%BARACK%') AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%' ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'obama', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%OBAMA%' OR NEWS_HEADLINE LIKE '%BARACK%')  AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%';

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pelosi', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%PELOSI%' OR NEWS_HEADLINE LIKE '%HOUSE%MINORITY%') -- AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pelosi', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%PELOSI%' OR NEWS_HEADLINE LIKE '%HOUSE%MINORITY%') -- AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%'
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'schumer', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%SCHUMER%' OR NEWS_HEADLINE LIKE '%SENATE%MINORITY%') -- AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'schumer', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%SCHUMER%' OR NEWS_HEADLINE LIKE '%SENATE%MINORITY%') -- AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%'
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'warren', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%WARREN%' OR NEWS_HEADLINE LIKE '%LIZ%WARREN%')  AND UPPER(NEWS_URL) NOT LIKE '%BUFFET%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'warren', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE '%WARREN%' OR NEWS_HEADLINE LIKE '%LIZ%WARREN%')  AND UPPER(NEWS_URL) NOT LIKE '%BUFFET%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mueller', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE '%MUELLER%' OR NEWS_HEADLINE LIKE '%SPECIAL%COUNSEL%') AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mueller', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%MUELLER%' OR NEWS_HEADLINE LIKE '%SPECIAL%COUNSEL%') AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'kamala', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE '%KAMALA%' OR NEWS_HEADLINE LIKE '%SENATOR%HARRIS%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'kamala', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%KAMALA%' OR NEWS_HEADLINE LIKE '%SENATOR%HARRIS%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'fein', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE '%FEINSTEIN%' OR NEWS_HEADLINE LIKE '%SENATOR%DIANNE%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'fein', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%FEINSTEIN%' OR NEWS_HEADLINE LIKE '%SENATOR%DIANNE%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'deblasio', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE '%DE%BLASIO%' OR NEWS_HEADLINE LIKE '%N%Y%%MAYOR%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'deblasio', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%DE%BLASIO%' OR NEWS_HEADLINE LIKE '%N%Y%%MAYOR%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'colbert', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE '%COLBERT%' OR NEWS_HEADLINE LIKE '%LATE%%SHOW%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'colbert', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%COLBERT%' OR NEWS_HEADLINE LIKE '%LATE%%SHOW%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'path', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%PATH%CITIZ%' OR NEWS_HEADLINE LIKE '%IMMI%'  
OR NEWS_HEADLINE LIKE '%DREAMERS%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'path', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%PATH%CITIZ%' OR NEWS_HEADLINE LIKE '%IMMI%'  
OR NEWS_HEADLINE LIKE '%DREAMERS%'  OR NEWS_HEADLINE LIKE '%ILLEG%IMMI%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pp', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%PLANNED%PARENT%' OR NEWS_HEADLINE LIKE '%ABORTION%'  
OR NEWS_HEADLINE LIKE '%ROE%WADE%' OR NEWS_HEADLINE LIKE '%WOM%RIGHT%CHOOSE%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pp', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%PLANNED%PARENT%' OR NEWS_HEADLINE LIKE '%ABORTION%'  
OR NEWS_HEADLINE LIKE '%ROE%WADE%' OR NEWS_HEADLINE LIKE '%WOM%RIGHT%CHOOSE%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'antifa', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%ANTIFA%' OR NEWS_HEADLINE LIKE '%OCCUPY%' 
OR NEWS_HEADLINE LIKE '%FREE%SPEECH%' OR NEWS_HEADLINE LIKE '%BLM%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'antifa', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%ANTIFA%' OR NEWS_HEADLINE LIKE '%OCCUPY%'  
OR NEWS_HEADLINE LIKE '%FREE%SPEECH%' OR NEWS_HEADLINE LIKE '%BLM%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'lgbt', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%LGBT%' OR NEWS_HEADLINE LIKE '%GAY%'  OR NEWS_HEADLINE LIKE '%TRANSG%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'lgbt', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%LGBT%' OR NEWS_HEADLINE LIKE '%GAY%'  OR NEWS_HEADLINE LIKE '%TRANSG%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'clime', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%CLIMATE%' OR NEWS_HEADLINE LIKE '%GLOBAL%WARM%'  OR NEWS_HEADLINE LIKE '%RENEWAB%'  
OR NEWS_HEADLINE LIKE '%FOSSIL%FUEL%'  OR NEWS_HEADLINE LIKE '%KYOTO%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'clime', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%CLIMATE%' OR NEWS_HEADLINE LIKE '%GLOBAL%WARM%'  OR NEWS_HEADLINE LIKE '%RENEWAB%'  
OR NEWS_HEADLINE LIKE '%FOSSIL%FUEL%'  OR NEWS_HEADLINE LIKE '%KYOTO%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

--


--

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pence', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%PENCE%' OR NEWS_HEADLINE LIKE '%VICE%PRESI%' OR NEWS_HEADLINE LIKE '%VEEP%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trump', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%PENCE%' OR NEWS_HEADLINE LIKE '%VICE%PRESI%' OR NEWS_HEADLINE LIKE '%VEEP%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'bannon', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%BANNON%' ) 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'bannon', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%BANNON%' ) 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ryan', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%PAUL%RYAN%' OR NEWS_HEADLINE LIKE '%HOUSE%SPEAKER%' OR NEWS_HEADLINE LIKE '%SPEAKER%HOUSE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ryan', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%PAUL%RYAN%' OR NEWS_HEADLINE LIKE '%HOUSE%SPEAKER%' OR NEWS_HEADLINE LIKE '%SPEAKER%HOUSE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mconel', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%MITCH%MCCON%' OR NEWS_HEADLINE LIKE '%SENATE%LEADER%' OR NEWS_HEADLINE LIKE '%MCCONNE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mconel', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%MITCH%MCCON%' OR NEWS_HEADLINE LIKE '%SENATE%LEADER%' OR NEWS_HEADLINE LIKE '%MCCONNE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ivanka', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%IVANKA%' OR NEWS_HEADLINE LIKE '%KUSHNER%' ) 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ivanka', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%IVANKA%' OR NEWS_HEADLINE LIKE '%KUSHNER%' ) 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ssand', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%SARA%SANDER%' OR NEWS_HEADLINE LIKE '%SARA%HUCKAB%' OR NEWS_HEADLINE LIKE '%HUCKAB%SANDER%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ssand', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%SARA%SANDER%' OR NEWS_HEADLINE LIKE '%SARA%HUCKAB%' OR NEWS_HEADLINE LIKE '%HUCKAB%SANDER%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'sessions', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%JEFF%SESSION%' OR NEWS_HEADLINE LIKE '%SESSIONS%' OR NEWS_HEADLINE LIKE '%ATTORN%GENERAL%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'sessions', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%JEFF%SESSION%' OR NEWS_HEADLINE LIKE '%SESSIONS%' OR NEWS_HEADLINE LIKE '%ATTORN%GENERAL%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'devos', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%BETSY%DEVOS%' OR NEWS_HEADLINE LIKE '%DEVOS%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'devos', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%BETSY%DEVOS%' OR NEWS_HEADLINE LIKE '%DEVOS%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pruitt', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%SCOTT%PRUITT%' OR NEWS_HEADLINE LIKE '%PRUITT%'  OR NEWS_HEADLINE LIKE '%-EPA-%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pruitt', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%SCOTT%PRUITT%' OR NEWS_HEADLINE LIKE '%PRUITT%'  OR NEWS_HEADLINE LIKE '%-EPA-%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mnuchin', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%STEVE%MNUCHIN%' OR NEWS_HEADLINE LIKE '%MNUCHIN%'  OR NEWS_HEADLINE LIKE '%-TREASURY-%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mnuchin', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%STEVE%MNUCHIN%' OR NEWS_HEADLINE LIKE '%MNUCHIN%'  OR NEWS_HEADLINE LIKE '%-TREASURY-%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'haley', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%NIKKI%HALEY%' OR NEWS_HEADLINE LIKE '%AMBA%%HALEY%'  OR NEWS_HEADLINE LIKE '%UNITED%NATIONS%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'haley', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%NIKKI%HALEY%' OR NEWS_HEADLINE LIKE '%AMBA%%HALEY%'  OR NEWS_HEADLINE LIKE '%UNITED%NATIONS%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'tiller', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%REX%TILLER%' OR NEWS_HEADLINE LIKE '%TILLERSO%'  OR NEWS_HEADLINE LIKE '%SEC%STATE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'tiller', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%REX%TILLER%' OR NEWS_HEADLINE LIKE '%TILLERSO%'  OR NEWS_HEADLINE LIKE '%SEC%STATE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'rush', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%RUSH%LIMB%' OR NEWS_HEADLINE LIKE '%LIMBAU%'  OR NEWS_HEADLINE LIKE '%BLOWHARD%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'rush', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%RUSH%LIMB%' OR NEWS_HEADLINE LIKE '%LIMBAU%'  OR NEWS_HEADLINE LIKE '%BLOWHARD%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'hannity', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%HANNITY%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'hannity', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL)  LIKE '%HANNITY%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'coulter', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%COULTER%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'coulter', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL)  LIKE '%COULTER%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'fox', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%FOX%NEWS%' )
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'fox', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL)  LIKE '%FOX%NEWS%' ) AND UPPER(NEWS_URL) NOT LIKE '%HTTP%FOXNEWS%'
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'breit', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%BREIT%' )
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'breit', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL)  LIKE '%BREIT%' ) AND UPPER(NEWS_URL) NOT LIKE '%HTTP%BREIT%'
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'immi', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%IMMIGR%' OR NEWS_HEADLINE LIKE '%-VISA-%'  OR NEWS_HEADLINE LIKE '%AMNESTY%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'immi', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%IMMIGR%' OR NEWS_HEADLINE LIKE '%-VISA-%'  OR NEWS_HEADLINE LIKE '%AMNESTY%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'nra', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%-NRA-%' OR NEWS_HEADLINE LIKE '%RIFLE%'  OR NEWS_HEADLINE LIKE '%SHOOTING%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'nra', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%-NRA-%' OR NEWS_HEADLINE LIKE '%RIFLE%'  OR NEWS_HEADLINE LIKE '%SHOOTING%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'abortion', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%ABORTION%' OR NEWS_HEADLINE LIKE '%PLANNED%PARENT%'  OR NEWS_HEADLINE LIKE '%CONTRACEPT%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'abortion', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%ABORTION%' OR NEWS_HEADLINE LIKE '%PLANNED%PARENT%'  OR NEWS_HEADLINE LIKE '%CONTRACEPT%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'altright', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%ALT%RIGHT%' OR NEWS_HEADLINE LIKE '%WHITE%SUPREM%%'  OR NEWS_HEADLINE LIKE '%STORMFRONT%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'altright', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%altright%' '%ALT%RIGHT%' OR NEWS_HEADLINE LIKE '%WHITE%SUPREM%%'  OR NEWS_HEADLINE LIKE '%STORMFRONT%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'gwarm', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%GLOBAL%WARM%' OR NEWS_HEADLINE LIKE '%CLIMATE%SCI%%'  OR NEWS_HEADLINE LIKE '%POLLUTION%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'gwarm', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%GLOBAL%WARM%' OR NEWS_HEADLINE LIKE '%CLIMATE%SCI%%'  OR NEWS_HEADLINE LIKE '%POLLUTION%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'gun', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_HEADLINE LIKE '%GUN%' OR NEWS_HEADLINE LIKE '%MASS%SHOOTI%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'gun', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%GUN%' OR NEWS_HEADLINE LIKE '%MASS%SHOOTI%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

--

/* 06/12/2019 - commenting out the trump part - just to research what drops out and can be captures by scrape_design_gen 
08/30/2019 AST: Adding back in */

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trump', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%TRUMP%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trump', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_HEADLINE LIKE '%TRUMP%' ) ;

--

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'hillary', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%HILLARY%' OR NEWS_EXCERPT LIKE '%CLINTON%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'hillary', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%HILLARY%' OR NEWS_EXCERPT LIKE '%CLINTON%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'bernie', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%BERNIE%' OR NEWS_EXCERPT LIKE '%SANDERS%') AND UPPER(NEWS_URL) NOT LIKE '%SARA%' ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'bernie', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_EXCERPT LIKE '%BERNIE%' OR NEWS_EXCERPT LIKE '%SANDERS%')  AND UPPER(NEWS_URL) NOT LIKE '%SARA%';

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'obama', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%OBAMA%' OR NEWS_EXCERPT LIKE '%BARACK%') AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%' ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'obama', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%OBAMA%' OR NEWS_EXCERPT LIKE '%BARACK%')  AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%';

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pelosi', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%PELOSI%' OR NEWS_EXCERPT LIKE '%HOUSE%MINORITY%') -- AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pelosi', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%PELOSI%' OR NEWS_EXCERPT LIKE '%HOUSE%MINORITY%') -- AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%'
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'schumer', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%SCHUMER%' OR NEWS_EXCERPT LIKE '%SENATE%MINORITY%') -- AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'schumer', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%SCHUMER%' OR NEWS_EXCERPT LIKE '%SENATE%MINORITY%') -- AND UPPER(NEWS_URL) NOT LIKE '%OBAMACARE%'
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'warren', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%WARREN%' OR NEWS_EXCERPT LIKE '%LIZ%WARREN%')  AND UPPER(NEWS_URL) NOT LIKE '%BUFFET%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'warren', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_EXCERPT LIKE '%WARREN%' OR NEWS_EXCERPT LIKE '%LIZ%WARREN%')  AND UPPER(NEWS_URL) NOT LIKE '%BUFFET%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mueller', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_EXCERPT LIKE '%MUELLER%' OR NEWS_EXCERPT LIKE '%SPECIAL%COUNSEL%') AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mueller', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%MUELLER%' OR NEWS_EXCERPT LIKE '%SPECIAL%COUNSEL%') AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'kamala', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_EXCERPT LIKE '%KAMALA%' OR NEWS_EXCERPT LIKE '%SENATOR%HARRIS%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'kamala', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%KAMALA%' OR NEWS_EXCERPT LIKE '%SENATOR%HARRIS%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'fein', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_EXCERPT LIKE '%FEINSTEIN%' OR NEWS_EXCERPT LIKE '%SENATOR%DIANNE%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'fein', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%FEINSTEIN%' OR NEWS_EXCERPT LIKE '%SENATOR%DIANNE%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'deblasio', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_EXCERPT LIKE '%DE%BLASIO%' OR NEWS_EXCERPT LIKE '%N%Y%%MAYOR%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'deblasio', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%DE%BLASIO%' OR NEWS_EXCERPT LIKE '%N%Y%%MAYOR%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'colbert', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_EXCERPT LIKE '%COLBERT%' OR NEWS_EXCERPT LIKE '%LATE%%SHOW%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'colbert', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%COLBERT%' OR NEWS_EXCERPT LIKE '%LATE%%SHOW%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'path', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%PATH%CITIZ%' OR NEWS_EXCERPT LIKE '%IMMI%'  
OR NEWS_EXCERPT LIKE '%DREAMERS%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'path', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%PATH%CITIZ%' OR NEWS_EXCERPT LIKE '%IMMI%'  
OR NEWS_EXCERPT LIKE '%DREAMERS%'  OR NEWS_EXCERPT LIKE '%ILLEG%IMMI%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pp', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%PLANNED%PARENT%' OR NEWS_EXCERPT LIKE '%ABORTION%'  
OR NEWS_EXCERPT LIKE '%ROE%WADE%' OR NEWS_EXCERPT LIKE '%WOM%RIGHT%CHOOSE%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pp', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%PLANNED%PARENT%' OR NEWS_EXCERPT LIKE '%ABORTION%'  
OR NEWS_EXCERPT LIKE '%ROE%WADE%' OR NEWS_EXCERPT LIKE '%WOM%RIGHT%CHOOSE%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'antifa', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%ANTIFA%' OR NEWS_EXCERPT LIKE '%OCCUPY%' 
OR NEWS_EXCERPT LIKE '%FREE%SPEECH%' OR NEWS_EXCERPT LIKE '%BLM%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'antifa', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%ANTIFA%' OR NEWS_EXCERPT LIKE '%OCCUPY%'  
OR NEWS_EXCERPT LIKE '%FREE%SPEECH%' OR NEWS_EXCERPT LIKE '%BLM%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'lgbt', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%LGBT%' OR NEWS_EXCERPT LIKE '%GAY%'  OR NEWS_EXCERPT LIKE '%TRANSG%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'lgbt', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%LGBT%' OR NEWS_EXCERPT LIKE '%GAY%'  OR NEWS_EXCERPT LIKE '%TRANSG%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'clime', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%CLIMATE%' OR NEWS_EXCERPT LIKE '%GLOBAL%WARM%'  OR NEWS_EXCERPT LIKE '%RENEWAB%'  
OR NEWS_EXCERPT LIKE '%FOSSIL%FUEL%'  OR NEWS_EXCERPT LIKE '%KYOTO%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'clime', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%CLIMATE%' OR NEWS_EXCERPT LIKE '%GLOBAL%WARM%'  OR NEWS_EXCERPT LIKE '%RENEWAB%'  
OR NEWS_EXCERPT LIKE '%FOSSIL%FUEL%'  OR NEWS_EXCERPT LIKE '%KYOTO%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

--


--

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pence', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%PENCE%' OR NEWS_EXCERPT LIKE '%VICE%PRESI%' OR NEWS_EXCERPT LIKE '%VEEP%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trump', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%PENCE%' OR NEWS_EXCERPT LIKE '%VICE%PRESI%' OR NEWS_EXCERPT LIKE '%VEEP%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'bannon', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%BANNON%' ) 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'bannon', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%BANNON%' ) 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ryan', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%PAUL%RYAN%' OR NEWS_EXCERPT LIKE '%HOUSE%SPEAKER%' OR NEWS_EXCERPT LIKE '%SPEAKER%HOUSE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ryan', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%PAUL%RYAN%' OR NEWS_EXCERPT LIKE '%HOUSE%SPEAKER%' OR NEWS_EXCERPT LIKE '%SPEAKER%HOUSE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mconel', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%MITCH%MCCON%' OR NEWS_EXCERPT LIKE '%SENATE%LEADER%' OR NEWS_EXCERPT LIKE '%MCCONNE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mconel', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%MITCH%MCCON%' OR NEWS_EXCERPT LIKE '%SENATE%LEADER%' OR NEWS_EXCERPT LIKE '%MCCONNE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ivanka', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%IVANKA%' OR NEWS_EXCERPT LIKE '%KUSHNER%' ) 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ivanka', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%IVANKA%' OR NEWS_EXCERPT LIKE '%KUSHNER%' ) 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ssand', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%SARA%SANDER%' OR NEWS_EXCERPT LIKE '%SARA%HUCKAB%' OR NEWS_EXCERPT LIKE '%HUCKAB%SANDER%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'ssand', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%SARA%SANDER%' OR NEWS_EXCERPT LIKE '%SARA%HUCKAB%' OR NEWS_EXCERPT LIKE '%HUCKAB%SANDER%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'sessions', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%JEFF%SESSION%' OR NEWS_EXCERPT LIKE '%SESSIONS%' OR NEWS_EXCERPT LIKE '%ATTORN%GENERAL%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'sessions', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%JEFF%SESSION%' OR NEWS_EXCERPT LIKE '%SESSIONS%' OR NEWS_EXCERPT LIKE '%ATTORN%GENERAL%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'devos', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%BETSY%DEVOS%' OR NEWS_EXCERPT LIKE '%DEVOS%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'devos', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%BETSY%DEVOS%' OR NEWS_EXCERPT LIKE '%DEVOS%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pruitt', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%SCOTT%PRUITT%' OR NEWS_EXCERPT LIKE '%PRUITT%'  OR NEWS_EXCERPT LIKE '%-EPA-%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'pruitt', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%SCOTT%PRUITT%' OR NEWS_EXCERPT LIKE '%PRUITT%'  OR NEWS_EXCERPT LIKE '%-EPA-%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mnuchin', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%STEVE%MNUCHIN%' OR NEWS_EXCERPT LIKE '%MNUCHIN%'  OR NEWS_EXCERPT LIKE '%-TREASURY-%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'mnuchin', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%STEVE%MNUCHIN%' OR NEWS_EXCERPT LIKE '%MNUCHIN%'  OR NEWS_EXCERPT LIKE '%-TREASURY-%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'haley', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%NIKKI%HALEY%' OR NEWS_EXCERPT LIKE '%AMBA%%HALEY%'  OR NEWS_EXCERPT LIKE '%UNITED%NATIONS%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'haley', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%NIKKI%HALEY%' OR NEWS_EXCERPT LIKE '%AMBA%%HALEY%'  OR NEWS_EXCERPT LIKE '%UNITED%NATIONS%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'tiller', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%REX%TILLER%' OR NEWS_EXCERPT LIKE '%TILLERSO%'  OR NEWS_EXCERPT LIKE '%SEC%STATE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'tiller', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%REX%TILLER%' OR NEWS_EXCERPT LIKE '%TILLERSO%'  OR NEWS_EXCERPT LIKE '%SEC%STATE%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'rush', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%RUSH%LIMB%' OR NEWS_EXCERPT LIKE '%LIMBAU%'  OR NEWS_EXCERPT LIKE '%BLOWHARD%') 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'rush', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%RUSH%LIMB%' OR NEWS_EXCERPT LIKE '%LIMBAU%'  OR NEWS_EXCERPT LIKE '%BLOWHARD%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'hannity', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%HANNITY%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'hannity', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL)  LIKE '%HANNITY%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'coulter', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%COULTER%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'coulter', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL)  LIKE '%COULTER%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'fox', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%FOX%NEWS%' )
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'fox', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL)  LIKE '%FOX%NEWS%' ) AND UPPER(NEWS_URL) NOT LIKE '%HTTP%FOXNEWS%'
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'breit', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%BREIT%' )
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'breit', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (UPPER(NEWS_URL)  LIKE '%BREIT%' ) AND UPPER(NEWS_URL) NOT LIKE '%HTTP%BREIT%'
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'immi', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%IMMIGR%' OR NEWS_EXCERPT LIKE '%-VISA-%'  OR NEWS_EXCERPT LIKE '%AMNESTY%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'immi', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%IMMIGR%' OR NEWS_EXCERPT LIKE '%-VISA-%'  OR NEWS_EXCERPT LIKE '%AMNESTY%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'nra', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%-NRA-%' OR NEWS_EXCERPT LIKE '%RIFLE%'  OR NEWS_EXCERPT LIKE '%SHOOTING%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'nra', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%-NRA-%' OR NEWS_EXCERPT LIKE '%RIFLE%'  OR NEWS_EXCERPT LIKE '%SHOOTING%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'abortion', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%ABORTION%' OR NEWS_EXCERPT LIKE '%PLANNED%PARENT%'  OR NEWS_EXCERPT LIKE '%CONTRACEPT%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'abortion', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%ABORTION%' OR NEWS_EXCERPT LIKE '%PLANNED%PARENT%'  OR NEWS_EXCERPT LIKE '%CONTRACEPT%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'altright', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%ALT%RIGHT%' OR NEWS_EXCERPT LIKE '%WHITE%SUPREM%%'  OR NEWS_EXCERPT LIKE '%STORMFRONT%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'altright', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%altright%' '%ALT%RIGHT%' OR NEWS_EXCERPT LIKE '%WHITE%SUPREM%%'  OR NEWS_EXCERPT LIKE '%STORMFRONT%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'gwarm', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%GLOBAL%WARM%' OR NEWS_EXCERPT LIKE '%CLIMATE%SCI%%'  OR NEWS_EXCERPT LIKE '%POLLUTION%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'gwarm', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%GLOBAL%WARM%' OR NEWS_EXCERPT LIKE '%CLIMATE%SCI%%'  OR NEWS_EXCERPT LIKE '%POLLUTION%')
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'gun', SCRAPE_TAG3 = 'L'  WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N' 
AND (NEWS_EXCERPT LIKE '%GUN%' OR NEWS_EXCERPT LIKE '%MASS%SHOOTI%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'gun', SCRAPE_TAG3 = 'H'  WHERE SCRAPE_TAG1 = 'USAPOLRW'  AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%GUN%' OR NEWS_EXCERPT LIKE '%MASS%SHOOTI%') -- AND UPPER(NEWS_URL) NOT LIKE '%TRUMP%' 
;

--

/* 06/12/2019 - commenting out the trump part - just to research what drops out and can be captures by scrape_design_gen 
08/30/2019 AST: Adding back in */

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trump', SCRAPE_TAG3 = 'H' WHERE SCRAPE_TAG1 = 'USAPOLLW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%TRUMP%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 = 'trump', SCRAPE_TAG3 = 'L' WHERE SCRAPE_TAG1 = 'USAPOLRW' AND MOVED_TO_POST_FLAG = 'N'
AND (NEWS_EXCERPT LIKE '%TRUMP%' ) ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 = 'USAPOL' WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'USA' 
AND SCRAPE_TAG2 = SCRAPE_TAG3 AND MOVED_TO_POST_FLAG = 'N' ;

/*	07/19/2020 AST: Added the TAG_DONE_FLAG = 'Y' to make it compatible with the new STP_STAG23_MICRO */

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y' WHERE SCRAPE_TAG3 IN ('L', 'H') ;

/* 	END OF 07/19/2020 AST ADDITION */

-- CALL STP_STAG1_1KW(1, 'USAPOL', 'USA') ;
-- CALL STP_MOP_UP('USAPOL') ;

--

-- CALL STP_STAG23_1KWINSERT('hillary', 'L', 2) ;
CALL STP_STAG23_MICRO('hillary', 'L') ;

-- CALL STP_STAG23_1KWINSERT('hillary', 'H', 5) ;
CALL STP_STAG23_MICRO('hillary', 'H') ;

-- CALL STP_STAG23_1KWINSERT('bernie', 'L', 2) ;
CALL STP_STAG23_MICRO('bernie', 'L') ;

-- CALL STP_STAG23_1KWINSERT('bernie', 'H', 5) ;
CALL STP_STAG23_MICRO('bernie', 'H') ;

-- CALL STP_STAG23_1KWINSERT('obama', 'L', 2) ;
CALL STP_STAG23_MICRO('obama', 'L') ;

-- CALL STP_STAG23_1KWINSERT('obama', 'H', 5) ;
CALL STP_STAG23_MICRO('obama', 'H') ;

-- CALL STP_STAG23_1KWINSERT('pelosi', 'L', 2) ;
CALL STP_STAG23_MICRO('pelosi', 'L') ;

-- CALL STP_STAG23_1KWINSERT('pelosi', 'H', 5) ;
CALL STP_STAG23_MICRO('pelosi', 'H') ;

-- CALL STP_STAG23_1KWINSERT('schumer', 'L', 2) ;
CALL STP_STAG23_MICRO('schumer', 'L') ;

-- CALL STP_STAG23_1KWINSERT('schumer', 'H', 2) ;
CALL STP_STAG23_MICRO('schumer', 'H') ;

-- CALL STP_STAG23_1KWINSERT('warren', 'L', 2) ;
CALL STP_STAG23_MICRO('warren', 'L') ;

-- CALL STP_STAG23_1KWINSERT('warren', 'H', 2) ;
CALL STP_STAG23_MICRO('warren', 'H') ;

-- CALL STP_STAG23_1KWINSERT('mueller', 'L', 3) ;
CALL STP_STAG23_MICRO('mueller', 'L') ;

-- CALL STP_STAG23_1KWINSERT('mueller', 'H', 5) ;
CALL STP_STAG23_MICRO('mueller', 'H') ;

-- CALL STP_STAG23_1KWINSERT('kamala', 'L', 3) ;
CALL STP_STAG23_MICRO('kamala', 'L') ;

-- CALL STP_STAG23_1KWINSERT('kamala', 'H', 5) ;
CALL STP_STAG23_MICRO('kamala', 'H') ;

-- CALL STP_STAG23_1KWINSERT('fein', 'L', 3) ;
CALL STP_STAG23_MICRO('fein', 'L') ;

-- CALL STP_STAG23_1KWINSERT('fein', 'H', 5) ;
CALL STP_STAG23_MICRO('fein', 'H') ;

-- CALL STP_STAG23_1KWINSERT('deblasio', 'L', 3) ;
CALL STP_STAG23_MICRO('deblasio', 'L') ;

-- CALL STP_STAG23_1KWINSERT('deblasio', 'H', 5) ;
CALL STP_STAG23_MICRO('deblasio', 'H') ;

-- CALL STP_STAG23_1KWINSERT('colbert', 'L', 3) ;
CALL STP_STAG23_MICRO('colbert', 'L') ;

-- CALL STP_STAG23_1KWINSERT('colbert', 'H', 5) ;
CALL STP_STAG23_MICRO('colbert', 'H') ;

-- CALL STP_STAG23_1KWINSERT('path', 'L', 3) ;
CALL STP_STAG23_MICRO('path', 'L') ;

-- CALL STP_STAG23_1KWINSERT('path', 'H', 5) ;
CALL STP_STAG23_MICRO('path', 'H') ;

-- CALL STP_STAG23_1KWINSERT('pp', 'L', 3) ;
CALL STP_STAG23_MICRO('pp', 'L') ;

-- CALL STP_STAG23_1KWINSERT('pp', 'H', 5) ;
CALL STP_STAG23_MICRO('pp', 'H') ;

-- CALL STP_STAG23_1KWINSERT('antifa', 'L', 3) ;
CALL STP_STAG23_MICRO('antifa', 'L') ;

-- CALL STP_STAG23_1KWINSERT('antifa', 'H', 5) ;
CALL STP_STAG23_MICRO('antifa', 'H') ;

-- CALL STP_STAG23_1KWINSERT('lgbt', 'L', 3) ;
CALL STP_STAG23_MICRO('lgbt', 'L') ;

-- CALL STP_STAG23_1KWINSERT('lgbt', 'H', 5) ;
CALL STP_STAG23_MICRO('lgbt', 'H') ;

-- CALL STP_STAG23_1KWINSERT('clime', 'L', 3) ;
CALL STP_STAG23_MICRO('clime', 'L') ;

-- CALL STP_STAG23_1KWINSERT('clime', 'H', 5) ;
CALL STP_STAG23_MICRO('clime', 'H') ;

--


--

-- CALL STP_STAG23_1KWINSERT('pence', 'H', 2) ;
CALL STP_STAG23_MICRO('pence', 'H') ;

-- CALL STP_STAG23_1KWINSERT('pence', 'L', 2) ;
CALL STP_STAG23_MICRO('pence', 'L') ;

-- CALL STP_STAG23_1KWINSERT('bannon', 'H', 2) ;
CALL STP_STAG23_MICRO('bannon', 'H') ;

-- CALL STP_STAG23_1KWINSERT('bannon', 'L', 2) ;
CALL STP_STAG23_MICRO('bannon', 'L') ;

-- CALL STP_STAG23_1KWINSERT('ryan', 'H', 2) ;
CALL STP_STAG23_MICRO('ryan', 'H') ;

-- CALL STP_STAG23_1KWINSERT('ryan', 'L', 2) ;
CALL STP_STAG23_MICRO('ryan', 'L') ;

-- CALL STP_STAG23_1KWINSERT('mconel', 'H', 2) ;
CALL STP_STAG23_MICRO('mconel', 'H') ;

-- CALL STP_STAG23_1KWINSERT('mconel', 'L', 2) ;
CALL STP_STAG23_MICRO('mconel', 'L') ;

-- CALL STP_STAG23_1KWINSERT('ivanka', 'H', 2) ;
CALL STP_STAG23_MICRO('ivanka', 'H') ;

-- CALL STP_STAG23_1KWINSERT('ivanka', 'L', 2) ;
CALL STP_STAG23_MICRO('ivanka', 'L') ;

-- CALL STP_STAG23_1KWINSERT('ssand', 'H', 2) ;
CALL STP_STAG23_MICRO('ssand', 'H') ;

-- CALL STP_STAG23_1KWINSERT('ssand', 'L', 2) ;
CALL STP_STAG23_MICRO('ssand', 'L') ;

-- CALL STP_STAG23_1KWINSERT('sessions', 'H', 2) ;
CALL STP_STAG23_MICRO('sessions', 'H') ;

-- CALL STP_STAG23_1KWINSERT('sessions', 'L', 2) ;
CALL STP_STAG23_MICRO('sessions', 'L') ;

-- CALL STP_STAG23_1KWINSERT('devos', 'H', 2) ;
CALL STP_STAG23_MICRO('devos', 'H') ;

-- CALL STP_STAG23_1KWINSERT('devos', 'L', 2) ;
CALL STP_STAG23_MICRO('devos', 'L') ;

-- CALL STP_STAG23_1KWINSERT('pruitt', 'H', 2) ;
CALL STP_STAG23_MICRO('pruitt', 'H') ;

-- CALL STP_STAG23_1KWINSERT('pruitt', 'L', 2) ;
CALL STP_STAG23_MICRO('pruitt', 'L') ;

-- CALL STP_STAG23_1KWINSERT('mnuchin', 'H', 2) ;
CALL STP_STAG23_MICRO('mnuchin', 'H') ;

-- CALL STP_STAG23_1KWINSERT('mnuchin', 'L', 2) ;
CALL STP_STAG23_MICRO('mnuchin', 'L') ;

-- CALL STP_STAG23_1KWINSERT('haley', 'H', 2) ;
CALL STP_STAG23_MICRO('haley', 'H') ;

-- CALL STP_STAG23_1KWINSERT('haley', 'L', 2) ;
CALL STP_STAG23_MICRO('haley', 'L') ;

-- CALL STP_STAG23_1KWINSERT('tiller', 'H', 2) ;
CALL STP_STAG23_MICRO('tiller', 'H') ;

-- CALL STP_STAG23_1KWINSERT('tiller', 'L', 2) ;
CALL STP_STAG23_MICRO('tiller', 'L') ;

-- CALL STP_STAG23_1KWINSERT('rush', 'H', 2) ;
CALL STP_STAG23_MICRO('rush', 'H') ;

-- CALL STP_STAG23_1KWINSERT('rush', 'L', 2) ;
CALL STP_STAG23_MICRO('rush', 'L') ;

-- CALL STP_STAG23_1KWINSERT('hannity', 'H', 2) ;
CALL STP_STAG23_MICRO('hannity', 'H') ;

-- CALL STP_STAG23_1KWINSERT('hannity', 'L', 2) ;
CALL STP_STAG23_MICRO('hannity', 'L') ;

-- CALL STP_STAG23_1KWINSERT('coulter', 'H', 2) ;
CALL STP_STAG23_MICRO('coulter', 'H') ;

-- CALL STP_STAG23_1KWINSERT('coulter', 'L', 2) ;
CALL STP_STAG23_MICRO('coulter', 'L') ;

-- CALL STP_STAG23_1KWINSERT('fox', 'H', 2) ;
CALL STP_STAG23_MICRO('fox', 'H') ;

-- CALL STP_STAG23_1KWINSERT('fox', 'L', 2) ;
CALL STP_STAG23_MICRO('fox', 'L') ;

-- CALL STP_STAG23_1KWINSERT('breit', 'H', 2) ;
CALL STP_STAG23_MICRO('breit', 'H') ;

-- CALL STP_STAG23_1KWINSERT('breit', 'L', 2) ;
CALL STP_STAG23_MICRO('breit', 'L') ;

-- CALL STP_STAG23_1KWINSERT('immi', 'H', 2) ;
CALL STP_STAG23_MICRO('immi', 'H') ;

-- CALL STP_STAG23_1KWINSERT('immi', 'L', 2) ;
CALL STP_STAG23_MICRO('immi', 'L') ;

-- CALL STP_STAG23_1KWINSERT('abortion', 'H', 2) ;
CALL STP_STAG23_MICRO('abortion', 'H') ;

-- CALL STP_STAG23_1KWINSERT('abortion', 'L', 2) ;
CALL STP_STAG23_MICRO('abortion', 'L') ;

-- CALL STP_STAG23_1KWINSERT('altright', 'H', 2) ;
CALL STP_STAG23_MICRO('altright', 'H') ;

-- CALL STP_STAG23_1KWINSERT('altright', 'L', 2) ;
CALL STP_STAG23_MICRO('altright', 'L') ;

-- CALL STP_STAG23_1KWINSERT('nra', 'H', 2) ;
CALL STP_STAG23_MICRO('nra', 'H') ;

-- CALL STP_STAG23_1KWINSERT('nra', 'L', 2) ;
CALL STP_STAG23_MICRO('nra', 'L') ;

-- CALL STP_STAG23_1KWINSERT('gwarm', 'H', 2) ;
CALL STP_STAG23_MICRO('gwarm', 'H') ;

-- CALL STP_STAG23_1KWINSERT('gwarm', 'L', 2) ;
CALL STP_STAG23_MICRO('gwarm', 'L') ;


-- CALL STP_STAG23_1KWINSERT('gun', 'L', 2) ;
CALL STP_STAG23_MICRO('gun', 'L') ;

-- CALL STP_STAG23_1KWINSERT('gun', 'H', 2) ;
CALL STP_STAG23_MICRO('gun', 'H') ;

--


-- CALL STP_STAG23_1KWINSERT('trump', 'H', 2) ;
CALL STP_STAG23_MICRO('trump', 'H') ;

-- CALL STP_STAG23_1KWINSERT('trump', 'L', 2) ;
CALL STP_STAG23_MICRO('trump', 'L') ;


--

/* 05/26/2018 AST: adding below: After this proc is executed, the scrapes that were converted into posts
should be swept into the WSR_CONVERTED table 

And the scrapes that remained untagged (and specific to IND, OLITICS should be swept to WSR_UNTAGGED 
This kind of step should be taken at the end of each topic STP - but combo topics
such as trending + politics, celeb + media become an issue. We will deal with it later.
*/

INSERT INTO WSR_CONVERTED(SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE)
SELECT SCRAPE_TOPIC, SCRAPE_SOURCE,  SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'USA' AND MOVED_TO_POST_FLAG = 'Y' ;

INSERT INTO OPN_WEB_LINKS(WEB_URL, URL_TITLE, URL_DESCRIPTION, IMAGE_URL, CREATION_DTM, CLEAN_FLAG)
SELECT NEWS_URL, IFNULL(NEWS_HEADLINE, NEWS_EXCERPT), IFNULL(NEWS_EXCERPT, NEWS_HEADLINE), NEWS_PIC_URL, NOW(), 'Y'
FROM WEB_SCRAPE_RAW WHERE NEWS_PIC_URL IS NOT NULL AND SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'USA' ;

SET POSTCOUNT = (SELECT COUNT(*) FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'USA' AND MOVED_TO_POST_FLAG = 'Y') ;

DELETE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'USA' AND MOVED_TO_POST_FLAG = 'Y' ;

/* 06/24/2023: AST: Introducing the STP_REMAINDER proc - instead of sweeping the untagged 
scrapes to WSR_UNTAGGED, they will be distributed among the BOTs that have received 
KWs in their carts recently. This will change the UNTAGGED calc - it will be the 
STP_REMAINDER count.

*/

SET UNTAGCOUNT = (SELECT COUNT(*) FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'USA' AND MOVED_TO_POST_FLAG = 'N') ;

CALL STP_REMAINDER('POLITICS', 1, 'USA') ;

INSERT INTO WSR_CONVERTED(STP_PROCESS, SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE)
SELECT 'STP_REMAINDER', SCRAPE_TOPIC, SCRAPE_SOURCE,  SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC IN ('POLITICS') AND COUNTRY_CODE = 'USA'   AND MOVED_TO_POST_FLAG = 'Y' ;

DELETE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC = 'POLITICS' AND COUNTRY_CODE = 'USA' AND MOVED_TO_POST_FLAG = 'Y' ;  

INSERT INTO OPN_STP_LOG(PROC_NAME, STP_TOPIC, STP_COUNTRY_CODE, POST_COUNT, UNTAG_COUNT, STP_PROC_DTM)
VALUES('STP_GRAND_T1USA', 'POLITICS', 'USA', POSTCOUNT, UNTAGCOUNT, NOW()) ;

/* End of STP logging */
  
  
  
END; //
 DELIMITER ;
 
 -- 