-- STP_REMAINDER_NONXYZ

DELIMITER //
DROP PROCEDURE IF EXISTS STP_REMAINDER_NONXYZ //
CREATE PROCEDURE STP_REMAINDER_NONXYZ(interest VARCHAR(25), TID INT, xyzkid int, ccode VARCHAR(5), numdays INT, scrcount INT)
thisProc: BEGIN
  DECLARE SCRAPEID, PBUID, PBUID2, KID, USERCNT, SCRAPECNT, UNTAG_CNT INT;
  DECLARE SCRAPEURL, URLTITLE, NEWSDESC VARCHAR(1000);
  DECLARE CCODEVAR VARCHAR(5) ;
  DECLARE SCRPTPC VARCHAR(30) ;
  DECLARE SCRDATE DATETIME ;

/* 

10/05/2024 AST: This proc will be mirror image of STP_REMAINDER - but will be used as follows:
	1. It will be used when the scrape count for TID/CCODE combo is > XYZBOTs in the OPN_XYZNEWS_BOTS
    2. Why ? because we want the scrape-to-post to be evenly distributed among XYZBOTs and the non-XYZBOTs
    
*/

    DECLARE DONE INT DEFAULT FALSE;
  DECLARE CURSOR_I CURSOR FOR 
  SELECT W.ROW_ID, IFNULL(W.NEWS_DATE, W.SCRAPE_DATE) SCRAPE_DATE
  , W.SCRAPE_TOPIC, SUBSTR(W.NEWS_URL, 1, 499) NEWS_URL, SUBSTR(W.NEWS_HEADLINE, 1, 499) NEWS_HEADLINE
  , SUBSTR(W.NEWS_EXCERPT, 1, 499) NEWS_EXCERPT, W.COUNTRY_CODE 
  FROM WEB_SCRAPE_RAW W
  WHERE W.SCRAPE_TOPIC = interest AND IFNULL(W.MOVED_TO_POST_FLAG, 'N') = 'N' AND W.COUNTRY_CODE = ccode
  AND IFNULL(NEWS_DATE, SCRAPE_DATE) IS NOT NULL 
  AND IFNULL(NEWS_DATE, SCRAPE_DATE)   > CURRENT_DATE() - INTERVAL numdays DAY LIMIT scrcount ;


   DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
  OPEN CURSOR_I;
   READ_LOOP: LOOP
    FETCH CURSOR_I INTO SCRAPEID, SCRDATE, SCRPTPC, SCRAPEURL, URLTITLE, NEWSDESC, CCODEVAR ;
     IF DONE THEN
      LEAVE READ_LOOP;
      END IF;

/*
SET UNTAG_CNT = (SELECT COUNT(1) FROM WEB_SCRAPE_RAW W   WHERE W.SCRAPE_TOPIC = interest AND W.COUNTRY_CODE = CCODEVAR 
AND W.MOVED_TO_POST_FLAG = 'N' )*2 ; 
06/20/2024 ast: Originally the PBUID below was selected using a more complex logic - in order to take the most recent
cart additions among the BOT users. But that would take 3-5 sec per PBUID generation - resulting into several
minutes for this proc.

Hence now we are doing the easier - more random - not ordered by the latest cart changes - PBUID gen.

Also, we are going to use this proc to generate Posts (news items) as well as Discussions. 

This will be done by just checking if the SCRAPEID is even then Discussion, if odd then post 
*/

SET PBUID = (SELECT DISTINCT USERID FROM OPN_USER_CARTS WHERE TOPICID = TID AND USERID IN 
(SELECT USERID FROM OPN_USERLIST WHERE BOT_FLAG = 'Y' AND COUNTRY_CODE = CCODEVAR )
AND USERID NOT IN (SELECT USERID FROM OPN_XYZNEWS_BOTS WHERE TOPICID = TID AND CCODE = CCODEVAR) ORDER BY RAND() LIMIT 1)  ;

/*
CASE WHEN TID = 1 THEN SET TAG1_KEYID = 105087, KEYID = 105087 ;
WHEN TID = 2 THEN SET TAG1_KEYID = 105654, KEYID = 105654 ;
WHEN TID = 3 THEN SET TAG1_KEYID = 105108, KEYID = 105108 ;
WHEN TID = 4 THEN SET TAG1_KEYID = 105653, KEYID = 105653 ;
WHEN TID = 5 THEN SET TAG1_KEYID = 105655, KEYID = 105655 ;
WHEN TID = 10 AND ccode = 'IND' THEN SET TAG1_KEYID = 105088, KEYID = 105088 ;
WHEN TID = 10 AND ccode = 'USA' THEN SET TAG1_KEYID = 105088, KEYID = 105088 ;

CASE WHEN SCRAPEID % 2 = 0 THEN THIS IS THE CONVERSION TO DISCUSSION WHERE DEMO_POST_FLAG = 'N' 

INSERT INTO OPN_POSTS_RAW(TOPICID, POST_DATETIME, POST_BY_USERID, POST_CONTENT, DEMO_POST_FLAG 
, EMBEDDED_CONTENT, EMBEDDED_FLAG, POSTOR_COUNTRY_CODE, SCRAPE_ROW_ID, URL_TITLE, URL_EXCERPT, STP_PROC_NAME
, MEDIA_CONTENT, MEDIA_FLAG)
VALUES( TID, SCRDATE, PBUID, SCRAPEURL, 'N', '', 'N', CCODEVAR, SCRAPEID, URLTITLE, NEWSDESC
, 'STP_REMAINDER', '', 'N');

THIS IS THE CONVERSION TO POST (INSTREAM) WHERE DEMO_POST_FLAG = 'Y' */

INSERT INTO OPN_POSTS_RAW(TOPICID, POST_DATETIME, POST_BY_USERID, POST_CONTENT, DEMO_POST_FLAG, TAG1_KEYID
, EMBEDDED_CONTENT, EMBEDDED_FLAG, POSTOR_COUNTRY_CODE, SCRAPE_ROW_ID, URL_TITLE, URL_EXCERPT, STP_PROC_NAME
, MEDIA_CONTENT, MEDIA_FLAG)
VALUES( TID, SCRDATE, PBUID, SCRAPEURL, 'Y', xyzkid, '', 'N', CCODEVAR, SCRAPEID, URLTITLE, NEWSDESC
, 'STP_REMAINDER', '', 'N');

-- END CASE ;

  UPDATE WEB_SCRAPE_RAW SET MOVED_TO_POST_FLAG = 'Y' WHERE ROW_ID = SCRAPEID ;
  
  	INSERT INTO WSR_CONVERTED(SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE
, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE, STP_PROCESS)
SELECT SCRAPE_TOPIC, SCRAPE_SOURCE,  SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT
, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE, 'STP_REMAINDER' FROM WEB_SCRAPE_RAW
WHERE  ROW_ID = SCRAPEID ;

DELETE FROM WEB_SCRAPE_RAW WHERE ROW_ID = SCRAPEID ;
 
        END LOOP;
  CLOSE CURSOR_I;
 
END

; //
 DELIMITER ;
 
 -- END OF STP_STAG23_MICRO

 -- 