
-- 

DELIMITER //
DROP PROCEDURE IF EXISTS STP_GRAND_T5IND //
CREATE PROCEDURE STP_GRAND_T5IND()
THISPROC: BEGIN

DECLARE POSTCOUNT, UNTAGCOUNT INT ;


UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 = 'BOLLYWOOD', SCRAPE_TAG2 = 'BOLLYWOOD', SCRAPE_TAG3 = 'BOLLYWOOD'
WHERE UPPER(SCRAPE_TOPIC) IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND' AND MOVED_TO_POST_FLAG = 'N' ;

/* 

06/12/2018 Added veere, raazi, 102, bhavesh, highjack, kaala, daasdev, hahm
07/19/2020 AST: ADDED TAG_DONE_FLAG = 'Y' AFTER UPDATE

09/19/2020 AST: Adding the tagging of 25 untagged scrapes to entertainmentnews5 KW
    10/04/2020 AST: adding filter to XYZNEWS to avoid: old news, stock market update, SHOPPING ADS ETC.
    10/10/2020 AST: removed the above - as a new proc was created for this purpose
    
            06/24/2023: AST: Introducing the STP_REMAINDER proc 

*/

DELETE FROM WEB_SCRAPE_RAW WHERE 1=1 AND COUNTRY_CODE = 'IND' AND SCRAPE_TOPIC IN ('ENT', 'CELEB') 
AND (NEWS_HEADLINE LIKE '%SALE%' OR NEWS_HEADLINE LIKE '% SHOP%' OR NEWS_HEADLINE LIKE '%DISCOUNT%'
OR NEWS_HEADLINE LIKE '%OFF%' OR NEWS_HEADLINE LIKE '%SAVE%' OR NEWS_HEADLINE LIKE '%TIKTOK%' OR NEWS_HEADLINE LIKE '%BOTOX%') ;

DELETE FROM WEB_SCRAPE_RAW WHERE 1=1 AND COUNTRY_CODE = 'IND' AND SCRAPE_TOPIC IN ('ENT', 'CELEB') 
AND (NEWS_URL LIKE '%SALE%' OR NEWS_URL LIKE '% SHOP%' OR NEWS_URL LIKE '%DISCOUNT%'
OR NEWS_URL LIKE '%OFF%' OR NEWS_URL LIKE '%SAVE%' OR NEWS_URL LIKE '%TIKTOK%' OR NEWS_URL LIKE '%BOTOX%') ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'padmavati'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%PADMAAV%'  OR UPPER(NEWS_URL) LIKE     '%BHANSALI%' ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'padmavati'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%PADMAAV%'  OR UPPER(NEWS_URL) LIKE     '%BHANSALI%' ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'mukka'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  '%MUKKAB%'  OR UPPER(NEWS_URL) LIKE '%VINEET%' 
OR UPPER(NEWS_URL) LIKE '%ZOYA%' OR UPPER(NEWS_URL) LIKE '%KASHYAP%') 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'mukka'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  '%MUKKAB%'  OR UPPER(NEWS_URL) LIKE '%VINEET%' 
OR UPPER(NEWS_URL) LIKE '%ZOYA%' OR UPPER(NEWS_URL) LIKE '%KASHYAP%') 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'pari'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%pari%') ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'pari'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%pari%') ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'sonu'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%SONU%TITU%') OR UPPER(NEWS_URL) LIKE  UPPER('%KARTHIK%') 
 OR UPPER(NEWS_URL) LIKE  UPPER('%ARYAN%')  OR UPPER(NEWS_URL) LIKE  UPPER('%SUNNY%SINGH%')  OR UPPER(NEWS_URL) LIKE  UPPER('%NUSHRAT%') ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'sonu'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%SONU%TITU%') OR UPPER(NEWS_URL) LIKE  UPPER('%KARTHIK%') 
 OR UPPER(NEWS_URL) LIKE  UPPER('%ARYAN%')  OR UPPER(NEWS_URL) LIKE  UPPER('%SUNNY%SINGH%')  OR UPPER(NEWS_URL) LIKE  UPPER('%NUSHRAT%') ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'raid'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%-raid-%') OR UPPER(NEWS_URL) LIKE  UPPER('%raid-%') 
 OR UPPER(NEWS_URL) LIKE  UPPER('%-raid%')  OR UPPER(NEWS_URL) LIKE  UPPER('%devgn%')  OR UPPER(NEWS_URL) LIKE  UPPER('%ileana%') ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'raid'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%-raid-%') OR UPPER(NEWS_URL) LIKE  UPPER('%raid-%') 
 OR UPPER(NEWS_URL) LIKE  UPPER('%-raid%')  OR UPPER(NEWS_URL) LIKE  UPPER('%devgn%')  OR UPPER(NEWS_URL) LIKE  UPPER('%ileana%') ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     '3story'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%3%storey%') OR UPPER(NEWS_URL) LIKE  UPPER('%richa%') 
 OR UPPER(NEWS_URL) LIKE  UPPER('%aisha%')  OR UPPER(NEWS_URL) LIKE  UPPER('%tarun%') ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     '3story'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%3%storey%') OR UPPER(NEWS_URL) LIKE  UPPER('%richa%') 
 OR UPPER(NEWS_URL) LIKE  UPPER('%aisha%')  OR UPPER(NEWS_URL) LIKE  UPPER('%tarun%') ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'aiyaary'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%aiyaary%') OR UPPER(NEWS_URL) LIKE  UPPER('%manoj%bajpai%') 
 OR UPPER(NEWS_URL) LIKE  UPPER('%sid%malho%')  OR UPPER(NEWS_URL) LIKE  UPPER('%naseer%') ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'aiyaary'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%aiyaary%') OR UPPER(NEWS_URL) LIKE  UPPER('%manoj%bajpai%') 
 OR UPPER(NEWS_URL) LIKE  UPPER('%sid%malho%')  OR UPPER(NEWS_URL) LIKE  UPPER('%naseer%') ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'hichki'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%hichki%') OR UPPER(NEWS_URL) LIKE  UPPER('%rani%muk%') 
 OR UPPER(NEWS_URL) LIKE  UPPER('%asif%')  OR UPPER(NEWS_URL) LIKE  UPPER('%supriya%') ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'hichki'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%hichki%') OR UPPER(NEWS_URL) LIKE  UPPER('%rani%muk%') 
 OR UPPER(NEWS_URL) LIKE  UPPER('%asif%')  OR UPPER(NEWS_URL) LIKE  UPPER('%supriya%') )  
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'baaghi'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%baaghi%') OR UPPER(NEWS_URL) LIKE  UPPER('%tiger%shr%') 
 OR UPPER(NEWS_URL) LIKE  UPPER('%disha%')  OR UPPER(NEWS_URL) LIKE  UPPER('%randeep%') ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'baaghi'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%baaghi%') OR UPPER(NEWS_URL) LIKE  UPPER('%tiger%shr%') 
 OR UPPER(NEWS_URL) LIKE  UPPER('%disha%')  OR UPPER(NEWS_URL) LIKE  UPPER('%randeep%') ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'yhm'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%ye%hai%moh%%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'yhm'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%ye%hai%moh%%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'supdancer'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%super%dance%%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'supdancer'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%super%dance%%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'kapilsharma'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%KAPIL%SHARMA%%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'kapilsharma'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%KAPIL%SHARMA%%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'veere'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%VEERE%WEDDING%%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'veere'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%VEERE%WEDDING%%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'raazi'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%RAAZI%%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'raazi'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%RAAZI%%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     '102'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%102%NOT%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     '102'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%102%NOT%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'kaala'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%KAALA%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'kaala'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%KAALA%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'bhavesh'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%BHAVESH%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'bhavesh'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%BHAVESH%')  )  
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'highjack'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%HIGH%JACK%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'highjack'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%HIGH%JACK%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'daasdev'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%DAAS%DEV%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'daasdev'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%DAAS%DEV%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'hahm'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%HOPE%HUM%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'hahm'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE  UPPER('%HOPE%HUM%')  ) 
AND COUNTRY_CODE = 'IND' AND UPPER(SCRAPE_TAG1) = 'BOLLYWOOD'     AND MOD(ROW_ID, 2) = 0 ;


/*	07/19/2020 AST: Added the TAG_DONE_FLAG = 'Y' to make it compatible with the new STP_STAG23_MICRO */

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y' WHERE SCRAPE_TAG3 IN ('L', 'H') ;

/* 	END OF 07/19/2020 AST ADDITION */

-- CALL STP_STAG23_1KWINSERT('hahm', 'H', 2) ;
CALL STP_STAG23_MICRO('hahm', 'H') ;

-- CALL STP_STAG23_1KWINSERT('hahm', 'L', 2) ;
CALL STP_STAG23_MICRO('hahm', 'L') ;

-- CALL STP_STAG23_1KWINSERT('daasdev', 'H', 2) ;
CALL STP_STAG23_MICRO('daasdev', 'H') ;

-- CALL STP_STAG23_1KWINSERT('daasdev', 'L', 2) ;
CALL STP_STAG23_MICRO('daasdev', 'L') ;

-- CALL STP_STAG23_1KWINSERT('highjack', 'H', 2) ;
CALL STP_STAG23_MICRO('highjack', 'H') ;

-- CALL STP_STAG23_1KWINSERT('highjack', 'L', 2) ;
CALL STP_STAG23_MICRO('highjack', 'L') ;

-- CALL STP_STAG23_1KWINSERT('bhavesh', 'H', 2) ;
CALL STP_STAG23_MICRO('bhavesh', 'H') ;

-- CALL STP_STAG23_1KWINSERT('bhavesh', 'L', 2) ;
CALL STP_STAG23_MICRO('bhavesh', 'L') ;

-- CALL STP_STAG23_1KWINSERT('kaala', 'H', 2) ;
CALL STP_STAG23_MICRO('kaala', 'H') ;

-- CALL STP_STAG23_1KWINSERT('kaala', 'L', 2) ;
CALL STP_STAG23_MICRO('kaala', 'L') ;

-- CALL STP_STAG23_1KWINSERT('102', 'H', 2) ;
CALL STP_STAG23_MICRO('102', 'H') ;

-- CALL STP_STAG23_1KWINSERT('102', 'L', 2) ;
CALL STP_STAG23_MICRO('102', 'L') ;

-- CALL STP_STAG23_1KWINSERT('raazi', 'H', 2) ;
CALL STP_STAG23_MICRO('raazi', 'H') ;

-- CALL STP_STAG23_1KWINSERT('raazi', 'L', 2) ;
CALL STP_STAG23_MICRO('raazi', 'L') ;

-- CALL STP_STAG23_1KWINSERT('veere', 'H', 2) ;
CALL STP_STAG23_MICRO('veere', 'H') ;

-- CALL STP_STAG23_1KWINSERT('veere', 'L', 2) ;
CALL STP_STAG23_MICRO('veere', 'L') ;

-- CALL STP_STAG23_1KWINSERT('kapilsharma', 'H', 2) ;
CALL STP_STAG23_MICRO('kapilsharma', 'H') ;

-- CALL STP_STAG23_1KWINSERT('kapilsharma', 'L', 2) ;
CALL STP_STAG23_MICRO('kapilsharma', 'L') ;

-- CALL STP_STAG23_1KWINSERT('supdancer', 'H', 2) ;
CALL STP_STAG23_MICRO('supdancer', 'H') ;

-- CALL STP_STAG23_1KWINSERT('supdancer', 'L', 2) ;
CALL STP_STAG23_MICRO('supdancer', 'L') ;

-- CALL STP_STAG23_1KWINSERT('yhm', 'H', 2) ;
CALL STP_STAG23_MICRO('yhm', 'H') ;

-- CALL STP_STAG23_1KWINSERT('yhm', 'L', 2) ;
CALL STP_STAG23_MICRO('yhm', 'L') ;

-- CALL STP_STAG23_1KWINSERT('baaghi', 'H', 2) ;
CALL STP_STAG23_MICRO('baaghi', 'H') ;

-- CALL STP_STAG23_1KWINSERT('baaghi', 'L', 2) ;
CALL STP_STAG23_MICRO('baaghi', 'L') ;

-- CALL STP_STAG23_1KWINSERT('hichki', 'H', 2) ;
CALL STP_STAG23_MICRO('hichki', 'H') ;

-- CALL STP_STAG23_1KWINSERT('hichki', 'L', 2) ;
CALL STP_STAG23_MICRO('hichki', 'L') ;

-- CALL STP_STAG23_1KWINSERT('aiyaary', 'H', 2) ;
CALL STP_STAG23_MICRO('aiyaary', 'H') ;

-- CALL STP_STAG23_1KWINSERT('aiyaary', 'L', 2) ;
CALL STP_STAG23_MICRO('aiyaary', 'L') ;

-- CALL STP_STAG23_1KWINSERT('3story', 'H', 2) ;
CALL STP_STAG23_MICRO('3story', 'H') ;

-- CALL STP_STAG23_1KWINSERT('3story', 'L', 2) ;
CALL STP_STAG23_MICRO('3story', 'L') ;

-- CALL STP_STAG23_1KWINSERT('raid', 'H', 2) ;
CALL STP_STAG23_MICRO('raid', 'H') ;

-- CALL STP_STAG23_1KWINSERT('raid', 'L', 2) ;
CALL STP_STAG23_MICRO('raid', 'L') ;

-- CALL STP_STAG23_1KWINSERT('sonu', 'H', 2) ;
CALL STP_STAG23_MICRO('sonu', 'H') ;

-- CALL STP_STAG23_1KWINSERT('sonu', 'L', 2) ;
CALL STP_STAG23_MICRO('sonu', 'L') ;

-- CALL STP_STAG23_1KWINSERT('pari', 'H', 2) ;
CALL STP_STAG23_MICRO('pari', 'H') ;

-- CALL STP_STAG23_1KWINSERT('pari', 'L', 2) ;
CALL STP_STAG23_MICRO('pari', 'L') ;

-- CALL STP_STAG23_1KWINSERT('mukka', 'H', 2) ;
CALL STP_STAG23_MICRO('mukka', 'H') ;

-- CALL STP_STAG23_1KWINSERT('mukka', 'L', 2) ;
CALL STP_STAG23_MICRO('mukka', 'L') ;

-- CALL STP_STAG23_1KWINSERT('padmavati', 'H', 2) ;
CALL STP_STAG23_MICRO('padmavati', 'H') ;

-- CALL STP_STAG23_1KWINSERT('padmavati', 'L', 2) ;
CALL STP_STAG23_MICRO('padmavati', 'L') ;

/*  Completing the entertainmentnews5 addition with STp MICRo call  */

CALL STP_STAG23_MICRO('entertainmentnews5', 'H') ;

CALL STP_STAG23_MICRO('entertainmentnews5', 'L') ;

/*  END OF Completing the entertainmentnews5 addition with STp MICRo call  */


/* 05/26/2018 AST: adding below: After this proc is executed, the scrapes that were converted into posts
should be swept into the WSR_CONVERTED table 

And the scrapes that remained untagged (and specific to IND, ENT/CELEB should be swept to WSR_UNTAGGED 
This kind of step should be taken at the end of each topic STP - but combo topics
such as trending + politics, celeb + media become an issue. We will deal with it later.
*/

INSERT INTO WSR_CONVERTED(SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE)
SELECT SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND' AND MOVED_TO_POST_FLAG = 'Y' ;

INSERT INTO OPN_WEB_LINKS(WEB_URL, URL_TITLE, URL_DESCRIPTION, IMAGE_URL, CREATION_DTM, CLEAN_FLAG)
SELECT NEWS_URL, IFNULL(NEWS_HEADLINE, NEWS_EXCERPT), IFNULL(NEWS_EXCERPT, NEWS_HEADLINE), NEWS_PIC_URL, NOW(), 'Y'
FROM WEB_SCRAPE_RAW WHERE NEWS_PIC_URL IS NOT NULL AND SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND' ;

SET POSTCOUNT = (SELECT COUNT(*) FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND' AND MOVED_TO_POST_FLAG = 'Y') ;

DELETE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND' AND MOVED_TO_POST_FLAG = 'Y' ;

/* 06/24/2023: AST: Introducing the STP_REMAINDER proc - instead of sweeping the untagged 
scrapes to WSR_UNTAGGED, they will be distributed among the BOTs that have received 
KWs in their carts recently. This will change the UNTAGGED calc - it will be the 
STP_REMAINDER count.

*/

SET UNTAGCOUNT = (SELECT COUNT(*) FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND' AND MOVED_TO_POST_FLAG = 'N') ;

CALL STP_REMAINDER('ENT', 5, 'IND') ;
CALL STP_REMAINDER('CELEB', 10, 'IND') ;

INSERT INTO WSR_CONVERTED(STP_PROCESS, SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE)
SELECT 'STP_REMAINDER', SCRAPE_TOPIC, SCRAPE_SOURCE,  SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND'   AND MOVED_TO_POST_FLAG = 'Y' ;

DELETE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC IN ('ENT', 'CELEB') AND COUNTRY_CODE = 'IND' AND MOVED_TO_POST_FLAG = 'Y' ;  

INSERT INTO OPN_STP_LOG(PROC_NAME, STP_TOPIC, STP_COUNTRY_CODE, POST_COUNT, UNTAG_COUNT, STP_PROC_DTM)
VALUES('STP_GRAND_T10IND', 'CELEB', 'IND', POSTCOUNT, UNTAGCOUNT, NOW()) ;

INSERT INTO OPN_STP_LOG(PROC_NAME, STP_TOPIC, STP_COUNTRY_CODE, POST_COUNT, UNTAG_COUNT, STP_PROC_DTM)
VALUES('STP_GRAND_T5IND', 'ENT', 'IND', POSTCOUNT, UNTAGCOUNT, NOW()) ;

  
  
  
END; //
 DELIMITER ;
 
 -- 