
-- 

DELIMITER //
DROP PROCEDURE IF EXISTS STP_GRAND_T2IND //
CREATE PROCEDURE STP_GRAND_T2IND()
THISPROC: BEGIN

/* 
	07/19/2020 AST: ADDED TAG_DONE_FLAG = 'Y' AFTER UPDATE
    
            09/19/2020 AST: Adding the tagging of 25 untagged scrapes to sportsnews2 KW
10/04/2020 AST: adding filter to XYZNEWS to avoid: old news, stock market update, SHOPPING ADS ETC.
 10/09/2020 AST: fixing the date issue in XYZNEWS  addition - also moving it to the front of the UPDATE
    10/10/2020 AST: removed the above - as a new proc was created for this purpose
    
     06/24/2023: AST: Introducing the STP_REMAINDER proc 

*/
DECLARE POSTCOUNT, UNTAGCOUNT INT ;

-- 


UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl'  , SCRAPE_TAG2 =     'iplmumbai'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE '%MUMB%IND%'  OR UPPER(NEWS_URL) LIKE '%INDIANS%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'     
ORDER BY RAND() LIMIT 2 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl'  , SCRAPE_TAG2 =     'iplmumbai'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE '%MUMB%IND%'  OR UPPER(NEWS_URL) LIKE '%INDIANS%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'ipldelhi'      WHERE  (UPPER(NEWS_URL) LIKE '%DELH%DARE%'  OR UPPER(NEWS_URL) LIKE '%DAREDE%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 2 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'ipldelhi'      WHERE  (UPPER(NEWS_URL) LIKE '%DELH%DARE%'  OR UPPER(NEWS_URL) LIKE '%DAREDE%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'iplkings'      WHERE  (UPPER(NEWS_URL) LIKE '%PUNJ%KING%'  OR UPPER(NEWS_URL) LIKE '%KING%XI%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'iplkings'      WHERE  (UPPER(NEWS_URL) LIKE '%PUNJ%KING%'  OR UPPER(NEWS_URL) LIKE '%KING%XI%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'iplkings'      WHERE  (UPPER(NEWS_URL) LIKE '%PUNJ%KING%'  OR UPPER(NEWS_URL) LIKE '%KING%XI%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'iplkings'      WHERE  (UPPER(NEWS_URL) LIKE '%PUNJ%KING%'  OR UPPER(NEWS_URL) LIKE '%KING%%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'iplchen'      WHERE  (UPPER(NEWS_URL) LIKE '%CHEN%SUPER%'  OR UPPER(NEWS_URL) LIKE '%SUPER%KING%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'iplchen'      WHERE  (UPPER(NEWS_URL) LIKE '%CHEN%SUPER%'  OR UPPER(NEWS_URL) LIKE '%SUPER%KING%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'iplkolk'      WHERE  (UPPER(NEWS_URL) LIKE '%KOLK%RIDER%'  OR UPPER(NEWS_URL) LIKE '%KNIGHT%RIDE%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 2 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'iplkolk'      WHERE  (UPPER(NEWS_URL) LIKE '%KOLK%RIDER%'  OR UPPER(NEWS_URL) LIKE '%KNIGHT%RIDE%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'iplbang'      WHERE  (UPPER(NEWS_URL) LIKE '%ROY%CHALL%'  OR UPPER(NEWS_URL) LIKE '%ROYAL%CHALL%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 2 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'iplbang'      WHERE  (UPPER(NEWS_URL) LIKE '%ROY%CHALL%'  OR UPPER(NEWS_URL) LIKE '%ROYAL%CHALL%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'iplhyd'      WHERE  (UPPER(NEWS_URL) LIKE '%HYD%SUN%'  OR UPPER(NEWS_URL) LIKE '%SUNRISER%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 2 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'iplhyd'      WHERE  (UPPER(NEWS_URL) LIKE '%HYD%SUN%'  OR UPPER(NEWS_URL) LIKE '%SUNRISER%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'iplroyals'      WHERE  (UPPER(NEWS_URL) LIKE '%RAJ%ROYALS%'  OR UPPER(NEWS_URL) LIKE '%ROYALS%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 2 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'iplroyals'      WHERE  (UPPER(NEWS_URL) LIKE '%RAJ%ROYALS%'  OR UPPER(NEWS_URL) LIKE '%ROYALS%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'sachin'      WHERE  (UPPER(NEWS_URL) LIKE '%SACHIN%TENDU%'  OR UPPER(NEWS_URL) LIKE '%TENDULKAR%'  OR UPPER(NEWS_URL) LIKE '%SRT%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'sachin'      WHERE  (UPPER(NEWS_URL) LIKE '%SACHIN%TENDU%'  OR UPPER(NEWS_URL) LIKE '%TENDULKAR%'  OR UPPER(NEWS_URL) LIKE '%SRT%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'kohli'      WHERE  (UPPER(NEWS_URL) LIKE '%VIRA%KOHLI%'  OR UPPER(NEWS_URL) LIKE '%KOHLI%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'kohli'      WHERE  (UPPER(NEWS_URL) LIKE '%VIRA%KOHLI%'  OR UPPER(NEWS_URL) LIKE '%KOHLI%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'dhoni'      WHERE  (UPPER(NEWS_URL) LIKE '%MAH%DHONI%'  OR UPPER(NEWS_URL) LIKE '%DHONI%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'dhoni'      WHERE  (UPPER(NEWS_URL) LIKE '%MAH%DHONI%'  OR UPPER(NEWS_URL) LIKE '%DHONI%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'shami'      WHERE  (UPPER(NEWS_URL) LIKE '%SHAMI%'  OR UPPER(NEWS_URL) LIKE '%SHAMI%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'shami'      WHERE  (UPPER(NEWS_URL) LIKE '%SHAMI%'  OR UPPER(NEWS_URL) LIKE '%SHAMI%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'jadeja'      WHERE  (UPPER(NEWS_URL) LIKE '%JADEJA%'  OR UPPER(NEWS_URL) LIKE '%JADEJA%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'jadeja'      WHERE  (UPPER(NEWS_URL) LIKE '%JADEJA%'  OR UPPER(NEWS_URL) LIKE '%JADEJA%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'rahane'      WHERE  (UPPER(NEWS_URL) LIKE '%RAHANE%'  OR UPPER(NEWS_URL) LIKE '%AJINKYA%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'rahane'      WHERE  (UPPER(NEWS_URL) LIKE '%RAHANE%'  OR UPPER(NEWS_URL) LIKE '%AJINKYA%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'dhawan'      WHERE  (UPPER(NEWS_URL) LIKE '%DHAWAN%'  OR UPPER(NEWS_URL) LIKE '%SHIKHAR%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'dhawan'      WHERE  (UPPER(NEWS_URL) LIKE '%DHAWAN%'  OR UPPER(NEWS_URL) LIKE '%SHIKHAR%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'ishant'      WHERE  (UPPER(NEWS_URL) LIKE '%ISHANT%'  OR UPPER(NEWS_URL) LIKE '%ISHANT%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'ishant'      WHERE  (UPPER(NEWS_URL) LIKE '%ISHANT%'  OR UPPER(NEWS_URL) LIKE '%ISHANT%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'rohit'      WHERE  (UPPER(NEWS_URL) LIKE '%ROHIT%'  OR UPPER(NEWS_URL) LIKE '%ROHIT%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'rohit'      WHERE  (UPPER(NEWS_URL) LIKE '%ROHIT%'  OR UPPER(NEWS_URL) LIKE '%ROHIT%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'hardik'      WHERE  (UPPER(NEWS_URL) LIKE '%HARDIK%'  OR UPPER(NEWS_URL) LIKE '%PANDYA%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'hardik'      WHERE  (UPPER(NEWS_URL) LIKE '%HARDIK%'  OR UPPER(NEWS_URL) LIKE '%PANDYA%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'bumrah'      WHERE  (UPPER(NEWS_URL) LIKE '%BUMRAH%'  OR UPPER(NEWS_URL) LIKE '%BUMRAH%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'bumrah'      WHERE  (UPPER(NEWS_URL) LIKE '%BUMRAH%'  OR UPPER(NEWS_URL) LIKE '%BUMRAH%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'ashwin'      WHERE  (UPPER(NEWS_URL) LIKE '%ASHWIN%'  OR UPPER(NEWS_URL) LIKE '%ASHWIN%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'ashwin'      WHERE  (UPPER(NEWS_URL) LIKE '%ASHWIN%'  OR UPPER(NEWS_URL) LIKE '%ASHWIN%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'yuvraj'      WHERE  (UPPER(NEWS_URL) LIKE '%YUVRAJ%'  OR UPPER(NEWS_URL) LIKE '%YUVI%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'yuvraj'      WHERE  (UPPER(NEWS_URL) LIKE '%YUVRAJ%'  OR UPPER(NEWS_URL) LIKE '%YUVI%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'bhuv'      WHERE  (UPPER(NEWS_URL) LIKE '%BHUVNESH%'  OR UPPER(NEWS_URL) LIKE '%BHUVI%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'bhuv'      WHERE  (UPPER(NEWS_URL) LIKE '%BHUVNESH%'  OR UPPER(NEWS_URL) LIKE '%BHUVI%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'chahal'      WHERE  (UPPER(NEWS_URL) LIKE '%CHAHAL%'  OR UPPER(NEWS_URL) LIKE '%YUZ%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'chahal'      WHERE  (UPPER(NEWS_URL) LIKE '%CHAHAL%'  OR UPPER(NEWS_URL) LIKE '%YUZ%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'gavaskar'      WHERE  (UPPER(NEWS_URL) LIKE '%GAVASK%'  OR UPPER(NEWS_URL) LIKE '%GAVASK%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'gavaskar'      WHERE  (UPPER(NEWS_URL) LIKE '%GAVASK%'  OR UPPER(NEWS_URL) LIKE '%GAVASK%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'saurav'      WHERE  (UPPER(NEWS_URL) LIKE '%SAURAV%'  OR UPPER(NEWS_URL) LIKE '%GANGUL%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'saurav'      WHERE  (UPPER(NEWS_URL) LIKE '%SAURAV%'  OR UPPER(NEWS_URL) LIKE '%GANGUL%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'laxman'      WHERE  (UPPER(NEWS_URL) LIKE '%LAXMAN%'  OR UPPER(NEWS_URL) LIKE '%VVS%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'laxman'      WHERE  (UPPER(NEWS_URL) LIKE '%LAXMAN%'  OR UPPER(NEWS_URL) LIKE '%VVS%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'dravid'      WHERE  (UPPER(NEWS_URL) LIKE '%DRAVID%'  OR UPPER(NEWS_URL) LIKE '%DRAVID%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'dravid'      WHERE  (UPPER(NEWS_URL) LIKE '%DRAVID%'  OR UPPER(NEWS_URL) LIKE '%DRAVID%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'kapil'      WHERE  (UPPER(NEWS_URL) LIKE '%KAPIL%'  OR UPPER(NEWS_URL) LIKE '%KAPIL%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'kapil'      WHERE  (UPPER(NEWS_URL) LIKE '%KAPIL%'  OR UPPER(NEWS_URL) LIKE '%KAPIL%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'cricket'      WHERE  (UPPER(NEWS_URL) LIKE '%CRICKET%'  OR UPPER(NEWS_URL) LIKE '%BATTING%' OR UPPER(NEWS_URL) LIKE '%BOWL%') 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'cricket'      WHERE  (UPPER(NEWS_URL) LIKE '%CRICKET%'  OR UPPER(NEWS_URL) LIKE '%BATTING%' OR UPPER(NEWS_URL) LIKE '%BOWL%') 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'ipl'      WHERE  (UPPER(NEWS_URL) LIKE '%IPL%'  ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 5 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'ipl', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'ipl'      WHERE  (UPPER(NEWS_URL) LIKE '%IPL%'  ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;


UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'badminton', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'sindhu'      WHERE  (UPPER(NEWS_URL) LIKE '%SINDHU%'  ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'badminton', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'sindhu'      WHERE  (UPPER(NEWS_URL) LIKE '%SINDHU%'  )  
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'badminton', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'saina'      WHERE  (UPPER(NEWS_URL) LIKE '%SAINA%' OR UPPER(NEWS_URL) LIKE '%NEHWAL%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'badminton', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'saina'      WHERE  (UPPER(NEWS_URL) LIKE '%SAINA%' OR UPPER(NEWS_URL) LIKE '%NEHWAL%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'badminton', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'badminton'      WHERE  (UPPER(NEWS_URL) LIKE '%BADMONTON%' OR UPPER(NEWS_URL) LIKE '%SHUTTL%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'badminton', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'badminton'      WHERE  (UPPER(NEWS_URL) LIKE '%BADMONTON%' OR UPPER(NEWS_URL) LIKE '%SHUTTL%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'kabaddi', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'kabaddi'      WHERE  (UPPER(NEWS_URL) LIKE '%KABADDI%'  ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'kabaddi', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'kabaddi'      WHERE  (UPPER(NEWS_URL) LIKE '%KABADDI%'  ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'indianteam'      WHERE  (UPPER(NEWS_URL) LIKE '%CRICKET%INDIA%' OR UPPER(NEWS_URL) LIKE '%INDIA%CRICKET%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'cricket', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'indianteam'      WHERE  (UPPER(NEWS_URL) LIKE '%CRICKET%INDIA%' OR UPPER(NEWS_URL) LIKE '%INDIA%CRICKET%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'      
;



UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'hockey', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'hockey'      WHERE  (UPPER(NEWS_URL) LIKE '%HOCKEY%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'hockey', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'hockey'      WHERE  (UPPER(NEWS_URL) LIKE '%HOCKEY%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'    
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'athletics', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'athletics'      WHERE  (UPPER(NEWS_URL) LIKE '%ATHLET%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'athletics', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'athletics'      WHERE  (UPPER(NEWS_URL) LIKE '%ATHLET%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'    
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'tennis', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'tennis'      WHERE  (UPPER(NEWS_URL) LIKE '%TENNIS%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'tennis', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'tennis'      WHERE  (UPPER(NEWS_URL) LIKE '%TENNIS%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'    
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'soccer', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'soccer'      WHERE  (UPPER(NEWS_URL) LIKE '%FOOTBALL%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'soccer', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'soccer'      WHERE  (UPPER(NEWS_URL) LIKE '%FOOTBALL%' ) 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'    
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'golf', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'golf'      WHERE  (UPPER(NEWS_URL) LIKE '%GOLF%' OR UPPER(NEWS_URL) LIKE '%PGA%') 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'golf', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'golf'      WHERE  (UPPER(NEWS_URL) LIKE '%GOLF%' OR UPPER(NEWS_URL) LIKE '%PGA%') 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'    
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'motor-sport', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'motor-sport'      WHERE  (UPPER(NEWS_URL) LIKE '%MOTOR%' OR UPPER(NEWS_URL) LIKE '%PRIX%') 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'motor-sport', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'motor-sport'      WHERE  (UPPER(NEWS_URL) LIKE '%MOTOR%' OR UPPER(NEWS_URL) LIKE '%PRIX%') 
AND COUNTRY_CODE = 'IND' AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'    
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'GSPORT', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'federer'      WHERE  (UPPER(NEWS_URL) LIKE '%FEDERER%' ) 
AND COUNTRY_CODE IN ('IND', 'GGG') AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'GSPORT', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'federer'      WHERE  (UPPER(NEWS_URL) LIKE '%FEDERER%' ) 
AND COUNTRY_CODE IN ('IND', 'GGG') AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'  
;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'GSPORT', SCRAPE_TAG3 = 'H'   
, SCRAPE_TAG2 =     'nadal'      WHERE  (UPPER(NEWS_URL) LIKE '%NADAL%' ) 
AND COUNTRY_CODE IN ('IND', 'GGG') AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N' 
ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 =     'GSPORT', SCRAPE_TAG3 = 'L'   
, SCRAPE_TAG2 =     'nadal'      WHERE  (UPPER(NEWS_URL) LIKE '%NADAL%' ) 
AND COUNTRY_CODE IN ('IND', 'GGG') AND SCRAPE_TAG1 = 'INDSPORTS'  AND   MOVED_TO_POST_FLAG = 'N'  
;

-- 
/*	07/19/2020 AST: Added the TAG_DONE_FLAG = 'Y' to make it compatible with the new STP_STAG23_MICRO */

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y' WHERE SCRAPE_TAG3 IN ('L', 'H') ;

/* 	END OF 07/19/2020 AST ADDITION */


-- CALL STP_STAG23_1KWINSERT('cricket','L',1) ;
CALL STP_STAG23_MICRO('cricket','L') ;
-- CALL STP_STAG23_1KWINSERT('cricket','H',1) ;
CALL STP_STAG23_MICRO('cricket','H') ;
-- CALL STP_STAG23_1KWINSERT('ipl','L',1) ;
CALL STP_STAG23_MICRO('ipl','L') ;
-- CALL STP_STAG23_1KWINSERT('ipl','H',1) ;
CALL STP_STAG23_MICRO('ipl','H') ;
-- CALL STP_STAG23_1KWINSERT('iplmumbai','L',1) ;
CALL STP_STAG23_MICRO('iplmumbai','L') ;
-- CALL STP_STAG23_1KWINSERT('iplmumbai','H',1) ;
CALL STP_STAG23_MICRO('iplmumbai','H') ;
-- CALL STP_STAG23_1KWINSERT('ipldelhi','L',1) ;
CALL STP_STAG23_MICRO('ipldelhi','L') ;
-- CALL STP_STAG23_1KWINSERT('ipldelhi','H',1) ;
CALL STP_STAG23_MICRO('ipldelhi','H') ;
-- CALL STP_STAG23_1KWINSERT('iplchen','L',1) ;
CALL STP_STAG23_MICRO('iplchen','L') ;
-- CALL STP_STAG23_1KWINSERT('iplchen','H',1) ;
CALL STP_STAG23_MICRO('iplchen','H') ;
-- CALL STP_STAG23_1KWINSERT('iplkings','L',1) ;
CALL STP_STAG23_MICRO('iplkings','L') ;
-- CALL STP_STAG23_1KWINSERT('iplkings','H',1) ;
CALL STP_STAG23_MICRO('iplkings','H') ;
-- CALL STP_STAG23_1KWINSERT('iplkolk','L',1) ;
CALL STP_STAG23_MICRO('iplkolk','L') ;
-- CALL STP_STAG23_1KWINSERT('iplkolk','H',1) ;
CALL STP_STAG23_MICRO('iplkolk','H') ;
-- CALL STP_STAG23_1KWINSERT('iplroyals','L',1) ;
CALL STP_STAG23_MICRO('iplroyals','L') ;
-- CALL STP_STAG23_1KWINSERT('iplroyals','H',1) ;
CALL STP_STAG23_MICRO('iplroyals','H') ;
-- CALL STP_STAG23_1KWINSERT('iplbang','L',1) ;
CALL STP_STAG23_MICRO('iplbang','L') ;
-- CALL STP_STAG23_1KWINSERT('iplbang','H',1) ;
CALL STP_STAG23_MICRO('iplbang','H') ;
-- CALL STP_STAG23_1KWINSERT('iplhyd','L',1) ;
CALL STP_STAG23_MICRO('iplhyd','L') ;
-- CALL STP_STAG23_1KWINSERT('iplhyd','H',1) ;
CALL STP_STAG23_MICRO('iplhyd','H') ;
-- CALL STP_STAG23_1KWINSERT('sachin','L',1) ;
CALL STP_STAG23_MICRO('sachin','L') ;
-- CALL STP_STAG23_1KWINSERT('sachin','H',1) ;
CALL STP_STAG23_MICRO('sachin','H') ;
-- CALL STP_STAG23_1KWINSERT('kohli','L',1) ;
CALL STP_STAG23_MICRO('kohli','L') ;
-- CALL STP_STAG23_1KWINSERT('kohli','H',1) ;
CALL STP_STAG23_MICRO('kohli','H') ;
-- CALL STP_STAG23_1KWINSERT('gavaskar','L',1) ;
CALL STP_STAG23_MICRO('gavaskar','L') ;
-- CALL STP_STAG23_1KWINSERT('gavaskar','H',1) ;
CALL STP_STAG23_MICRO('gavaskar','H') ;
-- CALL STP_STAG23_1KWINSERT('dhoni','L',1) ;
CALL STP_STAG23_MICRO('dhoni','L') ;
-- CALL STP_STAG23_1KWINSERT('dhoni','H',1) ;
CALL STP_STAG23_MICRO('dhoni','H') ;
-- CALL STP_STAG23_1KWINSERT('saurav','L',1) ;
CALL STP_STAG23_MICRO('saurav','L') ;
-- CALL STP_STAG23_1KWINSERT('saurav','H',1) ;
CALL STP_STAG23_MICRO('saurav','H') ;
-- CALL STP_STAG23_1KWINSERT('laxman','L',1) ;
CALL STP_STAG23_MICRO('laxman','L') ;
-- CALL STP_STAG23_1KWINSERT('laxman','H',1) ;
CALL STP_STAG23_MICRO('laxman','H') ;
-- CALL STP_STAG23_1KWINSERT('dravid','L',1) ;
CALL STP_STAG23_MICRO('dravid','L') ;
-- CALL STP_STAG23_1KWINSERT('dravid','H',1) ;
CALL STP_STAG23_MICRO('dravid','H') ;
-- CALL STP_STAG23_1KWINSERT('kapil','L',1) ;
CALL STP_STAG23_MICRO('kapil','L') ;
-- CALL STP_STAG23_1KWINSERT('kapil','H',1) ;
CALL STP_STAG23_MICRO('kapil','H') ;
-- CALL STP_STAG23_1KWINSERT('shami','L',1) ;
CALL STP_STAG23_MICRO('shami','L') ;
-- CALL STP_STAG23_1KWINSERT('shami','H',1) ;
CALL STP_STAG23_MICRO('shami','H') ;
-- CALL STP_STAG23_1KWINSERT('jadeja','L',1) ;
CALL STP_STAG23_MICRO('jadeja','L') ;
-- CALL STP_STAG23_1KWINSERT('jadeja','H',1) ;
CALL STP_STAG23_MICRO('jadeja','H') ;
-- CALL STP_STAG23_1KWINSERT('rahane','L',1) ;
CALL STP_STAG23_MICRO('rahane','L') ;
-- CALL STP_STAG23_1KWINSERT('rahane','H',1) ;
CALL STP_STAG23_MICRO('rahane','H') ;
-- CALL STP_STAG23_1KWINSERT('dhawan','L',1) ;
CALL STP_STAG23_MICRO('dhawan','L') ;
-- CALL STP_STAG23_1KWINSERT('dhawan','H',1) ;
CALL STP_STAG23_MICRO('dhawan','H') ;
-- CALL STP_STAG23_1KWINSERT('badminton','L',1) ;
CALL STP_STAG23_MICRO('badminton','L') ;
-- CALL STP_STAG23_1KWINSERT('badminton','H',1) ;
CALL STP_STAG23_MICRO('badminton','H') ;
-- CALL STP_STAG23_1KWINSERT('sindhu','L',1) ;
CALL STP_STAG23_MICRO('sindhu','L') ;
-- CALL STP_STAG23_1KWINSERT('sindhu','H',1) ;
CALL STP_STAG23_MICRO('sindhu','H') ;
-- CALL STP_STAG23_1KWINSERT('saina','L',1) ;
CALL STP_STAG23_MICRO('saina','L') ;
-- CALL STP_STAG23_1KWINSERT('saina','H',1) ;
CALL STP_STAG23_MICRO('saina','H') ;


-- CALL STP_STAG23_1KWINSERT('indianteam','L',1) ;
CALL STP_STAG23_MICRO('indianteam','L') ;
-- CALL STP_STAG23_1KWINSERT('indianteam','H',1) ;
CALL STP_STAG23_MICRO('indianteam','H') ;
-- CALL STP_STAG23_1KWINSERT('kabaddi','L',1) ;
CALL STP_STAG23_MICRO('kabaddi','L') ;
-- CALL STP_STAG23_1KWINSERT('kabaddi','H',1) ;
CALL STP_STAG23_MICRO('kabaddi','H') ;
-- CALL STP_STAG23_1KWINSERT('ishant','L',1) ;
CALL STP_STAG23_MICRO('ishant','L') ;
-- CALL STP_STAG23_1KWINSERT('ishant','H',1) ;
CALL STP_STAG23_MICRO('ishant','H') ;
-- CALL STP_STAG23_1KWINSERT('rohit','L',1) ;
CALL STP_STAG23_MICRO('rohit','L') ;
-- CALL STP_STAG23_1KWINSERT('rohit','H',1) ;
CALL STP_STAG23_MICRO('rohit','H') ;
-- CALL STP_STAG23_1KWINSERT('hardik','L',1) ;
CALL STP_STAG23_MICRO('hardik','L') ;
-- CALL STP_STAG23_1KWINSERT('hardik','H',1) ;
CALL STP_STAG23_MICRO('hardik','H') ;
-- CALL STP_STAG23_1KWINSERT('bumrah','L',1) ;
CALL STP_STAG23_MICRO('bumrah','L') ;
-- CALL STP_STAG23_1KWINSERT('bumrah','H',1) ;
CALL STP_STAG23_MICRO('bumrah','H') ;
-- CALL STP_STAG23_1KWINSERT('ashwin','L',1) ;
CALL STP_STAG23_MICRO('ashwin','L') ;
-- CALL STP_STAG23_1KWINSERT('ashwin','H',1) ;
CALL STP_STAG23_MICRO('ashwin','H') ;
-- CALL STP_STAG23_1KWINSERT('yuvraj','L',1) ;
CALL STP_STAG23_MICRO('yuvraj','L') ;
-- CALL STP_STAG23_1KWINSERT('yuvraj','H',1) ;
CALL STP_STAG23_MICRO('yuvraj','H') ;
-- CALL STP_STAG23_1KWINSERT('bhuv','L',1) ;
CALL STP_STAG23_MICRO('bhuv','L') ;
-- CALL STP_STAG23_1KWINSERT('bhuv','H',1) ;
CALL STP_STAG23_MICRO('bhuv','H') ;
-- CALL STP_STAG23_1KWINSERT('chahal','L',1) ;
CALL STP_STAG23_MICRO('chahal','L') ;
-- CALL STP_STAG23_1KWINSERT('chahal','H',1) ;
CALL STP_STAG23_MICRO('chahal','H') ;  

-- CALL STP_STAG23_1KWINSERT('hockey','L',1) ;
CALL STP_STAG23_MICRO('hockey','L') ;
-- CALL STP_STAG23_1KWINSERT('hockey','H',1) ;
CALL STP_STAG23_MICRO('hockey','H') ;
-- CALL STP_STAG23_1KWINSERT('athletics','L',1) ;
CALL STP_STAG23_MICRO('athletics','L') ;
-- CALL STP_STAG23_1KWINSERT('athletics','H',1) ;
CALL STP_STAG23_MICRO('athletics','H') ;
-- CALL STP_STAG23_1KWINSERT('tennis','L',1) ;
CALL STP_STAG23_MICRO('tennis','L') ;
-- CALL STP_STAG23_1KWINSERT('tennis','H',1) ;
CALL STP_STAG23_MICRO('tennis','H') ;
-- CALL STP_STAG23_1KWINSERT('soccer','L',1) ;
CALL STP_STAG23_MICRO('soccer','L') ;
-- CALL STP_STAG23_1KWINSERT('soccer','H',1) ;
CALL STP_STAG23_MICRO('soccer','H') ;
-- CALL STP_STAG23_1KWINSERT('golf','L',1) ;
CALL STP_STAG23_MICRO('golf','L') ;
-- CALL STP_STAG23_1KWINSERT('golf','H',1) ;
CALL STP_STAG23_MICRO('golf','H') ;
-- CALL STP_STAG23_1KWINSERT('motor-sport','L',1) ;
CALL STP_STAG23_MICRO('motor-sport','L') ;
-- CALL STP_STAG23_1KWINSERT('motor-sport','H',1) ;
CALL STP_STAG23_MICRO('motor-sport','H') ;
  
-- CALL STP_STAG23_1KWINSERT('federer','L',1) ;
CALL STP_STAG23_MICRO('federer','L') ;
-- CALL STP_STAG23_1KWINSERT('federer','H',1) ;
CALL STP_STAG23_MICRO('federer','H') ;
-- CALL STP_STAG23_1KWINSERT('nadal','L',1) ;
CALL STP_STAG23_MICRO('nadal','L') ;
-- CALL STP_STAG23_1KWINSERT('nadal','H',1) ;
CALL STP_STAG23_MICRO('nadal','H') ;  


/* 05/26/2018 AST: adding below: After this proc is executed, the scrapes that were converted into posts
should be swept into the WSR_CONVERTED table 

And the scrapes that remained untagged (and specific to IND, OLITICS should be swept to WSR_UNTAGGED 
This kind of step should be taken at the end of each topic STP - but combo topics
such as trending + politics, celeb + media become an issue. We will deal with it later.
*/

INSERT INTO WSR_CONVERTED(SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE)
SELECT SCRAPE_TOPIC, SCRAPE_SOURCE,  SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC LIKE 'SPORT%' AND COUNTRY_CODE = 'IND' AND MOVED_TO_POST_FLAG = 'Y' ;

INSERT INTO OPN_WEB_LINKS(WEB_URL, URL_TITLE, URL_DESCRIPTION, IMAGE_URL, CREATION_DTM, CLEAN_FLAG)
SELECT NEWS_URL, IFNULL(NEWS_HEADLINE, NEWS_EXCERPT), IFNULL(NEWS_EXCERPT, NEWS_HEADLINE), NEWS_PIC_URL, NOW(), 'Y'
FROM WEB_SCRAPE_RAW WHERE NEWS_PIC_URL IS NOT NULL AND SCRAPE_TOPIC LIKE 'SPORT%' AND COUNTRY_CODE = 'IND' ;

SET POSTCOUNT = (SELECT COUNT(*) FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC LIKE 'SPORT%' AND COUNTRY_CODE = 'IND' AND MOVED_TO_POST_FLAG = 'Y') ;

DELETE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC LIKE 'SPORT%' AND COUNTRY_CODE = 'IND' AND MOVED_TO_POST_FLAG = 'Y' ;

/* 06/24/2023: AST: Introducing the STP_REMAINDER proc - instead of sweeping the untagged 
scrapes to WSR_UNTAGGED, they will be distributed among the BOTs that have received 
KWs in their carts recently. This will change the UNTAGGED calc - it will be the 
STP_REMAINDER count.


*/

SET UNTAGCOUNT = (SELECT COUNT(*) FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC LIKE ('SPORT%') AND COUNTRY_CODE = 'IND' AND MOVED_TO_POST_FLAG = 'N') ;

CALL STP_REMAINDER('SPORTS', 2, 'IND') ;

INSERT INTO WSR_CONVERTED(STP_PROCESS, SCRAPE_TOPIC, SCRAPE_SOURCE, SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE)
SELECT 'STP_REMAINDER', SCRAPE_TOPIC, SCRAPE_SOURCE,  SCRAPE_DATE, NEWS_DATE, NEWS_HEADLINE, NEWS_EXCERPT, NEWS_PIC_URL, NEWS_URL, COUNTRY_CODE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC IN ('SPORTS') AND COUNTRY_CODE = 'IND'   AND MOVED_TO_POST_FLAG = 'Y' ;

DELETE FROM WEB_SCRAPE_RAW
WHERE SCRAPE_TOPIC IN ('SPORTS') AND COUNTRY_CODE = 'IND' AND MOVED_TO_POST_FLAG = 'Y' ;  

INSERT INTO OPN_STP_LOG(PROC_NAME, STP_TOPIC, STP_COUNTRY_CODE, POST_COUNT, UNTAG_COUNT, STP_PROC_DTM)
VALUES('STP_GRAND_T2IND', 'SPORTS', 'IND', POSTCOUNT, UNTAGCOUNT, NOW()) ;

/* End of STP logging */


  
END; //
 DELIMITER ;
 
 -- 