
-- 

DELIMITER //
DROP PROCEDURE IF EXISTS STP_GRAND_T10USA //
CREATE PROCEDURE STP_GRAND_T10USA()
THISPROC: BEGIN

/* 

    05/01/2019 AST:   removed CALL STP_STAG1_1KW(10, 'USACELEB', 'USA')
    07/19/2020 AST: ADDED TAG_DONE_FLAG = 'Y' AFTER UPDATE
    
    09/19/2020 AST: Adding the tagging of 25 untagged scrapes to CELEB NEWS KW
	10/04/2020 AST: adding filter to XYZNEWS to avoid: old news, stock market update, SHOPPING ADS ETC.
 10/09/2020 AST: fixing the date issue in XYZNEWS  addition - also moving it to the front of the UPDATE
    10/10/2020 AST: removed the above - as a new proc was created for this purpose

*/

-- PRIOR TO THIS, THE WEB_SCRAPE_RAW MUST BE DEDUPED

DELETE FROM WEB_SCRAPE_RAW WHERE 1=1 AND COUNTRY_CODE = 'USA' AND SCRAPE_TOPIC IN ('ENT', 'CELEB') 
AND (NEWS_HEADLINE LIKE '%SALE%' OR NEWS_HEADLINE LIKE '% SHOP%' OR NEWS_HEADLINE LIKE '%DISCOUNT%'
OR NEWS_HEADLINE LIKE '%OFF%' OR NEWS_HEADLINE LIKE '%SAVE%' OR NEWS_HEADLINE LIKE '%TIKTOK%' OR NEWS_HEADLINE LIKE '%BOTOX%') ;

DELETE FROM WEB_SCRAPE_RAW WHERE 1=1 AND COUNTRY_CODE = 'USA' AND SCRAPE_TOPIC IN ('ENT', 'CELEB') 
AND (NEWS_URL LIKE '%SALE%' OR NEWS_URL LIKE '% SHOP%' OR NEWS_URL LIKE '%DISCOUNT%'
OR NEWS_URL LIKE '%OFF%' OR NEWS_URL LIKE '%SAVE%' OR NEWS_URL LIKE '%TIKTOK%' OR NEWS_URL LIKE '%BOTOX%') ;
  
UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG1 = 'USACELEB', SCRAPE_TAG2 = 'USACELEB', SCRAPE_TAG3 = 'USACELEB' WHERE SCRAPE_TOPIC IN ('CELEB', 'ENT') AND COUNTRY_CODE = 'USA' ;

-- 

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'swift'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%TAYLOR%'     
OR UPPER(NEWS_URL) LIKE     '%-SWIFT-%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'swift'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%TAYLOR%'     
OR UPPER(NEWS_URL) LIKE     '%-SWIFT-%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'kimk'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%KARDASH%'     
OR UPPER(NEWS_URL) LIKE     '%-KANYE-%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'kimk'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%KARDASH%'     
OR UPPER(NEWS_URL) LIKE     '%-KANYE%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'depp'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%DEPP%'     
OR UPPER(NEWS_URL) LIKE     '%-PIRATE%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'depp'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%DEPP%'     
OR UPPER(NEWS_URL) LIKE     '%-PIRATE%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'angie'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%ANGIE%'     
OR UPPER(NEWS_URL) LIKE     '%JOLIE%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'angie'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%ANGIE%'     
OR UPPER(NEWS_URL) LIKE     '%JOLIE%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'pitt'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%PITT%'     
OR UPPER(NEWS_URL) LIKE     '%BRANGE%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'pitt'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%PITT%'     
OR UPPER(NEWS_URL) LIKE     '%BRANGE%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'julia'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%JULIA%ROB%'     
OR UPPER(NEWS_URL) LIKE     '%JULIA%ROB%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'julia'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%JULIA%ROB%'     
OR UPPER(NEWS_URL) LIKE     '%JULIA%ROB%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'cruise'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%TOM%CRUISE%'     
OR UPPER(NEWS_URL) LIKE     '%CRUISE%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'cruise'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%TOM%CRUISE%'     
OR UPPER(NEWS_URL) LIKE     '%CRUISE%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'jlaw'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%JEN%LAWR%'     
OR UPPER(NEWS_URL) LIKE     '%JENNI%LAWR%%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'jlaw'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%JEN%LAWR%'     
OR UPPER(NEWS_URL) LIKE     '%JENNI%LAWR%%'  )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'wahl'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%WAHL%'     
OR UPPER(NEWS_URL) LIKE     '%WAHL%')     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'wahl'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%WAHL%'     
OR UPPER(NEWS_URL) LIKE     '%WAHL%'  )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'sandler'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%SANDLER%'     
OR UPPER(NEWS_URL) LIKE     '%SANDLER%')     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'sandler'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%SANDLER%'     
OR UPPER(NEWS_URL) LIKE     '%SANDLER%'  )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'mila'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%KUNIS%'     
OR UPPER(NEWS_URL) LIKE     '%KUNIS%')     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'mila'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%KUNIS%'     
OR UPPER(NEWS_URL) LIKE     '%KUNIS%'  )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'scarjo'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%SCARLET%'     
OR UPPER(NEWS_URL) LIKE     '%JOHANSS%')     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'scarjo'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%SCARLET%'     
OR UPPER(NEWS_URL) LIKE     '%JOHANSS%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'aniston'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%ANISTON%'     
OR UPPER(NEWS_URL) LIKE     '%ANISTON%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'aniston'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%ANISTON%'     
OR UPPER(NEWS_URL) LIKE     '%ANISTON%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'emma'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%EMMA%'     
OR UPPER(NEWS_URL) LIKE     '%EMMA%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'emma'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%EMMA%'     
OR UPPER(NEWS_URL) LIKE     '%EMMA%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'vin'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%DIESEL%'     
OR UPPER(NEWS_URL) LIKE     '%-VIN-%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'vin'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%DIESEL%'     
OR UPPER(NEWS_URL) LIKE     '%-VIN-%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'rock'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%THE%ROCK%'     
OR UPPER(NEWS_URL) LIKE     '%DWAYNE%JOHN%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'rock'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%THE%ROCK%'     
OR UPPER(NEWS_URL) LIKE     '%DWAYNE%JOHN%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'theron'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%CHARLIZ%'     
OR UPPER(NEWS_URL) LIKE     '%THERON%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'theron'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%CHARLIZ%'     
OR UPPER(NEWS_URL) LIKE     '%THERON%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'downey'    , SCRAPE_TAG3 = 'H'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%DOWNEY%'     
OR UPPER(NEWS_URL) LIKE     '%DOWNEY%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB' ORDER BY RAND() LIMIT 1  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =      'downey'    , SCRAPE_TAG3 = 'L'     WHERE  MOVED_TO_POST_FLAG = 'N' AND SCRAPE_TAG2 = 'USACELEB'  AND (UPPER(NEWS_URL) LIKE     '%DOWNEY%'     
OR UPPER(NEWS_URL) LIKE     '%DOWNEY%' )     AND UPPER(SCRAPE_TAG1) = 'USACELEB'    ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'minaj'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%MINAJ%' OR UPPER(NEWS_URL) LIKE     '%MINAJ%' )     
AND UPPER(SCRAPE_TAG1) IN ('USACELEB', 'USAENT') ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'minaj'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%MINAJ%' OR UPPER(NEWS_URL) LIKE     '%MINAJ%' )     
AND UPPER(SCRAPE_TAG1) IN ('USACELEB', 'USAENT')  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'beyonce'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%BEYONCE%' OR UPPER(NEWS_URL) LIKE     '%JAY%Z%%' )     
AND UPPER(SCRAPE_TAG1) IN ('USACELEB', 'USAENT') ORDER BY RAND() LIMIT 3 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'beyonce'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%BEYONCE%' OR UPPER(NEWS_URL) LIKE     '%JAY%Z%%' )     
AND UPPER(SCRAPE_TAG1) IN ('USACELEB', 'USAENT')  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'oprah'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%OPRAH%' OR UPPER(NEWS_URL) LIKE     '%WINFREY%%' )     
AND UPPER(SCRAPE_TAG1) IN ('USACELEB', 'USAENT') ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'oprah'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%OPRAH%' OR UPPER(NEWS_URL) LIKE     '%WINFREY%%' )     
AND UPPER(SCRAPE_TAG1) IN ('USACELEB', 'USAENT')  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'cardi'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%CARDI%B%' OR UPPER(NEWS_URL) LIKE     '%ALMANZ%%' )     
AND UPPER(SCRAPE_TAG1) IN ('USACELEB', 'USAENT') ORDER BY RAND() LIMIT 3 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'cardi'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%CARDI%B%' OR UPPER(NEWS_URL) LIKE     '%ALMANZ%%' )     
AND UPPER(SCRAPE_TAG1) IN ('USACELEB', 'USAENT')  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'rihanna'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%RIHANNA%' OR UPPER(NEWS_URL) LIKE     '%RIHANNA%%' )     
AND UPPER(SCRAPE_TAG1) IN ('USACELEB', 'USAENT') ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'rihanna'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%RIHANNA%' OR UPPER(NEWS_URL) LIKE     '%RIHANNA%%' )     
AND UPPER(SCRAPE_TAG1) IN ('USACELEB', 'USAENT')  ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'kperry'    , SCRAPE_TAG3 = 'H'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%KATY%PERRY%' OR UPPER(NEWS_URL) LIKE     '%KATY%PERRY%%' )     
AND UPPER(SCRAPE_TAG1) IN ('USACELEB', 'USAENT') ORDER BY RAND() LIMIT 1 ;

UPDATE WEB_SCRAPE_RAW SET SCRAPE_TAG2 =     'kperry'    , SCRAPE_TAG3 = 'L'     
WHERE  MOVED_TO_POST_FLAG = 'N' AND (UPPER(NEWS_URL) LIKE     '%KATY%PERRY%' OR UPPER(NEWS_URL) LIKE     '%KATY%PERRY%%' )     
AND UPPER(SCRAPE_TAG1) IN ('USACELEB', 'USAENT')  ;

/*	07/19/2020 AST: Added the TAG_DONE_FLAG = 'Y' to make it compatible with the new STP_STAG23_MICRO */

UPDATE WEB_SCRAPE_RAW SET TAG_DONE_FLAG = 'Y' WHERE SCRAPE_TAG3 IN ('L', 'H') ;

/* 	END OF 07/19/2020 AST ADDITION */

-- CALL STP_STAG23_1KWINSERT('swift', 'H', 2) ;
CALL STP_STAG23_MICRO('swift', 'H') ;

-- CALL STP_STAG23_1KWINSERT('swift', 'L', 2) ;
CALL STP_STAG23_MICRO('swift', 'L') ;

-- CALL STP_STAG23_1KWINSERT('kimk', 'H', 2) ;
CALL STP_STAG23_MICRO('kimk', 'H') ;

-- CALL STP_STAG23_1KWINSERT('kimk', 'L', 2) ;
CALL STP_STAG23_MICRO('kimk', 'L') ;

-- CALL STP_STAG23_1KWINSERT('depp', 'H', 2) ;
CALL STP_STAG23_MICRO('depp', 'H') ;

-- CALL STP_STAG23_1KWINSERT('depp', 'L', 2) ;
CALL STP_STAG23_MICRO('depp', 'L') ;

-- CALL STP_STAG23_1KWINSERT('angie', 'H', 2) ;
CALL STP_STAG23_MICRO('angie', 'H') ;

-- CALL STP_STAG23_1KWINSERT('angie', 'L', 2) ;
CALL STP_STAG23_MICRO('angie', 'L') ;

-- CALL STP_STAG23_1KWINSERT('pitt', 'H', 2) ;
CALL STP_STAG23_MICRO('pitt', 'H') ;

-- CALL STP_STAG23_1KWINSERT('pitt', 'L', 2) ;
CALL STP_STAG23_MICRO('pitt', 'L') ;

-- CALL STP_STAG23_1KWINSERT('julia', 'H', 2) ;
CALL STP_STAG23_MICRO('julia', 'H') ;

-- CALL STP_STAG23_1KWINSERT('julia', 'L', 2) ;
CALL STP_STAG23_MICRO('julia', 'L') ;

-- CALL STP_STAG23_1KWINSERT('cruise', 'H', 2) ;
CALL STP_STAG23_MICRO('cruise', 'H') ;

-- CALL STP_STAG23_1KWINSERT('cruise', 'L', 2) ;
CALL STP_STAG23_MICRO('cruise', 'L') ;

-- CALL STP_STAG23_1KWINSERT('jlaw', 'H', 2) ;
CALL STP_STAG23_MICRO('jlaw', 'H') ;

-- CALL STP_STAG23_1KWINSERT('jlaw', 'L', 2) ;
CALL STP_STAG23_MICRO('jlaw', 'L') ;

-- CALL STP_STAG23_1KWINSERT('sandler', 'H', 2) ;
CALL STP_STAG23_MICRO('sandler', 'H') ;

-- CALL STP_STAG23_1KWINSERT('sandler', 'L', 2) ;
CALL STP_STAG23_MICRO('sandler', 'L') ;




-- CALL STP_STAG23_1KWINSERT('mila', 'H', 2) ;
CALL STP_STAG23_MICRO('mila', 'H') ;

-- CALL STP_STAG23_1KWINSERT('mila', 'L', 2) ;
CALL STP_STAG23_MICRO('mila', 'L') ;

-- CALL STP_STAG23_1KWINSERT('vin', 'H', 2) ;
CALL STP_STAG23_MICRO('vin', 'H') ;

-- CALL STP_STAG23_1KWINSERT('vin', 'L', 2) ;
CALL STP_STAG23_MICRO('vin', 'L') ;

-- CALL STP_STAG23_1KWINSERT('emma', 'H', 2) ;
CALL STP_STAG23_MICRO('emma', 'H') ;

-- CALL STP_STAG23_1KWINSERT('emma', 'L', 2) ;
CALL STP_STAG23_MICRO('emma', 'L') ;

-- CALL STP_STAG23_1KWINSERT('rock', 'H', 2) ;
CALL STP_STAG23_MICRO('rock', 'H') ;

-- CALL STP_STAG23_1KWINSERT('rock', 'L', 2) ;
CALL STP_STAG23_MICRO('rock', 'L') ;



-- CALL STP_STAG23_1KWINSERT('aniston', 'H', 2) ;
CALL STP_STAG23_MICRO('aniston', 'H') ;

-- CALL STP_STAG23_1KWINSERT('aniston', 'L', 2) ;
CALL STP_STAG23_MICRO('aniston', 'L') ;

-- CALL STP_STAG23_1KWINSERT('wahl', 'H', 2) ;
CALL STP_STAG23_MICRO('wahl', 'H') ;

-- CALL STP_STAG23_1KWINSERT('wahl', 'L', 2) ;
CALL STP_STAG23_MICRO('wahl', 'L') ;

-- CALL STP_STAG23_1KWINSERT('downey', 'H', 2) ;
CALL STP_STAG23_MICRO('downey', 'H') ;

-- CALL STP_STAG23_1KWINSERT('downey', 'L', 2) ;
CALL STP_STAG23_MICRO('downey', 'L') ;

-- CALL STP_STAG23_1KWINSERT('scarjo', 'H', 2) ;
CALL STP_STAG23_MICRO('scarjo', 'H') ;

-- CALL STP_STAG23_1KWINSERT('scarjo', 'L', 2) ;
CALL STP_STAG23_MICRO('scarjo', 'L') ;

-- CALL STP_STAG23_1KWINSERT('theron', 'H', 2) ;
CALL STP_STAG23_MICRO('theron', 'H') ;

-- CALL STP_STAG23_1KWINSERT('theron', 'L', 2) ;
CALL STP_STAG23_MICRO('theron', 'L') ;

-- 

-- CALL STP_STAG23_1KWINSERT('minaj', 'H', 2) ;
CALL STP_STAG23_MICRO('minaj', 'H') ;

-- CALL STP_STAG23_1KWINSERT('minaj', 'L', 2) ;
CALL STP_STAG23_MICRO('minaj', 'L') ;

-- CALL STP_STAG23_1KWINSERT('beyonce', 'H', 2) ;
CALL STP_STAG23_MICRO('beyonce', 'H') ;

-- CALL STP_STAG23_1KWINSERT('beyonce', 'L', 5) ;
CALL STP_STAG23_MICRO('beyonce', 'L') ;

-- CALL STP_STAG23_1KWINSERT('oprah', 'H', 2) ;
CALL STP_STAG23_MICRO('oprah', 'H') ;

-- CALL STP_STAG23_1KWINSERT('oprah', 'L', 5) ;
CALL STP_STAG23_MICRO('oprah', 'L') ;

-- CALL STP_STAG23_1KWINSERT('cardi', 'H', 2) ;
CALL STP_STAG23_MICRO('cardi', 'H') ;

-- CALL STP_STAG23_1KWINSERT('cardi', 'L', 5) ;
CALL STP_STAG23_MICRO('cardi', 'L') ;

-- CALL STP_STAG23_1KWINSERT('rihanna', 'H', 2) ;
CALL STP_STAG23_MICRO('rihanna', 'H') ;

-- CALL STP_STAG23_1KWINSERT('rihanna', 'L', 5) ;
CALL STP_STAG23_MICRO('rihanna', 'L') ;

-- CALL STP_STAG23_1KWINSERT('kperry', 'H', 2) ;
CALL STP_STAG23_MICRO('kperry', 'H') ;

-- CALL STP_STAG23_1KWINSERT('kperry', 'L', 5) ;
CALL STP_STAG23_MICRO('kperry', 'L') ;

/*  Completing the CELEBNEWS addition with STp MICRo call  */

CALL STP_STAG23_MICRO('CELEBNEWS', 'H') ;

CALL STP_STAG23_MICRO('CELEBNEWS', 'L') ;

/*  END OF Completing the CELEBNEWS addition with STp MICRo call  */
  
  
  
END; //
 DELIMITER ;
 
 -- 