-- suspendUser

-- 

 DELIMITER //
DROP PROCEDURE IF EXISTS suspendUser //
CREATE PROCEDURE suspendUser(uname varchar(40) )
BEGIN

/* 
09/07/2020 AST: initial Creation
		this proc is used for banning the user and all his profiles that we can find

 */

declare UID INT ;
DECLARE UUID VARCHAR(45) ;
DECLARE UTYPE VARCHAR(3) ;
DECLARE UDEVICE VARCHAR(200) ;
DECLARE UEMAIL, UFBID, UGID, UAID VARCHAR(100) ;
 SET SQL_SAFE_UPDATES = 0;

SELECT USERID, USER_UUID, FB_USER_FLAG, FB_USERID, IDENTIFIER_TOKEN, G_USERID, EMAIL_ADDR, A_USERID
INTO UID, UUID, UTYPE, UFBID, UDEVICE, UGID, UEMAIL, UAID FROM OPN_USERLIST  WHERE USERNAME = uname ;

CASE WHEN UTYPE = 'Y' THEN
UPDATE OPN_USERLIST SET USER_SUSPEND_FLAG = 'Y' WHERE FB_USERID = UFBID ;

 WHEN UTYPE = 'A' THEN
UPDATE OPN_USERLIST SET USER_SUSPEND_FLAG = 'Y' WHERE A_USERID = UAID ;

 WHEN UTYPE = 'G' THEN
UPDATE OPN_USERLIST SET USER_SUSPEND_FLAG = 'Y' WHERE G_USERID = UGID ;

 WHEN UTYPE = 'N' THEN
UPDATE OPN_USERLIST SET USER_SUSPEND_FLAG = 'Y' WHERE USERID = UID ;

END CASE ;

END //
DELIMITER ;

-- 