-- userActionCommon

 DELIMITER //
DROP PROCEDURE IF EXISTS userPostSearch //
CREATE PROCEDURE userPostSearch(UUID varchar(45), tid INT, searchterm varchar(60),fromindex INT, toindex INT)
BEGIN

/*
07/17/2020 AST: Building this proc as a Search for Posts
07/20/2020 AST: Added the T.TOPICID = tid FILTER
07/23/2020 AST: Added ORDER BY POST_ID DESC 
08/11/2020 Kapil: Confirmed
10/03/2020 AST: Changed the filter for CCODE to avoid showing BOT posts across the countries
				Exception GGG for handling the SCI posts - which are BOT and need to be 
                shown across the CCODE
*/

declare  UID INT;
declare CCODE varchar(5) ;
DECLARE UNAME VARCHAR(30) ;

SELECT USERID, USERNAME, COUNTRY_CODE INTO UID, UNAME, CCODE FROM OPN_USERLIST WHERE USER_UUID = UUID  ;

/* USER BEHAVIOR LOG */

INSERT INTO OPN_USER_BHV_LOG(USERNAME, USERID, USER_UUID, LOGIN_DTM, API_CALL, CONCAT_PARAMS)
VALUES(UNAME, UID, UUID, NOW(), 'userPostSearch', CONCAT(tid, '-', searchterm));

/* END OF USER BEHAVIOR LOG */

SELECT POST_ID, POST_BY_UID, POST_BY_UNAME, POST_DTM, POST_CONTENT 
FROM (
SELECT T.POST_ID, T.POST_BY_UID, T.POST_BY_UNAME, T.POST_DTM, T.POST_CONTENT
FROM OPN_POST_SEARCH_T T
, (SELECT DISTINCT B.USERID FROM
(SELECT C1.USERID, C1.TOPICID, C1.CART, C1.KEYID FROM OPN_USER_CARTS C1 
WHERE C1.USERID = UID) A ,
(SELECT C2.USERID, CU.BOT_FLAG, C2.TOPICID, C2.CART, C2.KEYID, C2.CREATION_DTM 
FROM OPN_USER_CARTS C2, OPN_USERLIST CU WHERE C2.USERID = CU.USERID AND
 C2.USERID NOT IN (SELECT OUUA.ON_USERID FROM OPN_USER_USER_ACTION OUUA 
 WHERE OUUA.BY_USERID = UID 
AND OUUA.TOPICID = tid AND OUUA.ACTION_TYPE = 'KO')) B 
WHERE A.TOPICID = B.TOPICID AND A.CART = B.CART 
AND A.KEYID = B.KEYID AND A.TOPICID = tid) UN
 WHERE T.POST_BY_UID = UN.USERID AND T.POSTOR_CCODE IN (CCODE, 'GGG')  AND T.TOPICID = tid
 AND MATCH(SEARCH_STRING) AGAINST (searchterm IN boolean MODE) 
 UNION ALL
 SELECT T.POST_ID, T.POST_BY_UID, T.POST_BY_UNAME, T.POST_DTM, T.POST_CONTENT
FROM OPN_POST_SEARCH_T T
, (SELECT DISTINCT B.USERID FROM
(SELECT C1.USERID, C1.TOPICID, C1.CART, C1.KEYID FROM OPN_USER_CARTS C1 
WHERE C1.USERID = UID) A ,
(SELECT C2.USERID, CU.BOT_FLAG, C2.TOPICID, C2.CART, C2.KEYID, C2.CREATION_DTM 
FROM OPN_USER_CARTS C2, OPN_USERLIST CU WHERE C2.USERID = CU.USERID 
AND CU.BOT_FLAG <> 'Y' 
AND C2.USERID NOT IN (SELECT OUUA.ON_USERID FROM OPN_USER_USER_ACTION OUUA 
 WHERE OUUA.BY_USERID = UID 
AND OUUA.TOPICID = tid AND OUUA.ACTION_TYPE = 'KO')) B 
WHERE A.TOPICID = B.TOPICID AND A.CART = B.CART 
AND A.KEYID = B.KEYID AND A.TOPICID = tid) UN
 WHERE T.POST_BY_UID = UN.USERID AND T.POSTOR_CCODE NOT IN (CCODE, 'GGG')  AND T.TOPICID = tid
 AND MATCH(SEARCH_STRING) AGAINST (searchterm IN boolean MODE) 
 )Q
ORDER BY POST_ID DESC LIMIT fromindex, toindex;

END //
DELIMITER ;

-- 
