-- USER_NETWORK_TRIGGER

DELIMITER $$
DROP TRIGGER IF EXISTS USER_NETWORK_TRIGGER $$
CREATE DEFINER=`root`@`%` TRIGGER USER_NETWORK_TRIGGER
AFTER INSERT ON OPN_USERLIST for each row
begin

INSERT INTO OPN_NW_STATS(USERID, USER_UUID, TOPICID, NW_COUNT_T1, NW_COUNT_T2, NWP_COUNT_T1, NWP_COUNT_T2, NW_T1_DTM, NW_T2_DTM)
SELECT U.USERID, U.USER_UUID, T.TOPICID, 0, 0, 0, 0, NOW(), NOW()
FROM OPN_USERLIST U, OPN_TOPICS T
WHERE U.USERID = NEW.USERID ;
-- ORDER BY U.USERID, T.TOPICID;

END$$

DELIMITER ; 

-- 


