-- whoLHMyPost

 DELIMITER //
DROP PROCEDURE IF EXISTS whoLHMyPost //
CREATE PROCEDURE whoLHMyPost(UUID varchar(45), postID INT, LorH varchar(2), fromIndex INT, toIndex INT)
BEGIN

/*
07/20/2020 AST: Initial Creation - Proc to find the list of Users who 
Loved or Hated my post
                    
CALL whoLHMyPost(BRINGUUID(1006545), 659819, 'L', 0,20) ;
08/11/2020 Kapil: Confirmed
	08/25/2020 AST: adding CHF to all users
*/

declare UID INT;
DECLARE UNAME VARCHAR(30) ;
DECLARE CHFG VARCHAR(4) ;

SELECT USERID, USERNAME, CHAT_FLAG INTO UID, UNAME, CHFG FROM OPN_USERLIST WHERE USER_UUID = UUID  ;

/* USER BEHAVIOR LOG */

INSERT INTO OPN_USER_BHV_LOG(USERNAME, USERID, USER_UUID, LOGIN_DTM, API_CALL, CONCAT_PARAMS)
VALUES(UNAME, UID, UUID, NOW(), 'whoLHMyPost', CONCAT(postID, '-', LorH));

/* END OF USER BEHAVIOR LOG */

SELECT UL.USERNAME, CASE WHEN CHFG = 'N' THEN 'N' ELSE UL.CHAT_FLAG END CHF
, UP.POST_ACTION_DTM,UL.DP_URL 
FROM OPN_USER_POST_ACTION UP, OPN_USERLIST UL
WHERE UP.ACTION_BY_USERID = UL.USERID
AND UP.CAUSE_POST_ID = postID AND UP.POST_ACTION_TYPE = LorH
ORDER BY UP.POST_ACTION_DTM DESC 
LIMIT fromindex, toindex;



END //
DELIMITER ;

-- 
