
-- WSR_DEDUPE_ALL

 DELIMITER //
DROP PROCEDURE IF EXISTS WSR_DEDUPE_ALL //
CREATE PROCEDURE WSR_DEDUPE_ALL()
thisProc: BEGIN

/* 10/15/2020 AST: Confirmed  */

  DECLARE  SCR_SRC VARCHAR(50) ;

    DECLARE DONE INT DEFAULT FALSE;
  DECLARE CURSOR_2L CURSOR FOR SELECT DISTINCT SCRAPE_SOURCE FROM WEB_SCRAPE_RAW WHERE MOVED_TO_POST_FLAG = 'N';

   DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
  OPEN CURSOR_2L;
   READ_LOOP: LOOP
    FETCH CURSOR_2L INTO SCR_SRC;
     IF DONE THEN
      LEAVE READ_LOOP;
      END IF;

CALL WSR_DEDUPE(SCR_SRC) ;
 
        END LOOP;
  CLOSE CURSOR_2L;

END //
DELIMITER ;

-- 